### ISSUE TITLE
Copy to clipboard button not visible

### ISSUE THREAD

**Issue by chinu-anand** [meshery/meshery.io#1000]
### Description

The Copy to clipboard is not visible on https://meshery.io/catalog page items.

### Expected Behavior

The button should be visible and working properly.

### Screenshots

https://user-images.githubusercontent.com/66985303/215340454-6bf60be2-957a-453a-91e8-312318d4f842.mov

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by chinu-anand** [comment]
@leecalcote please assign this issue to me. 😃

**Comment by leecalcote** [comment]
@chinu-anand will you propose a solution first?

**Comment by chinu-anand** [comment]
@leecalcote There are two solutions -
1. Make the "Copy to clipboard" visible always.
2. Remove the "Copy to clipboard" text and will modify the element in a way that, when the user clicks on the "Copy URL" button, a "Copied" or a "Copied to Clipboard" message will be shown on the right of that button. That would make more sense as the user will get to know that the action was completed successfully.

I think the second one is more UX-friendly.
