### ISSUE TITLE
[UI] The text isn't visible properly in dark mode in the catalog section

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1009]
#### Current Behavior
If you open the catalog section in the meshery website and then open any of the catalog in the new tab, the "updated and version" text isn't properly visible in dark mode but it works fine in light mode. 
### Dark Mode : 
<img src="https://user-images.githubusercontent.com/91362589/217281326-6bfb7572-1880-4d5a-b9db-e65eacc9394a.jpg" width ="600">

### Light Mode :
<img src="https://user-images.githubusercontent.com/91362589/217281945-5c154ccf-486e-46c1-b23e-92904d99c312.png" width="600">

#### Desired Behavior
Change the text to white in dark mode for better visibility.

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Savio629** [comment]
So, should I close this issue? @Yashsharma1911

**Comment by Savio629** [comment]
@asubedy I had created a pr regarding the text issue.
Can you check if it is valid?

**Comment by Avi-88** [comment]
Hi @Savio629 , the PR mentioned by @Yashsharma1911 has conflicts which haven't been fixed since a while ago. If you have a fix made for this do link it to this issue so it can be reviewed, thanks

**Comment by Savio629** [comment]
I haven't made a pr for this issue.
As soon I make it, I'll update here.

**Comment by Savio629** [comment]
@Avi-88 @Yashsharma1911 
Can you review it?
