### ISSUE TITLE
[UI] Text inside of chip tag of catalog card is not properly visible

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery.io#1011]
### Description
In the upper right corner of catalog card tag, text is not properly visible

### Current Behavior
https://user-images.githubusercontent.com/71271069/217500674-d276fd31-53d2-4460-b7ad-564037b3f0bc.mov

### Expected Behavior

https://user-images.githubusercontent.com/71271069/217500712-ece36a95-218d-417d-af2b-b0d0c124686a.mov

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Savio629** [comment]
Are you going to work on this issue? @Yashsharma1911

**Comment by Yashsharma1911** [comment]
Not yet but @Savio629 would you like to work on this issue?

**Comment by Savio629** [comment]
Yeah, sure.

**Comment by Yashsharma1911** [comment]
Amazing @Savio629 first we need approval for this issue @Shivam-AfA can you look into this

**Comment by Shivam-AfA** [comment]
Yes, this is a valid issue @Yashsharma1911. @Savio629 sure you can work on this one.

**Comment by Savio629** [comment]
@Yashsharma1911 
What should the color of text be?(black)
Should I keep the hover effect?

**Comment by Yashsharma1911** [comment]
the color should only be `black` as you can see in expected behavior video in the issue
