### ISSUE TITLE
[UI] Replace logo with the dark mode version when the website in dark mode.

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery.io#1016]
#### Current State of the Meshery.io site
![Screenshot from 2023-02-13 00-53-54](https://user-images.githubusercontent.com/51539117/218381001-4abb91d7-06e2-442e-9a95-814431ac2bc6.png)

The logo inside that yellow rectangle shown above does not resembles with the dark mode of the website.
link: https://meshery.io/service-mesh-interface

#### Desired State of the Meshery.io site
It should be replaced with the dark mode version of that logo when the website in dark mode.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Avi-88** [comment]
Hi @ritiksaxena124 , I'm not sure if we have a alternate logo for kuma , I've checked at two other places and it still uses the same one for both modes, if that's not the case please let me know so I can try and work on this, thanks

**Comment by Shyam-12** [comment]
Hi, @Avi-88 , @ritiksaxena124, I have found some different icons of Kuma on the CNCF official website, Can I be assigned this issue I would like to work on it.

**Comment by Srinja333** [comment]
Can I work on this

**Comment by arunavabasu-03** [comment]
I would like to work on this!!

**Comment by joshboye** [comment]
I have found alternative logo suitable for dark mode. I would like to work on this issue!

**Comment by ritiksaxena124** [comment]
Go ahead @joshboye if you have any doubts feel free to ask in our [slack channel](https://slack.layer5.io/) or in our [discussion forum](https://discuss.layer5.io/) so that other contributors can also help and guide to your way
