### ISSUE TITLE
[Dark Mode] Current date is not visible in the community calendar

### ISSUE THREAD

**Issue by deepakdinesh1123** [meshery/meshery.io#1019]
### Description
The current date is not visible in the community calendar

![Screenshot from 2023-02-13 19-49-10](https://user-images.githubusercontent.com/52698821/218482759-38e17202-f8de-4fd0-a8b3-975c62cf965a.png)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by TheOjasSingh** [comment]
Hi @deepakdinesh1123 I would Like to work on this issue can you elaborate this issue please.

**Comment by TheOjasSingh** [comment]
@deepakdinesh1123 This issue can be fixed by PR#1032
