### ISSUE TITLE
[Docs] Change Error codes table to merged moniker and code

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery.io#1020]
### Current State:
Currently we have two separate columns, one for moniker and the other for the error code.

### Desired State:
They should be merged into one column
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by BabyElias** [comment]
Hey! Can I work on this issue?

**Comment by Avi-88** [comment]
Hi @Revolyssup , could you please elaborate on how it should be displayed ? I was thinking that first it should be the code followed by its moniker , then the severity and description ( e.g : 1000 - ErrEmptyConfigCode  |  Alert  |  Config is empty ). Do let me know if I got something wrong or if any changes are needed, thanks

**Comment by vishalvivekm** [comment]
@leecalcote @Revolyssup please assign this issue to me !

**Comment by leecalcote** [comment]
@BabyElias I dropped a note your way in Slack.

**Comment by vishalvivekm** [comment]
@leecalcote @Revolyssup meshery/meshery#7193
