### ISSUE TITLE
Adding Margin from Top to Bottom 

### ISSUE THREAD

**Issue by Rishikavishnoi** [meshery/meshery.io#1021]
### Current Behavior

![WhatsApp Image 2023-02-13 at 8 41 55 PM](https://user-images.githubusercontent.com/84177590/218545699-2d37013a-f0a7-41c8-9f67-424cdb942eed.jpeg)

### Desired Behavior
Adding Margin from top to bottom to improve UI  
<img width="209" alt="image" src="https://user-images.githubusercontent.com/84177590/218546383-ba177f1f-0fef-4178-a605-2dd935ea370b.png">

### link :-https://meshery.io/service-mesh-interface
---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by AMRUTH-SANTOSH** [comment]
Hey @Rishikavishnoi I would like to work on this.

**Comment by Rishikavishnoi** [comment]
@AMRUTH-SANTOSH I'm working

**Comment by Avi-88** [comment]
Hi @Rishikavishnoi , while you are working on this could you please also try and fix the icon that is being cutoff in the center row, thanks

**Comment by Rishikavishnoi** [comment]
@Avi-88 I think the icon in the center row is perfect as it shows partially compatible so it needs to be like this but maybe I can be wrong

**Comment by Avi-88** [comment]
Oh, I never thought that could be the case. Well if the image itself is like that then nevermind , sorry for the unnecessary request.

**Comment by Avi-88** [comment]
Hi @Rishikavishnoi , could you please upodate your PR with the requested changes , thanks

**Comment by Savio629** [comment]
I'll work on this issue @Avi-88
