### ISSUE TITLE
Cli command not responsive 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1025]
### Expected Behavior
terminal should expand to show commands or commands should shrink to be more visible. 

### Screenshots
![A573961B-DF6B-4AA3-91F1-36F2B56AF4B8](https://user-images.githubusercontent.com/7570704/219274881-a264cefa-b35f-44a5-9bca-25f2ad41b776.png)

### Enviroment:
 - OS: iPhone 
 - Browser: Safari
 - Version: 
 - Device: Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Avi-88** [comment]
Hi @leecalcote ,  I've found the styling that is causing this issue and would like to work on this. I've made a mockup of the change, let me know your thoughts so I can proceed with making a PR for it, thanks
 
![image](https://user-images.githubusercontent.com/79744258/219363395-5e4bea1a-0726-496c-8f6d-9fa80e901d53.png)
