### ISSUE TITLE
Twitter testimonials

### ISSUE THREAD

**Issue by Ananya2001-an** [meshery/meshery.io#1036]
### Current Behavior

Currently we are just showing one tweet in the footer which looks kind of crammed.

### Desired Behavior

We can create a section for such tweets where people have tagged @meshery.io and then basically use it to display testimonials by the users. 

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/55504616/220302056-2effd69e-e28d-41b1-aa13-b68a3dd5f86b.png)

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ananya2001-an** [comment]
I would like to work on this.

**Comment by Avi-88** [comment]
Hi @Ananya2001-an , the purpose of that iframe is to display the latest tweet made via the meshery.io handle on twitter. I do like your idea of including testimonials, but it'll be better if there was a mockup displaying how the change will look. If you want you can bring this up in one of the website calls that happen weekly or just bring it up for discussion on slack, that way we can get more feedback on this , thanks

**Comment by Ananya2001-an** [comment]
> Hi @Ananya2001-an , the purpose of that iframe is to display the latest tweet made via the meshery.io handle on twitter. I do like your idea of including testimonials, but it'll be better if there was a mockup displaying how the change will look. If you want you can bring this up in one of the website calls that happen weekly or just bring it up for discussion on slack, that way we can get more feedback on this , thanks

Thanks for the response @Avi-88 I will surely try to come up with some mockups.

**Comment by Ananya2001-an** [comment]
> Hey @Ananya2001-an , though one can see only a single tweet, you can scroll down to see others.

Yeah but that's not what I am saying I meant to say that it would be good to show testimonials on the site given by users on Twitter. Every product site generally has testimonials and this is something that can be added here as well.

**Comment by Avi-88** [comment]
Hi @Ananya2001-an , please let me know if you plan on working on this issue, thanks

**Comment by Ananya2001-an** [comment]
> Hi @Ananya2001-an , please let me know if you plan on working on this issue, thanks  

Yeah there have been some work going on with it. The design is in progress. Once that is finalized I will be working on the code probably.

**Comment by Avi-88** [comment]
Awesome, let me know if you need any help, good luck :)

**Comment by Avi-88** [comment]
Hi @Ananya2001-an , just checking in again on the progress ? any updates ?

**Comment by Ananya2001-an** [comment]
> Hi @Ananya2001-an , just checking in again on the progress ? any updates ?

Hey @Avi-88 actually I am on a bit of a tight schedule at the moment so I won't be able to work on it...I think it would be better If someone else gets assigned to it 👍

**Comment by Avi-88** [comment]
> > Hi @Ananya2001-an , just checking in again on the progress ? any updates ?
> 
> Hey @Avi-88 actually I am on a bit of a tight schedule at the moment so I won't be able to work on it...I think it would be better If someone else gets assigned to it 👍

Ok cool, I think it would be difficult to hand it over as this originated as your idea and as it isn't a requirement atm I'll just close this issue. Feel free to open it again once you have time and are able to work on it @Ananya2001-an  :)

**Comment by Ananya2001-an** [comment]
Yeah great! I will close it for now.
