### ISSUE TITLE
UI bug on catalog deployment page when switched to the dark mode

### ISSUE THREAD

**Issue by yash37158** [meshery/meshery.io#1044]
### Description

Fix UI bug on catalog deployment page when switched to the dark mode

### Expected Behavior

updated name and versions name are not visible in dark mode

### Screenshots

<img width="400" alt="Screenshot 2023-02-28 at 1 32 50 AM" src="https://user-images.githubusercontent.com/68152307/221678786-25451f35-9853-4bbd-b803-a34d9898ce36.png">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
Hey @yash37158 , I have already raised a pr for this https://github.com/meshery/meshery.io/pull/1048
for issue #1045 . So I think you can close this issue as it may create conflict

**Comment by yash37158** [comment]
Yeah sure
