### ISSUE TITLE
Issue with the Active user card size

### ISSUE THREAD

**Issue by sidharthviz** [meshery/meshery.io#1046]
### Expected Behavior

Due to card size not able to close it. Active user card size should be reduce i think.

### Screenshots

https://user-images.githubusercontent.com/74046564/221782851-c5e52c08-d804-4794-9c91-7ce9cbc55d78.mp4

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sidharthviz** [comment]
I would like to work on it

**Comment by money8203** [comment]
@Chadha93 @vishalvivekm

**Comment by sidharthviz** [comment]
@vishalvivekm  I think it has been fixed. 
Thank you 👍🏼

**Comment by Savio629** [comment]
@sidharthviz If the issue has been fixed, can you close this issue?
