### ISSUE TITLE
[UI] unaligned icon with text in the community dropdown

### ISSUE THREAD

**Issue by Shivam164** [meshery/meshery.io#1052]
### Description
The dropdown menu for the Contribution option is not well-built. Icons are not well aligned with the text.
I think hovering animation can be improved as well.

### Expected Behavior
Icons should be well aligned with the text beside them.

### Screenshots
![Screenshot from 2023-03-02 12-58-29](https://user-images.githubusercontent.com/77626594/222361356-847e0c46-fe9f-4cab-97ee-086adfa748ef.png)

### Screen Recording
[Screencast from 02-03-23 12:59:51 PM IST.webm](https://user-images.githubusercontent.com/77626594/222361660-71182761-c687-4c2d-886c-5d150ee8f5be.webm)

### Enviroment:
 - OS: Linux
 - Browser: Chromium
 - Version: 
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
Hey @Shivam164 which icon are you talking about on the left side one or right
![image](https://user-images.githubusercontent.com/90546692/222510251-233a76e7-c47d-48b1-a8d4-9d921cd32a86.png)

**Comment by Shivam164** [comment]
> Hey @Shivam164 which icon are you talking about on the left side one or right
> ![image](https://user-images.githubusercontent.com/90546692/222510251-233a76e7-c47d-48b1-a8d4-9d921cd32a86.png)
> 

Here I meant the left one although right one also needs to be fixed in my opinion.

**Comment by sudhanshutech** [comment]
Though I think it is ok with alignment but I tried to give some margin to the icons like
![image](https://user-images.githubusercontent.com/90546692/222538207-42b66f81-d462-4d63-8fcd-ad4048c50877.png)

As per my suggestion, the external-link icon on the right side and hover is perfect. Need your suggestion on this @leecalcote and @Chadha93

**Comment by mukeshblackhat** [comment]
I tried something and I think this will be good  
![Screenshot from 2023-03-05 14-41-31](https://user-images.githubusercontent.com/59144700/222951883-5c65456c-3c36-4b49-acb2-8a0673381f70.png)

Please let me know if you want me to work on this and assign me this . @leecalcote @Chadha93

**Comment by leecalcote** [comment]
Much appreciated for this thoughtful suggestion, @Shivam164 and @mukeshblackhat. The placement of the external link as in the superscript is by design.
