### ISSUE TITLE
Invalid Link put out by Welcome Bot in the comments

### ISSUE THREAD

**Issue by sai-prasad-1** [meshery/meshery.io#1069]
### Description
when ever a new contributor opens a new issue the welcome bot puts a comment with the link to contribution guide and slack community in this the "[Meshery Contributors' Welcome Guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit?usp=sharing)" is pointing to a invalid google docs link   

### Expected Behavior
the link should point to valid file /document

### Screenshots

![Screenshot from 2023-03-11 13-08-48](https://user-images.githubusercontent.com/90447924/224471910-53e28d76-99df-46e6-aa83-a24055d8dc15.png)

![Screenshot from 2023-03-11 13-09-11](https://user-images.githubusercontent.com/90447924/224471913-9d9e623b-28c1-4ba7-bd98-077a82bd2cc0.png)

### Enviroment:
 - OS:  Linux 
 - Browser:  Firefox
 - Device: Desktop 

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
Valid point @sai-prasad-1 , would you like to fix it?

**Comment by sai-prasad-1** [comment]
yes @sudhanshutech i would like to fix this, could also give me the valid link for the same

**Comment by sudhanshutech** [comment]
@sai-prasad-1 there is no community guide at the moment so redirect the link with the newcomers guide as it you have done before

**Comment by sai-prasad-1** [comment]
so should we also up date the text "[Meshery Contributors' Welcome Guide]" to anything else or proceed with the same

**Comment by sudhanshutech** [comment]
Update phrase to Newcomers' Guide
