### ISSUE TITLE
UI- Menu is not aligned properly under mobile mode.

### ISSUE THREAD

**Issue by parmishh** [meshery/meshery.io#1070]
### Description
Menu text is not aligned properly under mobile mode.  https://meshery.io/

### Expected Behavior
should be aligned with hamburger
@leecalcote @Chadha93 you can assign me if this needs to be addressed😊.

### Screenshots
<img width="381" alt="menu" src="https://user-images.githubusercontent.com/91942072/224473037-52c618e3-a50b-46e6-b849-bbbe2f2ffdee.PNG">

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by yash37158** [comment]
LGTM, i can work on this issue

**Comment by leecalcote** [comment]
thank you, gents

**Comment by sudhanshutech** [comment]
Hey @yash37158 there is already an issue opened for this #1035 , where we discussed that menu text is not required in small screens only an icon would be enough. If you follow the conversation there you would get more idea
