### ISSUE TITLE
Website is not responsive

### ISSUE THREAD

**Issue by parmishh** [meshery/meshery.io#1072]
### Description
website not responsive due to hamburger and search icon  https://discuss.layer5.io/

### Expected Behavior
Should be Responsive
@leecalcote @Chadha93 I can give it a try if you assign it to me
### Screenshots

https://user-images.githubusercontent.com/91942072/224473756-0d4ad162-b644-4b70-adbc-dcf9ef1b47aa.mp4

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
Go ahead @parmishh

**Comment by thisiskaransgit** [comment]
@parmishh, I hope you know that this issue belongs to the meshery website, the discuss components are in the [meshery/meshery](https://github.com/meshery/meshery) repo, also since it has been 2 weeks, what's the update, are you still working on it?

cc : @leecalcote, @sudhanshutech

**Comment by parmishh** [comment]
@thisiskaransgit yes I am aware. And This issue is not visible in other devices it was only visible in my device. So I don't think it's a issue so I think I should close it?
