### ISSUE TITLE
Add Testimonials on Homepage 

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1080]
### Current Behavior

We don't display testimonials on the HomePage like we do [here on](https://layer5.io/cloud-native-management/meshmap#:~:text=Hear%20what%20other%20users%20have%20to%20say...) MeshMap page:

<img width="960" alt="testimonial sample" src="https://user-images.githubusercontent.com/110674407/225211897-c8c2fff0-2e8e-4291-b72d-4f76752b071b.png">

### Desired Behavior

Let's do it then.

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
> Thanks for opening this issue. A contributor will be by to give feedback soon. In the meantime, please review the [Newcomers' Guide](https://layer5.io/community/newcomers) and sure to join the [community Slack](https://slack.meshery.io/).

Thank you bot

**Comment by Srinja333** [comment]
can i work on this?

**Comment by ishaan812** [comment]
Can i be assigned this issue?
