### ISSUE TITLE
[BUG] On Catalog page text is very light 

### ISSUE THREAD

**Issue by himanshu1221** [meshery/meshery.io#1082]
### Description

In **Dark mode** when we click on import any catalog item the color of the text is too light 

### Expected Behavior

the colour should be dark enough so that it is clearly visible

### Screenshots

![Screenshot from 2023-03-15 18-43-22](https://user-images.githubusercontent.com/32031706/225319466-c289519d-e8dd-4a2c-b862-51171a0bb3d1.png)
![Screenshot from 2023-03-15 18-43-20](https://user-images.githubusercontent.com/32031706/225319477-670ec5a0-f200-4ae9-a6c3-fb0f2066519a.png)

### Enviroment:
 - OS:Linux
 - Browser: Chrome
 - Version: 110.0.5481.177
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by himanshu1221** [comment]
> Can I work on this?

Hey @Srinja333 I am looking forward to working on this issue waiting for a review by maintainers

**Comment by asubedy** [comment]
Seeing @himanshu1221 pointed out the issue first, I have to assign this to him. @Srinja333 be sure to give your reviews when @himanshu1221 makes his PR.

**Comment by Srinja333** [comment]
ok i will review it

**Comment by himanshu1221** [comment]
> Seeing @himanshu1221 pointed out the issue first, I have to assign this to him. @Srinja333 be sure to give your reviews when @himanshu1221 makes his PR.

Thanks For assigning me the issue @asubedy ill start woking on it
