### ISSUE TITLE
Update all links to Slack

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1093]
#### Current State of the Meshery.io site
Meshery.io points to the community slack workspace at using the URL slack.layer5.io. 

#### Desired State of the Meshery.io site
All instances of this URL can be changed to slack.meshery.io instead. 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Saksham294** [comment]
Hey @leecalcote I would like to work on this

**Comment by leecalcote** [comment]
Thank you, @Saksham294 👍

**Comment by sambhavgupta0705** [comment]
Hey @leecalcote ,if @Saksham294 is not working on this then I would like to work on this one.

**Comment by leecalcote** [comment]
It’s quite quick, so let’s I will sssign it to you as well and see who lands it first.

**Comment by Saksham294** [comment]
Hey sorry for the delay but I'm unable to setup Ruby on Mac to run meshery. So I'll let this issue go for now. Thanks @sambhavgupta0705 @leecalcote

**Comment by leecalcote** [comment]
@Saksham294 try https://rvm.io

**Comment by 0xSaksham** [comment]
Is there any update on this? Can I start working on it?

**Comment by Saksham294** [comment]
@leecalcote Hey I got the server running finally. So regarding the issue I checked the codebase and could not find links where slack.meshery.io was used. I found slack.meshery.io being used. Could you tell more where we wish to have the desired changed?

**Comment by leecalcote** [comment]
Oh, wow. It looks like this issue was taken care of previously and that there are no more old references. 

Thanks for look into this issue. We can close it out now.

**Comment by leecalcote** [comment]
@0xSaksham as it turns out, there is a reference or two in the meshery/play repo that needs replaced. Would you like to recreate this issue over there?

**Comment by 0xSaksham** [comment]
Sure @leecalcote ,can you point me there.

**Comment by leecalcote** [comment]
@0xSaksham I did: meshery/play. If you're not able to figure that out given this info, then you're not likely to have the skills to fix the issue, so this is a good qualification test.

**Comment by anshgoyalevil** [comment]
@leecalcote 

Can I please take up this issue. I would create a PR over there, and would link that to this issue. Or, If you prefer, I would create another issue over there only.
