### ISSUE TITLE
Add Metabit Trading logo to adopters list

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1094]
### Current Behavior
Metabit Trading is Meshery's latest adopter (see https://github.com/meshery/meshery/pull/7433)

### Desired Behavior
Metabit Trading logo should be displayed alongside others.

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by therajatrai** [comment]
Hey @leecalcote, can you assign this to me? Want to work on this.

**Comment by ShivangShandilya** [comment]
Would like to work on this issue if possible

**Comment by Mayaleeeee** [comment]
Hi, @leecalcote I would love to work on this.

**Comment by leecalcote** [comment]
Thanks! Note that finding an SVG of this logo might prove difficult. Ask Gen Yang for one, if needed. Note the opacity effect and difference between light and dark modes. 

Assigning the issue in chronological order… @therajatrai 

@Mayaleeeee now is a good time to build and run this site in preparation for other issues.

**Comment by Mayaleeeee** [comment]
Hi

**Comment by therajatrai** [comment]
@leecalcote I have raised a PR 
https://github.com/meshery/meshery.io/pull/1102
Kindly review it
