### ISSUE TITLE
Meshery.io website screenshot and Meshmates logo in README.md

### ISSUE THREAD

**Issue by ShivangShandilya** [meshery/meshery.io#1095]
### Description
 If you take a look at README.md, you'll notice the meshery.io website screenshot missing along with the Meshmates logo

### Expected Behavior
The screenshot and the logo should be visible.

### Screenshots

![image](https://user-images.githubusercontent.com/101946115/229270372-0bc8b88f-e0eb-4a41-b593-24ef8ca2014a.png)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by thisiskaransgit** [comment]
Hey @ShivangShandilya, thank you for pointing out this issue since you have already raised and worked on multiple good-first-issues, it would be great if someone else picked this up, I hope you would agree with me.

**Comment by Adi-ty** [comment]
Can I work on this?

**Comment by ShivangShandilya** [comment]
> Hey @ShivangShandilya, thank you for pointing out this issue since you have already raised and worked on multiple good-first-issues, it would be great if someone else picked this up and you can focus on some more exciting tasks, I hope you would agree with me.

Yeah sure @thisiskaransgit

**Comment by Adi-ty** [comment]
> > Hey @ShivangShandilya, thank you for pointing out this issue since you have already raised and worked on multiple good-first-issues, it would be great if someone else picked this up and you can focus on some more exciting tasks, I hope you would agree with me.
> 
> Yeah sure @thisiskaransgit, also @Adi-ty you should always wait for an issue to be assigned to you before working on one. I hope you understand

Ok I will surely wait to be assigned first before working from next time
