### ISSUE TITLE
Poor UI in CNCF programs page 

### ISSUE THREAD

**Issue by Adi-ty** [meshery/meshery.io#1098]
### Description
The UI of CNCF programs page is not looking good and different from other programs pages. Text is not visible in dark mode.

### Expected Behavior
UI of CNCF page should be similar to other program pages and text should be visible in dark mode also.

### Screenshots
<img width="948" alt="image" src="https://user-images.githubusercontent.com/92062352/229370084-35634a34-33f7-44d3-b7a5-5fc235e06aa4.png">

### Environment:
 - OS: Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Adi-ty** [comment]
Can I work on this issue.

**Comment by Chadha93** [comment]
Sure, thank you for opening the issue @Adi-ty
