### ISSUE TITLE
Add two new footer items and three new hyperlinks

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1103]
#### Current State of the Meshery.io site footer
<img width="845" alt="Screenshot 2023-04-04 at 9 28 49 PM" src="https://user-images.githubusercontent.com/7570704/229965672-090ec483-4c43-4811-a119-cabbfffa86c5.png">

#### Desired State of the Meshery.io site footer
<img width="841" alt="Screenshot 2023-04-04 at 9 24 33 PM" src="https://user-images.githubusercontent.com/7570704/229965551-4bcd5d78-18c5-426c-a5a7-202dc864dab4.png">

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by anshgoyalevil** [comment]
@leecalcote 
Please assign it to me.

**Comment by leecalcote** [comment]
Thanks, @anshgoyalevil

**Comment by 0xSaksham** [comment]
Hey, is there any update on this? If not I can work on this issue.

**Comment by anshgoyalevil** [comment]
@0xSaksham 

Please take another issue, I am working upon it. Thanks!

**Comment by 0xSaksham** [comment]
@anshgoyalevil Thanks for answering. I'll try another issue.
