### ISSUE TITLE
Replace the Logo of Layer5 with Meshery in ```config.yml``` workflow

### ISSUE THREAD

**Issue by anshgoyalevil** [meshery/meshery.io#1106]
### Description

Currently, we are using the Logo of Layer5 instead of Meshery. This repository is under the organization Meshery, so, there should be the image of Meshery.

**How to resolve this?**
- Go to https://github.com/meshery/meshery.io/tree/master/.github/welcome and replace this welcome image with the new one: 

![image](https://user-images.githubusercontent.com/94157520/230422041-ddacd2b8-ccd0-47d7-be6e-7ded7e486533.png)

Image Link: https://ibb.co/Wckh3qc

- Download this image, and upload with the correct name for future reference. The name of the image should be ```Meshery-celebration```.
- After uploading the image, and removing the previous image, go to https://github.com/meshery/meshery.io/blob/master/.github/config.yml and update the reference to previous image to the new image in the following part:

```
firstPRMergeComment: >
  Thanks for your contribution to the Layer5 and Meshery community! :tada:
   
  ![Congrats!](https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Layer5-celebration.png)
  &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; :star: Please leave a [star on the project](../stargazers). :smile:
```
- That's it.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by anshgoyalevil** [comment]
Please assign this issue to me.

**Comment by vishalvivekm** [comment]
> @leecalcote Please assign this issue to me.

There you go @anshgoyalevil

**Comment by anshgoyalevil** [comment]
Thanks @vishalvivekm Sir.
