### ISSUE TITLE
[Community] Broken image link to MeshMate logo

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1108]
### Description
In the meshery.io/community pages, there is a broken link to the MeshMates logo. See example here - https://meshery.io/contributors/subham-rai/

### Screenshots
<img width="491" alt="Screenshot 2023-04-06 at 5 31 28 PM" src="https://user-images.githubusercontent.com/7570704/230505712-335fabea-7fff-4561-8736-648003064acc.png">

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
This needs fixed in the readme, too: 
<img width="892" alt="Screenshot 2023-04-06 at 5 36 28 PM" src="https://user-images.githubusercontent.com/7570704/230506272-1c202209-696f-4a3a-b1bb-6cbeabeb8f92.png">

**Comment by anshgoyalevil** [comment]
@leecalcote Could you please assign this issue to me. Thanks!

**Comment by codewithnadeem14502** [comment]
Hello sir. Recently when I am creating my portfolio I also fave thus issue and here is my portfolio link: https://codewithnadeem14502.github.io/portfolioo/ you see my work. So I think I fix this in much better. So could you please assign me this .

**Comment by AbhishekGMV** [comment]
Hi @leecalcote, I have fixed this issue and have raised a PR. Can you please review it, Thanks.

**Comment by AbhishekGMV** [comment]
PS: I didn't work on fixing the logo in README issue as there is an approved PR for it

**Comment by AbhishekGMV** [comment]
> PS: I didn't work on fixing the logo in README issue as there's already an approved PR for it

Update: Included README file changes as well!

**Comment by Adi-ty** [comment]
> This needs fixed in the readme, too: <img alt="Screenshot 2023-04-06 at 5 36 28 PM" width="892" src="https://user-images.githubusercontent.com/7570704/230506272-1c202209-696f-4a3a-b1bb-6cbeabeb8f92.png">

This issue has been fixed in the PR #1100

**Comment by AbhishekGMV** [comment]
Ok, I saw the PR wasn't merged and it had been mentioned by @leecalcote again in this issue so I included it. Does it mean I'd have to exclude the readme file changes ?

**Comment by AbhishekGMV** [comment]
The PR for this issue has been approved and merged to master. You can consider closing this issue @leecalcote

**Comment by vishalvivekm** [comment]
done by #1109
