### ISSUE TITLE
Bug Report : Excessive margin at the bottom of the footer

### ISSUE THREAD

**Issue by Sumitmaithani** [meshery/meshery.io#1111]
### Description
The website has an excessive amount of margin at the bottom of the footer, resulting in a large white space.

### Expected Behavior
The footer should not have any margin at the bottom, resulting in a cleaner appearance without unnecessary white space.

### Screenshots

![Meshery The Kubernetes and Cloud Native Manager _ Meshery - Google Chrome 4_9_2023 11_08_26 PM_LI](https://user-images.githubusercontent.com/86047367/230788154-b2fdcd67-6e20-468d-9cbf-553f6becd2c9.jpg)

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Sumitmaithani** [comment]
Can I take this issue...

**Comment by anshgoyalevil** [comment]
@Sumitmaithani 

This may be an issue in your local server installation.
It's all right on meshery.io

![image](https://user-images.githubusercontent.com/94157520/230788871-b363f32f-59b1-4764-8887-90d6e1472c00.png)

Thanks!

**Comment by Sumitmaithani** [comment]
@anshgoyalevil 

This is happening in meshery.io also...

![Meshery The Kubernetes and Cloud Native Manager _ Meshery⁤ - Google Chrome 4_9_2023 11_34_34 PM](https://user-images.githubusercontent.com/86047367/230789189-d7f01948-7b12-45d3-a22b-df851a648e49.png)

Thanks!

**Comment by anshgoyalevil** [comment]
@Sumitmaithani 

I just re-verified. It's alright on my side. Could you please check if there's any conflicting extension installed due to which this is happening.

**Comment by Sumitmaithani** [comment]
@anshgoyalevil 

I have checked in all browsers and found that the issue is present only in my current browser, but not in the other browsers.

Thanks!
