### ISSUE TITLE
Bug Report : Text is not visible in dark mode

### ISSUE THREAD

**Issue by Sumitmaithani** [meshery/meshery.io#1112]
### Description
The text is not visible in many places while using dark mode.

![Jwt Filter _ Meshery - Google Chrome 4_10_2023 11_56_15 AM (5)](https://user-images.githubusercontent.com/86047367/230842212-c6745d9e-1ca9-4995-a638-86520da8c9d6.png)

![Http Auth _ Meshery - Google Chrome 4_10_2023 12_01_44 PM](https://user-images.githubusercontent.com/86047367/230842271-535d9650-c3e4-4df9-b707-2b264fc83bf6.png)

![Http Auth _ Meshery - Google Chrome 4_10_2023 11_59_33 AM](https://user-images.githubusercontent.com/86047367/230842079-48917f0d-baef-46d8-ad6e-9e4aac4b3387.png)

![Http Auth _ Meshery - Google Chrome 4_10_2023 12_01_02 PM](https://user-images.githubusercontent.com/86047367/230841912-f3ea4e6f-43ea-4f17-844a-1d6912bb1875.png)

### Expected Behavior
All text should be clearly visible and readable in dark mode.

![Jwt Filter _ Meshery - Google Chrome 4_10_2023 11_58_50 AM](https://user-images.githubusercontent.com/86047367/230842183-06ccf0c0-d2bf-4eed-9e73-538b72a5a397.png)
![Http Auth _ Meshery - Google Chrome 4_10_2023 12_02_40 PM](https://user-images.githubusercontent.com/86047367/230842233-0fdf3427-2cd0-48b8-bed4-e465ce65278d.png)
![Http Auth _ Meshery - Google Chrome 4_10_2023 12_01_24 PM](https://user-images.githubusercontent.com/86047367/230842302-e8acfd0a-8d4b-4d0d-8303-482259f2ebf9.png)
![Http Auth _ Meshery - Google Chrome 4_10_2023 12_00_29 PM](https://user-images.githubusercontent.com/86047367/230842015-3343b7af-8d5e-4f1a-830d-14b6025981be.png)

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Sumitmaithani** [comment]
Can I take this issue...

**Comment by vishalvivekm** [comment]
@Sumitmaithani  will you please confirm if you have [meshery.io](https://meshery.io/) set-up locally ?

**Comment by Sumitmaithani** [comment]
@vishalvivekm yes I have set up Meshery.io locally

**Comment by vishalvivekm** [comment]
> @vishalvivekm yes I have set up Meshery.io locally

Great @Sumitmaithani , assigning this to you.
Let's discuss this on the Websites call, Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Sumitmaithani** [comment]
@vishalvivekm 

Yes I have added this as an agenda item.
