### ISSUE TITLE
Replace the logo of Layer5 with Meshery in config.yml workflow

### ISSUE THREAD

**Issue by ShivangShandilya** [meshery/meshery.io#1116]
**Description**

Currently, we are using the Logo of Layer5 instead of Meshery. This repository is under the organization Meshery, so, there should be an image of Meshery.

**How to resolve this**

- Go to .github and replace this welcome image with the new one:

- Make sure to display the images conditionally, based on the theme selected by user.
Here's the sample code:

```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/w.png">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/b.png">
  <img alt="Meshery Logo" src="">
</picture>
```

New images are:

![image](https://user-images.githubusercontent.com/101946115/231824547-c6364b75-0108-4fcf-afaf-bebc06a57049.png)

![image](https://user-images.githubusercontent.com/101946115/231824562-f680a2c2-a6c2-49bd-bb57-516a358b4563.png)

- Download these images, and upload with an appropriate name. Make sure to use conditional rendering as described above.

- After uploading the image, and removing the previous image, go to .github/config.yml folder and update the reference to previous image to the new image in the following part:

```
firstPRMergeComment: >
  Thanks for your contribution to the Layer5 and Meshery community! :tada:
   
  ![Congrats!](https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Layer5-celebration.png)
  &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; :star: Please leave a [star on the project](../stargazers). :smile:
```
Here, replace `![Congrats!](https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Layer5-celebration.png)` with the code

```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/w.png">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/b.png">
  <img alt="Shows a black logo in light color mode and a white one in dark color mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
</picture>
```

make sure to change the image sources with the path to image in the folder where you upload it.

- That's it.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sidharthviz** [comment]
I'd like to work on this..

**Comment by vishalvivekm** [comment]
There you go @sidharthviz

**Comment by ShivangShandilya** [comment]
@vishalvivekm seems like @anshgoyalevil would be handling this issue, can you please unassign @sidharthviz

**Comment by vishalvivekm** [comment]
@ShivangShandilya please review @anshgoyalevil's PRs #1132

**Comment by ShivangShandilya** [comment]
> @ShivangShandilya please review @anshgoyalevil's PRs #1132

Sure sure

**Comment by leecalcote** [comment]
@ShivangShandilya  Please change the location for the new image location.

**Comment by leecalcote** [comment]
@anshgoyalevil

**Comment by leecalcote** [comment]
@ShivangShandilya @anshgoyalevil I still see the old reference in the issue description

**Comment by anshgoyalevil** [comment]
@leecalcote 

The image's location in the issue description is not the actual location. It is just for reference purpose only. We have used the reference to ```https://raw.githubusercontent............``` sample image to tell the contributor that an image source would look like it.

> make sure to change the image sources with the path to image in the folder where you upload it.

This line in issue description says it all. 

Image location would depend upon the folder where the image would be uploaded.

**Comment by thisiskaransgit** [comment]
@ShivangShandilya @anshgoyalevil, it is better to remove the reference code, the steps are more than enough, make sure this change in description is reflected in all the related issues( config.yml ) that both of you have raised.
