### ISSUE TITLE
Open modal when clicked on individual designs

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery.io#1120]
### Current Behavior
When clicked on any of the catalog content we open a new page for that design.

### Desired Behavior
We want a modal to open when clicked on the individual card design. This feature was already implemented previously the modal needs style enhancements. 

Location where modal needs to be added through include : https://github.com/meshery/meshery.io/blob/65d19db6ec1279c545b7dd9de2a7607e9cb1a0a6/catalog/index.html#L38

HTML file for modal:
https://github.com/meshery/meshery.io/blob/65d19db6ec1279c545b7dd9de2a7607e9cb1a0a6/_includes/modal.html

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ishan301** [comment]
Hi, I would like to work on this issue.

**Comment by asubedy** [comment]
Sure 🚀

**Comment by ishan301** [comment]
@asubedy I have fixed the issue and raised a PR for the same. Can you please review it?
