### ISSUE TITLE
Radio buttons are not displaying properly on mobile devices.

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1126]
### Description

Radio buttons are not displaying properly on mobile devices.

### Expected Behavior
Radio buttons should be displayed properly on mobile devices.

### Screenshots

<img src="https://user-images.githubusercontent.com/91362589/232561937-7ddfb6fe-79bb-4239-ad81-27de15adef1f.jpg" width="400">

### Enviroment:
 - Browser: Chrome 
 - Device: Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Simar-malhotra09** [comment]
I'd be more than happy to take this issue @leecalcote

**Comment by leecalcote** [comment]
Thanks, @Savio629 @Simar-malhotra09 👍

**Comment by Savio629** [comment]
Actually I was working on this issue...

**Comment by Simar-malhotra09** [comment]
Thank you and I will!

**Comment by Savio629** [comment]
@Simar-malhotra09 Updates?

**Comment by Simar-malhotra09** [comment]
Apologies, I should've updated earlier but i'm kind of having a setback. I just got a mac, and I'm having some trouble seetign up the local environment. I'm pretty sure I've figured out the issue; we add a media query w max width 600px and use transform prop to change scale. It's just im not been able to test it. i'm sorry but on what slack channel should i ask for help?
Thank you

**Comment by Savio629** [comment]
No worries. @Simar-malhotra09 
You can ask on `#general` channel on [Slack](https://slack.layer5.io/) or you check out [Community Forum](https://discuss.layer5.io/) for any solutions.

**Comment by Savio629** [comment]
@Simar-malhotra09 
any updates?

**Comment by DarrenDsouza7273** [comment]
if @Simar-malhotra09 you aren't working on this issue can i work on it @Chadha93

**Comment by Chadha93** [comment]
Yes please, @DarrenDsouza7273. 
@Simar-malhotra09 given no updates on this, let's not squat on the issue and free it up for more contributors. @Simar-malhotra09 Sinal when you are back, we have plenty of new items for contributors.
