### ISSUE TITLE
Make buttons UX consistent across the site

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery.io#1128]
### Description

Currently the ux of  buttons in meshery site is not consistent as all buttons are same in ui. Somewhere we have hover, somewhere we have hover and scaling and this is making ux a bit bad and creating ui bugs.

https://user-images.githubusercontent.com/90546692/233201764-943a33cc-6666-4494-9065-6b4f54c6a0b6.mp4

https://user-images.githubusercontent.com/90546692/233201995-5c5f4504-f3f7-4421-895e-07a8d25c5ebe.mp4

in https://meshery.io/blog

https://user-images.githubusercontent.com/90546692/233202401-a5d3afb8-846b-49a9-b830-3910cedc1ba5.mp4

### Expected Behavior

for now expected behaviour across all buttons should be in homepage https://meshery.io/ in `view catelog` button has
![image](https://user-images.githubusercontent.com/90546692/233202847-bfd9bb33-02a8-493f-bfa9-a57e36d3efd7.png)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Saksham294** [comment]
@sudhanshutech I'd like to work on this

**Comment by Saksham294** [comment]
Hey @vishalvivekm can you reopen this issue and close it with the PR.
