### ISSUE TITLE
Update Discussion Forum link

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1133]
### Description
Update Discussion Forum link

### Expected Behavior
On the meshery website replace the discuss forum link from https://discuss.layer5.io/ to http://discuss.meshery.io/
Note : The lack of “s” in http://discuss.meshery.io/ is intentional and the “s” is not to be added.

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by DarrenDsouza7273** [comment]
can i work on this issue
