### ISSUE TITLE
Integration name overflows or at the edge of card.

### ISSUE THREAD

**Issue by eagerashwani** [meshery/meshery.io#1137]
### Description
In the integration section, when we hover on icons that contains large text (3-4 words), it looks not so good. Please look at the below SS.

### Expected Behavior
Text Content must be inside the boundries of Integration Icon Card.

### Screenshots
![Screenshot (53)](https://user-images.githubusercontent.com/34451016/233743315-800f552e-a701-4b8c-b1b6-a847e879115a.png)
Look that Postgres Database(CrunchyData)
![Screenshot (56)](https://user-images.githubusercontent.com/34451016/233743488-165aab50-6727-49e6-96c6-542b23a489f5.png)
Now, look into this, isn't it looks good?

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by eagerashwani** [comment]
Hey @leecalcote , assigned it to me🤘

**Comment by leecalcote** [comment]
Good stuff, @eagerashwani
