### ISSUE TITLE
[Bug] Text not visible in dark mode

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery.io#1141]
### Description
Text not visible in dark mode for the "Build and Deploy" section and "Test" section in any web assembly filters -> [link](https://meshery.io/catalog/wasm/http-auth/)

### Expected Behavior
The text color should be changed so that it is visible in dark mode

### Screenshots
![Screenshot (108)](https://user-images.githubusercontent.com/51539117/235079533-a61e4d5d-9b1e-4e86-9864-4c1254ffa541.png)

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Sumitmaithani** [comment]
This issue is duplicate of this [issue](https://github.com/meshery/meshery.io/issues/1112)

**Comment by ritiksaxena124** [comment]
Ohh yes, thanks @Sumitmaithani for pointing that out.

Closing this
