### ISSUE TITLE
[UI] Create a flyer that showcases Meshery's stats.

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1142]
### Current Behavior
We need a flyer that showcases Meshery's stats and invites others to contribute to the project.

### Desired Behavior
Create a flyer that showcases Meshery's stats and which invites others to contribute to the project.

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Savio629** [comment]
@leecalcote @ritiksaxena124 
Thoughts or any Feedbacks?
I feel there are some adjustments needed....
![flyer](https://user-images.githubusercontent.com/91362589/235373004-b491ced8-e7e0-4428-b50c-f9c920a4c9cf.PNG)

**Comment by vishalvivekm** [comment]
cool @Savio629 
let's get others feedback too : add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) // @ritiksaxena124

**Comment by ritiksaxena124** [comment]
Hey @Savio629 you are doing a great job, it looks really cool 🔥. I have put some suggestions on the flyer Figma file you can check them else GREAT JOB!!

**Comment by Savio629** [comment]
Redesigned by @ritiksaxena124 
![playground](https://github.com/meshery/meshery.io/assets/91362589/1818a613-44fa-4a91-994c-0cbc87cee656)
