### ISSUE TITLE
Refactor text color styling to be applied in the include file

### ISSUE THREAD

**Issue by Sumitmaithani** [meshery/meshery.io#1148]
### Description
The current way text color style is implemented in the codebase, specifically in this [PR](https://github.com/meshery/meshery.io/pull/1124), is not optimal for maintaining the styling code. By applying the style inline, it becomes difficult to manage and read the code.

### Expected Behavior
The styling code should be moved to the include file, which will make it reusable and easy to manage across the codebase. This will improve code readability and maintainability.

### Screenshots
N/A

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by yash37158** [comment]
I would like to fix this @Sumitmaithani

**Comment by Sumitmaithani** [comment]
@yash37158 
I am working on it. Thanks for showing interest in it! 😊
