### ISSUE TITLE
Grammatical Mistakes in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ShivangShandilya** [meshery/meshery.io#1154]
### Current State:

![image](https://user-images.githubusercontent.com/101946115/236926165-d12f1c68-390e-4098-b266-800ff81c2c6c.png)

So there are several mistakes here such as above highlighted ones

### Desired State:

Make necessary changes and rectify above mistakes

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by ShivangShandilya** [comment]
I think I myself will work on this one cause I know what all mistakes are there.

**Comment by arunavabasu-03** [comment]
Can you assign it to me !!

**Comment by vishalvivekm** [comment]
> It's a small issue and I think I myself will work on this one cause I know what all mistakes are there.

Great @ShivangShandilya, 
Are we getting a PR on it,before tomorrow's websites call?

**Comment by ShivangShandilya** [comment]
> > It's a small issue and I think I myself will work on this one cause I know what all mistakes are there.
> 
> Great @ShivangShandilya, 
> Are we getting a PR on it,before tomorrow's websites call?

Yup you'll see one in around 2 hours 😂

**Comment by ShivangShandilya** [comment]
> > It's a small issue and I think I myself will work on this one cause I know what all mistakes are there.
> 
> Great @ShivangShandilya, 
> Are we getting a PR on it,before tomorrow's websites call?

Yes you'll get one before tomorrow 🙌
