### ISSUE TITLE
[Homepage] Responsive design issue in getting started section

### ISSUE THREAD

**Issue by VishrutAggarwal** [meshery/meshery.io#1161]
### Description

I came across this issue on https://meshery.io/#getting-started.

There are multiple issues in this section:

1. Incomplete Title
2. Improper wrapping of text.
3. The text causing confusion ("There is no step 2. Login and manage..." appears as if there are multiple points in the second step).

### Expected Behavior

The Getting Started section should be easy to read and understand. The following should be the minimum fixes on this section:

1. Complete the title.
2. Fix wrapping of the text.

### Screenshots

![image](https://github.com/meshery/meshery.io/assets/71827366/77be7078-cc60-41b4-9076-f4a6d4904368)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by VishrutAggarwal** [comment]
I would like to work on this issue myself.
Can someone please assign me this issue?

**Comment by shirsho-roy** [comment]
I would like to work on this issue.Could someone assign it to me?

**Comment by Savio629** [comment]
@shirsho-roy Is the issue still something you're willing to address?

**Comment by SimardeepSingh1450** [comment]
@shirsho-roy  I'd like to work on this issue, also please if you can specify the working-directory/files regarding this issue it would be helpful, since I am kind of new to contributing to meshery.

**Comment by aabidsofi19** [comment]
Hello Meshery maintainers,

I would like to work on this issue , with experience in front-end development, I am confident in resolving this issue effectively. I would appreciate being assigned this task to contribute to the improvement of the Meshery experience for new users.

Thank you for considering my request.

Best regards,
Aabid Sofi

**Comment by VishrutAggarwal** [comment]
Hey @Savio629,

I wanted to confirm if this issue could be assigned to me since I commented at the start and there's still no one assigned to the issue.

**Comment by Savio629** [comment]
Thank you @SimardeepSingh1450 and @aabidsofi19 for showing interest!
Let @VishrutAggarwal work on this issue as he commented first.
You guys can check out other issues present in the respository
