### ISSUE TITLE
Issues on subscribe page

### ISSUE THREAD

**Issue by HetviSoni** [meshery/meshery.io#1165]
### Current Behavior
1) On https://meshery.io/subscribe page the color of buttons does not match with other buttons on different pages.
2) There is a grey color border which ig is not needed
<img width="959" alt="image" src="https://github.com/meshery/meshery.io/assets/76479104/8e09198e-2fa6-4e3e-a58a-86167ef51f1a">

3) There is no hover effect on the cards.

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by 8rxn** [comment]
Hey @leecalcote @Nikhil-Ladha  
I would like to work on this if such a change may be required.

**Comment by Nikhil-Ladha** [comment]
The button color can be updated to be consistent with the whole site, and the border could be removed.
We don't need a hover effect on the card, because the card is not clickable, only the buttons are.

**Comment by 8rxn** [comment]
@Nikhil-Ladha I have raised the PR. Could you please review it </>
