### ISSUE TITLE
Text visibility and copy button issue

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1169]
### Description
Text visibility and copy button issue on meshery catalog page.
The meshery Ui and Meshery Cli text isn't visible in the dark mode and the copy button isn't working.
Link : https://meshery.io/catalog -> import any catalog item

### Expected Behavior
The text should be visible and the copy button should work as intended.

### Screenshots

https://github.com/meshery/meshery.io/assets/91362589/7fb6ae91-fb1b-48ff-9ace-46dfa48ae5ee

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by DarrenDsouza7273** [comment]
can i work on this issue

**Comment by Savio629** [comment]
@DarrenDsouza7273 Yeah go ahead

**Comment by leecalcote** [comment]
In addition to the issue that has pointed out, the colors used in the tabbed menus is atrocious.

**Comment by DarrenDsouza7273** [comment]
thanks @leecalcote

**Comment by DarrenDsouza7273** [comment]
@vishalvivekm am currently working on the copy button facing some issues with it but the text visibility is done, i dont think so the "copied" text is necessary as for now so should i just create a pr for the text visibility? and then later on we can discuss regarding the "copied" text which gets triggered when we press the copy button.

**Comment by DarrenDsouza7273** [comment]
@vishalvivekm we can have a discussion regarding the "copied" text on trigger during the weekly meeting

**Comment by vishalvivekm** [comment]
That'll be really helpful @DarrenDsouza7273, 
Would you please add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) ?

**Comment by DarrenDsouza7273** [comment]
@vishalvivekm i definitely will give me like 10 mins

**Comment by DarrenDsouza7273** [comment]
@vishalvivekm should i create a pr for the text?

**Comment by Savio629** [comment]
You can create a pr for the text visibility and push the copy button commits to the same branch. If that makes sense to you...

**Comment by vishalvivekm** [comment]
> @vishalvivekm should i create a pr for the text visibility? 
> 

@DarrenDsouza7273 Thanks, there are two PRs open.
Would you check if they do cover and propose a fix for this issue.
#1148 #1114 // @Savio629

**Comment by vishalvivekm** [comment]
> #-1148 is related to catalog #-1114 is a pr related to this same issue. Thanks for pointing out that the pr for the issue was already created. @vishalvivekm Should we close this issue?

Yes closing this issue is ideal @Savio629 
Please offer your reviews gents, on the PR proposing a fix @Savio629 @DarrenDsouza7273 : https://github.com/meshery/meshery.io/pull/1151

**Comment by thisiskaransgit** [comment]
Closing as completed via #1153
