### ISSUE TITLE
[UI] Fix the Alignment of Layer5 logo with other logos

### ISSUE THREAD

**Issue by Mohith234** [meshery/meshery.io#1170]
#### Current State of the Meshery.io site

The layer5 logo image doesn't align with the other logos in heroes section of meshery.io

#### Desired State of the Meshery.io site

The logos must be aligned in order to maintain a good UI

![image](https://user-images.githubusercontent.com/88539464/239702408-9d0e9b5d-f879-4e56-b41f-1fe9d151ffc8.png)
---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Mohith234** [comment]
I can work on this !

**Comment by atharvashirdhankar** [comment]
https://github.com/meshery/meshery.io/pull/1152#issuecomment-1558713118 

@Mohith234 I think the Meshery logo inside the "used-by" section will be removed in the next rollout.

**Comment by thisiskaransgit** [comment]
Since @DarrenDsouza7273, is already taking care of the issue, closing this one, thanks for looking up the tho 😄
