### ISSUE TITLE
Overlapping filter Menu with filter Button and Design Catalog Component

### ISSUE THREAD

**Issue by Cvr421** [meshery/meshery.io#1171]
### Description

Overlapping filter Menu with filter Button and Design Catalog Component . In Mobile view
https://meshery.io/catalog/deployment
### Expected Behavior

Their should be space between both the filter button and Design catalog component

### Screenshots

ISSUE
![meshery_issue](https://github.com/meshery/meshery.io/assets/82499697/873e8a2e-5c5b-407b-987a-7d9d34a0fd68)

Expected Outcome
![meshery_solution](https://github.com/meshery/meshery.io/assets/82499697/2ca28883-242c-4985-b2be-33402047c782)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by thisiskaransgit** [comment]
The filter button is a dropdown component, which on expanded shows the options, we do not need to separate them. Increase the  bottom margin and row-gap for the filter wrapper, such that it does not overlap, any component in any scenario

**Comment by Cvr421** [comment]
ok @thisiskaransgit
