### ISSUE TITLE
[UI] Fix the Alignment of Layer5 logo with other logos

### ISSUE THREAD

**Issue by 0xt3j4s** [meshery/meshery.io#1175]
### Description

The layer5 logo image doesn't align with the other logos in the **USED BY** section of [meshery.io](https://meshery.io/)

### Expected Behavior

The Layer5 logo must be aligned with the other logos.

### Screenshots

![image](https://github.com/meshery/meshery.io/assets/75741089/a01b2e0d-caba-4472-9ed4-3434a4da08f9)

### Environment:
 - OS: Windows
 - Browser: Chrome 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by anand346** [comment]
please assign this issue to me , I would love to solve it

**Comment by Savio629** [comment]
@0xt3j4s @anand346 There's already a open issue #1146 
I'll be closing this issue, you can work on some other issues...

**Comment by Savio629** [comment]
@0xt3j4s @anand346 There's already a open issue https://github.com/meshery/meshery.io/issues/1146
I'll be closing this issue, you can work on some other issues...

**Comment by 0xt3j4s** [comment]
@Savio629 But that issue is regarding the visibility and this one is regarding the alignment.

**Comment by Savio629** [comment]
In recent meeting we had discussed to completely remove meshery logo
