### ISSUE TITLE
New Section for GitOps Integration 

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1180]
Create a new section describing GitOps integration on the Meshery website
---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thank you, @thisiskaransgit

**Comment by aabidsofi19** [comment]
Hey @thisiskaransgit  I would like to work on this ..

**Comment by shadow0500** [comment]
Can I work on this?
