### ISSUE TITLE
[UI] Text-invisiblity in integrations page

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery.io#1181]
### Description

Currently the text isnt placed correctly and its also causing invisiblity dark mode

![image](https://github.com/meshery/meshery/assets/59855919/8675a2dd-03f2-4e95-8762-3c072d097397)

### Expected Behavior

We could remove the extra space from the top and use this to utilize the text-boxes.
![image](https://github.com/meshery/meshery/assets/59855919/f5c34649-55fa-4962-a922-6c240889713e)
![image](https://github.com/meshery/meshery/assets/59855919/cdf99915-8972-4077-9e27-9aa5f34447b2)
![image](https://github.com/meshery/meshery/assets/59855919/20dcc80d-9ceb-4e93-999b-20156c23ee2e)

![image](https://github.com/meshery/meshery/assets/59855919/287adc04-0903-49db-89a2-a48529be90da)
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ghat0tkach** [comment]
> Thanks for calling this out, @Ghat0tkach. Is this an issue that you would like to work on?

yes lee i would love to work on this issue , but i would take some time to solve this as i know how to solve this issue using the custom broweser-inspection tool . However unfamiliarity with the tech stack will result in delay.Is it fine with you?

Thank you

**Comment by leecalcote** [comment]
Thank you for setting expectations, @Ghat0tkach. This helps a good bit. Yes, let's see how far you're able to get along...

**Comment by Ghat0tkach** [comment]
> Thank you for setting expectations, @Ghat0tkach. This helps a good bit. Yes, let's see how far you're able to get along...

Yes @leecalcote , Thanks for understanding won't disappoint you!

**Comment by Ghat0tkach** [comment]
is already been fixed by #1209
