### ISSUE TITLE
Add "Star the Repository ⭐ " button for Meshery 

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1183]
### Current Behavior
Add a button on the HomePage to redirect the user to the [Meshery](https://github.com/meshery/meshery) Repository 

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Saksham294** [comment]
I'd like to work on this

**Comment by shadow0500** [comment]
Can I work on this?

**Comment by thisiskaransgit** [comment]
Following FCFS,  go ahead @Saksham294 🚀, thanks for volunteering @shadow0500, we often open beginner-friendly issues for new contributors to get started in their journey, be an active member in our community and we'll help you to land your first PR 😄

**Comment by Saksham294** [comment]
Hey @thisiskaransgit I would like to know if there is any design for the star button on the homepage, I couldn't find it in the figma design?
Thanks

**Comment by vishalvivekm** [comment]
@Saksham294 take inspiration from here: https://github.com/layer5io/layer5/pull/4370

**Comment by shadow0500** [comment]
> Following FCFS, go ahead @Saksham294 🚀, thanks for volunteering @shadow0500, we often open beginner-friendly issues for new contributors to get started in their journey, be an active member in our community and we'll help you to land your first PR 😄

Okay sure , I will look forward to grab the opportunity.

**Comment by leecalcote** [comment]
Do you mind going back into the history of this site? We had a star and a fork buttons with current count that would be ideal to resurrect.

**Comment by Saksham294** [comment]
<img width="451" alt="Screenshot 2023-06-21 at 10 07 28 PM" src="https://github.com/meshery/meshery.io/assets/86240862/6606cb13-a5a1-4e4f-92a0-bc32b1b8c6fb">
This @leecalcote ?

**Comment by Saksham294** [comment]
So we want to add fork button too apart from the star one?
