### ISSUE TITLE
Changes in filter on catalog page for mobile devices

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1185]
### Description
As we are not rendering cards for all option for mobile devices it's better if we remove 'All' option from catalog page for mobile devices.

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Rather, we need to get cards displaying in mobile view. We should still be able to have filters on the page, though. @vishalvivekm and @thisiskaransgit

**Comment by Savio629** [comment]
@thisiskaransgit and I thought of removing the all option.
If we need display the cards for mobile view I can do the required changes...
