### ISSUE TITLE
Community calendar events not being added to google calendar.

### ISSUE THREAD

**Issue by joshboye** [meshery/meshery.io#1188]
### Description

There seems to be an issue when certain events are clicked in the community calendar, where it shows `cannot open the requested event` in google calendar, specifically for the _website weekly call_ and _Meshery development meeting_ events (other events like layer5 newcomers meet is working fine). 

Link for community calendar - https://meshery.io/calendar
### Expected Behavior

When the specific events are clicked, the event should be added to the google calendar to the specific date and time.
### Screenshots

https://github.com/meshery/meshery.io/assets/32410081/578e1726-8fe5-4859-85a6-f03eb6c25d17

### Enviroment:
 - OS: Windows
 - Browser: Chrome Firefox
 - Device: Desktop 

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
@joshboye both the websites as well as development meeting's events work just fine for me.
Are you trying to access the events with some different email than the one you used while filling in the [newcomers form](https://layer5.io/newcomers) ?

**Comment by Ghat0tkach** [comment]
its working fine for me as well

**Comment by joshboye** [comment]
I guess this might be a system specific issue of mine. I was using the email id given in the newcomers forum. I shall close the issue.
