### ISSUE TITLE
 Visualization Sizing on Meshery Integrations Page 

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1190]
### Description
 Upon visiting the [Meshery integrations](https://meshery.io/integrations) page,  the visualization does not fit on the screen properly. This causes some visual elements to be cut off and makes it difficult to view all relevant information.
 
### Expected Behavior
The visualization on the Meshery integrations page should be adjusted so that it fits properly onto the screen

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ghat0tkach** [comment]
i already opened this issue in #1181 and fixed in pr #1189

**Comment by thisiskaransgit** [comment]
@Ghat0tkach, this is different, the table view of the visualization is not positioned in the center, and we have to fix that issue.
