### ISSUE TITLE
Text Visibility issue inside Introduction to Meshery Popup in Dark Mode

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1196]
### Description
Text Visibility in Introduction to Meshery Popup in Dark Mode
Link: https://meshery.io/talks-and-presentations (Click on 'Find Videos and Slides here' button)

### Expected Behavior
The text (An Introduction to Meshery CNCF Webinar on Demand) should visible in dark mode.

### Screenshots

![mesherytext](https://github.com/meshery/meshery.io/assets/91362589/abc52acd-bac9-441b-a87b-5a7899f7b556)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by niranjan-kurhade** [comment]
Can you assign it to me?

**Comment by vinyashegde** [comment]
Also can you assign it to me?

**Comment by thisiskaransgit** [comment]
Following FCFS, go ahead @samyakshah3008  rocket, thanks for volunteering @niranjan-kurhade and @vinyashegde, we often open beginner-friendly issues for new contributors to get started in their journey, be an active members in our community and we'll help you to land your first PR smile.

**Comment by samyakshah3008** [comment]
Hi @thisiskaransgit @Savio629 can you please provide the Figma design which we have for "dark theme modal"? 
I assumed the color according to the overall meshery website and edited the modal. 

Current design: 

![image](https://github.com/meshery/meshery.io/assets/86982322/f2628cdf-d592-4e80-88c7-e0d53aa5934c)


Probable Expected design one: 

![image](https://github.com/meshery/meshery.io/assets/86982322/9efbf63c-fb66-42db-820d-85b0678180aa)

Probable Expected design second: 

![image](https://github.com/meshery/meshery.io/assets/86982322/6a4d3a87-6655-4a45-b071-02152805e47a)

Probable Expected design third: 

![image](https://github.com/meshery/meshery.io/assets/86982322/f6ef4ffe-1b2b-42d4-b14f-fc5be1d9d203)

**Comment by samyakshah3008** [comment]
@thisiskaransgit by second do you mean probable design one or probable design second? Just to confirm. 
Also about the cross, yes I will take care of it! 

Cheers.

**Comment by Savio629** [comment]
My vote goes for expected design one!
As Karan mentioned do take care of the cross button...

**Comment by samyakshah3008** [comment]
Cool, 
I have raised a PR, please check @Savio629 @thisiskaransgit 😄

**Comment by thisiskaransgit** [comment]
Closed as Completed via #1199
