### ISSUE TITLE
Brainstorm for better content for contributors profile page in meshery.io

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery.io#1197]
#### Current State of the Meshery.io site

Right now in page https://meshery.io/community/ we used to show contributors profile which is no longer maintained and the contributor section is shift to layer5 website. So we are no in need of that page.

#### Desired State of the Meshery.io site

We need to replace the page with meaningful content which can help contributors to get help from or page which should basically describe the community more well so that any member should get familiar with. We need some brainstorming ideas.
When we fixed some idea will close this issue and open another to work on.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Ignoring design and style, we'll want to ensure that at least this information is offered - https://github.com/meshery/meshery#join-the-meshery-community. The calendar can also be published on this same page (while still staying published under /calendar, too).

**Comment by Ghat0tkach** [comment]
We have a [thread](https://discuss.meshery.io/t/share-your-experiences-in-contributing-to-meshery/2832/7) on discuss.meshery.io .
I probably think its a good section to add  in order to encourage newcomers.

We could also exhibit the perks they get (in form of community members) if they are consistent and helpful while contributing.


Could also provide them links of resources to start their journey (the service mesh books as well as tutorials available).

Can also show a glimpse of newcomers meetings which happens weekly.

What are your thoughts on this @sudhanshutech ?

**Comment by Savio629** [comment]
We can maybe show good-first-issue or any design related or stale issues on the website which will redirected to the actual issue/feature.
Ref: https://www.asyncapi.com/community/dashboard

**Comment by vishalvivekm** [comment]
A good topic to discuss in the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk), if you would :)
// @sudhanshutech @Ghat0tkach @Savio629

**Comment by sudhanshutech** [comment]
That was a good reference @Savio629 @Ghat0tkach and keeping in mind @leecalcote points we can start with some mockup in figma.
@Ghat0tkach or @Savio629 do you guys want to try hands on?
Points to prepare a mockup:
1. Informataion of joining community with buttons for github(meshery), calendar,  and more important info from here [Info](https://github.com/meshery/meshery#join-the-meshery-community)
2. Some glimpse of newcomers meet would be good
3.  And reference provided by Savio on issues to show

**Comment by Savio629** [comment]
Are we going ahead with the mentioned points? @sudhanshutech

**Comment by sudhanshutech** [comment]
@Savio629 yes we can start with the mentioned points, lets have a mockup

**Comment by Ghat0tkach** [comment]
> @Savio629 yes we can start with the mentioned points, lets have a mockup

We have to create mockups as different components on figma for different devices. Right?

**Comment by Savio629** [comment]
Yes @Ghat0tkach 
Initially we'll have a mockup for desktop only. Once it looks good, we can go ahead with creating designs for smaller devices.

**Comment by Ghat0tkach** [comment]
> Yes @Ghat0tkach Initially we'll have a mockup for desktop only. Once it looks good, we can go ahead with creating designs for smaller devices.
Thanks for the guidance @Savio629  , currently a newbie in figma will create my mockups by this weekend.

**Comment by ankur0904** [comment]
@sudhanshutech We can also add the `general flow of contributions` . 
- About the projects 
- Flow of contribution (clone the repo etc.)
-  If stuck anywhere, where to go for help 
-  Curate all the necessary resource (as @leecalcote mentioned ) 
       e.g. join-the-meshery-community, calendar etc.
- we can also add some blogs realted to the contributor

**Comment by sudhanshutech** [comment]
@Savio629 @Ghat0tkach any updates here?

**Comment by Ghat0tkach** [comment]
hey @sudhanshutech  , [here](
https://www.figma.com/file/DaWgFtcDXO0TeJOSzNnd60/Untitled?type=design&node-id=1%3A5&mode=design&t=DHY2xp3nAicB1GWs-1)i s my figma link for newcomer's meeting. First time using figma , was definately a hassle . Need your feedbacks to improve 🙌

**Comment by sudhanshutech** [comment]
Thank you every one we have a mockup up for the page so lets close this one and open another issue for that:
[Figma mockup](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16435%3A39494&mode=design&t=6qls5jOGn5gJKKgm-1)
