### ISSUE TITLE
[Site] Update Internship programs content

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery.io#1200]
### Current Behavior
1. The Programs mentioned on the programs page are outdated with their timeline, it needs to be updated according to new timelines.
2. Content needs an update for each program - https://meshery.io/programs

### Desired Behavior
1. Refer to the page on Layer5.io - https://layer5.io/careers/programs to update the timelines and content of all programs. 
2. Remove the video (What does Layer5 mean) from each program and replace it with a graphic used in the Layer5 programs.
3. Add Internship FAQs.

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by samyakshah3008** [comment]
I would like to work on this issue! 🚀

**Comment by Naresh-chandanbatve** [comment]
hey @Chadha93 
I would like to work on this issue can you assign this to me?

**Comment by leecalcote** [comment]
@Naresh-chandanbatve how is this effort coming along?

**Comment by leecalcote** [comment]
Will you join tomorrow's Websites meeting and give an update? Meeting details - meshery.io/calendar. Please add an agenda item into the [meeting agenda](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by samyakshah3008** [comment]
@leecalcote I would like to work on this if naresh is not available. 😄

**Comment by leecalcote** [comment]
@samyakshah3008 thanks for volunteering here. If we don't hear from @Naresh-chandanbatve at tomorrow's meeting (in the meeting or asynchronously), let's see if you can't offer a helping hand. There are a number of pages to update, so there's some load to share. 👍

**Comment by samyakshah3008** [comment]
Sounds cool @leecalcote 👌

**Comment by samyakshah3008** [comment]
Hi @leecalcote 👋 
I see @Naresh-chandanbatve has still not showed up, I would like to work on this if you permit. 
As I see if there are bunch of changes to be done, Me and @HarshDobariya79 can collab and work on sub-tickets at the same time and get the work done to the soonest!

**Comment by HarshDobariya79** [comment]
I would like to work on this issue 😀

**Comment by samyakshah3008** [comment]
> I would like to work on this issue 😀

Yay!

**Comment by Chadha93** [comment]
Thanks, gents, since not heard from @Naresh-chandanbatve, let's assign this to @samyakshah3008 and @HarshDobariya79 .

**Comment by samyakshah3008** [comment]
Cheers! @Chadha93 👌

**Comment by thisiskaransgit** [comment]
Hey, @HarshDobariya79 and @samyakshah3008, wanted to check in on the progress. We appreciate your contribution and would love to know if you are still actively working on it. It would be better if there's a PR open to track the progress.

**Comment by samyakshah3008** [comment]
Hi -- @thisiskaransgit thanks for checking out on the progress. 
As I mentioned in the slack about my OOO status, I am back to office from today and will be syncing up with Harsh to get the work done to the soonest. 

Update on the progress: 
Harsh has made progress but we both we down due to exams. 

Tentative deadline which I would like to give is 9th July when PR will be ready to review.

**Comment by HarshDobariya79** [comment]
@samyakshah3008 Due to some health conditions I'm on total rest, so I won't be able to collaborate on this one. So let's not waste time and can you please go ahead with this issue?

**Comment by ranjanmangla1** [comment]
@samyakshah3008 assign me this issue, if you are not working on it

**Comment by samyakshah3008** [comment]
Sure @ranjanmangla1 thanks for leading. 
Please go ahead. 

Since I am already working on other issue ticket, to make the work faster, it's always better to share the load. 
Good luck and let me know if you are facing any blockers.

**Comment by thisiskaransgit** [comment]
@ranjanmangla1, I'm taking this one off your list, since you're already working on multiple issues at this time, let's make sure they get merged. Thank you for volunteering 😄

**Comment by lanzkrish** [comment]
Hey, If no one is working can I work on this?
