### ISSUE TITLE
[Site] Enhance and update the features page

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery.io#1201]
#### Current State of the Meshery.io site
The whole features page needs to be refactored in terms of UI and content. The content is outdated and needs to be updated with the latest features.

#### Desired State of the Meshery.io site
1. Refer to this feature page on layer5.io - https://layer5.io/cloud-native-management/meshery to implement the new for this site.
2. Also mention Meshery's extensibility features - Meshery Extension, Catalog, Snapshot. 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaibhav-xt** [comment]
I would like to work in collaborations with someone who has experience. As a new commer, I will learn a lot and will able to contribute deeply.

**Comment by ankur0904** [comment]
I want to work on this issue.

**Comment by Savio629** [comment]
Are you still up to take up on this issue @ankur0904 ?

**Comment by ankur0904** [comment]
@Savio629 Yes 👍

**Comment by Chadha93** [comment]
@ankur0904, thank you.

**Comment by vishalvivekm** [comment]
@ankur0904 What's the update on the issue?

**Comment by ankur0904** [comment]
@vishalvivekm I setup the project locally, made the required change in content of the /features route

**Comment by thisiskaransgit** [comment]
Since the assignee, isn't actively working on this issue ([ #comment](https://github.com/meshery/meshery.io/pull/1268#issuecomment-1643553036) ) I will be taking over this one.
