### ISSUE TITLE
[Site] Enhance Community Calendar page

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery.io#1202]
#### Current State of the Meshery.io site
The content, styles, and links need to be enhanced with the latest information. 

#### Desired State of the Meshery.io site
1. Eliminate the extra whitespace between the header and the community calendar section. 
![image](https://github.com/meshery/meshery.io/assets/65453826/3b0f0858-36db-48f2-8b92-80ff089800ac)
2. Update the link for the welcome guide to - https://layer5.io/community/newcomers.
3. Don't use italics in the community links section.
4. Add a CTA (Call to action) for newcomers welcome, ref - https://layer5.io/community/calendar

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaibhav-xt** [comment]
I want to work on this issue.

**Comment by gaurab-khanal** [comment]
@Chadha93 Can you please assign me this issue? I am a beginner and as a beginner, this issue is beginner friendly.

**Comment by Chadha93** [comment]
Thanks for volunteering guys, @vaibhav-xt Since you got another issue assigned, let's give this opportunity to @gaurab-khanal.

**Comment by gaurab-khanal** [comment]
@Chadha93 I couldn't find the file where I can make a change regarding the 2nd and 3rd point changes above. Also, should I add  CTA (Call to action) in program-block class?

**Comment by gaurab-khanal** [comment]
> @gaurab-khanal for the 2nd and the 3rd point you can go to _includes\partials\community.html and change there.

Already made those changes. I am confused about 4th one. Unable to understand the problem statement.

**Comment by Mohith234** [comment]
> Already made those changes. I am confused about 4th one. Unable to understand the problem statement.

- You need to add a CTA for newcomers. For reference, check this site - https://meshery.io/community/calendar 
- You just need to implement a similar CTA on the page you're working on

@gaurab-khanal

**Comment by gaurab-khanal** [comment]
> > Already made those changes. I am confused about 4th one. Unable to understand the problem statement.
> 
> * You need to add a CTA for newcomers. For reference, check this site - https://meshery.io/community/calendar
> * You just need to implement a similar CTA on the page you're working on
> 
> @gaurab-khanal

![image](https://github.com/meshery/meshery.io/assets/40165867/6746ca02-371f-4bfe-8885-4c611e9ee91e)

Do you mean I need to implement this image?
What should I add instead of Newcomers' Guide, Community Guide, MESHMATE, Newcomers' Meeting, Repository Overview? 

@Mohith234

**Comment by thisiskaransgit** [comment]
@gaurab-khanal, What's your progress?

**Comment by thisiskaransgit** [comment]
@Mohith234 @Gautam-666, if any of you are looking to work on this, please signal.

**Comment by Gautam-666** [comment]
You can assign me this....i would love to work on this

**Comment by thisiskaransgit** [comment]
Hey @Gautam-666, wanted to check in on the progress. We appreciate your contribution and would love to know if you are still actively working on it. It would be better if there's a PR open to track the progress.

**Comment by Gautam-666** [comment]
I have completed the first 3 issues I am facing issue in recreating the
image for the CTA Section.

**Comment by thisiskaransgit** [comment]
@Gautam-04, any updates on the task?

**Comment by Gautam-04** [comment]
Karan you can assign it to someone else since I won't be able to complete
it .
Reason:-
https://meshery.slack.com/archives/CDMAJJ0CW/p1689520866921499?thread_ts=1689520866.921499&cid=CDMAJJ0CW
