### ISSUE TITLE
[Site] [Dark Mode] Update import catalog modal according to theme

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery.io#1203]
#### Current State of the Meshery.io site
Dark mode issues with modals:
The text is not visible in dark mode. 
1. Import catalog item modal.
![image](https://github.com/meshery/meshery.io/assets/65453826/7178060f-a484-4491-9dea-6543eb8db2da)

#### Desired State of the Meshery.io site
Update modal text and icons according to dark mode. 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaibhav-xt** [comment]
@Chadha93 
Hey, I want to work on this issue. Please assign it to me.

**Comment by rush33** [comment]
@Chadha93 I kindly request permission to resolve this issue. Thanks!

**Comment by Chadha93** [comment]
Thanks for volunteering, guys! Assigning in chronological order...

**Comment by Savio629** [comment]
@Chadha93 Can you look at this closed issue? #1169 
Sudhanshu was already working on it but his pr was closed and after that I guess @thisiskaransgit misunderstood the issue with the some other pr...

**Comment by thisiskaransgit** [comment]
@vaibhav-xt, what's your progress?

**Comment by vaibhav-xt** [comment]
@thisiskaransgit 
Since I was not active for 3-4 days. I'll be make pr tomorrow.

**Comment by Savio629** [comment]
@vaibhav-xt There's also an issue present on catalog light theme
![catalog-light](https://github.com/meshery/meshery.io/assets/91362589/d5bab8e3-cf49-4df7-a911-0e84ec0b5f8d)

**Comment by vaibhav-xt** [comment]
@Savio629 I'll do it. Nice Catch!😎

**Comment by vaibhav-xt** [comment]
@Chadha93 please have a look now.
