### ISSUE TITLE
Error in MakeFile

### ISSUE THREAD

**Issue by gaurab-khanal** [meshery/meshery.io#1204]
### Description

`make site` command throws error
error: `bundle install; bundle exec jekyll serve --drafts --livereload
Could not find command "install;".
Did you mean?  "install"
make: *** [Makefile:4: site] Error 15`

### Expected Behavior

`make site` command should work

### Screenshots

![image](https://github.com/meshery/meshery.io/assets/40165867/994a5159-9a60-4043-9093-b2c85e7f48aa)

### Enviroment:
 - OS:  Windows 10
 - Browser: Chrome 
 - Version: Ruby- 2.7.5
 - Device: Laptop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by gaurab-khanal** [comment]
Can I work on this issue? Please assign me this issue.

**Comment by Rajivkumawat3** [comment]
can you please assign me this issue . I want to work on this issue .

**Comment by gaurab-khanal** [comment]
Remove semi colon and break the line after semi colon. No need to remove -livereload. It will avoid automatic reload.

**Comment by vishalvivekm** [comment]
@gaurab-khanal Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by gaurab-khanal** [comment]
@vishalvivekm I missed it. will add to next week meeting

**Comment by gaurab-khanal** [comment]
> @gaurab-khanal, Kindly add information about your Development environment, and how you got stumbled upon this issue, I don't see any reason why it should not work. The message clearly states that an error occurred since the terminal interpreted the semicolon(;) as a part of the install command. Please confirm that you have all the prerequisites installed on your system by including their version numbers in the issue description.

@thisiskaransgit I have added the development environment. Can you look into it?. Now I am facing new error. I can't even run project locally. Can you help me?

**Comment by gaurab-khanal** [comment]
@thisiskaransgit I have mentioned the issue here briefly.  https://discuss.meshery.io/t/unable-to-setup-meshery-io/2970

**Comment by gaurab-khanal** [comment]
> @gaurab-khanal Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

How can I add? I am new to it. @vishalvivekm

**Comment by vishalvivekm** [comment]
For Meshery Development call 7:30 PM IST Today, add this as an agenda item in the  [Meeting Docs](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#).
