### ISSUE TITLE
Text color in the background of video in pattern section not visible in light mode

### ISSUE THREAD

**Issue by VishwaRaval247** [meshery/meshery.io#1205]
### Description
In the pattern section of the [https://meshery.io/](url) website, located below the integration section, there is a video where in the background text is not visible in light mode.
### Expected Behavior
The text in the background of the video to be visible in light mode, maintaining consistency with the rest of the website's design.

### Screenshots
Dark Mode:
![Screenshot from 2023-06-21 11-54-12](https://github.com/meshery/meshery.io/assets/97004502/3850f418-da3d-4a4b-93ac-36d4251c1c4c)

Light Mode:
![Screenshot from 2023-06-21 11-55-19](https://github.com/meshery/meshery.io/assets/97004502/c7627252-c889-45d9-bc11-6e5a0bc186f2)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by VishwaRaval247** [comment]
I would like to work on this issue, can you please assign it to me.

**Comment by Rajivkumawat3** [comment]
I would also like to work on this issue. Could someone please assign it to me?

**Comment by Rajivkumawat3** [comment]
Can I work on this issue? Please assign me this issue.

**Comment by anshgoyalevil** [comment]
Assigning in chronological order. Here you go @VishwaRaval247 🛫
