### ISSUE TITLE
Potential bug in login and playground access

### ISSUE THREAD

**Issue by Boombag0607** [meshery/meshery.io#1206]
**How can we help?**
Is there an existing issue in the **layer5.io** and **meshery.io** website login? I was able to access the Meshery playground with this [link](https://play.meshery.io/), after filling out the Community Member form, but as soon as I logged out, I could not access it. Moreover I logged in with my Github account but can't login again because it keeps redirecting to the signup page, it seems. Can anybody reproduce this?

**Comment by leecalcote** [comment]
@Boombag0607 thanks for raising this question. When you visit https://playground.meshery.io, are you able to login successfully?

**Comment by Boombag0607** [comment]
@leecalcote
1. This link directs me to the login page
2. I click Sign in with Github since I used my GH account to sign up
3. It redirects to the signup page 
4. I click continue which and returned response is "An account with the same identifier (email, phone, username, ...) exists already."
Same thing happens with the Google Account.

**Comment by leecalcote** [comment]
When did you first sign up for playground access (what date)? Try the "forgot my password" link.

**Comment by Boombag0607** [comment]
I signed up and could access the playground on 20/06/2023 (dd/mm/yyyy). "forgot my password" kind of worked, it logged me into "meshery.layer5.io" but I still can't seem to access the playground. Directs to the signup form "[https://play.meshery.io/#signup-form](https://play.meshery.io/#signup-form)".

**Comment by MUzairS15** [comment]
@Boombag0607 thanks for raising this concern, we will look into this issue.
We will also require more inputs about your scenario  as we debug this issue

**Comment by Boombag0607** [comment]
@MUzairS15 I looked into the code and could not find the authentication code for the playground; if you can point it out, I can see if anything works.

**Comment by MUzairS15** [comment]
@Boombag0607 as a workaround, what you can do is, go to meshery.layer5.io, copy the link that you received in the email and then it should ask you to enter `recovery code` (which is provided in the email itself)

Try the above step once, I am hopeful you will be able to set up your account and access Playground.

**Comment by Boombag0607** [comment]
Oh I can access it now. I logged in the website yesterday. Thanks for the help.
