### ISSUE TITLE
Publish "Changing Release-Channels" blog 

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1207]
The blog on [Changing Meshery Release channels](https://layer5.io/blog/meshery/changing-meshery-release-channels) has been published on [Layer5.io](https://layer5.io/) website, we need the same blog to be published on [meshery.io/blogs](https://meshery.io/blog) too

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Mohith234** [comment]
I would like to work on this. This will be my first contribution to meshery.

**Comment by ranjanmangla1** [comment]
hi @thisiskaransgit , I am new to open source and the community, would love to contribute in this issue. Kindly assign me this issue.

**Comment by Manish254252** [comment]
Hello If no one is working on this please assign this to me ?

**Comment by vishalvivekm** [comment]
@Mohith234 update?

**Comment by Mohith234** [comment]
@vishalvivekm Sorry, I wasn't available these 2 days. I will raise a PR by today evening mostly.
