### ISSUE TITLE
Error: YAML Exception Reading 

### ISSUE THREAD

**Issue by vaibhav-xt** [meshery/meshery.io#1208]
### Description

On running the command `make site` it shows me an error. A small update needs to both files. 
![Screenshot (86)](https://github.com/meshery/meshery.io/assets/90946899/936b29cc-5ee2-4baa-a13a-f215fbb6bf04)

##### [Here is the link to one of the files:](https://github.com/meshery/meshery.io/blob/master/collections/_catalog/deployment/2df29b2b-7e5e-4d8b-a5b3-3dea569f4d25.md) 
![Screenshot (88)](https://github.com/meshery/meshery.io/assets/90946899/19a79bd3-b5fc-4ffb-80d5-fe2c154b6d53)

### Expected Behavior

Don't show any errors. 

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaibhav-xt** [comment]
I would like to work on this issue.

**Comment by Rajivkumawat3** [comment]
@vaibhav-xt have you solved YAML error .

**Comment by vaibhav-xt** [comment]
@Rajivkumawat3 yes I solved issue and raised pr.

**Comment by Rajivkumawat3** [comment]
ok because I also had solved this issue

**Comment by theBeginner86** [comment]
We can mark this as completed.
Thanks @vaibhav-xt for raising this issue. 👍
