### ISSUE TITLE
 ERROR:  2.7/rubyeventmachine (LoadError)

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery.io#1210]
###  Description:
On running the command "bundle exec jekyll serve --drafts --livereload" it shows me an error. 

###  Expected Behavior:
Don't show any errors.

### Screenshots
<img width="960" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/95c3da26-cf73-4974-8732-3101f50edbf7">

 ###Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajivkumawat3** [comment]
I would like to work on this issue.

**Comment by Rajivkumawat3** [comment]
I want to work on this issue . can you assign this issue to me .

**Comment by Savio629** [comment]
You can overcome this issue by just running `bundle exec jekyll serve --drafts` and skipping --livereload

**Comment by Savio629** [comment]
@Rajivkumawat3 If you face any issue while setting up, do search on discuss.meshery.io or ask doubts on Slack

**Comment by Rajivkumawat3** [comment]
@Savio629 when i run command without --livereload then it also shows YAML error

**Comment by Savio629** [comment]
Try running `gem install eventmachine --platform ruby`
and then `bundle exec jekyll serve`
If this still doesn't work open a post on [discuss.meshery.io](https://discuss.meshery.io/)
