### ISSUE TITLE
kuma.svg file is missing

### ISSUE THREAD

**Issue by vaibhav-xt** [meshery/meshery.io#1212]
### Description

Kuma.svg file is missing. 

### Expected Behavior

Not show any errors.

### Screenshots

![Screenshot (92)](https://github.com/meshery/meshery.io/assets/90946899/bb11ab08-d34d-4a48-a3dd-ad173e5eaf1f)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaibhav-xt** [comment]
@Chadha93 I want to work on this issue. Can you please assign it to me?

**Comment by Chadha93** [comment]
@vaibhav-xt Thanks for opening up the issue, could you also post a screenshot of the site where is the file missing, I see the issue in your terminal. :heavy_check_mark: 

Let's get it fixed.

**Comment by Chadha93** [comment]
@thisiskaransgit ^^

**Comment by vaibhav-xt** [comment]
@Chadha93 
There is no issue with my local setup. I found that the file is missing in the upstream repository. Search `kuma.svg` file in [directory](https://github.com/meshery/meshery.io/tree/master/assets/images). And this error occur on visiting Resources/Cloud-Native-Catalog

Here is the screenshot:
![Screenshot (95)](https://github.com/meshery/meshery.io/assets/90946899/2192c9e0-d290-44b3-a1a0-ee606e8f69d7)
![Screenshot (94)](https://github.com/meshery/meshery.io/assets/90946899/25b1cca2-ee73-45db-bb93-19196f0c552c)

**Comment by Chadha93** [comment]
Good to go @vaibhav-xt :rocket:

**Comment by sambhavgupta0705** [comment]
@Chadha93 If this issue is  still open then can I work on it.

**Comment by vaibhav-xt** [comment]
Hey @sambhavgupta0705, Please look for another issue, currently I am working on this issue. The pr was closed by me due to the problems I was facing.
