### ISSUE TITLE
No dark mode for Twitter Timeline Widget [UI]

### ISSUE THREAD

**Issue by ranjanmangla1** [meshery/meshery.io#1213]
#### Current Behavior
There is no dark mode for twitter timeline in footer

#### Desired Behavior
The twitter timeline should also change with dark mode of site

#### Purposed Solution
The theme of widget can be changed according to the guidelines given here:
https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/cms-best-practices 

#### Screenshots/Logs
![image](https://github.com/meshery/meshery/assets/93506927/581ad0bd-45fb-4103-8fd8-f3549c9a7c35)

Please assign me this issue

**Comment by Savio629** [comment]
@ranjanmangla1 Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by thisiskaransgit** [comment]
Closing as due to duplication.
