### ISSUE TITLE
text not visible in dark mode

### ISSUE THREAD

**Issue by ranjanmangla1** [meshery/meshery.io#1214]
#### Current Behavior
The text 01 & 02 are not clearly visible
![image](https://github.com/meshery/meshery/assets/93506927/fa3b2d0f-57a4-479a-80b6-7b84de42b991)

here too:
![image](https://github.com/meshery/meshery/assets/93506927/dff1bc0e-f267-4f5c-9a25-de1680e1c71f)

#### Expected Behavior
The 01 & 02 should be green /black  in color or any other color

Please assign me this issue

**Comment by leecalcote** [comment]
Thank you for raising this up, @ranjanmangla1.

**Comment by vishalvivekm** [comment]
@ranjanmangla1 would you like to give an update?

**Comment by Ardent10** [comment]
Can I work on this ? @vishalvivekm @leecalcote

**Comment by thisiskaransgit** [comment]
Sure @Ardent10,  go ahead and fix it :rocket:

**Comment by Ghat0tkach** [comment]
its visible in mine however
![image](https://github.com/meshery/meshery.io/assets/59855919/24d0e02d-4211-4f0d-ace4-2f2ea640103f)

**Comment by Ghat0tkach** [comment]
//@thisiskaransgit

**Comment by thisiskaransgit** [comment]
Thanks @Ghat0tkach, yeah the adopter container looks fine, the step numbers can use another shade though, since we haven't heard back from @ranjanmangla1. Assigning the issue to @Ardent10 🚀 , for only updating the step-number color.

**Comment by ranjanmangla1** [comment]
@thisiskaransgit Sorry, I had been inactive for a week, i have solved this issue already, and i just have to make a pull request. Sorry, had been busy ,somehere. @Ardent10 , if you don't mind, can this issue be reassigned to me?

**Comment by Ardent10** [comment]
@ranjanmangla1 you can ask @thisiskaransgit.

**Comment by thisiskaransgit** [comment]
@ranjanmangla1, push the update please

**Comment by nakulbh** [comment]
@thisiskaransgit can i work on this issue

**Comment by Savio629** [comment]
Guys updates? @Ardent10 @ranjanmangla1

**Comment by ranjanmangla1** [comment]
Solved, sending a pr @Savio629

**Comment by ranjanmangla1** [comment]
hi @thisiskaransgit and @Ghat0tkach , i have fixed this, i have found another issue here in meshery.io: 
there is no hierarchy in headings of catalog, calendar, and programs, these headings convey an important info and should be highlighted.
Catalog:
![image](https://github.com/meshery/meshery.io/assets/93506927/5e7ab01c-9010-4acf-ae33-c6766bb24ba0)
![image](https://github.com/meshery/meshery.io/assets/93506927/c8988e6a-047c-476c-a8f8-dd302d4e2307)

Community Calendar
![image](https://github.com/meshery/meshery.io/assets/93506927/fb79e4d2-18a0-4a63-85aa-fa283febf147)
![image](https://github.com/meshery/meshery.io/assets/93506927/1896d298-6fc1-4201-8799-e929c6185f75)

Programs: 
![image](https://github.com/meshery/meshery.io/assets/93506927/f79a4cf0-d683-4983-aba9-0fdea04a5e1b)
![image](https://github.com/meshery/meshery.io/assets/93506927/f34d022a-0103-4ba9-a9f2-c43ac9cff0f4)

Should i modify this changes in pr of this issue itself as these are just minor changes or i should open a new issue?
