### ISSUE TITLE
Icons not visible in Dark Mode [UI] 

### ISSUE THREAD

**Issue by ranjanmangla1** [meshery/meshery.io#1215]
#### Current Behavior
GItHub Icons are not visible in Dark Mode, icons specifically for dark mode should be, also from an asthetic point of view their alignments are not correct

#### Desired Behavior
Specific icons should be used for dark mode

#### Screenshots/Logs
![image](https://github.com/meshery/meshery/assets/93506927/ace6f13a-fc9f-40bf-900a-bb68d033d1c4)

Please assign me this issue

**Comment by Vivek-Prajapatii** [comment]
Hi @ranjanmangla1 if anyone is not working on this you can assign this to me

**Comment by ranjanmangla1** [comment]
@Vivek-Prajapatii I am working on it!

**Comment by Savio629** [comment]
We don't require this change as this page is going to update with some new content.
More info: https://github.com/meshery/meshery.io/issues/1197
