### ISSUE TITLE
Responsiveness Issue at https://docs.meshery.io/v0.5/ 

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery.io#1216]
### Description
 Responsiveness issue at https://docs.meshery.io/v0.5/  , on this page .

### Expected Behavior
  page should be responsive for small devices also.

### Screenshots

<img width="270" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/c38c50c1-0fb3-4548-b645-c24bdaef4bda">

**at bottom of the page docker and message icons are not visiable , And youtube and Email icons are half visiable**

<img width="222" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/ae5647ee-6b4e-4df9-a1e9-3d2af64e20e9">

**meshery icon  and Meshery documentation is not fully visiable on the top of the page.**

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by DarrenDsouza7273** [comment]
Good catch @Rajivkumawat3

**Comment by Vivek-Prajapatii** [comment]
Hi @Rajivkumawat3 , if you are working on #1217 can i please work on this issue?
let me know

**Comment by thisiskaransgit** [comment]
@Rajivkumawat3 Thank you for your for addressing the issue of documentation responsiveness for older versions. We appreciate the time and effort you have put into this task.
However, we would like to request that moving forward, you focus your time and energy on fixing any issues related to our latest version(s). It is important that our current users have access to up-to-date documentation that reflects all relevant changes in functionality and features.
Just to be clear, for all the [docs.meshery.io](https://github.com/meshery/meshery.io/issues/docs.meshery.io) related concerns, you can find the source code in the [meshery repository](https://github.com/meshery/meshery/tree/master/docs).

Will be closing this issue and issue https://github.com/meshery/meshery.io/issues/1217, but thank you for your efforts!
