### ISSUE TITLE
Responsiveness issue at https://docs.meshery.io/v0.4/

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery.io#1217]
### Description
Responsiveness  issue at https://docs.meshery.io/v0.4/  and almost half page have is blank space .

### Expected Behavior
there should not be blank screen on right side in mobile devices  and website at this page should be responsive

### Screenshots
<img width="219" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/37feba16-96ab-40e9-800f-de05c8e051dc">

**Blank space at right of the page in mobile devices and not responsive**

<img width="219" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/523a2f9a-d9d5-400b-b138-7469fd8e93c2">

**at bottom some icons like docker are not visiable are also blank space** 
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajivkumawat3** [comment]
can you assign this issue to me . I want to work on this issue

**Comment by DarrenDsouza7273** [comment]
Great Catch @Rajivkumawat3

**Comment by Vivek-Prajapatii** [comment]
Hi , if anyone is not working on it, you can assign this to me
as i'm new to this project

**Comment by thisiskaransgit** [comment]
@Rajivkumawat3  Thank you for your for addressing the issue of documentation responsiveness for older versions. We appreciate the time and effort you have put into this task.
However, we would like to request that moving forward, you focus your time and energy on fixing any issues related to our latest version(s). It is important that our current users have access to up-to-date documentation that reflects all relevant changes in functionality and features. 
Just to be clear, for all the [docs.meshery.io](docs.meshery.io) related concerns,  you can find the source code in the [meshery repository](https://github.com/meshery/meshery/tree/master/docs).  

Will be closing this issue, but thank you for your efforts!

**Comment by Kevin-Usadadiya** [comment]
Can i work on this issue.

**Comment by Rajivkumawat3** [comment]
@Kevin-Usadadiya  i think  , there is no worthy to work on this issue because it is in older version .
