### ISSUE TITLE
Buttons and Zoom in or Zoom out related issue at  /integrations page 

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery.io#1220]
### Description
There is extra div and buttons should not be in mid of the container . another issue is that if we click anywhere on the page then the image zoom in or zoom out easily and hover on the text .

### Expected Behavior
  There should not be extra div and  buttons should be top of the container or bottom of the container . if we zoom the image then it's zooming behaviour should be inside it's container itself , it should not be efffected another container.

### Screenshots

<img width="653" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/a9da0011-eec0-4741-ac48-0f5a0be27e65">

<img width="552" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/9281b485-d8be-4f89-a80a-c0777359a628">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by thisiskaransgit** [comment]
- issue #1190

**Comment by thisiskaransgit** [comment]
@Rajivkumawat3,  We can close this one as the concerned issue has been taken care of, see the latest deployment for this. Thank you for looking up.

**Comment by thisiskaransgit** [comment]
@Rajivkumawat3,  We can close this one as the concerned issue has been taken care of, see the latest deployment for this. Thank you for looking up.
