### ISSUE TITLE
[UI] Unnecessary space and scrollbar in Meshery Cloud Website

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery.io#1221]
### Description

The login page of meshery cloud [website](https://meshery.layer5.io/login?flow=6664a086-713f-45e0-9906-d8779908e340)
has unecessary spaces in the the view which hinders the faq section. Also as per the norms , faq should be in uppercase.

![image](https://github.com/meshery/meshery.io/assets/59855919/8c67eb91-d565-47a0-b28f-2ba5788b234b)

### Expected Behavior

This eradicates the unecessary scrollbar .
![image](https://github.com/meshery/meshery.io/assets/59855919/79a9abd7-1305-4131-96ea-43250243ea60)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Kevin-Usadadiya** [comment]
Hey I would like to contribute on this issue as it is my First open source contribution.

**Comment by Ghat0tkach** [comment]
> Hey I would like to contribute on this issue as it is my First open source contribution.

Thanks for your interest @Kevin-Usadadiya  , however Im afraid this issue is for a private repository .
Don't worry I got you an issue , refer this [link](https://github.com/meshery/meshery-osm/issues/245)

**Comment by Kevin-Usadadiya** [comment]
![Screenshot (13)](https://github.com/meshery/meshery.io/assets/83108939/7531a3de-c8c4-431a-a452-44fa3531641b)

**Comment by Kevin-Usadadiya** [comment]
this is the change that i have made

**Comment by Kevin-Usadadiya** [comment]
> > Hey I would like to contribute on this issue as it is my First open source contribution.
> 
> Thanks for your interest @Kevin-Usadadiya , however Im afraid this issue is for a private repository . Don't worry I got you an issue , refer this [link](https://github.com/meshery/meshery-osm/issues/245)

Yes i could not found the link

**Comment by Ghat0tkach** [comment]
> > > Hey I would like to contribute on this issue as it is my First open source contribution.
> > 
> > 
> > Thanks for your interest @Kevin-Usadadiya , however Im afraid this issue is for a private repository . Don't worry I got you an issue , refer this [link](https://github.com/meshery/meshery-osm/issues/245)
> 
> Yes i could not found the link

just click on the link please , thanks a lot for your efforts however its a private repository and we wish to remove the extra white spaces

**Comment by Kevin-Usadadiya** [comment]
Okay, Thanks for the feedback.
