### ISSUE TITLE
Update calendar 

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery.io#1228]
### Description
Hii everyone, in desktop and mobile our calendar  is seems to be very awkward , the text inside dates are not proper and there is blue highlighter for text which is not matching idea .

### Expected Behavior
want to change this behaviour of calander , there should be like hover effecting or something else which can show our meeting content (edited) 

### Screenshots
<img width="267" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/9a5002e5-1f89-46a9-954d-c4d966956a6c">
<img width="191" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/ced86301-1b2b-4f1b-b9cf-48bcdb0319a5">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajivkumawat3** [comment]
can i work on this issue

**Comment by Ghat0tkach** [comment]
@thisiskaransgit isnt it duplicate issue for #1202 ?

**Comment by Rajivkumawat3** [comment]
@thisiskaransgit  made  pr , now all the text will visiable after hovering .
