### ISSUE TITLE
Extra apace between Navbar and starting text of the page 

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery.io#1229]
### Description
There is Extra apace between Navbar and starting text of the page  . here are some locations 
http://127.0.0.1:4000/catalog/
http://127.0.0.1:4000/talks-and-presentations
http://127.0.0.1:4000/programs/
http://127.0.0.1:4000/subscribe
127.0.0.1:4000 avoid it 

### Expected Behavior
Should not be extra space there

### Screenshots

<img width="935" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/a3526727-7164-4d02-999c-1b8cff2ad179">
<img width="824" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/3c37a863-6fa0-4796-80a0-0d23179fb4e6">
<img width="889" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/dc98f2c7-8b5d-43a6-a8b5-80a23608607b">
<img width="792" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/53433911-79da-45a0-af9a-e7e4e42fd2a0">

### Enviroment:

 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajivkumawat3** [comment]
@thisiskaransgit I have made pull request for this issue can you review and merge it

**Comment by Rajivkumawat3** [comment]
@thisiskaransgit  sir I have made changes in commit and did not make change in gem file. Now please review this latest pull request

**Comment by thisiskaransgit** [comment]
@Rajivkumawat3, you could have reverted the changes asked in the review, creating another PR makes the work of more time-consuming. All the requested changes haven't been incorporated in either of the PRs, so close one of them and move forward with another.

**Comment by Rajivkumawat3** [comment]
but sir this PR is okay and will not impact another prs because i just remove extra padding and margin from the elements to reduce extra space .
