### ISSUE TITLE
[Update] GIF on homepage needs to be updated

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery.io#1231]
### Current Behavior
The GIF on the [meshery.io](https://meshery.io/) website in the hero section is old 

![gif-update](https://github.com/meshery/meshery.io/assets/51539117/2dce710e-bd08-452c-8b61-e8706256ad64)

### Desired Behavior
The GIF on the meshery.io website in the hero section needs to be updated with the newer look of [meshery](https://playground.meshery.io/)

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by samyakshah3008** [comment]
I would like to work on this small fix.

**Comment by vaibhav-xt** [comment]
I would like to work on this issue.

**Comment by vishalvivekm** [comment]
As @samyakshah3008 is working on other issues, let's assign this one to Vaibhav.
@vaibhav-xt You're up!
