### ISSUE TITLE
[Enhancement] Disable the modal on catalog page

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery.io#1232]
### Current Behavior
1. Clicking on any card on [catalog](https://meshery.io/catalog) page a modal pops up on the screen
2. On clicking the redirect icon on modal -> opens a new tab with catalog info

<img width="500" alt="Group 1116599533 (1)" src="https://github.com/meshery/meshery.io/assets/51539117/6c94bebc-c30a-44de-9e68-0be93677ca4e">

### Desired Behavior
1. Disable the modal shown above
2. Clicking on any card on [catalog](https://meshery.io/catalog) page should open the catalog info page in the same tab instead of a new tab

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ghat0tkach** [comment]
Hey @ritiksaxena124 , May I work on this issue?

**Comment by Ghat0tkach** [comment]
https://github.com/meshery/meshery.io/assets/59855919/de5b9fa2-d4eb-4a25-9989-c1afd1b6deb6

**Comment by thisiskaransgit** [comment]
Sure go ahead and fix this @Ghat0tkach 🚀

**Comment by Ghat0tkach** [comment]
@

> Sure go ahead and fix this @Ghat0tkach 🚀

Thanks a lot 🙌🙌
