### ISSUE TITLE
Improve performance of Meshery home page

### ISSUE THREAD

**Issue by HarshDobariya79** [meshery/meshery.io#1235]
### Description

- The image is present at https://github.com/meshery/meshery.io/blob/master/assets/images/ken-owens.png
- This image is present in the **testimonials** section.
- The current size of the image is over **3MB** which needs to be reduced to around **150KB** just like other images because the displayed image size is quite small.
- The image is around **1600x1600px** but it can be reduced to around **600x600px** which will help reduce the overall size.
- Fixing this issue will improve the **performance** of the site.
- There are some images which can be **lazy-loaded** to improve the **performance** further more.

### Screenshots

![image](https://github.com/meshery/meshery.io/assets/29772969/f862896d-88b4-4825-a2f3-f522290d454e)

### Environment:
 - OS: Linux
 - Browser: Chrome
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by HarshDobariya79** [comment]
I would like to work on this issue :smile:

**Comment by ritiksaxena124** [comment]
Assigned @HarshDobariya79 👌
