### ISSUE TITLE
Responsiveness issue at /programs

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery.io#1238]
### Description
 there is extra white space in mobile devices in dark mode 
### Expected Behavior
there should not be extra white space

### Screenshots
<img width="242" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/4e5439cb-8330-4ec4-9cab-94fc2f97a531">
<img width="236" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/237e02ec-ab12-4a25-a69c-c7ee76f46503">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajivkumawat3** [comment]
please assign me this issue , i want to work on this issue

**Comment by thisiskaransgit** [comment]
@Rajivkumawat3,  Thank you for looking into this issue, the responsiveness needs to be fixed. Since there are already two contributors working alongside to update the programs page (issue #1200), this will be taken care of by them too.

**Comment by samyakshah3008** [comment]
Noted, @thisiskaransgit ✅

**Comment by Rajivkumawat3** [comment]
ok sir

**Comment by itsajay1029** [comment]
Can you assign this issue to me and explain on what needs to be done ? @samyakshah3008

**Comment by Rajivkumawat3** [comment]
@itsajay1029 I also wanted to work on it but as they said that two contributors is already working on this

**Comment by Kevin-Usadadiya** [comment]
Can anyone assign me this issue?

**Comment by itsajay1029** [comment]
> @itsajay1029 I also wanted to work on it but as they said that two contributors is already working on this

Ohh, ok. No problem

**Comment by vishalvivekm** [comment]
@samyakshah3008 would you like to give an update here?

**Comment by JayKay24** [comment]
I could work on this. You could assign it to me.
