### ISSUE TITLE
[BUG] nav item is overlaping with the toggle icon 

### ISSUE THREAD

**Issue by anikdhabal** [meshery/meshery.io#1243]
### Description

"Getting Started" nav item is overlaping with the toggle icon at the of reloading.
### Expected Behavior

It should behave like normal.
### Screenshots

![Screenshot 2023-06-30 225446](https://github.com/meshery/meshery.io/assets/81948346/165d7da9-e8fb-4629-86bb-9b6870e1fa2a)
![Screenshot 2023-06-30 225809](https://github.com/meshery/meshery.io/assets/81948346/2b89f521-eea1-4bc4-aad1-86b687349c70)

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ghat0tkach** [comment]
Hello @anikdhabal , Thanks for raising this issue however its a duplicate for the issue #1162

**Comment by Savio629** [comment]
@anikdhabal Do comment on the mentioned issue #1162 
Will get you assigned.
