### ISSUE TITLE
Incorrect number of total Integrations

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery.io#1248]
### Description

The homepage at meshery , shows 200+ integrations and then gets updated to 210+ integrations in a few secs . The show all integrations page also exhibit the similar issue
### Expected Behavior

The numbers should be 210+
### Screenshots
![Screenshot_20230702-113258.png](https://github.com/meshery/meshery.io/assets/59855919/a27e7c13-f990-4c0c-9411-8ab1e5829111)

## Possible Fix
- updating the number 210 from 200 in [index.html](https://github.com/meshery/meshery.io/blob/7561fd843466d279574f78d8fd4cdfc1d1b0f55f/integrations/index.html#L169)
And [integration.html](https://github.com/meshery/meshery.io/blob/7561fd843466d279574f78d8fd4cdfc1d1b0f55f/_includes/partials/homePage-integrations.html#L4)
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaibhav-xt** [comment]
@Ghat0tkach I would like to work on this issue.

**Comment by Kumar-Monisankar-Basu** [comment]
@Ghat0tkach , I would like to work on this issue

**Comment by Ghat0tkach** [comment]
@vaibhav-xt  , let us give @Kumar-Monisankar-Basu this chance since its his first contribution🙌

**Comment by Kumar-Monisankar-Basu** [comment]
@Ghat0tkach please assign this issue to me 🙏🏽
