### ISSUE TITLE
Update the theme of scrollbar to be consistent on other pages

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1257]
### Description
Update the theme of scrollbar to be consistent on other pages as the homepage and also make it more visible on light theme.

### Screenshots

![meshery1](https://github.com/meshery/meshery.io/assets/91362589/d8c10e2d-4e37-496b-9c2e-b7194045608c)
![meshery2](https://github.com/meshery/meshery.io/assets/91362589/fd9f42db-c6f9-4c96-9986-75ea6835e141)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ranjanmangla1** [comment]
please assign me this issue @Savio629

**Comment by Faizan711** [comment]
Is anyone working on this issue @Savio629 , if not then I would like to be assigned to work on this.

**Comment by Savio629** [comment]
@ranjanmangla1 As you are working some other issues, let @Faizan711 take up this issue 😄

**Comment by vishalvivekm** [comment]
@Faizan711 Please let us know of your progress so far

**Comment by Faizan711** [comment]
@vishalvivekm I have changed the scroll bar for home and catalog page, more pages left.
Will raise a PR when whole site is done.

**Comment by thisiskaransgit** [comment]
Closed as completed via https://github.com/meshery/meshery.io/pull/1361
