### ISSUE TITLE
Creating a custom twitter widget

### ISSUE THREAD

**Issue by ranjanmangla1** [meshery/meshery.io#1258]
### Description

As twitter has imposed rate limits and is not allowing anyone who has not logged in to read tweets, we are seeing this: 
![image](https://github.com/meshery/meshery.io/assets/93506927/62dce64c-ddcb-4da3-b4cc-4c7674c09943)

What we can do is, create a custom twitter widget that displays tweet. All we will require is a twitter api key.

### Additional Benefit
The dark mode and light mode logic will become much simpler. As I was working on #1242 for dark mode, I encountered several problems and then I had to settle on idea of removing the old and creating a new widget on each toggle switch, which leads to a slight delay, this can be observed in this preview: https://deploy-preview-1256--mesheryio-preview.netlify.app/

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ranjanmangla1** [comment]
Can someone assign me this issue?

**Comment by thisiskaransgit** [comment]
Thanks for raising the issue, but since we have moved on from using the twitter embed for now, due to their public access request, we won't be moving ahead with this enhancement.
