### ISSUE TITLE
Enhancement Request: Icon Representation for Light and Dark Mode Themes 

### ISSUE THREAD

**Issue by abhiraj-ku** [meshery/meshery.io#1269]
Current Behavior
I would like to propose an enhancement for the icon representation of light and dark mode themes on our website. Currently, we are using the sun icon to indicate the light and the moon icon for dark mode.

Desired Behavior
when the theme is light, the theme toggle icon should be of moon icon which can serve as a recognizable visual cue for users to switch the theme and the same for light mode.

This update will enhance the user experience by ensuring the icons accurately convey the available themes and assist users in easily identifying and switching between light and dark modes.

### Screenshots
![meshry-sun-icon](https://github.com/meshery/meshery.io/assets/113116498/9b4e3932-3919-4ce2-8823-1fd743b7309c)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by abhiraj-ku** [comment]
@thisiskaransgit  I have raised this issue here

**Comment by Mohith234** [comment]
Can I work on this ?

**Comment by abhiraj-ku** [comment]
hey @thisiskaransgit should I raise a pr for this ?

**Comment by thisiskaransgit** [comment]
@abhiraj-ku The proposed change does not go well here as we intend to show the current theme of the website with the toggle. But thank you for your efforts and for discussing it with the community 🙌🏼. Will be closing this issue for now, but rest assured we often raise beginner-friendly issues for new contributors to get started in their journey, be an active member of our community and we'll help you to land your first PR 😄
