### ISSUE TITLE
Issue Template Updates for Figma link

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1282]
#### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

#### Desired Behavior
Each template that has a reference to Figma in its resources section should an invite link added.

#### Implementation

In each [issue template](../blob/master/.github/ISSUE_TEMPLATE/) that refers to Figma, replace the current line referring to Figma with this line:

```
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)```
```

#### Acceptance Tests
1. All references to Figma include the "open invite" link.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by codingmickey** [comment]
Hi @leecalcote I would like to work on this!

**Comment by Yana-Gupta** [comment]
Hi @leecalcote I would like to work on this issue.

**Comment by leecalcote** [comment]
Sounds good, @codingmickey. Thank you.

**Comment by leecalcote** [comment]
@Yana-Gupta here's one that you might comment on and be assigned to https://github.com/meshery/meshery-linkerd/issues/527
