### ISSUE TITLE
Content Overflowing out of the card

### ISSUE THREAD

**Issue by yashchaddha** [meshery/meshery.io#1283]
### Description

Content Overflows out of the Card
![image](https://github.com/meshery/meshery.io/assets/25150314/5465b934-2c16-4760-9925-ae4844564e4c)

### Expected Behavior

Content to stay within the card
![image](https://github.com/meshery/meshery.io/assets/25150314/2c36c0fb-7d4c-4abe-9fc9-211819b3a311)

font-size needs to be updated, from 0.8rem to 0.7rem

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by yashchaddha** [comment]
Kindly let me know if I can be assigned on this one! Thanks

**Comment by roy2pushkar** [comment]
Hey @yashchaddha I want to work on this issue . please assign me this issue if you not assigned any one .

**Comment by roy2pushkar** [comment]
@yashchaddha I want to work on this Please Assign me this issue .

**Comment by leecalcote** [comment]
If you reproach the solution as text-overflow: ellipsis, let's proceed, @yashchaddha.

**Comment by leecalcote** [comment]
@roy2pushkar here's an open issue - https://github.com/meshery/meshery-nsm/issues/161

**Comment by yashchaddha** [comment]
Yup, i agree, lets do it! I would like to contribute on this one, would request you to kindly assign it to me

> If you reproach the solution as text-overflow: ellipsis, let's proceed, @yashchaddha.

**Comment by thisiskaransgit** [comment]
@yashchaddha, assigning you for this 🚀 , we had an unfinished effort on it before, let's conclude it this time.

**Comment by Savio629** [comment]
@yashchaddha Updates?

**Comment by yashchaddha** [comment]
Hi @Savio629  

Approaching the solution with text-overflow:ellipsis

I added 

overflow:hidden
text-overflow : ellipsis

It was coming like this 
![image](https://github.com/meshery/meshery.io/assets/25150314/46cc055e-d5ee-4cc2-b759-c076550b2ca1)

Because of display:flex property and when I removed this 

It was coming up perfectly like this 
![image](https://github.com/meshery/meshery.io/assets/25150314/06ffff50-82cb-442a-bff3-76884d943702)

Now the main issue which came was other card content were stacked up like this 

![image](https://github.com/meshery/meshery.io/assets/25150314/3da17fb7-cd62-40c9-8066-a467dba665fb)


Now at this point I guess we should be adding another div inside the 
 <div class="card-back">
                        Name of card
  </div>
  
Another approach which I recommened was making the font-size:0.7rem instead of 0.8 rem which would not cause any of these changes 

It would come like this 


![image](https://github.com/meshery/meshery.io/assets/25150314/828c1418-57ae-4aaa-80c0-3c8fe0e86ca5)


I would be needing more time and insights on 1st approach while for second, I have a PR ready

Lemme know

Thanks

**Comment by AdityaAgarwaal** [comment]
Hi @leecalcote, we can add a string truncate function that would simply take the card text string and a specific feasible length using which if the string length is greater than the feasible length provided, the function would truncate the string and add "..." at the end.

function truncateString(str, num) {
  if (str.length > num) {
    return str.slice(0, num) + "...";
  } else {
    return str;
  }
}

![image](https://github.com/meshery/meshery.io/assets/60563388/30eac56c-8a52-46c9-b860-a57e7f8f42f2)



I would like to co-author with @yashchaddha  on this issue

**Comment by yashchaddha** [comment]
Sure @AdityaAgarwaal 

Hi @leecalcote this solution seems good to me and I would love to coauthor with @AdityaAgarwaal on this one

**Comment by leecalcote** [comment]
@yashchaddha  🙁
