### ISSUE TITLE
Tweets are not showing

### ISSUE THREAD

**Issue by kumarankit999** [meshery/meshery.io#1284]
### Description
The Real time Tweets of Meshery organization by its twitter handle aren't fetched and not showing on Meshery's Program Page.

### Expected Behavior
Tweets of Real-time should be shown here at the bottom of the Page.

### Screenshots

![image](https://github.com/meshery/meshery.io/assets/111564362/3d91a424-96d4-4230-bb9d-85cfb715153a)

### Enviroment:
 - OS: Windows
 - Browser: Chrome
 - Version: 11
 - Device: Desktop 

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yana-Gupta** [comment]
Hi, can you assign me to this issue.

**Comment by leecalcote** [comment]
Let's wait and see what Twitter's guidance is going forward.

**Comment by thisiskaransgit** [comment]
Thanks for raising the issue, but since we have moved on from using the Twitter embed for now, due to their public access update,  we won't be moving ahead with this enhancement. Thus closing it.
