### ISSUE TITLE
Making the community news letter card responsive

### ISSUE THREAD

**Issue by ShivangRawat30** [meshery/meshery.io#1291]
#### Current State of the Meshery.io site

Currently the Community news letter card is not responsive
<img width="367" alt="Screenshot 2023-07-12 at 9 19 33 PM" src="https://github.com/meshery/meshery.io/assets/114716075/d18dcc8c-a72a-40ee-b331-a7d44fb7f1fb">

#### Desired State of the Meshery.io site

The input fields should be little small and should have less padding, the font size should be small too.
---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShivangRawat30** [comment]
@leecalcote can I work on this issue ?

**Comment by leecalcote** [comment]
So long as you leave the font size, the field padding and button size all the same and simply wrap the last name to a new row as the only change, yes, @ShivangRawat30.

First
Last
Email
Subscribe
