### ISSUE TITLE
responsiveness of Project mailing list card.

### ISSUE THREAD

**Issue by ShivangRawat30** [meshery/meshery.io#1292]
#### Current State of the Meshery.io site

The project mailing list is not responsive.
<img width="366" alt="Screenshot 2023-07-12 at 9 19 48 PM" src="https://github.com/meshery/meshery.io/assets/114716075/cd963868-40d2-4ba3-a784-013bdbf0d989">
#### Desired State of the Meshery.io site

the content side this list contain large margin top and bottom, I am requesting to decrease the margin of the content.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
assigned @ShivangRawat30

**Comment by ShivangRawat30** [comment]
I think we should remove the unnecessary div from the mail-container and keep the all `<p> </p>` inside a single div.

<img width="956" alt="Screenshot 2023-07-17 at 2 17 35 PM" src="https://github.com/meshery/meshery.io/assets/114716075/acef92d9-cafb-4635-9edc-c10bfe66a464">

**Comment by Savio629** [comment]
@ShivangRawat30 It would be better if you open a pr for this issue. It would be easier to give feedbacks...

**Comment by ShivangRawat30** [comment]
@Savio629 sorry for the delay, I'll open a pr tomorrow.
