### ISSUE TITLE
responsiveness of the footer.

### ISSUE THREAD

**Issue by ShivangRawat30** [meshery/meshery.io#1293]
#### Current State of the Meshery.io site

The footer looks very odd in mobile phone because of the empty spaces.
<img width="366" alt="Screenshot 2023-07-12 at 9 32 13 PM" src="https://github.com/meshery/meshery.io/assets/114716075/94e7731a-3ce3-435c-9eb1-ab44cb6c7b96">

#### Desired State of the Meshery.io site

I would like to make the footer small by reducing the empty space.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yana-Gupta** [comment]
@leecalcote I would like to work on this issue.

**Comment by vishalvivekm** [comment]
@ShivangRawat30 will you please say a bit more on what's your proposed fix here? // @thisiskaransgit

**Comment by ShivangRawat30** [comment]
@vishalvivekm I am proposing to make the footer look like this on mobile screens.
<img width="351" alt="Screenshot 2023-07-16 at 10 58 40 PM" src="https://github.com/meshery/meshery.io/assets/114716075/f6be1f72-226f-4a18-86a8-160c6238033f">

**Comment by DkRadhey** [comment]
@ShivangRawat30  Is this issue assigned to anyone? If not, can I work on this?

**Comment by leecalcote** [comment]
Thanks, gents, but no thanks. Let's get you on to one of the current ~160 other open "help wanted" issues. Find the link to these in the readme.
