### ISSUE TITLE
incorrect links inside pull request template

### ISSUE THREAD

**Issue by Yana-Gupta** [meshery/meshery.io#1300]
### Description
The path inside [pull request template](https://github.com/meshery/meshery.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1) for signed in comments is incorrect.  Currently it is directing to **Not Found** page. 
```
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
```

### Expected Behavior
It should be: 
```
**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
```
### Enviroment:
 - OS:  Linux 
 - Browser: Brave
 - Version: 
 - Device: Desktop 

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
Thanks @Yana-Gupta for pointing it out.

We can update the link to `https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin`.
what d'you say?

**Comment by Yana-Gupta** [comment]
> Thanks @Yana-Gupta for pointing it out.
> 
> We can update the link to `https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin`. what d'you say?

Yes for sure!

**Comment by Yana-Gupta** [comment]
> 

@vishalvivekm then should I update it in the issue?

**Comment by Debjyoti0404** [comment]
Hey @Yana-Gupta, can I work on this issue?

**Comment by TheOjasSingh** [comment]
@Yana-Gupta is this issue resolved ?

**Comment by Yana-Gupta** [comment]
// @vishalvivekm

**Comment by vishalvivekm** [comment]
> > 
> 
> @vishalvivekm then should I update it in the issue?

Thanks @Yana-Gupta.

@Yana-Gupta @Debjyoti0404 @TheOjasSingh we follow FCFS to assign issues.
@Yana-Gupta would you like to work on or pass this issue to @Debjyoti0404 ?

**Comment by Yana-Gupta** [comment]
> > > 
> > 
> > 
> > @vishalvivekm then should I update it in the issue?
> 
> Thanks @Yana-Gupta.
> 
> @Yana-Gupta @Debjyoti0404 @TheOjasSingh we follow FCFS to assign issues. @Yana-Gupta would you like to work on or pass this issue to @Debjyoti0404 ?

yea

**Comment by vishalvivekm** [comment]
> > > > 
> > > 
> > > 
> > > @vishalvivekm then should I update it in the issue?
> > 
> > 
> > Thanks @Yana-Gupta.
> > @Yana-Gupta @Debjyoti0404 @TheOjasSingh we follow FCFS to assign issues. @Yana-Gupta would you like to work on or pass this issue to @Debjyoti0404 ?
> 
> yea I would like to pass on to @Debjyoti0404


There you go @Debjyoti0404

**Comment by Debjyoti0404** [comment]
Thanks @Yana-Gupta @vishalvivekm :smile:
