### ISSUE TITLE
add a quote in community page

### ISSUE THREAD

**Issue by Yana-Gupta** [meshery/meshery.io#1301]
#### Desired State of the Meshery.io site
We want to include a comment by username [@priyanshu-kun](https://github.com/priyanshu-kun) in the [discussion form](https://discuss.layer5.io/t/can-someone-explain-me-what-this-meshery-or-none-provider-mean-here/3107/2) in [meshery.io/community](https://meshery.io/community/) page. 

> "Wow, you're incredibly helpful, I wish every open-source community is as friendly as yours."

Be creative and try to find out suitable place to add it. 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ghat0tkach** [comment]
Meshery contributing  page is currently work in progress.

**Comment by ayushsinha25** [comment]
can you assign this to me?

**Comment by thisiskaransgit** [comment]
@Yana-Gupta, Thank you for raising this feature addition, as pointed out by @Ghat0tkach, the contribution is still a work in progress, we will be holding up this addition for now.

**Comment by Chadha93** [comment]
@thisiskaransgit ^^

**Comment by Layak-Ali** [comment]
@Chadha93 @Ghat0tkach can you assign this task to me?
