### ISSUE TITLE
Increasing the z-index of the scroll up button.

### ISSUE THREAD

**Issue by ShivangRawat30** [meshery/meshery.io#1303]
#### Current State of the Meshery.io site

The subscribe button is overlapping with the scroll up button.
<img width="274" alt="Screenshot 2023-07-17 at 6 36 11 PM" src="https://github.com/meshery/meshery.io/assets/114716075/e7a7eb09-6e59-4619-bd20-6f0b464fe52d">

#### Desired State of the Meshery.io site

showing the scroll up button over the subscribe button.
---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by nakulbh** [comment]
Hey @leecalcote @ShivangRawat30 can i work on this

**Comment by Karmpatel960** [comment]
hey @leecalcote @ShivangRawat30 can I Please work on it ?
