### ISSUE TITLE
[Catalog] Missing Information for deployements catalog

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery.io#1320]
Add or update the following [Meshery Catalog](https://meshery.io/catalog.) item(s):
The following individual design-page lacks information about them .

Images for better Understanding
Let's take a look at Busy box catalog
| Catalog box        | Model page   |
| ------------- |:-------------:|
| ![image](https://github.com/meshery/meshery.io/assets/59855919/6af558db-7c45-4663-adf4-639e3697294d)
 

The following needs to be updated ,
1)Busybox
2)ByteVerse Shecodes
3)Caddy
4)Cassandra statefulset
5)Emojivoto
6)Istio BookInfo
7)RBAC for Elastic search
8)Redis Leader Deployment
9)nginx-deployement (1)
10)network-design1

We need to update the .md of these files under

https://github.com/meshery/meshery.io/tree/master/collections/_catalog/deployment

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](https://slack.meshery.io) for access.

**Comment by theBeginner86** [comment]
@Ghat0tkach 
Thank you for raising this issue. 

Here, updating .md files wouldn't fix things as our nightly workflow https://github.com/meshery/meshery.io/blob/master/.github/workflows/add-catalog.yml would again overwrite it from the data in Meshery Cloud.

So, update needs to be done in DB or un-publishing and re-publishing.

**Comment by theBeginner86** [comment]
I fixed this for other catalog items. Looks like these were left out. I'll look into them 👍

**Comment by Vivek-Prajapatii** [comment]
Hi @leecalcote, if anyone is not working on it, may i proceed with this issue?

**Comment by theBeginner86** [comment]
All catalog items have a description now.
Refer:
https://meshery.io/catalog
https://meshery.meshery.io/catalog

Commits: 
https://github.com/meshery/meshery.io/commit/1f0d94aa6cd509946f32ead7e8b42e419fa8015a
https://github.com/meshery/meshery.io/commit/c6dfd873074b038056b23579e29307d46b064516

So we can close this issue 👍
