### ISSUE TITLE
Filters and Patterns should be Clickable

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery.io#1321]
#### Current State of the Meshery.io site

Currently the patters and filters image in the meshery.io/catalog doesnt perform anything .
#### Desired State of the Meshery.io site
These should be clickable and the action should lead to sorting the filters and patterns respectively

Change the cursor to point whenever we hover filters or patterns
![image](https://github.com/meshery/meshery.io/assets/59855919/2bf55202-dfcb-4e83-9e2b-1a7b62293f0a)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShivangRawat30** [comment]
I would like to work on this issue

**Comment by Ghat0tkach** [comment]
There you go @ShivangRawat30

**Comment by Ghat0tkach** [comment]
There you go @ShivangRawat30
