### ISSUE TITLE
Remove the Service Mesh Interface from Footer

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery.io#1325]
### Description

![image](https://github.com/meshery/meshery.io/assets/59855919/a8fc5eb0-5633-4268-ad2e-742322771ee9)
Comment out the Service Mesh interface 
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by csengineer1990** [comment]
can I work on this? could you assign it to me?

**Comment by marvY-O** [comment]
I'd like to resolve this.

**Comment by abhijeetgauravm** [comment]
I would like to work on this issue!
