### ISSUE TITLE
Liquid Template for Code Copy Component

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1337]
#### Current State of the Meshery.io site

The code component for copying code to clipboard on the site has multiple repetitions of HTML code and is not using the Jekyll Liquid templating system. This can make it difficult to maintain and update the code component across the site.

#### Desired State of the Meshery.io site

Use  Liquid template system for the code copy component on the site. This would allow to reduce the amount of repetitive HTML code and make updates to the component more efficient.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by parth721** [comment]
I can work on it

**Comment by JayKay24** [comment]
@parth721 Has already state interest.

**Comment by leecalcote** [comment]
@JayKay24 :(
