### ISSUE TITLE
Clarification in README.md Regarding 'bundle install' Execution

### ISSUE THREAD

**Issue by iArchitSharma** [meshery/meshery.io#1338]
### Issue:
The **README.md** file in the Meshery.io repository suggests running `bundle install` explicitly before executing the `make site` command, which might lead to confusion as the `make site` command already takes care of running `bundle install`.

### Proposed Solution:
To avoid any confusion, we can update the **README.md** to reflect that running `bundle install` explicitly is unnecessary when using the `make site` command. The `make site` target in the **Makefile** already handles the `bundle install` internally before serving the site locally.

### We can solve it using two ways:
1) By removing `bundle install` part from **README.md**
2) By removing `bundle install;` part from **Makefile**

_I would love to work on this issue!_

Thank you for your attention to this matter. Let's ensure that the documentation is clear and helpful to all contributors.

---

**Comment by EraKin575** [comment]
Can I work on this issue?

**Comment by Ghat0tkach** [comment]
hey @iArchitSharma 


Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by iArchitSharma** [comment]
@Ghat0tkach I actually missed it. Let's discuss it at the Meshery Development Meeting.

**Comment by thisiskaransgit** [comment]
@iArchitSharma, no worries I've taken a look at it, looks like you wanted to get the assignment

@YashRajSingh-4799, please refrain from making PRs without getting assigned, this is a general contribution guideline that we follow in the community to help track contributors' progress. The assignment may get delayed in confirming the relevancy of the issue. Hope you will take care of this next time.

@iArchitSharma, do help us review the PR.

**Comment by iArchitSharma** [comment]
@thisiskaransgit Of course, no worries. I'll take a look at the PR.
