### ISSUE TITLE
Change Twitter Logo to X(New logo)

### ISSUE THREAD

**Issue by EraKin575** [meshery/meshery.io#1340]
### Current Behavior
Currently the old twitter logo is presented on meshery.io
![image](https://github.com/meshery/meshery.io/assets/100225222/2a913374-ab0d-4a66-9014-6c5b7acacecf)

### Desired Behavior
Change Twitter logo to X

### Logo
![image](https://github.com/meshery/meshery.io/assets/100225222/9e0a504c-a567-4e45-9e98-3b7bd90c0871)

---
I would like to work on this issue
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
@EraKin575 🚀

**Comment by leecalcote** [comment]
Use an SVG

**Comment by aaronsgeorge** [comment]
Can i work on this issue
