### ISSUE TITLE
[UI] Tab title is UUID in Meshery Catalog

### ISSUE THREAD

**Issue by zakisk** [meshery/meshery.io#1346]
#### Current Behavior

in Meshery Catalogue when a user sees details of a catalog item let's say Apache ShardingSphere Operator, on the tab title it is shown UUID instead of the Title "Apache ShardingSphere Operator".

#### Desired Behavior

The tab title should be the name of the catalog item

#### Screenshots/Logs

![Screenshot from 2023-08-03 09-28-08](https://github.com/meshery/meshery/assets/49492007/623f4d68-aef8-4ffb-a198-33950c2355f8)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by zakisk** [comment]
@abhijeetgauravm if you still want to work on this head over to [meshery/meshery.io](https://github.com/meshery/meshery.io)

**Comment by DkRadhey** [comment]
@Chadha93 @zakisk I would like to work on this issue. Could you please assign it to me?

**Comment by abhijeetgauravm** [comment]
@zakisk yeah i would like to work!

**Comment by thisiskaransgit** [comment]
@abhijeetgauravm, catalog files are automatically generated they are not to be manually edited, change the page's metadata to display the pattern's name

**Comment by abhijeetgauravm** [comment]
hey @thisiskaransgit i m not able to get it in codebase where's u r pointing!

**Comment by thisiskaransgit** [comment]
@abhijeetgauravm, it is an easy fix, include a script that will update the tab title depending on the pattern name.
If you're unable to conclude this one, that's okay, we will pass the task to another volunteer.

**Comment by abhijeetgauravm** [comment]
ok @thisiskaransgit !
