### ISSUE TITLE
Improve Styling Buttons

### ISSUE THREAD

**Issue by kumarankit999** [meshery/meshery.io#1352]
#### Current State of the Meshery.io site
The Join Community button has no margin bottom, which appears very bad.

![image](https://github.com/meshery/meshery.io/assets/111564362/29987d4f-131a-4af5-8a07-573724236225)

#### Desired State of the Meshery.io site
The Join Community Button has to be at least 5px margin bottom.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sooovamm** [comment]
Would like to contribute to this issue. Can you please assign this issue to me ?

**Comment by Sranjan0208** [comment]
Can i work on this issue?
