### ISSUE TITLE
Introduce Sorting of Cards in Meshery Catalog

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1355]
Introduce sort by option as a dropdown in Meshery Catalog, which arranges the cards alphabetically and on the basis of time of update, both in ascending and descending manner.  

For reference take a look at [meshery.layer5.io/catalog](https://meshery.layer5.io/catalog)

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by tdadadavid** [comment]
The reference link doesn't work it shows page not found

**Comment by gopivaibhav** [comment]
Maybe this is the [link](https://meshery.meshery.io/catalog) for reference @tdadadavid

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by thisiskaransgit** [comment]
@Sranjan0208, sure go ahead 🚀

**Comment by Sranjan0208** [comment]
@thisiskaransgit I am really sorry because of Signing-off error from my side there was error in both this issue and in Issue #1352 so I had to start all over again. But I have added for both the issue in this PR. Again, I am really sorry for the trouble.

**Comment by Lucif3r-in** [comment]
Taking a look into it @thisiskaransgit . Please assign.

**Comment by Lucif3r-in** [comment]
@thisiskaransgit Is this issue still active as I can see a sort feature on the catalog page which is not functional.

**Comment by iArchitSharma** [comment]
@Sranjan0208, are you still working on this issue? If not, then I'll take over it.

**Comment by abhijeetgauravm** [comment]
Hey @Lucif3r-in, would you like to work on this issue for now?

**Comment by Lucif3r-in** [comment]
> Hey @Lucif3r-in, would you like to work on this issue for now?

Yes can do for sure😊

**Comment by abhijeetgauravm** [comment]
Since there have been no updates from @Sranjan0208 for a while, let's assign it to you, @Lucif3r-in

**Comment by Lucif3r-in** [comment]
@abhijeetgauravm Just for clarification I have to make changes to `catalog/index.html` right?

**Comment by iArchitSharma** [comment]
@Lucif3r-in I can see a **timestamp** key value in yaml files

**Comment by ashutosh-rath02** [comment]
> @Lucif3r-in I can see a **timestamp** key value in yaml files

There are multiple timestamps, and those are related to some texts i guess.
Also can you guide me which is the repo for [meshery.cloud](https://meshery.meshery.io/catalog)

**Comment by iArchitSharma** [comment]
oh I see those are messages, I guess we don't have any publishing date
so go with alphabetical sorting for now

**Comment by ashutosh-rath02** [comment]
> oh I see those are messages, I guess we don't have any publishing date so go with alphabetical sorting for now

Cool!! Please update me with the repo for https://meshery.meshery.io/catalog

**Comment by iArchitSharma** [comment]
@Lucif3r-in Take a look here: https://meshery.io/handbook/repository-overview

**Comment by iArchitSharma** [comment]
@Lucif3r-in It's a private repo i guess, wait ill confirm

**Comment by Lucif3r-in** [comment]
> @Lucif3r-in It's a private repo i guess, wait ill confirm

Ya I think that too, I tried searching for the repo through code also couldn't find it😅

**Comment by Lucif3r-in** [comment]
Also I was going through the PRs attached to this issue and the code seem alright, don't know why it didn't work tho🤔

**Comment by iArchitSharma** [comment]
@

> > @Lucif3r-in It's a private repo i guess, wait ill confirm
> 
> Ya I think that too, I tried searching for the repo through code also couldn't find it😅

Yup i confirmed , its a private one!

**Comment by iArchitSharma** [comment]
> Also I was going through the PRs attached to this issue and the code seem alright, don't know why it didn't work tho🤔

@Lucif3r-in I have not checked that code, so logic was already written but not working??

**Comment by Lucif3r-in** [comment]
> > Also I was going through the PRs attached to this issue and the code seem alright, don't know why it didn't work tho🤔
> 
> @Lucif3r-in I have not checked that code, so logic was already written but not working??

It seems correct can you look into it once?

**Comment by iArchitSharma** [comment]
@Lucif3r-in, I've checked the deployed build, and it does have a dropdown option, but it's not functioning when any option is selected.

**Comment by Lucif3r-in** [comment]
@iArchitSharma @abhijeetgauravm Raise PR #1480 🚀🚀🚀
