### ISSUE TITLE
Margin issue with "join community" button

### ISSUE THREAD

**Issue by charu1603** [meshery/meshery.io#1362]
### Current Behavior
the "join community" button is experiencing a margin issue causing it to touch the footer section.  This issue affects the overall design. 
![Screenshot (380)](https://github.com/meshery/meshery/assets/96014425/40eb3b46-c773-48a9-b5ce-473d5690ff83)
### Expected Behavior
![Screenshot (381)](https://github.com/meshery/meshery/assets/96014425/c58efa00-91e4-4e31-b34e-c4338730a12a)

Please assign me this issue

**Comment by thisiskaransgit** [comment]
@charu1603 , go ahead 👍🏼. Adding just a bottom margin of will work

**Comment by het4399** [comment]
@charu1603 please assign this to me
