### ISSUE TITLE
Overlapping issue of dropdown items with navbar content

### ISSUE THREAD

**Issue by charu1603** [meshery/meshery.io#1365]
### Current Behavior
In the navbar, the dropdown section slightly overlaps with the "getting started button" and the hover area.
![Screenshot (386)](https://github.com/meshery/meshery.io/assets/96014425/c5c53c7b-b28e-4a3b-9a6e-a045d9dd26bd)
![Screenshot (389)](https://github.com/meshery/meshery.io/assets/96014425/62a7c403-cf05-4605-9b95-c3c9bdf1fd41)

### Desired Behavior
![Screenshot (388)](https://github.com/meshery/meshery.io/assets/96014425/174d91d2-d330-4ea1-a096-ee1022e09faf)
![Screenshot (387)](https://github.com/meshery/meshery.io/assets/96014425/39f75859-01e0-4889-b028-58fcbfce6500)

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by thisiskaransgit** [comment]
@Ghat0tkach is this something you are fixing, or shall I assign this to @charu1603? Please signal

**Comment by Ghat0tkach** [comment]
@thisiskaransgit , you can assign this to @charu1603 😄.

**Comment by het4399** [comment]
Hey @thisiskaransgit can you assign it to me .I want to begin my open-source journey.I will fix it.
