### ISSUE TITLE
[UI] Hovering issues for Twitter icon

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery.io#1367]
### Description

![image](https://github.com/meshery/meshery.io/assets/59855919/29414b0b-3893-4ae2-a741-05fe3103e645)

### Expected Behavior

The Twitter X logo should be white on hover
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by mayurjadhav2002** [comment]
@Ghat0tkach Understood! Looks easy : ), Can you please assign it to me?

**Comment by thisiskaransgit** [comment]
@mayurjadhav2002, go ahead

**Comment by Layak-Ali** [comment]
@Ghat0tkach @thisiskaransgit I completed the task. Can you please review and merge my pull request #1377 ?

**Comment by Ghat0tkach** [comment]
@Layak-Ali thanks for showing interest in our community! However please refrain from opening pull requests without getting assignment of issue.
Let us keep the spirit of Open source Alive!
This issue was assigned to someone else , if they are unable to raise a PR .The next one gets assigned.

Please take care of these things in the near future

**Comment by Layak-Ali** [comment]
Oh sorry. I am new to Open source and i don't really know much about the rules. I tried to do my first contribution and couldn't find any easy one without any assigned. But i hope you merge my request if @mayurjadhav2002 isn't able to do it.

**Comment by mayurjadhav2002** [comment]
@Layak-Ali, it's great to see you diving into open source! I've been busy with other tasks and haven't looked at the icon issue yet. @Ghat0tkach, could you please assign this issue to Layak-Ali? They've already submitted a pull request related to it.

**Comment by Ghat0tkach** [comment]
Thank you @mayurjadhav2002 🙌.

**Comment by Layak-Ali** [comment]
Thank you @mayurjadhav2002
