### ISSUE TITLE
[UI] Community Link doesnt redirect

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery.io#1368]
### Description

The current community link on the navbar doesnt redirect to https://meshery.io/community/

### Expected Behavior

It should redirect to https://meshery.io/community/

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by mayurjadhav2002** [comment]
@Ghat0tkach but it's a dropdown menu if the link is applied to the dropdown button on a mobile screen, the user will not be able to see other options ie. user will be redirected to the community page and see would be unaware of "calender", "program" page links.
**please let me know your pov.** 
In my opinion, it would be better we if add one more link in the "Community" dropdown button with the text "**Join Our Community**". Like I attached in the below image


![Screenshot from 2023-08-19 18-27-56](https://github.com/meshery/meshery.io/assets/63432459/91ef1a56-bfed-49bd-a221-d508a5fda047)

**Comment by Ghat0tkach** [comment]
@mayurjadhav2002 , The community sections consists of all the sublinks mentioned on the drop down options .

**Comment by mayurjadhav2002** [comment]
@Ghat0tkach Yeap, So I guess the option is to add a link in the navbar which redirects to the community page. we can add that link in the community dropdown button.

**Comment by kituuu** [comment]
Can I try?

**Comment by swastik959** [comment]
@Ghat0tkach can you please assign this issue to me

**Comment by SUNNYKUMAR1232** [comment]
@Ghat0tkach   please assign this issue to me

**Comment by Vivek-Prajapatii** [comment]
Hi @Ghat0tkach , can you assign this issue to me ?
as i'm new to this project

**Comment by het4399** [comment]
hey @Ghat0tkach can you assign this to me , i want to start my journey in open-source!

**Comment by Ghat0tkach** [comment]
Thanks for your interest gents , Assigning issue in chronological order
@kituuu  , there you go

**Comment by Ghat0tkach** [comment]
@kituuu 


Let's discuss your progress on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Mohith234** [comment]
@rohan472000 Would you like to work on this issue?

**Comment by rohan472000** [comment]
Yeah sure, Thanks @Mohith234.

**Comment by rohan472000** [comment]
@Ghat0tkach can u explain a bit about this issue clearly like what exactly needs to do, adding one more menu in the drop-down or something else??

**Comment by arunavabasu-03** [comment]
can I work on this ?

**Comment by iArchitSharma** [comment]
@rohan472000 are you still working on this issue?

**Comment by rohan472000** [comment]
@iArchitSharma yes... working and also waiting for more clarity about this issue.

**Comment by iArchitSharma** [comment]
@Ghat0tkach, can you please clarify what exactly needs to be done here?

**Comment by Ghat0tkach** [comment]
Apologies for the late reply gents ,

So basically , whenever user clicks on community  . They should be redirected to meshery.io/community

**Comment by iArchitSharma** [comment]
@Ghat0tkach ok so dropdown has to be removed too than?

**Comment by rohan472000** [comment]
> Apologies for the late reply gents ,
> 
> So basically , whenever user clicks on community  . They should be redirected to meshery.io/community

So what about those drop-downs??

**Comment by Ghat0tkach** [comment]
Nope drop down should be there

**Comment by iArchitSharma** [comment]
@Ghat0tkach got it, thanks!
@rohan472000 I hope everything is clear to you now

**Comment by rohan472000** [comment]
> @Ghat0tkach got it, thanks!
> @rohan472000 I hope everything is clear to you now

Drop down should also be there and that community button should redirect also...how both would be possible with the same community button, plz correct me if I got wrong.

**Comment by Ghat0tkach** [comment]
> > @Ghat0tkach got it, thanks!
> > @rohan472000 I hope everything is clear to you now
> 
> Drop down should also be there and that community button should redirect also...how both would be possible with the same community button, plz correct me if I got wrong.

When we hover the drop-down should appear but while clicking we need to redirect to community page

**Comment by rohan472000** [comment]
> > > @Ghat0tkach got it, thanks!
> > > @rohan472000 I hope everything is clear to you now
> > 
> > Drop down should also be there and that community button should redirect also...how both would be possible with the same community button, plz correct me if I got wrong.
> 
> When we hover the drop-down should appear but while clicking we need to redirect to community page

Ahh ..got it.
