### ISSUE TITLE
Add alt tags to all images for improved accessibility and SEO

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1369]
### Description

Alt attributes within `<img>` tags are used by search engines to understand the contents of your images. They provide a textual description of images, allowing visually impaired users to understand the content and search engines to index images accurately.
Neglecting them will negatively affect the ranking in search results
### Expected Behavior

add alt tags to all images on the following pages. Alt tags should be descriptive and concise, conveying the purpose or context of the image without being overly verbose.
1. homepage
2. programs page
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by RavindraP04** [comment]
Please assign this to me @thisiskaransgit
I can solve this issue.

**Comment by blindaks** [comment]
I just attended the Open Source session! Can you assign this issue to me?

**Comment by thisiskaransgit** [comment]
Thanks for volunteering folks. As @RavindraP04 have been assigned other issue @blindaks,  go ahead with this one 🚀

**Comment by anonymous4561** [comment]
@thisiskaransgit can u also assign me any task I'm new comer to this repo

**Comment by leecalcote** [comment]
@blindaks how's your progress coming along?

**Comment by blindaks** [comment]
@leecalcote @thisiskaransgit I am unable to sign commits properly. It would be great if you could help me out.

**Comment by het4399** [comment]
@thisiskaransgit Hey can you assign this to me ,i want to begin my journey in open-source!

**Comment by RavindraP04** [comment]
@blindaks Are you still facing the issue to signoff  the commits ?

This is what helped me
Now you need to close the existing PR and raise a new one with proper signoff commits

To signoff the commits you can use --signoff or -s while writing the command to commit the changes
Use this command: $ git commit -s -m “my commit message”

For more info you can checkout this one :- https://volunteer.coscup.org/docs/en/dev/how-to-signoff/

**Comment by blindaks** [comment]
> @blindaks Are you still facing the issue to signoff the commits ?
> 
> This is what helped me Now you need to close the existing PR and raise a new one with proper signoff commits
> 
> To signoff the commits you can use --signoff or -s while writing the command to commit the changes Use this command: $ git commit -s -m “my commit message”
> 
> For more info you can checkout this one :- https://volunteer.coscup.org/docs/en/dev/how-to-signoff/

Thanks @RavindraP04 ! Could you please check if everything is correct now?

**Comment by RavindraP04** [comment]
Yes @blindaks, Now its correct

**Comment by blindaks** [comment]
> Yes @blindaks, Now its correct

Thanks for helping out :)
