### ISSUE TITLE
Utilize Liquid templates for feature sections on the homepage

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1370]
### Current Behavior
Currently, the feature sections on the homepage of meshery.io are hardcoded in HTML, which makes it challenging to update or maintain them efficiently.

### Desired Behavior
 To enhance flexibility and ease of maintenance, it is recommended to transition to Liquid templates for rendering the feature sections dynamically on the homepage. The features sections should be moved in the includes directory and are used as liquid templates.

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by samyakshah3008** [comment]
Ravindra Pandey wants to contribute, shall we assign?

**Comment by RavindraP04** [comment]
Please assign this issue to me @samyakshah3008 @thisiskaransgit

**Comment by samyakshah3008** [comment]
Please go ahead!

**Comment by Ghat0tkach** [comment]
hey @RavindraP04 
let's discuss about your progress on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by RavindraP04** [comment]
@thisiskaransgit @Ghat0tkach Can you please review the PR
