### ISSUE TITLE
Reduce the initial number of Integrations card  

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1371]
### Current Behavior
Currently, the Meshery.io homepage contains a large number of initial integration cards, which can negatively impact the payload and loading time of the website. This issue aims to address the payload concern by reducing the number of initial integration cards displayed on the homepage.

### Desired Behavior
Upon visiting the Meshery.io homepage, the number of initial integration cards should be reduced (for reference visit layer5.io), resulting in a decreased payload and improved loading performance.

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by mayurjadhav2002** [comment]
@thisiskaransgit, hey hi, I would be happy to work on this issue. can you assign me to this issue?
Also, the meshery.io have "see all" button in integration cards which redirects to another page, So you mean to add same "see all" button to meshery?

**Comment by thisiskaransgit** [comment]
@mayurjadhav2002, the button redirecting to [meshery.io/integrations](https://meshery.io/integrations) is already available

**Comment by Gautam-04** [comment]
![Screenshot (60)](https://github.com/meshery/meshery.io/assets/124668418/22ba3359-9862-46c1-ba42-c7b406973295)

Are we planning to implement something similar ??If yes then can you assign me this issue.

**Comment by fiifidawson** [comment]
@thisiskaransgit, if this is still open can you assign me to it?

**Comment by Layak-Ali** [comment]
@thisiskaransgit can you assign this to me?? No one is assigned yet

**Comment by mayurjadhav2002** [comment]
> @mayurjadhav2002, the button redirecting to [meshery.io/integrations](https://meshery.io/integrations) is already available

Ok so like, we can reduce the number of cards like on meshery. I understood 😀
Looks like no one assigned yet, can you assign this issue to me? 
I'd be happy to work on this issue.

**Comment by Mohith234** [comment]
If this issue is stale and unassigned I would like to work on it

**Comment by dhiraj0911** [comment]
would like to work on this issue
@thisiskaransgit can you assign this to me?

**Comment by vishalvivekm** [comment]
Folks, as we follow FCFS while assigning issues, I'll need to first ask @mayurjadhav2002 if he's still willing to drive this home.
Not getting a response, we'll proceed with assigning this issue to anyone of you up for it.

**Comment by mayurjadhav2002** [comment]
@vishalvivekm sure, I'd be happy to work on this issue. If I stuck somewhere regarding information, I'll try to cover it in meetings.

**Comment by iArchitSharma** [comment]
Self assigning this issue

**Comment by iArchitSharma** [comment]
This issue is solved by #1476
