### ISSUE TITLE
Utilize the unused footer space

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1372]
### Current Behavior
 Footer does not effectively utilize the available space, resulting in more vertical space. 

### Desired Behavior
Update the container style to effectively use the horizontal area 
### Screenshots / Mockups
<img src="https://github.com/meshery/meshery.io/assets/92504666/079b3e4e-1b7c-418a-8088-d451add7ade5" width="25%">

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by swastik959** [comment]
@thisiskaransgit hi can I work on this

**Comment by thisiskaransgit** [comment]
Thanks for volunteering @swastik959,  since @Sranjan0208 is already assigned an issue, you can go ahead with this one

**Comment by leecalcote** [comment]
Not an issue.

**Comment by leecalcote** [comment]
@swastik959  apologies, this issue is invalid. Justify is by design here. Let's find another issue to assign you...
