### ISSUE TITLE
"Coming Soon" Image Overlaps Main Image on mobile device with width under 600px

### ISSUE THREAD

**Issue by charu1603** [meshery/meshery.io#1384]
### Description
There is an issue where the "coming soon" image in the cloud native catalog page, occupies the entire available space, causing the main image to be hidden from view on the mobile device with  width under 600px 
Also, there is some extra space under the filter button on the same page with width under 770px

![Screenshot (392)](https://github.com/meshery/meshery.io/assets/96014425/aed9158a-86c9-439f-8ef5-b3212d000d2f)
![Screenshot (391)](https://github.com/meshery/meshery.io/assets/96014425/fdd19c25-5676-4600-a2a0-89502e3af37a)
![Screenshot (395)](https://github.com/meshery/meshery.io/assets/96014425/f2f74f65-6aef-44f5-83d6-e99eb0dfb293)

### Expected Behavior

![Screenshot (393)](https://github.com/meshery/meshery.io/assets/96014425/ad1ee3f4-4c09-479f-a9de-0c6b8fc00bd4)
![Screenshot (394)](https://github.com/meshery/meshery.io/assets/96014425/02e23376-7187-4ff4-a676-c171e54bbc80)

Please assign  this issue to me 
---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by kituuu** [comment]
Can I do it?

**Comment by Ghat0tkach** [comment]
@kituuu  , there you go

**Comment by charu1603** [comment]
@Ghat0tkach I want to work on this issue , can you please assign

**Comment by Ghat0tkach** [comment]
@kituuu 
let's discuss about your progress on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by het4399** [comment]
Can i work on this issue @charu1603 ?

**Comment by Ghat0tkach** [comment]
@kituuu , are you still working on this issue?

**Comment by kituuu** [comment]
> @kituuu , are you still working on this issue?
> 

Yeah, asked something in the slack, but no-one replied.

**Comment by charu1603** [comment]
What are the issues you are facing  ?

**Comment by kituuu** [comment]
Oh sry that was for another issue,for this I will make a pr by EOD or tomorrow

**Comment by Ghat0tkach** [comment]
> > @kituuu , are you still working on this issue?
> 
> Yeah, asked something in the slack, but no-one replied.

@kituuu , We did brought this topic on website meeting , however your presence was necessary to address this further

**Comment by charu1603** [comment]
@kituuu are you still working on this issue ?

**Comment by charu1603** [comment]
@Ghat0tkach can I work on this issue ?

**Comment by kituuu** [comment]
@Ghat0tkach @charu1603 due to some issues/emergencies I can't contribute for 10-15 days. Extremely sorry for that. Currently I have 2 open PR. Other than that I have 2 issues assigned to me. This one and one more. For the time being, can you assign these 2 issues to newcomers or someone else. I will comment on the other issue as well.

**Comment by Narottamchy** [comment]
Hey I'm working on this issue please assign this to me I'm opening the pull request it's done from my side

**Comment by Ghat0tkach** [comment]
@charu1603  there you go ,

@Narottamchy , we assign issues in chronological order and since @charu1603 raised this issue , she may wish to work on this one as well

**Comment by Narottamchy** [comment]
ohkk no worry

**Comment by abhijeetgauravm** [comment]
> @Ghat0tkach can I work on this issue? I know how to fix this and have been waiting since I opened this issue

Hey @charu1603 Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)

**Comment by charu1603** [comment]
Please review this pr @abhijeetgauravm @Ghat0tkach
