### ISSUE TITLE
Search Bar loses Focus when you don't type fast.

### ISSUE THREAD

**Issue by Layak-Ali** [meshery/meshery.io#1385]
### Description
I'm having trouble with Meshery's website's search function. When I type to search for blogs, it shows results for each letter I enter. However, if I don't type quickly, it removes my cursor, which makes the search frustrating. For instance, I need to click the search bar multiple times to search for something like '**How to bind Kubernetes**'.

### Expected Behavior
The cursor should remain in the search bar without being interrupted or removed, regardless of typing speed.

### Screenshots
![Screenshot (28)](https://github.com/meshery/meshery.io/assets/93964740/9d4db9fd-0ec2-46f3-95fc-d2da629a6633)

### Enviroment:
 - OS: Windows
 - Browser: Chrome
 - Version: 
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ghat0tkach** [comment]
@Layak-Ali , this is related to meshery website . Please open this issue on https://github.com/meshery/meshery/issues

**Comment by Layak-Ali** [comment]
okay @Ghat0tkach
