### ISSUE TITLE
Aligning Theme Change Icon in the Navbar

### ISSUE THREAD

**Issue by Adi-ty** [meshery/meshery.io#1386]
### Description
The theme change icon in the navbar is not properly aligned with the rest of the navbar. Currently, it is slightly positioned upwards, creating a visual misalignment within the navigation bar. 

### Expected Behavior
The theme change icon in the navbar should be in alignment with rest of the navbar.

### Screenshots

<img width="960" alt="image" src="https://github.com/meshery/meshery.io/assets/92062352/330a28ed-174e-43e0-8cd0-488874fe6560">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Layak-Ali** [comment]
@Adi-ty its working fine for me. I didn't encounter a bug. Check again in different browser.

**Comment by iArchitSharma** [comment]
@Adi-ty, I've confirmed the alignment issue across Chrome, Firefox, and Edge browsers. The theme change icon in the navbar is slightly off, causing a visual disconnect.

**Comment by iArchitSharma** [comment]
@Ghat0tkach Can I work on this issue?

**Comment by Nidhi-Sharma9419** [comment]
Can I work on this issue? It is not aligned.

**Comment by het4399** [comment]
can you assign me ,i want to work on this @Adi-ty

**Comment by iArchitSharma** [comment]
@Ghat0tkach Made the PR do give it a check #1394
