### ISSUE TITLE
[Docs] Multiple spelling errors in architecture/adapters 

### ISSUE THREAD

**Issue by FirePing32** [meshery/meshery.io#1390]
https://docs.meshery.io/concepts/architecture/adapters#is-each-meshery-adapter-made-equal
`infrastructure` is wrongly typed in multiple places along with some grammatical mistakes.

**Comment by kumarankit999** [comment]
Can I work on this

**Comment by FirePing32** [comment]
Closing since this is relevant to https://github.com/meshery/meshery
