### ISSUE TITLE
Catalog open-modal margin issue

### ISSUE THREAD

**Issue by vaibhav-xt** [meshery/meshery.io#1391]
### Description
I found a bug on open-modal. margin should be zero (width < 700px) it should same as the desktop. 

![sdfs (3)](https://github.com/meshery/meshery.io/assets/90946899/38e6b356-a822-471f-afd2-83d4f56917e7)

### Expected Behavior
margin should be zero.
> expected 
![Screenshot (280)](https://github.com/meshery/meshery.io/assets/90946899/41b9153d-a03f-4674-a9b6-b5a3322d1719)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---

 
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by harish343** [comment]
I want to like work on this issue

**Comment by harish343** [comment]
Hey @vaibhav-xt can you tell me where i can make change in which file
