### ISSUE TITLE
Import any catalog item responsive issue

### ISSUE THREAD

**Issue by vaibhav-xt** [meshery/meshery.io#1392]
### Description
Import any catalog item window is not properly responsive for a mobile device. 

![WhatsApp Image 2023-08-31 at 10 14 31 (1)](https://github.com/meshery/meshery.io/assets/90946899/8919d6a3-7d12-468c-8695-a5b34778af6e)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Mohith234** [comment]
I would like to work on this issue

**Comment by vaibhav-xt** [comment]
Go ahead @Mohith234

**Comment by vaibhav-xt** [comment]
@Mohith234 , kindly provide your latest updates during today's (Monday) website call. Please refer to the attached [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima) for reference.

**Comment by Mohith234** [comment]
@vaibhav-xt I was unable to join the meet but yeah I'll be raising the PR by tomorrow.
