### ISSUE TITLE
Copy blogs from smp-spec.io to meshery.io/blog

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1395]
#### Current State of the Meshery.io site

The blogs on the meshery.io site can be found at https://meshery.io/blog.
Head over to https://smp-spec.io/ and locate the BLOG section on the homepage

#### Desired State of the Meshery.io site

Copy the blogs from https://smp-spec.io/ to https://meshery.io/blog while maintaining the original date and author's name.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by akhilender-bongirwar** [comment]
Hey @vishalvivekm, I would like to work on this issue.

**Comment by vaibhav-xt** [comment]
@akhilender-bongirwar you go.

**Comment by vishalvivekm** [comment]
> @akhilender-bongirwar you go.

Thanks @vaibhav-xt :) // @akhilender-bongirwar

**Comment by vaibhav-xt** [comment]
@akhilender-bongirwar, kindly provide your latest updates during today's (Monday) website call. Please refer to the attached [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima) for reference.

**Comment by Sangam-ghimire** [comment]
@vaibhav-xt what's the status, I think I can work on this...
