### ISSUE TITLE
Add recent talks into meshery.io talks and presentations page

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1396]
#### Current State of the Meshery.io site

Talks And Presentations can be found at https://meshery.io/talks-and-presentations

#### Desired State of the Meshery.io site

Navigate to https://layer5.io/community/events/2 and access the Events section. 
 - <img width="678" alt="Screenshot 2023-09-01 010047" src="https://github.com/meshery/meshery.io/assets/110674407/8c7be18a-d51d-4a04-bd1a-21bd36c56afe">
Incorporate the ten most recent <b>Talks</b> into the https://meshery.io/talks-and-presentations page.

<h3><details><summary>Click to get the ten most recent Talks</summary>
<ol>
<li><a href="https://layer5.io/community/events/kubecon-cloudnativecon-north-america-chicago-2023">https://layer5.io/community/events/kubecon-cloudnativecon-north-america-chicago-2023</a></li>
<li><a href="https://layer5.io/community/events/istiocon-virtual-2023">https://layer5.io/community/events/istiocon-virtual-2023</a></li>
<li><a href="https://layer5.io/community/events/kcd-chennai-2023">https://layer5.io/community/events/kcd-chennai-2023</a></li>
<li><a href="https://layer5.io/community/events/may-maintainers-circle-2023">https://layer5.io/community/events/may-maintainers-circle-2023</a></li>
<li><a href="https://layer5.io/community/events/kubecon-cloudnativecon-eu-amsterdam-2023">https://layer5.io/community/events/kubecon-cloudnativecon-eu-amsterdam-2023</a></li>
<li><a href="https://layer5.io/community/events/kubecon-cloudnative-north-america-2022">https://layer5.io/community/events/kubecon-cloudnative-north-america-2022</a></li>
<li><a href="https://layer5.io/community/events/hacktoberfest-prep-easing-into-cncf-open-source-projects">https://layer5.io/community/events/hacktoberfest-prep-easing-into-cncf-open-source-projects3</a></li>
<li><a href="https://layer5.io/community/events/devops-and-docker-live-show">https://layer5.io/community/events/devops-and-docker-live-show</a></li>
<li><a href="https://layer5.io/community/events/open-source-summit-north-america-2022">https://layer5.io/community/events/open-source-summit-north-america-2022</a></li>
<li><a href="https://layer5.io/community/events/kubecon-cloudnativecon-eu-virtual-2022">https://layer5.io/community/events/kubecon-cloudnativecon-eu-virtual-2022</a></li>
</ol>
</details></h3>

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by akhilender-bongirwar** [comment]
Hey @vishalvivekm, I would like to work on this issue.

**Comment by nakulbh** [comment]
Hey @vishalvivekm i would like to work on this

**Comment by vaibhav-xt** [comment]
Since you've already assigned an issue to @akhilender-bongirwar, it's now your turn, @nakulbh, to proceed.

**Comment by nakulbh** [comment]
okay i will start working on it

**Comment by vaibhav-xt** [comment]
@nakulbh, kindly provide your latest updates during the Monday website call. Please refer to the attached [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima) for reference.

**Comment by nakulbh** [comment]
@vaibhav-xt sorry sir but for some reasons i was not working on the issue, it would be better if i leave this issue can you please assign it to someone else. Thank you

**Comment by akhilender-bongirwar** [comment]
@vaibhav-xt I would like to work on this issue.

**Comment by vaibhav-xt** [comment]
@nakulbh no worries & @akhilender-bongirwar, you proceed.

**Comment by dhiraj0911** [comment]
@akhilender-bongirwar are you still working on this?
I did some research and I'm about to raised pr but getting some errors can me help me @vaibhav-xt @vishalvivekm

**Comment by vaibhav-xt** [comment]
@akhilender-bongirwar please provide us with your latest updates regarding this issue.

**Comment by akhilender-bongirwar** [comment]
@vaibhav-xt , I have started working on the issue.

**Comment by hevaibhavmaurya** [comment]
@dhiraj0911 go with these [issues](https://discuss.meshery.io/t/good-first-issues/3553).
