### ISSUE TITLE
Update Tutorials link reference

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1397]
#### Current State of the Meshery.io site

On the [Community page](https://meshery.io/community/), under Resources section 'Tutorials' card points to https://layer5.io/learn.

#### Desired State of the Meshery.io site

It should point to Tutorials section [here 👇 ](https://meshery.io/talks-and-presentations):
<img width="954" alt="Screenshot 2023-09-01 013408" src="https://github.com/meshery/meshery.io/assets/110674407/b322ffad-f4d0-4075-acb8-8783b1a3cba7">

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Nithinyanamaddi** [comment]
I would like to work on this issue, could someone assign it to me, if not already assigned.
