### ISSUE TITLE
update 'Mentorship Program' button link to point to correct URL

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1398]
#### Current State of the Meshery.io site

<img width="693" alt="Screenshot 2023-09-01 014450" src="https://github.com/meshery/meshery.io/assets/110674407/f7cbd1da-62e7-4fa4-876d-0b65def7f353">

On https://meshery.io/community page the "Mentorship Program" button points to https://layer5.io/community/meshmates

#### Desired State of the Meshery.io site

It should point to https://meshery.io/programs

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Nithinyanamaddi** [comment]
I would like to work on this issue, could someone assign it to me, if not assigned.
