### ISSUE TITLE
Lack of Spacing Between Next and Previous Blog Links in Blog Pagination

### ISSUE THREAD

**Issue by akhilender-bongirwar** [meshery/meshery.io#1402]
### Description
We can see the links for the next and previous blog are attached together for all the blogs in the website https://meshery.io/blog
![Screenshot 2023-09-02 225200](https://github.com/meshery/meshery.io/assets/112749383/74a6e066-c64e-41c4-a8ac-15d6562ac593)

### Expected Behavior

There should be enough gap between both the previous and next links for the good visibility and also for good user interaction (UX).

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by akhilender-bongirwar** [comment]
I want to work on this issue.

**Comment by Akshun-01** [comment]
Hi, I would like to take up this issue, if its still unassigned

**Comment by charu1603** [comment]
I would like to work on this issue

**Comment by Akhilbisht798** [comment]
Hi, can i work on this issue?

**Comment by vishalvivekm** [comment]
@akhilender-bongirwar 
As you have a couple of PRs above and assigned to a couple more, Let's give this issue to other contributors.

**Comment by vishalvivekm** [comment]
> @akhilender-bongirwar As you have a couple of PRs up and are assigned to a couple more, Let's give this issue to other contributors.

@akhilender-bongirwar Yes? No? :))

**Comment by mikenrowland** [comment]
Still unassigned? Can this be assigned to someone so that we know what issues are available to work on?

**Comment by Narottamchy** [comment]
Hey this issue is fixed now please review my pull request and merge the request

fix#1402
