### ISSUE TITLE
Navigation between blogs are in reverse direction

### ISSUE THREAD

**Issue by Mohith234** [meshery/meshery.io#1410]
### Description

- If you visit any blog in [meshery.io/blog](https://meshery.io/blog/) you will find the next blog and previous blog are in opposite directions at the bottom
- This is according to the dates, but as the user gets to see the newest on the top of the home page, the next blog should go to the old blog chronologically

### Expected Behavior

- The previous blog should be on the left and the next blog should be on the right.
### Screenshots

![image](https://github.com/meshery/meshery.io/assets/88539464/bc82978f-4039-48ae-8566-b72692ed3b47)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Mohith234** [comment]
If it seems like a valid issue, then I would like to work on this

**Comment by Mohith234** [comment]
@RavindraP04 I don't think it's the same issue. The issue you've mentioned is for space between the links. I am talking about the navigation of the links, where the right link should point to the next chronologically older post 

Hope I was clear.

**Comment by vaibhav-xt** [comment]
@vishalvivekm

**Comment by abhijeetgauravm** [comment]
[meshery.io/blog](https://meshery.io/blog/) why blogs arent visible to me?

**Comment by Ayush9026** [comment]
Hi @vishalvivekm sir i will try to fix #1402 issue.

**Comment by priyankarpal** [comment]
@Mohith234 404 
![image](https://github.com/meshery/meshery.io/assets/88102392/9b3991a7-88fa-46da-b8c3-5f965cc88b38)

**Comment by Mohith234** [comment]
@priyankarpal remove the `/` after the `blog`

URL - `meshery.io/blog`

**Comment by iArchitSharma** [comment]
@Mohith234, I don't see any issues; everything seems to be working perfectly here!

**Comment by iArchitSharma** [comment]
It was fixed with PR #1409
