### ISSUE TITLE
Button text are not visible due to small height of button

### ISSUE THREAD

**Issue by Cvr421** [meshery/meshery.io#1413]
### Description

Button Height are too small that why the button text are not visible . 
https://meshery.io/community/meshmate/members
### Screenshots

![Screenshot 2023-09-07 121133](https://github.com/meshery/meshery.io/assets/82499697/3797b2bf-4865-4e1d-9725-99ea682b0a5b)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Cvr421** [comment]
@Chadha93 @vishalvivekm /assign so i can fix this issue.

**Comment by Akshun-01** [comment]
Hi @Cvr421, can I take up this issue. I also wanted to start contributing to this repo and this issue seems fine.
If its okay with you, I can fix it ?

**Comment by hemantmm** [comment]
Hi @Cvr421 can I take up the issue?

**Comment by Ayush9026** [comment]
@Chadha93 and @leecalcote sir i created PR for this issue please review it.
https://github.com/meshery/meshery.io/pull/1414
