### ISSUE TITLE
Transparent Space Between Navbar items and Logo in Mobile view.

### ISSUE THREAD

**Issue by VivekBaldha0712** [meshery/meshery.io#1418]
### Description
When we click on the navbar icon in mobile view, There is a transparent space between logo and navbar items  

### Expected Behavior
The transparent space should not be there.

### Screenshots
<img width="179" alt="Screenshot 2023-09-09 102347" src="https://github.com/meshery/meshery.io/assets/86009821/7e3ceeae-30ff-41c8-be45-c9c847e3fc69">

### Enviroment:
 - OS: Windows
 - Browser: Chrome

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Akshun-01** [comment]
hi, I would like to work on this issue

**Comment by Manish4044** [comment]
Can I get to work on this?

**Comment by VivekBaldha0712** [comment]
@vishalvivekm Can you please assign this task to me.

**Comment by Ishwar-Zatke** [comment]
@vishalvivekm Can you assign this task to me. As a newcommer here, it can help me understand codebase and more.

**Comment by hemantmm** [comment]
Hi, @vishalvivekm, @Ghat0tkach  can I work on this issue

**Comment by Ghat0tkach** [comment]
Thanks for volunteering gents ,assigning in chronological order
