### ISSUE TITLE
[UX - Responsiveness] Learn - text alignment not consistent

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery.io#1425]
### Current Behaviour

- Link to website: https://play.meshery.io/
- The paragraph text under "The Cloud Native Playground" is center aligned
- However the text under "Sign-up to receive a user account..." is left aligned, additionally, the subheading under "Frequently Asked Questions" is also left aligned.

#### Screenshots

![su](https://github.com/layer5io/layer5/assets/19821445/4f8b370b-0232-4b02-b8ae-5dc9e3cd1a30)
![fqa](https://github.com/layer5io/layer5/assets/19821445/4e957960-d23a-4c31-906f-1abfc9eb0153)

### Suggested Behaviour
- To maintain design consistency text should have the same format i.e either left aligned or center aligned.

#### Screenshots

![mp](https://github.com/layer5io/layer5/assets/19821445/70d23f48-746e-41f7-bc11-eb929ca8aacd)
![su](https://github.com/layer5io/layer5/assets/19821445/14b9406d-cf77-4ce0-9aef-3ee44783ceb4)

### Environment:
- Host OS: Mobile responsiveness
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by dhiraj0911** [comment]
@sandramsc can you assign this to me

**Comment by sandramsc** [comment]
> @sandramsc can you assign this to me

Thank you for your interest in working on this issue! Its transferred from a different repo, and is already assigned to @anubhav1206

**Comment by anubhav1206** [comment]
Where exactly is the file to be modified located?

**Comment by abhijeetgauravm** [comment]
> > @sandramsc can you assign this to me
> 
> CC: @abhijeetgauravm
> 
> Thank you for your interest in working on this issue! Its transferred from a different repo, and is already assigned to @anubhav1206 (still might need to ask for re-assignment if interested)

@Ghat0tkach Can u assign him ?

**Comment by Mohith234** [comment]
@anubhav1206 Would you still like to work on this?

**Comment by sandramsc** [comment]
@r0nz-29 Hi, issues are assigned on a first come first serve basis to be fair to all contributors in the community, it's great that you're eager to contribute, however, you did not ask for this issue to be assigned to you, yet you already created a PR. Let's focus on collaboration first and not competition. If you haven't already, take a look at the contributing guidelines [here](https://meshery.io/community/newcomers), particularly the section on "Finding an Issue to Work On".

**Comment by anubhav1206** [comment]
> @anubhav1206 Would you still like to work on this?

If someone else would like to work then they surely can

**Comment by r0nz-29** [comment]
Well, the issue was inactive since days so i thought no one was working on it.
Didn't mean to offend anyone
Let me know if I have to delete the PR

**Comment by Mohith234** [comment]
@r0nz-29 Appreciate your enthusiasm toward contributing to the project. 

I would suggest "asking" before making a straight PR instead. Next time, do get assigned before working on the issue also give the [Contributing guidelines](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md) a read.

P.S. No need to delete the PR as of now, will review it and give feedback soon

**Comment by abhijeetgauravm** [comment]
hey @Mohith234 @sandramsc it seems like this issue belongs to [this](https://github.com/meshery/play) repo.

**Comment by sandramsc** [comment]
> hey @Mohith234 @sandramsc this issue belongs to [play](https://github.com/meshery/play) repo.

Thanks for noticing, I will recreate it in the mentioned repo (learning which website belongs to which repo has been a learning process in itself.)

**Comment by sandramsc** [comment]
@abhijeetgauravm @Mohith234 , Issue has been created in [play](https://github.com/meshery/play) repo as suggested and is open for assignment.

**Comment by r0nz-29** [comment]
Do I have to update my PR to reference the new issue? 
@sandramsc @abhijeetgauravm @Mohith234

**Comment by sandramsc** [comment]
> Do I have to update my PR to reference the new issue? @sandramsc @abhijeetgauravm @Mohith234

I would suggest following the contributor [guidelines](https://meshery.io/community/newcomers) mentioned in earlier comments, by asking the issue to be assigned to you first and making the PR you made (if assigned the issue), then you'll be good to go. Additional suggestions @Mohith234 @abhijeetgauravm ?

**Comment by abhijeetgauravm** [comment]
> Do I have to update my PR to reference the new issue? @sandramsc @abhijeetgauravm @Mohith234

Yeah after the assignment u can update your PR referencing the new issue.

**Comment by Mohith234** [comment]
Closing this issue as it is not related to this repository.

Thank you
