### ISSUE TITLE
[Documentation] update the CONTRIBUTING.md with Issues & Pull Requests sections

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery.io#1428]
Link to issue: [meshery.io](https://github.com/layer5io/layer5/issues/4932)

**Comment by sandramsc** [comment]
Hi, can I have this issue assigned to me, please?

- currently working on this issue in the Layer5 repo, creating a new issue in each repo mentioned so as to effectively maintain the procedure of creating an issue and thereafter a PR that closes it.

**Comment by SimardeepSingh-zsh** [comment]
Hey, I would be glad to contribute to this issue, please assign this issue to me.
