### ISSUE TITLE
Dark Mode by Default

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1429]
### Description
The meshery.ioi website is supposed to be in dark mode by default.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by toth2000** [comment]
looking into this

**Comment by rajatrar** [comment]
hey @leecalcote can you please assign me this issue.

**Comment by leecalcote** [comment]
@toth2000, did you find a solution?

@rajatrar, how about you?

**Comment by rajatrar** [comment]
@leecalcote am on it but I am unable to find the CSS/js file where the function of the button component is located I am on it as we have to change the function of the dark button so if anyone wants to change the mode in light mode can access that.

**Comment by rajatrar** [comment]
got the button file as i got the solution will let you know

**Comment by toth2000** [comment]
Good to hear @rajatrar . You can definitely take this issue. And feel free to ping me if you need any help.
