### ISSUE TITLE
lightmode syle improvement

### ISSUE THREAD

**Issue by ASIMNEUPANE** [meshery/meshery.io#1436]
### Screenshots / Mockups
![image](https://github.com/meshery/meshery.io/assets/124865108/a41a73e3-1f9a-4bb6-9925-dd2eefe0bb3e)

---

**Comment by ASIMNEUPANE** [comment]
let me handle this issue

**Comment by abhijeetgauravm** [comment]
hey @ASIMNEUPANE it's a duplicate issue of #1386 .

**Comment by iArchitSharma** [comment]
> hey @ASIMNEUPANE it's a duplicate issue of #1386 .
