### ISSUE TITLE
icon adjustment in the footer

### ISSUE THREAD

**Issue by ASIMNEUPANE** [meshery/meshery.io#1437]
### Current Behavior
There is a icon for only calendar it is looking bad let me fix that .

### Desired Behavior
 By removing calendar icon or add other element icon also helps the footer to look good .

### Screenshots / Mockups
![calender](https://github.com/meshery/meshery.io/assets/124865108/765fc52d-deaa-4ac6-8594-0c94a54e6e98)

**Comment by arunavabasu-03** [comment]
can I work on this ?

**Comment by nik132-eng** [comment]
searching for the first issue to work. can you please assign me this issue?

**Comment by tehami02** [comment]
May I work on this ?

**Comment by sudhanshu042004** [comment]
Could you assign me to this issue if it's not already assigned?

**Comment by vishalvivekm** [comment]
@arunavabasu-03 
Let's discuss this on Monday's website call. Please add it as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), If you would :)

**Comment by ASIMNEUPANE** [comment]
> @ASIMNEUPANE Let's discuss this on Monday's website call. Please add it as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), If you would :)

okay this would be great what is the time of the meeting?

**Comment by vishalvivekm** [comment]
> > @ASIMNEUPANE Let's discuss this on Monday's website call. Please add it as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), If you would :)
> 
> okay this would be great what is the time of the meeting?

5:30 PM IST.
Find all the meeting details here: https://meet.layer5.io
@ASIMNEUPANE

**Comment by iArchitSharma** [comment]
@ASIMNEUPANE @vishalvivekm, was this issue discussed in the meeting? If so, what was the conclusion?

**Comment by sudhanshu042004** [comment]
@iArchitSharma This issue couldn't be  discussed in the meeting

**Comment by abhijeetgauravm** [comment]
Hey @ASIMNEUPANE Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)

**Comment by hemantmm** [comment]
Hi, @abhijeetgauravm @vishalvivekm can I take up this issue?

**Comment by leecalcote** [comment]
@hemantmm additional icons would be nice.

**Comment by hemantmm** [comment]
Sure @leecalcote
