### ISSUE TITLE
Twitter logo need to be Updated to X

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery.io#1442]
### Description

Twitter logo in the last section of [meshery.io/community](https://meshery.io/community/#:~:text=meetings%20and%20events.-,Add%20Calendar,-Community) need to be updated to X

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by infiniteltd** [comment]
I would to work on this issue.

**Comment by infiniteltd** [comment]
I mean would love to work on this issue.

**Comment by saurabh100ni** [comment]
Go on @infiniteltd 😎🚀

**Comment by infiniteltd** [comment]
Thanks boss.

**Comment by saurabh100ni** [comment]
I see @adi-ray, @infiniteltd any updates?
PS: @adi-ray it's recommended to work on issue after assignment  ^ ^

**Comment by infiniteltd** [comment]
I have also made the changes. Creating a Pr soon.

**Comment by saurabh100ni** [comment]
@adi-ray @infiniteltd ,
Let's go with @infiniteltd 's PR as he was assigned to the issue.

I'm sure @adi-ray there are many open issues you can contribute to ^ ^

**Comment by adi-ray** [comment]
@saurabh100ni There is no PR raised, so it would be great if i continue with this issue, as I had already made the required changes.
Thanking You.

**Comment by sandramsc** [comment]
> @saurabh100ni There is no PR raised, so it would be great if i continue with this issue, as I had already made the required changes. Thanking You.

@adi-ray thank you for your enthusiasm, as @saurabh100ni has already tried to emphasize, you need to request for an issue to be assigned to you first before opening PR (this reduces the risk of wasting your time and effort as a result of the issue being rightfully assigned to someone else), i.e only after it is assigned to you then open the PR. If you haven't already, consider familiarizing yourself with the  [Contributing guidelines](https://layer5.io/community/newcomers), particularly the section under "Finding an Issue to Work On".

**Comment by hemantmm** [comment]
Hi, @saurabh100ni could I work on this issue?

**Comment by abhijeetgauravm** [comment]
@infiniteltd updates here?

**Comment by sohamtembhurne** [comment]
Hi @abhijeetgauravm,
I think the PR here fixes the issue. Since its a small issue, I don't think it should take 2 weeks to fix it.

**Comment by adi-ray** [comment]
> @saurabh100ni could you please assign this issue to me . I have made the required changes .

@abhijeetgauravm

**Comment by abhijeetgauravm** [comment]
> > @saurabh100ni could you please assign this issue to me . I have made the required changes .
> 
> @abhijeetgauravm

Hey @adi-ray, since there is already a PR, you can help in reviewing the PR.

**Comment by adi-ray** [comment]
Ohk !!!

**Comment by HimanshuMahto** [comment]
hey can you assign me this work as a  new to open source world it would be a great help to work on this.
