### ISSUE TITLE
missing catalog when opened in firefox

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1443]
### Description

-  When opened in Firefox,  https://meshery.io/catalog doesn't show any catalog:
<img width="957" alt="image" src="https://github.com/meshery/meshery.io/assets/110674407/b0e5a5fe-5ab4-40b1-9c44-6bdfa6b4f409">

### Expected Behavior

- The catalog cards should be visible:
<img width="816" alt="image" src="https://github.com/meshery/meshery.io/assets/110674407/7711be15-7603-4b8e-9ac5-fb37db4eb5ca">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment]
i would like to work on this one!
