### ISSUE TITLE
[Visual Design] Improve the catalog modal

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery.io#1445]
### Current Behavior
When a user clicks on a catalog card on the [catalog page](https://meshery.io/catalog) a modal pops up, it looks something like shown in the image below.
![image](https://github.com/meshery/meshery.io/assets/51539117/9515f08b-7eb4-442c-98d5-9cb6005cc083)

### Desired Behavior
Create and implement a mockup for the design of the modal that pops up when a user clicks on the catalog card.
### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Harsh3363** [comment]
Hi @ritiksaxena124 I would like to work on this issue, please assign this to me.
Thanks

**Comment by ritiksaxena124** [comment]
Sure @Harsh3363 go ahead 👍

**Comment by vishalvivekm** [comment]
@Harsh3363 any updates? 
would you like to sound off in today's websites meeting? : https://meet.layer5.io at 5:30 PM IST.

**Comment by Harsh3363** [comment]
Hey, I'm really sorry for the delay, I've been working on the issue, and right now I'm figuring out how to fix this.

**Comment by Harsh3363** [comment]
Hi @ritiksaxena124 can we connect on Discord I want to have some info regarding the expected outcome you want for this issue

**Comment by ritiksaxena124** [comment]
You can join our [Slack ](https://meshery.slack.com/ssb/redirect) channel. BTW the modal needs redesign. Currently, it doesn't look good so a mockup is needed for it

**Comment by sudhanshutech** [comment]
There was recent enhancement to the modal, that works fine. Lets comeplete this issue for now and open other of needed
