### ISSUE TITLE
Github create issue for catalog bug 

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/meshery.io#1447]
The schema used to create an catalog issue have a link linked to wrong URL 

### Example
[Screencast from 2023-10-02 19-39-02.webm](https://github.com/meshery/meshery.io/assets/59491379/e0f660e0-cab7-476b-a1f9-e350c3f47a77)

**Comment by captain-Akshay** [comment]
@vishalvivekm i would like take this one too

**Comment by vishalvivekm** [comment]
There you go @captain-Akshay
