### ISSUE TITLE
[Catalog] CI: Update catalog workflow is failing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1449]
See log here - https://github.com/meshery/meshery.io/actions/runs/6392065869/job/17348590571

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](https://slack.meshery.io) for access.

**Comment by leecalcote** [comment]
I thought that this might have been an issue with the lack of authentication, but that doesn't appear to be the case necessarily.

**Comment by theBeginner86** [comment]
This has been fixed. https://github.com/meshery/meshery.io/actions/runs/6503963117

It was due to missing support to dynamically create directory for different types of catalog content, eg: `deployment`, `workloads` etc.
