### ISSUE TITLE
Nav bar not properly aligned

### ISSUE THREAD

**Issue by GouravKumar13** [meshery/meshery.io#1450]
### Description
Nav bar is not properly aligned

### Screenshots
![image](https://github.com/meshery/meshery.io/assets/55110247/644e3b02-1d1e-4801-ab26-f2a875d892d5)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by shiivamtaneja** [comment]
I would like to work on this

**Comment by iArchitSharma** [comment]
Hi @GouravKumar13,
This issue has already been mentioned and is being worked on. You can track its progress here: [#1386](https://github.com/meshery/meshery.io/issues/1386)"

**Comment by leecalcote** [comment]
Thank you very much, @GouravKumar13 and @iArchitSharma
