### ISSUE TITLE
Flickering in default dark theme

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1451]
### Description

There's flickering in default dark theme on reload or while navigating to other pages of site.

https://github.com/meshery/meshery.io/assets/110674407/c3cc5eaf-642d-443d-90b7-99e71431254d

### Expected Behavior

 The light theme doesn't have any flickering issue and the same is desired for the dark-theme too.

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by coder12git** [comment]
@vishalvivekm I want to work on this. So, just for surity, I want to ask that issue is mainly that the site has default dark theme but on navigating to different pages of site, it's showing light theme first and after few seconds it's coming to it's default dark mode, and this is same for reloading the site. Am I right?

**Comment by ArpitShukla3** [comment]
i am looking into it

**Comment by ArpitShukla3** [comment]
No, but i am trying to understand code flow

**Comment by ArpitShukla3** [comment]
@coder12git could you help me in getting started with its code flow

**Comment by vishalvivekm** [comment]
> @vishalvivekm I want to work on this. So, just for surity, I want to ask that issue is mainly that the site has default dark theme but on navigating to different pages of site, it's showing light theme first and after few seconds it's coming to it's default dark mode, and this is same for reloading the site. Am I right?

Right @coder12git. 
Will be following FCFS while assigning // @coder12git @ArpitShukla3 

> could you help me in getting started with its code flow

Great call out by @ArpitShukla3, :)

**Comment by coder12git** [comment]
> @coder12git could you help me in getting started with its code flow

Sure, you can message me on slack ;)
