### ISSUE TITLE
Alignment issue in the navbar

### ISSUE THREAD

**Issue by Khalid-debugg** [meshery/meshery.io#1456]
### Description

There is a clear alignment gap in the navbar
### Expected Behavior

quick fix to the alignment

### Screenshots

![2 issue](https://github.com/meshery/meshery.io/assets/62448116/b82c4783-458d-4410-99fc-fce971b3622a)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by abhijeetgauravm** [comment]
Hey @Khalid-debugg its a duplicate issue of #1386 .

**Comment by iArchitSharma** [comment]
> Hey @Khalid-debugg its a duplicate issue of #1386 .

As mentioned, I'm closing this issue!
