### ISSUE TITLE
Theme toggle icon not aligned properly

### ISSUE THREAD

**Issue by HarshDeep61034** [meshery/meshery.io#1464]
### Description
The theme toggle button in https://meshery.io website's navbar is not aligned properly along with the other text content.

### Expected Behavior
it should aling in height exactly as `Getting Started` button.

### Screenshots
![Screenshot from 2023-10-13 11-22-28](https://github.com/meshery/meshery.io/assets/121210012/ffef200a-59c5-48ed-8620-f77dfc29b667)

### Enviroment:
 - OS: Linux
 - Browser: Chrome 
 - Version: Ubuntu 22.04 LTS
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ratishjain12** [comment]
@HarshDeep61034 assign me this issue so I can fix it asap :)

**Comment by HarshitVashisht11** [comment]
Can you assign this to me i can fix this issue

**Comment by abhijeetgauravm** [comment]
Hey @HarshDeep61034 its a duplicate issue of #1386 .
