### ISSUE TITLE
Button text becoming rarely visible on hover

### ISSUE THREAD

**Issue by singodiyashubham87** [meshery/meshery.io#1466]
### Description

When I hovered over Become an Adopter button its brightness increased and the font text remained white which made the text visibility low which is bad for the UX

### Expected Behavior
The text color should have to be black on hover

### Screenshots

![image](https://github.com/meshery/meshery.io/assets/93720428/c8ddf593-c356-44d7-b4f3-f0c74a32dd5c)

### Environment:
 - OS:  Linux 
 - Browser: Brave
 - Version: 1.57
 - Device: Desktop 

Kindly assign me this issue.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by singodiyashubham87** [comment]
@itsarraj But still It'll be better for the user experience if we do some styling changes.

**Comment by coder12git** [comment]
Yes i agree with @itsarraj , actually the button is perfect and rest all buttons on the site also follows the same design, so it's fine!

**Comment by Rohxn16** [comment]
Can I get assigned to this issue?

**Comment by sudhanshutech** [comment]
All buttons are consistent so it doesn't required, @Rohxn16 lets get you assigned to other issue. Thanks @singodiyashubham87
