### ISSUE TITLE
Add a dark-mode version of eBPF logo on meshery catalog page

### ISSUE THREAD

**Issue by Shreyas0410** [meshery/meshery.io#1470]
Currently the eBPF logo is not visible accurately [on](https://meshery.io/catalog)

![Screenshot 2023-10-19 195715](https://github.com/meshery/meshery.io/assets/70795867/98779f8e-40ad-47c7-8e2e-1c8a84f32365)

Add a suitable dark mode image following the guidelines of eBPF logo mentioned [here](https://ebpf.foundation/brand-guidelines/)

**Comment by iArchitSharma** [comment]
@vishalvivekm, do we really need this? I believe all 4 logos are meant to be the same for both theme modes.

**Comment by iArchitSharma** [comment]
As @sudhanshutech already mentioned [here](https://github.com/meshery/meshery.io/pull/1473#issuecomment-1793567099) that there is no need of dark-mode version of eBPF logo
