### ISSUE TITLE
Add horizontal slider for showcasing Meshery Extension.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery.io#1477]
#### Current State of the Meshery.io site
<img width="1150" alt="Screenshot 2023-10-26 at 9 54 36 PM" src="https://github.com/meshery/meshery.io/assets/79860504/b730d9f3-b578-4d00-a48f-5c1e611c6522">

The screenshot and text doesn't describe the capability of Meshery Extension to its fullest.
#### Desired State of the Meshery.io site

Add a vertical slider instead of the current screenshot. The left hand side of the slider would contain a K8s manifest for a multi-tier application. 
The right side of the slider would contain the simplified view of the manifest i.e. Screenshot of  manifest rendered on canvas.

_If the contributor working on this issue, cannot find a screenshot/YAML to display, please atleast proceed with implementing the slider, leaving the screenshot/YAML as a placeholder._

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@yash37158 any progress?

**Comment by yash37158** [comment]
Apologies for being inactive on this issue, as I was travelling last week. I'll raise PR for this ASAP!

**Comment by yash37158** [comment]
is it fine, if I change the .gitignore file @vishalvivekm @MUzairS15 ?

**Comment by leecalcote** [comment]
FYI @yash37158 and I chatted about why `_site` can't be modified and is ignored.
