### ISSUE TITLE
[Docs]:  Back-to-Top Button in README

### ISSUE THREAD

**Issue by Killer2OP** [meshery/meshery.io#1486]
### Current State:
![image](https://github.com/meshery/meshery.io/assets/111378171/18dc2a39-6fad-4bec-ada2-517aad826dce)

### Desired State:
![image](https://github.com/meshery/meshery.io/assets/111378171/21d10b85-b4e6-4063-a276-93b2668a43f6)

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Killer2OP** [comment]
@leecalcote Can you assign me this issue.

**Comment by coder12git** [comment]
@Killer2OP i don't believe it's an issue.

**Comment by Killer2OP** [comment]
> @Killer2OP i don't believe it's an issue.

I am suggesting that , we can add the back-to-top the button in readme to enhance the user experience .

**Comment by abhijeetgauravm** [comment]
Hey @Killer2OP  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by iArchitSharma** [comment]
@Killer2OP, can you tell us more about why you think it's an important feature to have?

**Comment by iArchitSharma** [comment]
We do not need this currently.

**Comment by abhijeetgauravm** [comment]
Hey @Killer2OP Let's discuss this on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by abhijeetgauravm** [comment]
Hey @Killer2OP  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Aseem22** [comment]
hey @iArchitSharma, can I work on this task?
