### ISSUE TITLE
[FEAT] : Search feature for the catalog page

### ISSUE THREAD

**Issue by Lucif3r-in** [meshery/meshery.io#1488]
### Current Behavior

In the catalog section of meshery.io [meshery.io/catalog](https://meshery.io/catalog) we do not have search feature for the cards.
### Desired Behavior

We can introduce a searching feature for the catalog page
### Screenshots / Mockups

For reference : [here](https://meshery.layer5.io/catalog)

Comment reference:
@Lucif3r-in do we have an open issue on search for the catalog? If not, do you mind opening one?

We can use https://lunrjs.com or similar.

_Originally posted by @leecalcote in https://github.com/meshery/meshery.io/issues/1481#issuecomment-1789286810_
---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Lucif3r-in** [comment]
I would love to work on this😊

**Comment by abhijeetgauravm** [comment]
There u go @Lucif3r-in

**Comment by abhijeetgauravm** [comment]
any updates here @Lucif3r-in ?

**Comment by Lucif3r-in** [comment]
> any updates here @Lucif3r-in ?

Yeah will make a draft PR today, I am having some issue in having full width for the searched card.

**Comment by Raj100679** [comment]
Is this issue still open?
