### ISSUE TITLE
[catalog] Display lazy loading in catalog page

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery.io#1497]
### Desired Behavior

A lazy loading should display unless the catalog cards are properly loaded

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by balagowda** [comment]
I would like to work on this

**Comment by sudhanshutech** [comment]
great, have you build meshery.io succesfuly?

**Comment by balagowda** [comment]
yes , I'm successful building locally

**Comment by abhijeetgauravm** [comment]
There u go @balagowda

**Comment by balagowda** [comment]
as i observed that many cards are not receiving the image. the source of image is blank
-->
https://raw.githubusercontent.com/layer5labs/meshe…n-assets/76c9f25a-fb01-48d6-9f07-4c476c6104f9.png
--

<img width="1440" alt="Screenshot 2023-11-15 at 6 38 13 PM" src="https://github.com/meshery/meshery.io/assets/111847375/c98b5023-e38d-40a7-81de-66b3e671fc2b">

**Comment by coder12git** [comment]
> as i observed that many cards are not receiving the image. the source of image is blank
> 
> https://raw.githubusercontent.com/layer5labs/meshery-extensions-packages/master/action-assets/design-assets/76c9f25a-fb01-48d6-9f07-4c476c6104f9.png
> 
> <img alt="Screenshot 2023-11-15 at 6 38 13 PM" width="1440" src="https://user-images.githubusercontent.com/111847375/283125277-c98b5023-e38d-40a7-81de-66b3e671fc2b.png">

This is fixed in upcoming release.

**Comment by sudhanshutech** [comment]
@balagowda can you come up with the implementation bit quick, this is required item

**Comment by Raj100679** [comment]
I will try working on this

**Comment by Raj100679** [comment]
Hello @sudhanshutech , Can you explain how does the desired behaviour looks like?

**Comment by balagowda** [comment]
> @balagowda can you come up with the implementation bit quick, this is required item

Desired outcome is needed for reference
