### ISSUE TITLE
[Catalog] Make thumbnail clickable; display full-size image

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1505]
:help-wanted: on <http://meshery.io/catalog|meshery.io/catalog> -

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1701278812084059)

**Comment by Raj100679** [comment]
Hey @leecalcote , Can you assign this issue to me?

**Comment by Raj100679** [comment]
@leecalcote When image is expanded how much width should it take and should we also need to provide close button to minimize it again?

**Comment by leecalcote** [comment]
@Raj100679 let me know what you figure out... make a proposal. Ideally, as large as the modal. Ideally, the modal doesn't go away, but perhaps another on top or just the same modal, but screenshot taking the whole space. Yes, user should return to their original location (modal) when done.

**Comment by 0xSaksham** [comment]
Hey any update on this issue?

**Comment by Raj100679** [comment]
@0xSaksham , will work on it today

**Comment by Raj100679** [comment]
Hey @0xSaksham , was not able to solve it, You can assign anyone who wants to work on this issue. Thanks

**Comment by 0xSaksham** [comment]
@Raj100679 I'll try this today.

**Comment by Raj100679** [comment]
@0xSaksham Sorry, I guess I have got it now, @leecalcote Can you suggest what more should i do ?

https://github.com/meshery/meshery.io/assets/85561967/0a0f6fd8-33b2-4b8b-9218-c8c69269df6d

**Comment by leecalcote** [comment]
@0xSaksham i think you nailed it. Looks great.

**Comment by abhijeetgauravm** [comment]
Hey @Raj100679  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Raj100679** [comment]
Hey @leecalcote , So I have stopped scrolling and centered image, more work has to be done when window size goes down 1300px, Any suggestions?
https://github.com/meshery/meshery.io/assets/85561967/9854a74e-945b-468f-bb16-cbf2f428a666

**Comment by leecalcote** [comment]
@leecalcote, please engage with other contributors as needed.

**Comment by Raj100679** [comment]
@abhijeetgauravm , what do u think abt it, should i raise a pr

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm , what do u think abt it, should i raise a pr

Looks good to me @Raj100679

**Comment by Raj100679** [comment]
@abhijeetgauravm will improve the css for responsiveness and will raise a pr by the end of week
