### ISSUE TITLE
Meshery Catalog crashing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1509]
### Description

![image](https://github.com/meshery/meshery.io/assets/7570704/2be2e9cf-3eeb-4656-8eb2-3571d32f6ee6)

### Enviroment:
 - OS: iOS
 - Browser: Safari AND Chrome
 - Device: Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShivamPandey00** [comment]
Hi @leecalcote
Is this still an issue, i checked it on both safari and chrome its just working fine.

**Comment by leecalcote** [comment]
@ShivamPandey00 thank you for confirming. I think we're good to go here now. 👍
