### ISSUE TITLE
[BUG]: The catalog search feature is misbehaving

### ISSUE THREAD

**Issue by Shurtu-gal** [meshery/meshery.io#1512]
### Description
The catalog search goes into an irrecoverable state when none of the search matches.

### Expected Behavior
Show that there is nothing and add recovery

### Screenshots
![image](https://github.com/meshery/meshery.io/assets/100484401/1ceb3cdd-e629-4f3d-aa1d-e7be6d7e1aaf)

### Enviroment:
 - OS: Linux
 - Browser: Chrome Firefox
 - Version: latest
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Shurtu-gal** [comment]
Hey, if possible I would love to work on this.

**Comment by abhijeetgauravm** [comment]
> Hey, if possible I would love to work on this.

there u go @Shurtu-gal
