### ISSUE TITLE
[Catalog] Frontmatter values with colon causing issue (e.g. userAvatarURL and image)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1516]
### Description

The image and userAvatarURLs have colons in them, which cause an issue when Jekyll is interpreting the page.

```
---
layout: item
name: Elastic search
userId: 551dcb82-7643-4709-8500-9a60e60030b9
userName: Yash Sharma
userAvatarURL: https://avatars.githubusercontent.com/u/71271069?v=4
type: Scaling
compatibility: 
        - KUBERNETES
patternId: 792f17b4-08f5-4654-8c10-3628fd56ac03
image: https://raw.githubusercontent.com/layer5labs/meshery-extensions-packages/master/action-assets/design-assets/792f17b4-08f5-4654-8c10-3628fd56ac03.png
```

### Expected Behavior
All frontmatter values must be in quotes.

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@MUzairS15 FYI

**Comment by Aseem22** [comment]
Both colons and hyphens can cause challenges in YAML front matter. To tackle this, we the option to enclose the troublesome text in double quotes, providing a means of escaping these characters. Another solution can be adding >(greater-than sign), for longer multiline texts, with proper indentation. In many places colons and/ hyphens are used that might cause issues.

**Comment by sudhanshutech** [comment]
This is done right @Yashsharma1911 ?

**Comment by Yashsharma1911** [comment]
Yes Sudhanshu
