### ISSUE TITLE
Add Recognition Program Link to Community section

### ISSUE THREAD

**Issue by iArchitSharma** [meshery/meshery.io#1520]
#### Current State of the Meshery.io site
![image](https://github.com/meshery/meshery.io/assets/74408634/a01691f4-80bc-4a18-a73c-3b9b91b564ba)
![image](https://github.com/meshery/meshery.io/assets/74408634/5350fb25-4b0f-4447-9034-d47eba6fb0e9)

#### Desired State of the Meshery.io site
Add [Recognition Program](https://badges.layer5.io/) link to the header and footer of the site, under the Community section

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
@iArchitSharma , I would like to work on this

**Comment by iArchitSharma** [comment]
@Raj100679 how is the progress?

**Comment by Raj100679** [comment]
@iArchitSharma not much, will work on it tomorrow

**Comment by iArchitSharma** [comment]
@Raj100679, this is an important task, please get it done by tomorrow

**Comment by Raj100679** [comment]
Sure @iArchitSharma

**Comment by Raj100679** [comment]
@iArchitSharma do we have any icon for recognition

**Comment by leecalcote** [comment]
There is an icon defined for the program currently. // @nwanduka @ritiksaxena124

**Comment by ritiksaxena124** [comment]
Icon for Recognition @Raj100679 
![Recognition](https://github.com/meshery/meshery.io/assets/51539117/16f7263d-070f-4068-bafc-6541872781a4)

**Comment by Raj100679** [comment]
@iArchitSharma @ritiksaxena124 Thanks I will raise a pr till midnight
