### ISSUE TITLE
Pagination of blog posts doesn’t work

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1522]
### Description
Pagination of blog posts doesn’t work on [meshery.io/blog](http://meshery.io/blog)

Blog list: https://github.com/meshery/meshery.io/tree/master/collections/_posts

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Lucif3r-in** [comment]
@Savio629 Currently we are seeing all the blog-posts at a single page. Is that correct?

**Comment by Lucif3r-in** [comment]
Got the issue @Savio629 @leecalcote please assign.
![image](https://github.com/meshery/meshery.io/assets/85403534/36e82808-fa3e-4b92-bfa2-5f3e79534642)
