### ISSUE TITLE
Alignment issue in the footer

### ISSUE THREAD

**Issue by charu1603** [meshery/meshery.io#1530]
### Description

I have identified an alignment issue with the item heading in the footer. The elements in the footer are not properly aligned, causing a visual inconsistency.

![Screenshot (518)](https://github.com/meshery/meshery.io/assets/96014425/05c2dc3c-2e9d-44e6-b364-d80abfbb87f1)

### Expected Behavior
![Screenshot (517)](https://github.com/meshery/meshery.io/assets/96014425/a5b378d5-3fb9-4986-b86e-ebe0bc23d6ec)

I want to work on this issue , please assign it to me .

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by abhijeetgauravm** [comment]
@charu1603 do you want to address this?

**Comment by charu1603** [comment]
Yes , I want to work on this issue

**Comment by abhijeetgauravm** [comment]
> Yes , I want to work on this issue

Thanks, Let it get assigned to you!
