### ISSUE TITLE
Overflow Issues on Meshery.io/blog

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery.io#1531]
### Description
There's Overflow issue on https://meshery.io/blog/unleashing-power-and-flexibility-the-synergy-of-rest-and-graphql-in-meshery

### Expected Behavior
This Behaviour needs to be fixed.

### Screenshots
![Screenshot_20231213-001355_Chrome](https://github.com/meshery/meshery.io/assets/101441772/fa37d075-0df2-44bc-8d80-ab774bb332b0)

### Enviroment:
 - OS: Android
 - Browser: Chrome
 - Version: 
 - Device: Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@saurabh100ni, thanks for raising this. If you're not taking assignment, please mark with `help wanted`.

**Comment by Lucif3r-in** [comment]
Hey @leecalcote, I can work on this please assign😊

**Comment by saurabh100ni** [comment]
@Lucif3r-in make sure to always ask for the assignment on issue before raising the PR next time, assigning you now.

**Comment by leecalcote** [comment]
Thank you, @Lucif3r-in 👍
