### ISSUE TITLE
Any blog isn't visible on the blog page of the site

### ISSUE THREAD

**Issue by abhijeetgauravm** [meshery/meshery.io#1533]
### Description

Any blog isn't visible on the blog [page](https://meshery.io/blog) of the [site](https://meshery.io/)
![image](https://github.com/meshery/meshery.io/assets/65087356/59edcd9f-84f7-474d-a6ba-edd12cd29313)

### Expected Behavior

All the blogs should be visible on the blog [page](https://meshery.io/blog) of the [site](https://meshery.io/).
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox Edge
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Shiva953** [comment]
would like taking this up

**Comment by abhijeetgauravm** [comment]
There u go @Shiva953

**Comment by leecalcote** [comment]
@Lucif3r-in can you try to fix as well?

**Comment by Lucif3r-in** [comment]
It is somehow working in my localhost and not in the main site🤔

**Comment by Savio629** [comment]
Similar issue as https://github.com/meshery/meshery/issues/9612
