### ISSUE TITLE
[Implementation] New page for brand resources

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery.io#1537]
### Current Behavior
We don't have a page on the meshery.io site from where contributors can download the resources related to meshery as we have on the layer5.io site (https://layer5.io/company/brand)

### Desired Behavior
- A new page is needed that is dedicated to all the resources related to Meshery, the same as we have on [layer5.io](https://layer5.io/company/brand)

- The layout of the page can be same 
- The URL of the new page could be meshery.io/brand
---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by omesh-omg** [comment]
@ritiksaxena124  can you assign this issue to me

**Comment by Raj100679** [comment]
@ritiksaxena124 I can work on this, if u can provide me with the zip file's link to meshery

**Comment by ritiksaxena124** [comment]
Thanks for your interest @Raj100679, we follow first come first serve basis so @omesh-omg you can start working on the issue 👍. you can find some meshery assets from[ meshery brand page](https://meshery.io/company/brand)

**Comment by omesh-omg** [comment]
okay @ritiksaxena124  thankyou 👍

**Comment by leecalcote** [comment]
@omesh-omg any progress to report? Will you present your work (completed) on this Monday's Websites meeting? Details -- https://meshery.io/calendar

**Comment by omesh-omg** [comment]
not compeleted working on it

**Comment by omesh-omg** [comment]
by mistake i removed myself 😵‍💫

**Comment by shourya2002-geek** [comment]
Hi, if this issue has not been completed yet, can you assign it to me ?

**Comment by sandramsc** [comment]
Hi @omesh-omg do you still intend to work on this issue? Let us know so we know to allow you more time, otherwise, we'll need to free (unassign you) the issue to allow other contributors to give it a go.

**Comment by omesh-omg** [comment]
Sorry I have a thesis seminar so please unassigne me thanks for it, @sandramsc

**Comment by shourya2002-geek** [comment]
Hi @sandramsc, can you assign it to me please ?

**Comment by sandramsc** [comment]
@shourya2002-geek I have assigned this to you, a quick reminder to take note on previous work done on the issue by reading previous comments etc., also if any questions come up while working on the task...creating a thread on the [discussion forum](https://discuss.meshery.io/) is a great way to get the wider community involved.

**Comment by leecalcote** [comment]
@shourya2002-geek how are things coming along here?

**Comment by shourya2002-geek** [comment]
> @shourya2002-geek how are things coming along here?

Hi @leecalcote, thanks for following up. 
Currently working on the layout of the brand page. Will post an update in a few days.

**Comment by leecalcote** [comment]
@Rexford74 you don’t have a draft design for this page, by chance?

**Comment by sudhanshutech** [comment]
@shourya2002-geek still working?

**Comment by shourya2002-geek** [comment]
> @shourya2002-geek still working?

Yes, @sudhanshutech , I am almost done with the page. Need some time for making the page responsive.

**Comment by sudhanshutech** [comment]
@shourya2002-geek last call , any progress?
If not,  join tomorrow website call @Rexford74 have a design up for review for this area

**Comment by shourya2002-geek** [comment]
@sudhanshutech , I need some help with making the page responsive. I'll show the progress in the websites call tomorrow. Does that work ?

**Comment by sudhanshutech** [comment]
yes sure , we are there to help you. Contact with @Rexford74 also tomorrows call he has a figma design that he will show

**Comment by shourya2002-geek** [comment]
Alright, thanks for understanding!

**Comment by sudhanshutech** [comment]
@Satakshijain // @Rexford74

**Comment by sudhanshutech** [comment]
@Rexford74 have you update the latest design here

**Comment by leecalcote** [comment]
@Satakshijain, can you pick this up? We’re getting no response from @shourya2002-geek in Slack.

**Comment by leecalcote** [comment]
Lots of issues with the implementation, @shourya2002-geek. Refactor. Stop creating one of styles. Stop duplicative, including scripts. Stop writing custom scripts.
