### ISSUE TITLE
Responsiveness of Meshery.io page on Mobile phones

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery.io#1541]
### Description
Responsiveness of Meshery.io page on Mobile phones

### Screenshots

<img src="https://github.com/meshery/meshery.io/assets/91362589/af023bde-ed1e-46cb-89c1-c1e181513953"  width="400"/>

### Enviroment:
 - OS: Android
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by yogesh-sirsat** [comment]
Hey @Savio629, can I work on this?

**Comment by LakshyaSatpal** [comment]
willing to work on this

**Comment by LakshyaSatpal** [comment]
Not able to reproduce this issue. Below is the screenshot from meshery.io:
![image](https://github.com/meshery/meshery.io/assets/81241551/46a04727-7583-4415-9815-98dc2c185bef)

This does not like the one given in the issue. @sudhanshutech Is this still open?
