### ISSUE TITLE
Adding icons to headings in footer

### ISSUE THREAD

**Issue by charu1603** [meshery/meshery.io#1543]
### Description
I would like to request the addition of icons to the headings in the footer for better visual representation and user experience

### Expected Behavior
Users should be able to easily associate each footer heading with its corresponding content through the addition of icons.

### Screenshots
![Screenshot (517)](https://github.com/meshery/meshery.io/assets/96014425/2616d2e8-9d7e-404d-8b95-a45408f77167)

I want to work on this issue. Please assign this issue to me 

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thanks, @charu1603. The Catalog has an [existing logo](https://layer5.io/company/brand)

**Comment by het4399** [comment]
Hello,I would love to work on this!.

**Comment by hemantmm** [comment]
@leecalcote would like to work on this issue.

**Comment by het4399** [comment]
Can i use font awesome icon? or is there any specific thing?
@leecalcote

**Comment by leecalcote** [comment]
The Catalog has an [existing logo](https://layer5.io/company/brand). Cloud Native Performance does, too, @het4399. Yes, I think that the rest can be generic.

**Comment by hemantmm** [comment]
@leecalcote In the Cloud Native Performance file when downloading the logo assets, there is no JavaScript file because there is a JavaScript file for the catalog when downloaded.

**Comment by leecalcote** [comment]
@hemantmm you've lost me. Javascript has nothing to do with this issue.

**Comment by hemantmm** [comment]
@leecalcote Sorry for this!

**Comment by het4399** [comment]
Heyy , i want to work on this issue.Sorry i couldnt made it earlier..
