### ISSUE TITLE
Responsiveness issue on meshery.io/blog

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery.io#1550]
### Description
meshery.io/blog page has responsive issues to be fixed

### Screenshots
![image](https://github.com/meshery/meshery.io/assets/101441772/3755f9d2-e30b-4e32-b620-85daa487338c)

### Enviroment:
 - OS: Windows
 - Browser: Chrome
 - Version: 
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by horizenight** [comment]
Kindly , assign this issue to me

**Comment by saurabh100ni** [comment]
Go on @horizenight 😎🚀
