### ISSUE TITLE
[Blog] Missing image and tags responsiveness

### ISSUE THREAD

**Issue by ashutosh-rath02** [meshery/meshery.io#1551]
### Description

- [x] In [meshery/blog](https://meshery.io/blog/page/2/) the image is missing for the blog.
- [ ] The tags are not looking good for smaller screens

### Screenshots
Screenshot for both missing image and responsiveness issue of tags
![Screenshot 2023-12-21 181430](https://github.com/meshery/meshery.io/assets/85403534/01399b09-5cef-496d-b5a7-234e574c01e6)

### Expected Behavior
The images should be visible along with the tags to have flex-column for smaller screens.
![image](https://github.com/meshery/meshery.io/assets/85403534/719f01b6-1f49-4c4e-b30f-571872baa453)

### Enviroment:
 - OS: Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop & Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
Can I work on this?

**Comment by horizenight** [comment]
Hello 
as the [meshery/blog](https://meshery.io/blog/page/2/) image is missing for the blog, issue is fixed. 
I will be working on the tags 🫡
