### ISSUE TITLE
Replace Id with Name of design in single catalog page 

### ISSUE THREAD

**Issue by Raj100679** [meshery/meshery.io#1569]
### Description

In catalog section when any card is clicked and when the my first app card is clicked it redirects to individual component page and the h2 tag shows the pattern-id value, instead it should show the pattern-name in h2 tag
Attaching a video below

https://github.com/meshery/meshery.io/assets/85561967/b6bed8c3-dfc0-4f18-8cd1-dba21875bfb2

### Expected Behavior
It should have shown the pattern - name there

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
If this issue is valid , Can you assign this to me?

**Comment by shourya2002-geek** [comment]
Hi, I would be happy to work on this issue. Can it be assigned to me if it is still valid ?

**Comment by Raj100679** [comment]
@leecalcote @vishalvivekm Can you check this and assign me

**Comment by sudhanshutech** [comment]
@Raj100679 this is urgent, please move here asap

**Comment by leecalcote** [comment]
@GaganpreetKaurKalsi might be able to assist.

**Comment by vishalvivekm** [comment]
> @Raj100679 this is urgent, please move here asap

@sudhanshutech fixed here: https://github.com/meshery/meshery.io/pull/1613

**Comment by Raj100679** [comment]
@sudhanshutech Sorry, I was away, If needed any help I can assist, Thanks
