### ISSUE TITLE
meshery install script fails with patch releases

### ISSUE THREAD

**Issue by hexxdump** [meshery/meshery.io#1573]
### Description
`curl -L https://meshery.io/install | bash - ` fails when the latest release is of type patch, for e.g. v0.7.3-patch.3

### Expected Behavior
install script should not fail, when the mesheryctl install packages are not available under:
https://github.com/meshery/meshery/releases/, by falling back to last stable version
Rather, the mesheryctl executables should made available for patch/beta/alpha/rc releases.
https://github.com/meshery/meshery/pull/9642 talks about the recent changes to the publishing of the install packages.

### Screenshots
![image (10)](https://github.com/meshery/meshery.io/assets/631835/0283a019-534d-40fb-85aa-002394fdb4d4)

### Enviroment:
 - OS: Any
 - Browser: Any
 - Version: v0.7.3-patch.3
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by cosmos1721** [comment]
@hexxdump 
i've recently observed the same issue and i'm trying to find what's causing the same. Thus i had  created an issue #10049

**Comment by hexxdump** [comment]
Will fix it to fall back to last stable release.

**Comment by hexxdump** [comment]
Will raise PR this week
