### ISSUE TITLE
Add support for dark/light mode snapshots on catalog page

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1575]
#### Desired State of the Meshery.io site

On https://meshery.io/catalog, we'll have dark and light versions of snapshots available and so the snapshots being shown should be compatible with current theme of the site.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
@vishalvivekm Can you explain what do you want here?

**Comment by surajvast1** [comment]
Hey I would like to work on this
