### ISSUE TITLE
[Site] Features: Incompatibility with dark mode

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1576]
### Description
The https://meshery.io/features page has a dark mode compatibility issue. See screenshot.

### Screenshots
<img width="1276" alt="Screenshot 2024-01-11 at 2 53 57 PM" src="https://github.com/meshery/meshery.io/assets/7570704/ded57a94-7952-4aa0-957e-7168d4091392">

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Gauravjadhav22** [comment]
Hi @leecalcote, I have set up Meshery.io and am eager to contribute. Could you please assign me this issue

**Comment by leecalcote** [comment]
Thank you for confirming that you have a working development environment for this project. That's very helpful, @Gauravjadhav22. Sure, you bet.

**Comment by Gauravjadhav22** [comment]
Hi @leecalcote I didn't find the Figma file for the Meshery.io/features page. Can you please confirm if it has been fixed?
https://github.com/meshery/meshery.io/assets/75011596/fc751456-54a3-4212-bc7a-6d0bb8e4d1ca

**Comment by leecalcote** [comment]
I don't know if there is a Figma page for this. There might be. Be sure to look in both "Meshery UI" and "Meshery Designs" design files.

**Comment by Gauravjadhav22** [comment]
Hi @leecalcote 
I couldn't find the Figma for this component, but I've fixed the background color to be compatible with the website's theme. Shall I proceed to raise the pull request?
https://github.com/meshery/meshery.io/assets/75011596/51e094da-677c-4aa3-9144-e18432aab919

**Comment by leecalcote** [comment]
@Gauravjadhav22  thank you. Yes, please.
