### ISSUE TITLE
[Website] enhance before and after screenshot

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1580]
### Current Behavior
On the homepage, there is a before and after section. The after screenshot is not the best.

![image](https://github.com/meshery/meshery.io/assets/7570704/968193bf-1c8b-46e5-8434-84b96f2352e6)

### Desired Behavior
Replace the after screenshot with a more intriguing version, like this one:

![image](https://github.com/meshery/meshery.io/assets/7570704/c779dc50-310a-467f-9aba-0a427e7c37b2)

Crop the image as needed.

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
@leecalcote Can you assign this issue to me? Also should I use the image that is provided by you?

**Comment by surajvast1** [comment]
@leecalcote Can you please assign this issue to me ?, it would mean a lot thanks.
