### ISSUE TITLE
[Platform Engineering with Meshery's Extension Points] - Grammar adjustment

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery.io#1590]
#### Current State of the Meshery.io site
 Link: [Platform Engineering with Meshery's Extension Points](https://meshery.io/)

Currently, this sentence reads as follows: "The great number of [extension points](https://docs.meshery.io/extensibility) in Meshery make it ideal as the foundation of your internal deleloper platform."
### Desired State

For increased readability and user experience the sentence could read as follows: "The great number of [extension points](https://docs.meshery.io/extensibility) in Meshery make it ideal as the foundation of your internal developer platform."

#### Screenshot

![dev](https://github.com/meshery/meshery.io/assets/19821445/40038bda-ffd5-4626-a19a-14cc11fff0e3)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
@sandramsc I would like to work on this

**Comment by sandramsc** [comment]
@Raj100679  I have assigned this to you.

**Comment by Raj100679** [comment]
@sandramsc Will raise a PR till midnight, Thanks :)
