### ISSUE TITLE
[Website UI] - The image is not being displayed.

### ISSUE THREAD

**Issue by BigBang001** [meshery/meshery.io#1595]
### Description

The image is not being properly displayed on the "meshery.io" main page/homepage, instead a image icon appears under the name "Content -aware OPA".

### Desired Behavior

The related image should be seen instead of image icon.

### Screenshots/Logs

Screenshot_20240121-191223_Chrome.jpg

### Environment

Browser: Chrome Safari Firefox
Host OS: Mac Linux Windows
Meshery Server Version: stable-v
Meshery Client Version: stable-v
Platform: Docker Kubernetes

### Contributor Guides and Handbook

🎨 Wireframes and designs for Meshery UI in Figma (open invite)

🖥 Contributing to Meshery UI

🙋🏾🙋🏼 Questions: Discussion Forum and Community Slack

**Comment by vishalvivekm** [comment]
Fixed.
