### ISSUE TITLE
[Docs Integrations & Extensions] - Missing list item description

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery.io#1599]
### Current State
Link: [Meshery Docs](https://docs.meshery.io/)
Currently the majority of the list items under "Integrations & Extensions" --> sub-section "Extensions" have a description. However, there are items without one.
#### Screenshot
![Screenshot 2024-01-23 025514](https://github.com/meshery/meshery.io/assets/19821445/e36db822-8379-490b-982b-90cdf5deb6ef)

### Desired State
Add missing descriptions for items under "Extensions".

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by sandramsc** [comment]
CC: @iArchitSharma

**Comment by Raj100679** [comment]
@sandramsc I would like to work on this, Can I know what should I add here?

**Comment by sandramsc** [comment]
Migrated issuse to [meshery repo](https://github.com/meshery/meshery/issues/10252)
