### ISSUE TITLE
[UI Bug] - Discussion Forum Image not visible

### ISSUE THREAD

**Issue by shourya2002-geek** [meshery/meshery.io#1601]
### Description

The Discussion Forum Image is not visible on the community page of Meshery.io. 
Link: https://meshery.io/community
Section: Community Forum

### Expected Behavior

The Discussion Forum Image should be visible 

### Screenshots

<img width="1501" alt="Screenshot 2024-01-23 at 3 44 17 PM" src="https://github.com/meshery/meshery.io/assets/75240318/54257137-3f33-4e02-9d30-2da6c5f948e1">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by suraj-py** [comment]
Hello @leecalcote sir, I have looked into the issue and found that the **"discussion-forum.png"** image is not present in the _/assets/images/_ directory.

**Comment by leecalcote** [comment]
Yikes!

@iArchitSharma @vishalvivekm do we know how this happened?

@suraj-py @shourya2002-geek could one of you fix urgently?

**Comment by leecalcote** [comment]
Be sure to search across the rest of the code base. I might have just been relocated. 

If you can't find it _anywhere_, then try reusing the discussion forum image from here - https://docs.meshery.io.

**Comment by shourya2002-geek** [comment]
Sure @leecalcote , on it already! You can assign to me.

**Comment by leecalcote** [comment]
@shourya2002-geek link to the image that you found?

**Comment by leecalcote** [comment]
I deleted this image by accident as it got grouped up in a collection of a few hundred others that I deleted.

The image from the other docs site is better than this one.
![](https://github.com/meshery/meshery.io/blob/1fe8002e7dfc30196eece0409528dc211674438b/assets/images/discussion-forum.png)

**Comment by shourya2002-geek** [comment]
<img width="1510" alt="Screenshot 2024-01-24 at 2 23 40 AM" src="https://github.com/meshery/meshery.io/assets/75240318/cadabc2b-4dad-44ac-893f-f89ba2e085f7">

@leecalcote , this one ?

**Comment by leecalcote** [comment]
yes

**Comment by shourya2002-geek** [comment]
@leecalcote , I have fixed the issue, and opened a PR.
