### ISSUE TITLE
[Catalog] Missing Technologies / missing images

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1603]
### Description
<img width="1204" alt="Screenshot 2024-01-23 at 3 59 37 PM" src="https://github.com/meshery/meshery.io/assets/7570704/6bdc0c5d-f179-4e45-9ee4-13be9ef9619f">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by surajvast1** [comment]
I would like to work on this

**Comment by theBeginner86** [comment]
Fixed. // @Yashsharma1911 

![Screenshot 2024-01-25 at 4 02 38 AM](https://github.com/meshery/meshery.io/assets/73700530/0fe799ba-438d-41f9-8b65-abe0cbbd71ac)
