### ISSUE TITLE
[Docs] 'Installation' link issue under 'Overview' 

### ISSUE THREAD

**Issue by udeet27** [meshery/meshery.io#1606]
### Current State:
- Clicking on 'Installation' under 'Overview' in the docs leads to 404.
<img width="1438" alt="Screenshot 2024-01-24 at 7 34 52 PM" src="https://github.com/meshery/meshery.io/assets/75639351/649a39ac-e412-4094-bc08-b9bee486c21a">

### Desired State:
- Simple fix to the href removing the trailing '/' 
<img width="1438" alt="image" src="https://github.com/meshery/meshery.io/assets/75639351/502b670e-4643-4601-8b60-c6497fc8d4c4">

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by udeet27** [comment]
Probably better suited for https://github.com/meshery/meshery

**Comment by saiyerniakhil** [comment]
I would like to work on this issue. Could anyone assign this to me?

**Comment by udeet27** [comment]
> I would like to work on this issue. Could anyone assign this to me?

sigh

**Comment by saiyerniakhil** [comment]
@udeet27 newbie here, please bear with me 😅

**Comment by omesh-omg** [comment]
@vishalvivekm I think this issue is not there right now it works fine for me, maybe we should close it ?
@udeet27

**Comment by udeet27** [comment]
yup seems fixed, can close
