### ISSUE TITLE
[bug] Fix overflow of text in Catalog Info Modal

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery.io#1608]
### Description

![Screenshot 2024-01-25 at 3 24 14 AM](https://github.com/meshery/meshery.io/assets/73700530/e789c53e-da75-4de3-87cb-065559c75f24)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by theBeginner86** [comment]
@surajvast1?

**Comment by dragon-slayer875** [comment]
Hello. Newcomer to the Meshery project!
I have read through the contributing guide and think I can fix this bug.
I intend to change some css rules in the ```catalog.scss``` file.
Particularly in the classes - ```.modal-image, .vertical-line and .pre-white-space```
I would like to request my assignment to this issue.
