### ISSUE TITLE
[Home] Dark mode compatibility for Layer5 logo

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1611]
### Current Behavior

<img width="847" alt="Screenshot 2024-01-22 at 6 12 44 PM" src="https://github.com/meshery/meshery.io/assets/7570704/bb688241-e56a-4a50-9f83-0c2daa62c0aa">

See layer5.io/brand for logos, if needed.

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by fardeenhasib** [comment]
Can I be assigned this issue?

**Comment by Shahbaz898414** [comment]
Can you assigned to this issue to me?

**Comment by Shahbaz898414** [comment]
@fardeenhasib are working on this issue?
