### ISSUE TITLE
Website does not have the correct trademark disclaimer

### ISSUE THREAD

**Issue by thisisobate** [meshery/meshery.io#1622]
As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

**Comment by Aseem22** [comment]
![copyright_1622](https://github.com/meshery/meshery.io/assets/89309144/36343b95-0866-46e5-b17a-b6900cb57c05)
Hey @thisisobate, I have added the provided content and link to the footer section of Meshery.io site.
Can you confirm if this is the desired result? I would like to work on this issue.

**Comment by surajvast1** [comment]
Hey I would like to work on this , considering that asking and working on issue only once,assigned was the procedure !!

**Comment by thisisobate** [comment]
@Aseem22 Yes, this is the desired result.

**Comment by Aseem22** [comment]
@thisisobate can you please assign me this issue?

**Comment by psankhe28** [comment]
@thisisobate , is this issue still available to work on?

**Comment by Rexford74** [comment]
Hi Pratiksha! I've taken a look at the implementation, and just having the word 'Trademarks' there looks a little vague. Is it possible to have something like what was implemented here as this has been confirmed to be the desired result by the issue raiser?

> ![copyright_1622](https://private-user-images.githubusercontent.com/89309144/300651593-36343b95-0866-46e5-b17a-b6900cb57c05.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDA0NDYsIm5iZiI6MTcxNTM0MDE0NiwicGF0aCI6Ii84OTMwOTE0NC8zMDA2NTE1OTMtMzYzNDNiOTUtMDg2Ni00NmU1LWIxN2EtYjY5MDBjYjU3YzA1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDExMjIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NmIyNjUxYzIxYTc2ZDVkM2NhNDUzOTM3ZmYyN2U5ZDlkOTFhNGU3NzA4ZWM0MzA2YmVlZDVkOWM5Y2U2MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T8y_35pgLnUhXxTY4iB17i6jtXJ1TFUSFeb06L27yZ0) Hey @thisisobate, I have added the provided content and link to the footer section of Meshery.io site. Can you confirm if this is the desired result? I would like to work on this issue.
