### ISSUE TITLE
Issue with Before Button Visibility in Slider

### ISSUE THREAD

**Issue by surajvast1** [meshery/meshery.io#1627]
### Current Behavior
The "Before" button on the website does not satisfies to the requirement of hiding when a scrollbar is above it.
You can find it [here ](https://meshery.io/)

### Desired Behavior
The "Before" button should be modified to hide when a scrollbar is above it.

### Screenshots / Mockups
![image](https://github.com/meshery/meshery.io/assets/99933579/1059135e-bc16-474f-b744-7ce496b535c7)

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
This is a bug. Thanks for calling this out, @surajvast1. Are you wanting to work on this one or are you opening it for general help?

**Comment by surajvast1** [comment]
I would like to open it for general help

**Comment by surajvast1** [comment]
@hardikn13 someone will surely assign you this !!
