### ISSUE TITLE
Removing errors from the website main page 

### ISSUE THREAD

**Issue by surajvast1** [meshery/meshery.io#1628]
### Current Behavior
The homepage of the website is generating errors every few seconds. And it keeps pilling up.

### Desired Behavior
The homepage should function without generating errors

### Screenshots / Mockups
![image2](https://github.com/meshery/meshery.io/assets/99933579/6537d655-d59f-4fdd-93f4-e87099f3d97a)

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by surajvast1** [comment]
I would like to work on this. Thanks

**Comment by sudhanshutech** [comment]
go ahead @surajvast1
