### ISSUE TITLE
broken integration images

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1639]
### Description

<img width="739" alt="image" src="https://github.com/meshery/meshery.io/assets/110674407/e7bb558a-5f5d-4827-88e6-3aeff5ca4d8b">

### Expected Behavior

This should be fixed
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by dextrot** [comment]
I could fix this @vishalvivekm

**Comment by vishalvivekm** [comment]
> I could fix this @vishalvivekm

👍
