### ISSUE TITLE
[DevOps] Populate Meshery Catalog with Sample Apps using mesheryctl

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1650]
## Current Situation
[Meshery Catalog](https://meshery.io/catalog) has a relatively small number of published designs.

## Desired Situation

Meshery Catalog is populated with a variety of published designs, representing any number of technologies in the designs and representing different categories of designs. 

## Difficultly Level: Beginner

This is a beginner-level issue designed to both help introduce you, the contributor, to additional Kubernetes concepts and DevOps practices, and to aid in creating a robust catalog full of cloud native design patterns and sample apps in the Meshery Catalog.

## Skills Needed

1. No coding skills needed.
2. Awareness of Kubernetes.

## Implementation

1. **Identify a Kubernetes sample app**
    1. Bring your own Kubernetes manifest or Helm Chart or Docker Compose file or...
    3. ...or identify a sample app from any available in public repos ([example 1](https://github.com/AdminTurnedDevOps/kubernetes-examples), [example 2](https://github.com/kubernetes/examples), [example 3](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples)).
    1. Attempt to identify resources that can benefit both newcomers and seasoned professionals.
1. **Import Kubernetes App**
    1. Import the sample application using `mesheryctl app import` command, [following this guide](https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-cli). 
1. **Publish Kubernetes App**
    1. Publish your sample app into the Meshery Catalog. Guides: Using Meshery UI or [Using MeshMap](https://docs.meshery.io/extensions/publishing-a-design).
1. **[Optional] Open App in Playground**
    1. Access [Meshery Playground](https://play.meshery.io) and open your app in [MeshMap](https://docs.meshery.io/extensions/meshmap).
1. **[Optional] Share your Kubernetes App**
    1. Be social and share your imported apps on twitter or linkedin and the Meshery project accounts will repost.
1. **Repeat**
    1. Import and publish five or more sample apps.

## Acceptance Criteria
1. Five or more new sample apps have been imported into Meshery and published into the Meshery Catalog.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Sangam-ghimire** [comment]
Hey @leecalcote I am learning this, I can help but will take some time.
If time is flexible, can you assign it to me.

**Comment by leecalcote** [comment]
Thanks for setting expectations, @Sangam-ghimire. Let's give it a go. 👍

**Comment by UncleWeeds** [comment]
@leecalcote, I am new to the community and have quite a bit of experience with Kubernetes and devOps related tech stack. I would love to work on this issue.

**Comment by sandramsc** [comment]
@UncleWeeds I have assigned this to you, go ahead.

**Comment by sandramsc** [comment]
@UncleWeeds Hi, it's been a while since this issue was assigned, with no updates, please let us know if you are still working towards a solution, what the update, if not we'll re-assigm to give other contributors a go at it.

**Comment by UncleWeeds** [comment]
@sandramsc Assign it to someone else

**Comment by shivankurchavan** [comment]
Is this issue still open and relevent ?? Can i work on it ?

**Comment by sandramsc** [comment]
@shivankurchavan You're welcome to give it a go. I've assigned it to you.

**Comment by sandramsc** [comment]
Hi @shivankurchavan it's been a while since this issue was assigned, and haven't had an update yet, let us know how progress is going, otherwise we'll need to re-assign to give other contributors a chance to give it a go.

**Comment by shivankurchavan** [comment]
yes i am working

**Comment by leecalcote** [comment]
@shivankurchavan It's been a little over a month and half since assignment. What progress can you share?

**Comment by THEBOSS0369** [comment]
Hey @leecalcote ! Yesterday i joined the meshery community and as a beginner searching for the beginner friendly issue and this one i came up to, so can i work on this issue. However, I’m relatively new to many concepts and tools mentioned in the issue, such as mesheryctl, Helm Charts, and the process of importing and publishing applications in Meshery. I think i can learn these things from this issue. I can't guarantee that i can complete this issue, but i will give my best shot and keep you updated what's going on with the process. I will try to complete this in one week.

**Comment by Ashparshp** [comment]
@shivankurchavan, Any luck?

**Comment by ziadhany** [comment]
I’m planning to work on this issue. Please let me know if anyone else is already working on it, and if not, feel free to assign it to me.

**Comment by Ashparshp** [comment]
@ziadhany, Go ahead!
