### ISSUE TITLE
Enhance the latest blog

### ISSUE THREAD

**Issue by iArchitSharma** [meshery/meshery.io#1651]
Add an image to the latest blog post and bold some of the bullet points for consistent formatting.
Blog - https://meshery.io/blog/simplifying-cloud-infrastructure-and-kubernetes-management

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](https://slack.meshery.io) for access.

**Comment by Satakshijain** [comment]
@iArchitSharma I would like to work on this issue can you assign it to me

**Comment by iArchitSharma** [comment]
@Satakshijain sure go on
