### ISSUE TITLE
Reduce the number of cards shown on initial page load

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1656]
### Description

when [meshery.io/catalog](https://meshery.io/catalog) loads, it displays all the patternCards at once. 
### Expected Behavior

It should show only the first 10 cards.
Visitors can then use `Prev` and `Next` buttons to display cards.
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by omesh-omg** [comment]
@vishalvivekm Hello can you assign this issue to me?
