### ISSUE TITLE
Top promotional banner is not responsive

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery.io#1659]
### Current Behavior
The top promotional banner is overflowing in mobile view and content is also clipped out
![WhatsApp Image 2024-03-19 at 6 03 32 PM](https://github.com/meshery/meshery.io/assets/51539117/03a6ccbe-94d4-4f87-a897-4f32ff108232)

### Desired Behavior
Fix the overflowing issue and the clipped content

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Fixed in https://github.com/meshery/meshery.io/commit/4381c13eeb4a740a474113920aa09f1a9b7a91d4
