### ISSUE TITLE
Enhance the pagination ux in blog page

### ISSUE THREAD

**Issue by ShivamCoder23** [meshery/meshery.io#1661]
### Current Behavior

Currently its ux is not good it  shows older post and newer post as pagination which is not we follow elsewhere:
![image](https://github.com/meshery/meshery.io/assets/160073697/1b1c339c-26e1-4efa-9a15-ab3b6a42d584)

### Desired Behavior

It should have a either button next page or prev page or something similar like layer5 blog
![image](https://github.com/meshery/meshery.io/assets/160073697/63bbc88e-19b4-40df-a362-f5f66eae2d87)

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayush844** [comment]
can i work on this issue

**Comment by ayush844** [comment]
@sudhanshutech,
do we need to keep the prev and next btn with the page number btns or just page number btns,
here is how it is looking right now with the prev and next buttons:

![Screenshot from 2024-03-27 15-39-52](https://github.com/meshery/meshery.io/assets/113158635/4228a189-377d-4b0b-b73e-dcfffd0a6656)

![Screenshot from 2024-03-27 15-40-00](https://github.com/meshery/meshery.io/assets/113158635/51802e06-4f75-4b75-82c5-eaf180cfac2a)

**Comment by ayush844** [comment]
and this is how it is looking without prev and next btns

![Screenshot from 2024-03-27 17-12-38](https://github.com/meshery/meshery.io/assets/113158635/370f3efb-c3f8-4f64-9af3-dbf125221e8d)
