### ISSUE TITLE
Meshery Logo not aligned in large screens

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [meshery/meshery.io#1664]
### Description
Meshery Logo is not properly aligned on larger screens (screen sizes greater than 1024px). There is extra spacing in the bottom area of the logo.

### Expected Behavior
The logo should be centered vertically and aligned consistently with other elements.

### Screenshots
![meshery-io-navbar-issue](https://github.com/meshery/meshery.io/assets/54661456/c85e8fff-3f5b-4659-93fb-52a858084056)

### Enviroment:
 - OS: Linux (Ubuntu)
 - Browser: Chrome
 - Version: Ubuntu 22.04.4 LTS
 - Device: Desktop Mobile

### Note:
I am resolving this issue, kindly assign it to me. Thank you.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
@Muhammed-Moinuddin Let's discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

**Comment by abhishekmmgn** [comment]
If no one is working on the issue can I work on that? 
It's a quick one, in the layout sass file we have to add flex book to project-name class.

**Comment by Muhammed-Moinuddin** [comment]
> If no one is working on the issue can I work on that? 
> It's a quick one, in the layout sass file we have to add flex book to project-name class.

Thank you for your interest but I'm already done with that.
