### ISSUE TITLE
Verify Meshery Charts repo as a publisher on Artifact Hub

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1667]
### Current Behavior
The Meshery Helm Chart repo is not listed as a verified publisher - https://artifacthub.io/packages/helm/meshery/meshery

### Desired Behavior
Verification process - https://artifacthub.io/docs/topics/repositories/#verified-publisher

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by marblom007** [comment]
I would like to assist here. 😄

**Comment by jameshorton2337** [comment]
I can give this a go.
