### ISSUE TITLE
Horizontally scrolling due to message-header and extra spacing.

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [meshery/meshery.io#1673]
### Description
Meshery website has spacing and scrolling issue, most probably due to new message header.

### Expected Behavior
There should be no extra spacing and scrolling in any of the screen sizes.

### Screenshots

https://github.com/meshery/meshery.io/assets/54661456/474eb834-77bf-40ed-8a4c-97bd6b50f81a

### Enviroment:
 - OS: Linux (Ubuntu)
 - Browser: Chrome
 - Version: Ubuntu 22.04.4 LTS
 - Device: Desktop Mobile

### Note:
I would like to work on this issue. Thanks.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ashutosh-rath02** [comment]
Hey @Muhammed-Moinuddin quick headsup!!
![image](https://github.com/meshery/meshery.io/assets/85403534/ac7d6dce-c5a2-4cf9-90fe-1e939886412a)

**Comment by ShivamAhir** [comment]
@Muhammed-Moinuddin I would like to work on this. can you please assign this to me

**Comment by Muhammed-Moinuddin** [comment]
> Hey @Muhammed-Moinuddin quick headsup!! This is causing the overflow, you can check even for mobile screens. ![image](https://private-user-images.githubusercontent.com/85403534/317565921-ac7d6dce-c5a2-4cf9-90fe-1e939886412a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NzQyODAsIm5iZiI6MTcxMTc3Mzk4MCwicGF0aCI6Ii84NTQwMzUzNC8zMTc1NjU5MjEtYWM3ZDZkY2UtYzVhMi00Y2Y5LTkwZmUtMWU5Mzk4ODY0MTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA0NDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMzE2ZmM2MTRlODQzMjVlOGY0OTI4YTlkZjI5NjBhNjJmYzIzNTI5NDZhNmEzMmRkMzY4Mjc5NDNkOWNjYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IqhEUf4CuuYM0c48Cfi_Fepe_utHc0xgb7EARagYMzE)

Noted. I'll check it out

**Comment by Muhammed-Moinuddin** [comment]
I've started working on it. Kindly assign it to me.

**Comment by iArchitSharma** [comment]
@Muhammed-Moinuddin there you go

**Comment by iArchitSharma** [comment]
@ShivamAhir Since issues are assigned in chronological order, we have some other open issues that you can take on.
