### ISSUE TITLE
Incorrect menu options  brand on mobile screens

### ISSUE THREAD

**Issue by ShivamAhir** [meshery/meshery.io#1685]
### Description
menu option under brand is not correct 

### Expected Behavior
![image](https://github.com/meshery/meshery.io/assets/74092725/7e09e8cc-6ec3-4e0a-b1ac-b53e0a1f0a61)

### Screenshots
<img width="666" alt="Sc
reenshot 2024-03-30 at 12 34 09 AM" src="https://github.com/meshery/meshery.io/assets/74092725/d5ac6db6-1284-4676-8f49-322458f03ae4">

on reloading browser

<img width="649" alt="Screenshot 2024-03-30 at 12 34 18 AM" src="https://github.com/meshery/meshery.io/assets/74092725/de1a9347-2e53-4bb1-96cd-72a3ad81ebaf">

video

https://github.com/meshery/meshery.io/assets/74092725/a4842002-bbea-489a-80cc-20ff92d5b4e4

### Enviroment:
 - Browser: Chrome 
 - Device: Mobile like iPhone

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShivamAhir** [comment]
@leecalcote I would like to work on the issue

**Comment by leecalcote** [comment]
Thanks, @ShivamAhir 👍 

FYI @abhishekmmgn @dragon-slayer875

**Comment by dragon-slayer875** [comment]
@leecalcote I have already raised a PR but the deployed preview helped point it out that css from one of the core files will need to be changed. 
Will update with a solution in the morning.

**Comment by ShivamAhir** [comment]
closing this issue as it is already resolve
