### ISSUE TITLE
page number in blog  section is not in centre 

### ISSUE THREAD

**Issue by ShivamAhir** [meshery/meshery.io#1686]
### Description
position of page number, newer button and older post button is not correct. page button should be in centre all the time but here combination of page number and button is in centre

### Expected Behavior
<img width="376" alt="Screenshot 2024-03-30 at 12 57 28 AM" src="https://github.com/meshery/meshery.io/assets/74092725/68609250-e5f8-42ee-ab58-cd1928bb465a">
<img width="381" alt="Screenshot 2024-03-30 at 12 57 05 AM" src="https://github.com/meshery/meshery.io/assets/74092725/b20f2d13-7c9f-4d8b-8b73-3c0df88a9284">
<img width="382" alt="Screenshot 2024-03-30 at 12 56 52 AM" src="https://github.com/meshery/meshery.io/assets/74092725/b8a6ad09-458b-4ca3-8125-71cb0e8cafc9">

### Screenshots
<img width="379" alt="Screenshot 2024-03-30 at 1 02 49 AM" src="https://github.com/meshery/meshery.io/assets/74092725/ab4eec27-03c0-4289-b098-b1830531d15d">
<img width="381" alt="Screenshot 2024-03-30 at 12 57 05 AM" src="https://github.com/meshery/meshery.io/assets/74092725/45ab1763-a7a4-4377-9990-cdef932ba3ad">
<img width="379" alt="Screenshot 2024-03-30 at 1 02 49 AM" src="https://github.com/meshery/meshery.io/assets/74092725/25b5df71-b5d6-4c3a-8f12-496ef0272430">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thanks, @ShivamAhir
