### ISSUE TITLE
Adding spacing between sidebar and catalogs

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [meshery/meshery.io#1690]
### Current Behavior
Sidebar is too close to catalogs

### Desired Behavior
There should be some space between them.

### Screenshots / Mockups
![Screenshot from 2024-03-30 15-56-13](https://github.com/meshery/meshery.io/assets/54661456/280e8e8b-475e-499d-9f3c-50cd34811730)

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by abhishekmmgn** [comment]
When data of cards is loading
![image](https://github.com/meshery/meshery.io/assets/107319349/dfa0d62e-1ebd-4989-a7af-e99b8d85c5df)
After loaded
![image](https://github.com/meshery/meshery.io/assets/107319349/e5a8c57e-c882-4883-8626-674420f3e43b)

Day before yesterday I had limit the number of cards, that time it was fine.
There is issues in css.

**Comment by Muhammed-Moinuddin** [comment]
> When data of cards is loading
> ![image](https://github.com/meshery/meshery.io/assets/107319349/dfa0d62e-1ebd-4989-a7af-e99b8d85c5df)
> After loaded
> ![image](https://github.com/meshery/meshery.io/assets/107319349/e5a8c57e-c882-4883-8626-674420f3e43b)
> 
> Day before yesterday I had limit the number of cards, that time it was fine.
> There is issues in css.
> 

Yes issue was in CSS and It is resolved now.
Thanks.

**Comment by abhishekmmgn** [comment]
The changes have not been merged yet, have they?

**Comment by abhishekmmgn** [comment]
Also, their is CLS (cls cumulative layout shift) when meshery.io is opened.
![image](https://github.com/meshery/meshery.io/assets/107319349/4c3db917-2a98-484a-9198-291de82db8dd)
![image](https://github.com/meshery/meshery.io/assets/107319349/790f59c1-fc0a-4144-87e9-aa6adaeef762)

Could you also look into that.

**Comment by sandramsc** [comment]
> > When data of cards is loading
> > ![image](https://private-user-images.githubusercontent.com/107319349/318222343-dfa0d62e-1ebd-4989-a7af-e99b8d85c5df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzY1MDMsIm5iZiI6MTcxMzk3NjIwMywicGF0aCI6Ii8xMDczMTkzNDkvMzE4MjIyMzQzLWRmYTBkNjJlLTFlYmQtNDk4OS1hN2FmLWU5OWI4ZDg1YzVkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNjMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzRlY2MzNTYwZWVlZDdjMzllNjdmYTNiNWViMjhmY2JjMWQ4ZDQwYWIzMWZjYTlkYzdkNTEwNzE1Zjc4MzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ixf-7HQJTOYDi4i7sgNqxuJqLhF6GbjI0iP3m8E_6vU)
> > After loaded
> > ![image](https://private-user-images.githubusercontent.com/107319349/318222356-e5a8c57e-c882-4883-8626-674420f3e43b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzY1MDMsIm5iZiI6MTcxMzk3NjIwMywicGF0aCI6Ii8xMDczMTkzNDkvMzE4MjIyMzU2LWU1YThjNTdlLWM4ODItNDg4My04NjI2LTY3NDQyMGYzZTQzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNjMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmY3NWQ2OGNmMThlYjUzOGRhOTExYmU3MmU5MTY1MTExNDczZTNlZDBiYzZlNzZkMTEzNWY4YzUwNDdiMWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j9zWczU8JPdY0Mz1VEme5S2vvmxeTNa8XKhJETEmeGQ)
> > Day before yesterday I had limit the number of cards, that time it was fine.
> > There is issues in css.
> 
> Yes issue was in CSS and It is resolved now. Thanks.

Hi @Muhammed-Moinuddin  can you please share how you came to the conclusion that the issue has been resolved, a reference to the resolution would be beneficial to future contributors might they come across this issue. With that said I'll go ahead and close this issue.

**Comment by sandramsc** [comment]
> > When data of cards is loading
> > ![image](https://private-user-images.githubusercontent.com/107319349/318222343-dfa0d62e-1ebd-4989-a7af-e99b8d85c5df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzY1MDMsIm5iZiI6MTcxMzk3NjIwMywicGF0aCI6Ii8xMDczMTkzNDkvMzE4MjIyMzQzLWRmYTBkNjJlLTFlYmQtNDk4OS1hN2FmLWU5OWI4ZDg1YzVkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNjMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzRlY2MzNTYwZWVlZDdjMzllNjdmYTNiNWViMjhmY2JjMWQ4ZDQwYWIzMWZjYTlkYzdkNTEwNzE1Zjc4MzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ixf-7HQJTOYDi4i7sgNqxuJqLhF6GbjI0iP3m8E_6vU)
> > After loaded
> > ![image](https://private-user-images.githubusercontent.com/107319349/318222356-e5a8c57e-c882-4883-8626-674420f3e43b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzY1MDMsIm5iZiI6MTcxMzk3NjIwMywicGF0aCI6Ii8xMDczMTkzNDkvMzE4MjIyMzU2LWU1YThjNTdlLWM4ODItNDg4My04NjI2LTY3NDQyMGYzZTQzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNjMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmY3NWQ2OGNmMThlYjUzOGRhOTExYmU3MmU5MTY1MTExNDczZTNlZDBiYzZlNzZkMTEzNWY4YzUwNDdiMWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j9zWczU8JPdY0Mz1VEme5S2vvmxeTNa8XKhJETEmeGQ)
> > Day before yesterday I had limit the number of cards, that time it was fine.
> > There is issues in css.
> 
> Yes issue was in CSS and It is resolved now. Thanks.

Hi @Muhammed-Moinuddin  can you please share how you came to the conclusion that the issue has been resolved? A reference to the resolution would be beneficial to future contributors might they come across this issue. With that said I'll go ahead and close this issue.
