### ISSUE TITLE
Meshery Brand Page Update [Website] 

### ISSUE THREAD

**Issue by Rexford74** [meshery/meshery.io#1692]
#### Current State of the Meshery.io site
The current mehsery brand page meshery.io/brand does not meet up to code requirements and needs to be restructured. An update has also been made to the design which needs to be included in the current implementation.

#### Desired State of the Meshery.io site
Restructure the code for the Meshery Brand page and ensure it meets up to the desired requirements. Link to [brand page](https://meshery.io/brand).
Include the updates to the designs in Figma. Find the designs in the Meshery UI design file using [this link](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=27509%3A126093&mode=design&t=TQ3giaDQe33TH1HI-1).

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@Rexford74 please update the issue, it does have brand page , but code is poorly written so some restructure is required

**Comment by Rexford74** [comment]
Oh I see. I didn't know it was eventually merged. Is it the one that Shourya worked on, @sudhanshutech ?

**Comment by Rexford74** [comment]
Thanks Lakshya. You have been assigned. Just let me know if you have any questions or need any clarifications. Thank you.

**Comment by psankhe28** [comment]
Hi @lakshz , are you still working on this?

**Comment by lakshz** [comment]
@psankhe28 currently not, due to my summer exams, will be on it after a week.

 Let me know if you are interested to work on this.

**Comment by psankhe28** [comment]
Yes, I am interested in working on this.

**Comment by psankhe28** [comment]
@Rexford74 Can you please give access to the Figma link? I have requested the access.

**Comment by Rexford74** [comment]
Hi @psankhe28! Thank you for indicating your interest to work on this. I have assigned you to this issue. As for the Figma access, I'll have to open up my PC to grant the access you need. Please give me a few minutes. Thanks.

**Comment by Rexford74** [comment]
I'm assuming you already have Figma access @psankhe28? I saw you on the board earlier. Just let me know if you need anything else. Thanks.

**Comment by psankhe28** [comment]
> I'm assuming you already have Figma access @psankhe28? I saw you on the board earlier. Just let me know if you need anything else. Thanks.

Yes, someone granted me the access.

**Comment by psankhe28** [comment]
@Rexford74 I needed to download the image, but the export option is disabled.

**Comment by Rexford74** [comment]
Hey Pratiksha! I'm so sorry for the delay on my part. These are the brand page assets you requested. Thank you for your patience.
[Meshery Brand Page Assets.zip](https://github.com/meshery/meshery.io/files/15047414/Meshery.Brand.Page.Assets.zip)

**Comment by psankhe28** [comment]
Thank you @Rexford74 !
