### ISSUE TITLE
Reduce content size.

### ISSUE THREAD

**Issue by abhishekmmgn** [meshery/meshery.io#1694]
This was discussed on the website development meeting.

### Current Behavior
Currently, on the homepage (https://meshery.io), we're fetching assets that are way too big.
1. The size of the video in the hero section is about 2.7 MB, which can be drastically reduced if we use formats like .webm.
2. The height of the avatars is 100–120px, and we are loading images up to 512*512px; they too can be reduced.

If we select the top images/gifs and reduce their size, we can easily save up to 4-5 MB. On the web, this could result in a lot of performance gains.

### Desired Behavior
-  Changed the hero section video to .webm format.
-  Reduced the size/dimension of avatar images to 128 or 256*256. And also converted them to .webp format.
- Reduced other big images, if any.

### Screenshots / Mockups
![image](https://github.com/meshery/meshery.io/assets/107319349/185834cc-cdc9-4491-aba0-62c220649aeb)

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by JayKay24** [comment]
Hi. I'd like to work on this.

**Comment by abhishekmmgn** [comment]
@vishalvivekm Could you please assign someone the task of reducing the content size?

**Comment by vishalvivekm** [comment]
> Hi. I'd like to work on this.

Thanks @JayKay24 
For reducing PNGs' size, look up tinypng.com

**Comment by abhishekmmgn** [comment]
@JayKay24 
Also, this site has a lot of tools, [RedKetchup](https://redketchup.io/). Or the [squoosh](https://squoosh.app/editor).
