### ISSUE TITLE
[Extensions] Descriptions needed for each extension

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1703]
:help-wanted:

Most of the “Considerations” portion of these extensions has invalid information and needs to be updated.

This modal is also in need of a button in order to visit the URL associated with the extension.

:help-wanted:

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1712231965378789?thread_ts=1712187401.607579&cid=C015QJKUMPU)

**Comment by singh1203** [comment]
@ritiksaxena124 please assign,
Thank you.
