### ISSUE TITLE
[Website] Features: missing items in list

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1729]
#### Current State of the Meshery.io site
On this page, https://meshery.io/features, items are missing.

<img width="429" alt="Screenshot 2024-04-26 at 3 45 40 PM" src="https://github.com/meshery/meshery.io/assets/7570704/3a0d55c2-3297-4bb9-8797-51190d4aff33">

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by shailpujan88** [comment]
Hey @leecalcote, can I work on this issue?

**Comment by ritiksaxena124** [comment]
Sure @shailpujan88 go ahead. Take a look at https://meshery.io/pricing for content to be added.
