### ISSUE TITLE
[UI] Programs Page

### ISSUE THREAD

**Issue by psankhe28** [meshery/meshery.io#1730]
### Description
On hovering the cards, the text is not properly aligned. It can be seen in the below video:

[Vid1](https://github.com/meshery/meshery.io/assets/84843461/c83814e6-d316-4ceb-9856-0487402421a8)

### Expected Behavior
[Vid2](https://github.com/meshery/meshery.io/assets/84843461/50935bd5-aff1-4baf-9864-50a7a8088b50)

### Enviroment:
 - OS:  Windows
 - Browser: Brave
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ritiksaxena124** [comment]
Thank you @psankhe28 for opening up an issue for this. I was thinking if we should keep the position of the text at the bottom-left and the text decoration be left-align or the position of the text  be bottom-center and the text-decoration be center because if we are positioning the text at the center both vertically and horizontally as you have shown in expected behavior video then the text LFX and MLH is not quite visible.

**Comment by psankhe28** [comment]
Should I proceed with the left-aligned version or the centered one?

**Comment by ritiksaxena124** [comment]
text-decoration: center; will work better in my opinion because other 3 cards (from start) are center aligned.

**Comment by psankhe28** [comment]
Should I make a PR with the change?

**Comment by ritiksaxena124** [comment]
Go ahead
