### ISSUE TITLE
Add a better background color to Choose your platform section on homepage

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery.io#1735]
### Current Behavior
The background color of a section that comes up when you click on any of the platforms under the `Choose your platform` section is the same as that of the whole section. 
![image](https://github.com/meshery/meshery.io/assets/51539117/07113a63-33f5-4d65-aa87-8666e52e2ae0)

### Desired Behavior
Change the background color of that inner section that pops up

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by MiirzaBaig** [comment]
Should I fix it?

**Comment by vishalvivekm** [comment]
> Hi @ritiksaxena124 , can I work on this issue?

Hi @psankhe28, 
As you're already working on a couple of items, let's keep this one for new contributors and make a call for volunteers.

**Comment by vishalvivekm** [comment]
> Should I fix it?

Hi @MiirzaBaig, 
Apologies to have missed your message.
Will you plesae confirm if you have the site running locally ?

**Comment by shailpujan88** [comment]
Hi @ritiksaxena124 , can I work on this issue?

**Comment by RishiGupta-05** [comment]
Can I work on this issue?

**Comment by iArchitSharma** [comment]
Thanks, @RishiGupta-05, but this issue is already assigned to someone else. Let's find another issue for you to work on.

**Comment by barkhaaroraa** [comment]
hi can i work on this issue?
