### ISSUE TITLE
[Catalog] Mispelled content category

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1741]
#### Current State of the Meshery.io site

On https://meshery.io/catalog, there is a misspelled category. 

![Screenshot 2024-05-14 at 6 43 18 AM](https://github.com/meshery/meshery.io/assets/7570704/9ef6e762-8c9a-4eed-b8f9-c20f60a521de)

#### Desired State of the Meshery.io site
This fix may or may not need to be down in GitHub Workflow.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1715687039631969?thread_ts=1715687039.631969&cid=C015QJKUMPU)

**Comment by iArchitSharma** [comment]
Fixed with this PR - https://github.com/meshery/meshery.io/pull/1743
