### ISSUE TITLE
update SM Icon with Pattern's

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1744]
### Description

Update Service Mesh Icon with Pattern's icon in https://meshery.io/catalog modal
![imageedit_2_9252050808](https://github.com/meshery/meshery.io/assets/110674407/1aa01516-4fc9-421a-899e-e9c6600ffac9)

Patterns Icon: https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/service-mesh-pattern.svg

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Muhu-Muza** [comment]
Hello @vishalvivekm ,
I would like to take on this task.

**Comment by vishalvivekm** [comment]
> Hello @vishalvivekm , I would like to take on this task.

Thank you @Muhu-Muza
