### ISSUE TITLE
[Website] Responsive issue with main menu at 1138px

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1749]
### Description
Please notice the unwanted behavior that occurs in-between the desktop and mobile-style menus. There is a transition starting at about 1138px that renders the menu unusable.

https://github.com/meshery/meshery.io/assets/7570704/cbb37951-555e-490a-b5dc-041121d04ab6

### Expected Behavior
The menu should always be in a usable state.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aryakoste** [comment]
Hello @leecalcote I would like to work on this issue.

**Comment by shailpujan88** [comment]
Hello @leecalcote I am not able to replicate this issue and can you please confirm if it is not device device-specific issue?
Please find the attached screenshot and screen recording for some reference.

https://github.com/meshery/meshery.io/assets/114280481/7234ba0a-0cb2-4596-953f-2ed3f67025ac

![WhatsApp Image 2024-05-20 at 11 45 18_2eaf5374](https://github.com/meshery/meshery.io/assets/114280481/b2a2a6a9-41d4-4973-a9f9-731d33ae5bfa)

**Comment by Aryakoste** [comment]
yeah i am also not able to replicate this issue. I tested on my device the menu occurence occurs at 1141px and the menu works fine on that. Below that hamburger icon is available.

**Comment by 26vanshika** [comment]
Hey I would like to work upon this issue @leecalcote

**Comment by sudhanshutech** [comment]
hey @26vanshika let's do it

**Comment by leecalcote** [comment]
Please note that this issue only occurs in Safari. Access to macOS is necessary in order to test.
