### ISSUE TITLE
[Website] Integrations icon updates

### ISSUE THREAD

**Issue by mayocream** [meshery/meshery.io#1760]
#### Current State of the Meshery.io site

Homepage: https://meshery.io/

Some application icons of integrations are missing and being default icon.

#### Desired State of the Meshery.io site

Review Integrations icons and updates.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by mayocream** [comment]
I'd like to assign myself on this task.
/assign @mayocream

**Comment by shubhusion** [comment]
@mayocream I would like to contribute to this issue. please assign this to me.

**Comment by mayocream** [comment]
@shubhusion please feel free to contribute :)

**Comment by vishalvivekm** [comment]
@shubhusion 
Do you have updates to share on this item ?
If yes, Let's discuss this on Websites call on Monday. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by ayushrakesh** [comment]
@vishalvivekm Can I work on this issue, as their is no updates from other sides.

**Comment by shubhusion** [comment]
Hi @vishalvivekm, apologies for the delay. I am working on it.

**Comment by shubhusion** [comment]
@vishalvivekm Some of the integration icons appear twice like GitHub, and kubesphere with the same permalinks. Should I remove one of them ?

**Comment by shubhusion** [comment]
PR under review
