### ISSUE TITLE
[Home] Relationships carousel does not update the focused text on rotate

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1763]
### Description
The text label for the first type of relationship is perpetually displayed as the focus text, leading site visitors to confuse the difference between the relationship examples in this carousel.

### Expected Behavior
Text label focus should rotate in concert with the carousel timing.

### Screenshots
<img width="523" alt="Screenshot 2024-06-13 at 4 42 33 PM" src="https://github.com/meshery/meshery.io/assets/7570704/d523cb0a-92a8-4563-9e83-a73bb0259070">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile
---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by asr2003** [comment]
@leecalcote @yash37158 I would like to work on this issue

**Comment by leecalcote** [comment]
Sounds good, @asr2003 👍

**Comment by vishalvivekm** [comment]
@asr2003 Thanks for chiming in.
Do you have updates to share on this item ?
Let's discuss this on Websites call on Monday. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

**Comment by ayushrakesh** [comment]
@leecalcote @vishalvivekm Can I work on this issue?

**Comment by sudhanshutech** [comment]
@asr2003 any progress?

**Comment by vishalvivekm** [comment]
@ayushrakesh @sudhanshutech 
Let's discuss this on websites call, I'll be adding it to agenda items: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by vishalvivekm** [comment]
Making this issue free of assignment..

**Comment by vishalvivekm** [comment]
Just one note: 
Currently, the carousel shows "Edge" relationships by default and changes to the respective relationship type only when the corresponding tab is clicked.

do we want that the carousel should automatically rotate through all relationship categories ("Edge," "Hierarchical," and "Sibling"), with the text label focus updating accordingly?

**Comment by preyanshu** [comment]
@vishalvivekm hii can i work on this?

**Comment by jaysomani** [comment]
Interested in working on this, can you assign me ?

**Comment by vishalvivekm** [comment]
Thank you everyone
you can watch this issue being discussed in the last Websites meeting on Moday, here: https://www.youtube.com/watch?v=7MqUgXDouJg&t=2573s

Following FCFS, I'll ask @ayushrakesh if you have the site set up and running ? If yes, let's assign this to you.

**Comment by ayushrakesh** [comment]
@vishalvivekm Yes, I have site setup locally, please assign to me.

**Comment by leecalcote** [comment]
@vishalvivekm, you might determine that this is an invalid issue that I have raised. In retrospect, I think that it’s validity can easily be called into question.

**Comment by shubhusion** [comment]
is this issue still relevant ?

**Comment by vishalvivekm** [comment]
> is this issue still relevant ?

Hi, thanks for asking.
I don't think so, at least now.
