### ISSUE TITLE
[Catalog] Enhancing “add catalog” workflow to auto-generate “artifacthub-pkg”

### ISSUE THREAD

**Issue by dusdjhyeon** [meshery/meshery.io#1764]
### Descriptions
- When catalog is added/updated the content of directory should be created/updated.
-  We need a small golang program which gets invoked as part of the add-catalog github workflow.
1. use the Catalog API to get all your catalog items
2. repeat 1 to generate the corresponding markdown file and write it to the correct location
3. call meshkit to get the artifacthub-pkg
4. create a folder name based on its ID
5. create both design files and artifacthub-pkg files in that directory

### Expected Behavior
- By autogenerating an artifacthub-pkg.yml, Catalogs can be automatically listed inside artifacthub.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](https://slack.meshery.io) for access.

**Comment by leecalcote** [comment]
Tagging @ctcarrier
