### ISSUE TITLE
[Website] Update "Import Any Catalog Item" Section with Correct `mesheryctl`

### ISSUE THREAD

**Issue by singh1203** [meshery/meshery.io#1765]
#### Current State of the Meshery.io site

The "Import Any Catalog Item" section on the [Meshery Catalog page](https://meshery.io/catalog) currently contains outdated mesheryctl commands and an incorrect documentation hyperlink. 

#### Desired State of the Meshery.io site

These need to be updated to reflect the latest meshery CLI commands (mesheryctl) and direct users to the most relevant documentation page [Catalog Management Guide](https://docs.meshery.io/guides/configuration-management/importing-designs#importing-designs-1) to ensure users have accurate instructions for importing catalog items into Meshery.
---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@singh1203 make sure to link your PRs and issues.
