### ISSUE TITLE
[Catalog] Capture content item metrics in remote provider

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1768]
### Current Behavior
Actions such as "Download", "Clone" and so on do not have their count incremented in order to track content popularity in the meshery.io/catalog

### Desired Behavior
Increment count in remote provider catalog.

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by codeSafari10** [comment]
please assign to me

**Comment by akshansh-modi** [comment]
@leecalcote i would like to work on this

**Comment by leecalcote** [comment]
@codeSafari10 @MUzairS15 has this functionality been completed?

**Comment by MUzairS15** [comment]
@aabidsofi19 ensured that a request was made to the remote provider when the download button was clicked.

@aabidsofi19 Did you also account for clone?

**Comment by leecalcote** [comment]
@MUzairS15 under what metric would he have done so for Download?

**Comment by leecalcote** [comment]
@akshansh-modi, sounds great. I can confirm that there is a "Downloads" metric available.

![Screenshot 2024-07-31 at 4 42 39 PM](https://github.com/user-attachments/assets/c9c60ced-8fc3-4597-a547-0df1eb8a4869)


See the [Cloud API](https://meshery.meshery.io/system/api/docs), if helpful.

**Comment by akshansh-modi** [comment]
@leecalcote i am unable to download , it seems to me that this is a cors issue 
![image](https://github.com/user-attachments/assets/86a76a94-8874-4095-b875-4344004494a4)

![Screenshot from 2024-08-02 16-22-53](https://github.com/user-attachments/assets/6a831cff-3c85-445b-8d7c-a3c5f3ed2a2c)

![Screenshot from 2024-08-02 16-23-26](https://github.com/user-attachments/assets/4a84b967-d5b3-42eb-9a0a-3cdcea39b291)

**Comment by akshansh-modi** [comment]
Is the catalog leaderboard you mentioned the one at [meshery.meshery.io](https://meshery.meshery.io/catalog/leaderboard)?

**Comment by leecalcote** [comment]
> Is the catalog leaderboard you mentioned the one at [meshery.meshery.io](https://meshery.meshery.io/catalog/leaderboard)?

Yes

**Comment by akshansh-modi** [comment]
@leecalcote, I looked into it and it seems to be an issue with the backend rather than with the meshery.io repository. If the link https://playground.meshery.io/api/pattern/download/${patternId} is the correct one being used here, that might be where the problem lies.
