### ISSUE TITLE
Add documentation hyperlink to each integration card

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1775]
### Current Behavior
The cards displayed in the visualization on https://meshery.io/integrations are not clickable.

### Desired Behavior
Programmatically ensure that each card has a hyperlink to its respective Meshery Docs page.

Example:

Camel K card should link to https://docs.meshery.io/extensibility/integrations/camel-k.

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by hargunkaur286** [comment]
Can I work on this issue?

**Comment by 2003Aditya** [comment]
> ### Current Behavior
> The cards displayed in the visualization on https://meshery.io/integrations are not clickable.
> 
> ### Desired Behavior
> Programmatically ensure that each card has a hyperlink to its respective Meshery Docs page.
> 
> Example:
> 
> Camel K card should link to https://docs.meshery.io/extensibility/integrations/camel-k.
> 
> <img alt="" width="16px" src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png">
> 
> #### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
> * 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
> * 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
> * 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

Sir, can u please explain a little bit more so i can work on this one

**Comment by 2003Aditya** [comment]
Sir! can you please explain little bit more
