### ISSUE TITLE
[Home] The switching of images in the relationships carousel causes the page contents to jump

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1795]
### Description
On the home page of meshery.io, there is a carousel causing a slightly jarring experience.
<img width="467" alt="Screenshot 2024-07-02 at 4 07 33 PM" src="https://github.com/meshery/meshery.io/assets/7570704/7d680225-5473-49f6-b1d0-fd663a274f95">

### Expected Behavior

The switching of images in the carousel should not cause any other elements on the page to move.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sethdivyansh** [comment]
I am interested to solve this issue. Please assign it to me.

**Comment by kanishk6103** [comment]
Hey Lee! I am interested in working on this issue.
