### ISSUE TITLE
Add search (filter) for an specific Integration on Homepage's Integrations section

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1798]
### Current Behavior

On https://meshery.io/ homepage  a section displays all the integrations that the project supports.
### Desired Behavior

[meshery.io](http://meshery.io/)’s home page is in need of a search (filter) for site visitors who wish to search for a specific integration.<br>

### Screenshots / Mockups

![Screenshot 2024-07-03 at 2 19 02 PM](https://github.com/meshery/meshery.io/assets/110674407/9b7249ee-e581-40aa-8bd2-23a19b8433f5)
---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by shubhusion** [comment]
@vishalvivekm please assign this issue to me.

**Comment by kanishk6103** [comment]
I wish to work on this issue. @vishalvivekm

**Comment by vishalvivekm** [comment]
Thank you gents for showing your interest in working on this issue.

Following FCFS, @shubhusion will you please let me know if you've the site set up and running ?

**Comment by shubhusion** [comment]
> Thank you gents for showing your interest in working on this issue.
> 
> Following FCFS, @shubhusion will you please let me know if you've the site set up and running ?

Yes, @vishalvivekm , I recently completed the integration icon updates issue , which is related to this. The site is set up and running.

**Comment by vishalvivekm** [comment]
Sounds goo @shubhusion.

@kanishk6103 Please feel free to look for the open issues using this link:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by kanishk6103** [comment]
Thank you i'll look into them @vishalvivekm

**Comment by shubhusion** [comment]
Hi @vishalvivekm,

I have successfully integrated the search bar on the home page as per the mockup provided. Do I also need to add the next and previous buttons present alongside the search bar with their functionalities?

**Preview:**

![image](https://github.com/meshery/meshery.io/assets/96301987/c2277d38-e8b7-401c-87cc-8f390b200382)

**Comment by shubhusion** [comment]
PR under review
