### ISSUE TITLE
Glitch in Vertical Scroll 

### ISSUE THREAD

**Issue by akshansh-modi** [meshery/meshery.io#1800]
### Description
The problem is that the website has an automatic vertical scroll, and after reaching a certain part of the page, it glitches.

### Expected Behavior
The automatic vertical scroll should function smoothly without glitches or interruptions.

### Vedio
https://github.com/meshery/meshery.io/assets/92106389/b007b586-3366-477b-bda1-23dedb8510df

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by akshansh-modi** [comment]
I have read contributing guidelines, and would like to work on this issue, please assign it to me

**Comment by akshansh-modi** [comment]
The scroll effect issue on the website was traced back to the slider script (`slick.js`). I suggest disabling the slider to improve user experience. By removing its autoplay functionality, we can eliminate unintended scroll interruptions and resolve the bug effectively.

**Comment by Ashparshp** [comment]
@akshansh-modi Please specify the browser and OS where you noticed the issue. It seems fine on my end! can you try again?

**Comment by akshansh-modi** [comment]
Browser: Chrome Version 126.0.6478.127
OS: Windows 11
Yup, I tried again. Sometimes it's working perfectly fine, but other times this glitch happens.

https://github.com/meshery/meshery.io/assets/92106389/c622aaad-4170-4a61-afbd-6671bfbad4fb

**Comment by akshansh-modi** [comment]
I also think we don't need the scroll effect it just hinders the user experience.
What are your thoughts on this?

**Comment by Ashparshp** [comment]
It seems like a design choice, so let's leave it as is. Let's also get @vishalvivekm thoughts on this.

**Comment by akshansh-modi** [comment]
Oh, it turns out the problem was due to a Chrome extension on my end called 'Video Speed Controller,' not the website itself. Sorry for any inconvenience this may have caused.
