### ISSUE TITLE
Catalog filter not working as expected

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery.io#1806]
### Description
On clicking technology it filters the data however on unclicking it it should filter again which it is not doing, also if I select technology I can select `Categories` and if I selected `Categories` then it will get deselect technology filters.

As you can see in video, it shows number `3` after Thanos technology however on click it only renders one design, either number is wrong or rendering

https://github.com/meshery/meshery.io/assets/71271069/c190de0b-06cc-4f5d-addd-384625ea31ce

### Expected Behavior
- [ ] User should be allowed to select both categories and technology
- [ ] On deselect trigger filter again to update rendered designs

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by kanishk6103** [comment]
I think I can help with this one

**Comment by iharshyadav** [comment]
I can do this and fix the issue.

**Comment by Yashsharma1911** [comment]
Thankyou gents for raising your hand, please can any of you confirm that you are able to run meshery.io locally?

**Comment by kanishk6103** [comment]
> Thankyou gents for raising your hand, please can any of you confirm that you are able to run meshery.io locally?

Yes everything is up and running 🫡

**Comment by Yashsharma1911** [comment]
Thanks for confirming @kanishk6103 here you go, @iharshyadav as we follow FCFS I will let @kanishk6103 take this issue you can checkout my recent issue which also needs help

**Comment by kanishk6103** [comment]
I have fixed this, can you kindly check that? @Yashsharma1911
