### ISSUE TITLE
Use pattern icon in catalog single page as fallback icon

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery.io#1809]
### Description
Currently incase snapshot of designs gets error or not able to render we show service mesh icon it should be replace with pattern icon

Here is a screenshot of the bug

![Screenshot 2024-07-06 at 10 05 07 PM](https://github.com/meshery/meshery.io/assets/71271069/6be8ce73-0cfc-4236-88c6-844ddf9434ff)

Here is a screenshot of pattern icon with which we want to replace it with, it can be found in existing assets

![Screenshot 2024-07-06 at 10 07 38 PM](https://github.com/meshery/meshery.io/assets/71271069/9fbb154a-a3ea-46b3-a801-927777c02892)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by krishkumar84** [comment]
hey kindly assign this to me i want to contribute in this

**Comment by Ashparshp** [comment]
@krishkumar84 Go ahead!

**Comment by Yashsharma1911** [comment]
@krishkumar84 checking in! are you still working on this?

**Comment by krishkumar84** [comment]
> @krishkumar84 checking in! are you still working on this?

yes recently i am working on another issue thats why now i am working on this

**Comment by Ashparshp** [comment]
Thanks for the update, @krishkumar84!
