### ISSUE TITLE
add padding to the hero section

### ISSUE THREAD

**Issue by preyanshu** [meshery/meshery.io#1811]
### Description
 we can use some padding or margin for the hero section content  https://meshery.io/brand 

![image](https://github.com/meshery/meshery.io/assets/118627824/a115995a-3880-4bb0-87bd-bbfc68c35c4d)
![image](https://github.com/meshery/meshery.io/assets/118627824/c62f08fd-9c45-4a51-a75f-58a999e01e57)

### Expected Behavior
give margin and padding to the hero section content and manage the image height in smaller devices

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by jaysomani** [comment]
Can i work on this issue ?

**Comment by mannika763** [comment]
Hey @preyanshu 
I would like to work on this issue

**Comment by Ashparshp** [comment]
@jaysomani, this issue is all yours now! 🎉 Thanks for stepping up!

@mannika763 Thanks for asking... we assign tasks chronologically to ensure fairness. Don't worry, more opportunities are on the way! 👍😊
