### ISSUE TITLE
[Website] Url contains name of the design 

### ISSUE THREAD

**Issue by rishabhsharma1997** [meshery/meshery.io#1812]
#### Current State of the Meshery.io site
When a catalog design is open in meshery.io the link looks `https://meshery.io/catalog/deployment/37792455-294f-481b-a7a8-13e79ca835ca.html` 

#### Desired State of the Meshery.io site

we want to display the name in slugify way in the url for better SEO 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by kanishk6103** [comment]
I wish to work on this issue

**Comment by jaysomani** [comment]
can i work on this ?

**Comment by Ashparshp** [comment]
@rishabhsharma1997, it looks like this issue is still in progress and hasn't been fully finalized page might still be in the works. If you have more information or updates about it, could you please share them? This will help us move forward more effectively...

**Comment by vaishnaviadhau** [comment]
@rishabhsharma1997 @Ashparshp i would like to work on this issue could you pls assign it to me
