### ISSUE TITLE
Implement Two-Column Layout for Mobile

### ISSUE THREAD

**Issue by Ashparshp** [meshery/meshery.io#1827]
### Description
Update the mobile view to use a two-column layout for better space utilization in footer section.

### Screenshots
![Screenshot_2024-07-18-17-57-20-728_com android chrome](https://github.com/user-attachments/assets/8f0f66eb-f1d7-44ff-802e-8539ff4e0a67)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by AdityaDKale** [comment]
Hello I want to work on this issue. Can you please assign it to me

**Comment by Ashparshp** [comment]
@AdityaDKale You're new to the community?

**Comment by AdityaDKale** [comment]
Yes

**Comment by Ashparshp** [comment]
@AdityaDKale Go ahead!!

**Comment by AdityaDKale** [comment]
Hey this is actually already creating two column layout above 450px
![image](https://github.com/user-attachments/assets/a4c716e3-28d1-4f4c-b6ce-f2758f97e5ca)
And below that it is shifting to single column layout to avoid overflow which can be caused by overlapping of the container items. I think forcing two column layout may cause overflow and overlapping of text. We can try reducing the margins or reducing the size of container-items but maybe it is not a good idea to force two column layout.

I may be wrong here but I think it requires a further discussion before any code changes. Thanks and apologizes if I come out in a rude way.

**Comment by vishalvivekm** [comment]
@AdityaDKale 
Let's discuss this one on websites call, please add it in agenda items if you would :) /
Meeting minutes: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by Ashparshp** [comment]
@AdityaDKale Let's discuss this in evening call.. adding this to the [meeting minutes..](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

**Comment by Aarav238** [comment]
Hey @AdityaDKale , I would really like to work on it.
can you please assign this to me..

**Comment by Ashparshp** [comment]
Thank you for showing interest @Aarav238! However, I noticed that @rahulrana701, have some pending assignments and PRs. Please prioritize completing those first. Also, as we usually do, let’s proceed with tasks in chronological order. I’m assigning this task to Aarav for now.

**Comment by Aarav238** [comment]
@Ashparshp Thanks. I will try to raise a PR as soon as possible.

**Comment by snehaio** [comment]
can i work on this issue @Ashparshp ? if its still open
