### ISSUE TITLE
Modal Overflow and Scrolling Issue

### ISSUE THREAD

**Issue by vaishnaviadhau** [meshery/meshery.io#1830]
**Current Behavior**
When users click on a deployment model to open a modal window on meshery.io/catalog website, the top part of the modal content is cut off and users are unable to scroll to see the entire content.
### Screenshots
![meshery io catalog](https://github.com/user-attachments/assets/86e7caf8-a48a-4338-a931-4d85ec2b3e10)

 Expected Behavior
The modal window should be centered vertically and horizontally. Users should be able to scroll through the content if it exceeds the available height, ensuring that all content is accessible and visible.

https://github.com/user-attachments/assets/bbe78f2a-c0ab-4f58-bcd1-8b2d6bfa29a7

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaishnaviadhau** [comment]
@antweiss @ctcarrier @ramrodo @hexxdump                                                                                                                                       I would like to work on this issue . Could you please assign this to me

**Comment by kanishk6103** [comment]
This issue has already been raised: [#1803](https://github.com/meshery/meshery.io/issues/1803)
a PR for the same has been raised as well: https://github.com/meshery/meshery.io/pull/1805

**Comment by vaishnaviadhau** [comment]
okay
