### ISSUE TITLE
Add Linux Foundation trademark disclaimer

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1831]
### Current Behavior
[Meshery is failing](https://clomonitor.io/projects/cncf/meshery#meshery_legal) the [trademark disclaimer check](https://clomonitor.io/docs/topics/checks/#trademark-disclaimer)

### Desired Behavior

```
The Linux Foundation. Meshery has registered trademarks and uses trademarks
```

### Screenshots / Mockups

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by akshansh-modi** [comment]
i would like to work on this

**Comment by shubhusion** [comment]
@leecalcote Kindly assign this issue to me
