### ISSUE TITLE
[UI] Overlap button in mobile view

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery.io#1839]
### Description
In the mobile view, the image with "before" and "after" text overlaps the "View Docs" button.

### Expected Behavior
There should be a top margin for the image in the mobile view to fix this overlap.

### Screenshots
![image](https://github.com/user-attachments/assets/d3530ede-d738-4c1f-b44d-efba2b6c1be0)

### Enviroment:
 - OS:  Linux
 - Browser:  Firefox
 - Version: 
 - Device: Desktop Mobile

### Additional Information
If you find this issue valid, I can fix this issue.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by amitamrutiya** [comment]
Closing this issue because it is a duplicate of #1822.

**Comment by Ashparshp** [comment]
@amitamrutiya Opening this as we haven't heard back from @rahulrana701. You can proceed with the PR. Let's discuss it in our next Monday call.

**Comment by Ashparshp** [comment]
Fixes #1822

**Comment by amitamrutiya** [comment]
Sure, I will work on it shortly.

**Comment by Aviral0702** [comment]
@amitamrutiya Please include the steps to reproduce the issue or the URL of the page where the problem occurs. This will help others replicate the issue more easily.

**Comment by Ashparshp** [comment]
@Aviral0702 Refer: #1822
