### ISSUE TITLE
Navbar tiles become transparent when the accordion is opened in mobile view

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery.io#1840]
### Description
In mobile view, when we click on the Navbar expandable tile, the components below it become transparent.

### Expected Behavior
The components should retain their original color.

### Screenshots
![image](https://github.com/user-attachments/assets/4b9db75d-a983-4763-9721-c6ca163ee68a)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

### Additional Information
If you find this issue valid and worth fixing, please let me know, and I will work on it.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thank you for raising this issue, @amitamrutiya. 👍 

Is this something that you would like to work on?
