### ISSUE TITLE
Broken link on Perfomance Management

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery.io#1841]
### Description
Page not found error when clicking on the performance section learn more button. 
URL: https://meshery.io/features
This redirects to https://docs.meshery.io/tasks/performance-management is not valid.

### Expected Behavior
I think we have to replace that with this link https://docs.meshery.io/guides/performance-management/performance-management

### Screenshots
![image](https://github.com/user-attachments/assets/fc7c20f6-6f62-4de7-b744-3274ba4d4a9e)

### Additional Information
If you find this issue valid then i will fix this.

### Enviroment:
 - OS: Linux
 - Browser: Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by amitamrutiya** [comment]
What I mentioned on expected behavior is right?

**Comment by hargunkaur286** [comment]
> What I mentioned on expected behavior is right?

yes
