### ISSUE TITLE
Tap Highlight Color in Mobile View

### ISSUE THREAD

**Issue by akshansh-modi** [meshery/meshery.io#1842]
### Description
When interacting with elements in the mobile view, the default tap highlight color appears, which affects the user experience.

### Expected Behavior
tap highlight color  should be transparent 
### Screenshots
![Screenshot from 2024-08-02 16-57-04](https://github.com/user-attachments/assets/72a74997-d914-4d39-a225-3210ba6ff8d5)
![Screenshot from 2024-08-02 16-53-53](https://github.com/user-attachments/assets/fd2b643f-aeea-4d9c-9510-a9c3ef7c7cf9)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by akshansh-modi** [comment]
i would like to work on this

**Comment by Ashparshp** [comment]
@akshansh-modi Not a valid issue probably but let's hear from others @hargunkaur286 @sudhanshutech.

**Comment by Ashparshp** [comment]
@akshansh-modi, Not a valid issue!
