### ISSUE TITLE
Unable to download catalog item 

### ISSUE THREAD

**Issue by akshansh-modi** [meshery/meshery.io#1843]
### Description
 i am unable to download catalog item  , it seems to me that this is a CORS issue

### Screenshots
![image](https://github.com/user-attachments/assets/afcebec7-abaa-4dba-a41c-3463ef541684)
![image](https://github.com/user-attachments/assets/c7fed985-98f0-4eb9-8823-b383f8d639c0)
![image](https://github.com/user-attachments/assets/75f40e3a-68ad-4deb-8983-5a6febfb7ad3)

Workaround : opening download link in another tab seems to work 

### Enviroment:
 - OS: Linux 
 - Browser: Chrome 
 - Version: 
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@akshansh-modi are willing to work on the issue?

**Comment by akshansh-modi** [comment]
Yes, I was looking into it since I am also working on issue #1768. This appears to be an easy one-line fix. Could you please assign it to me so I can create the PR?

**Comment by akshansh-modi** [comment]
@sudhanshutech, should I go ahead and create a PR?

**Comment by leecalcote** [comment]
> @sudhanshutech, should I go ahead and create a PR?

What' fix are you proposing?

**Comment by akshansh-modi** [comment]
Update the link from:
```
<a href="/catalog/{{type.downloadLink}}" download>
```
to:
```
<a href="https://playground.meshery.io/api/pattern/download/{{type.patternId}}" download>
```
