### ISSUE TITLE
[Website] The Layer5 Cloud extension should have a "5" mark, not Meshery logo

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1851]
#### Current State of the Meshery.io site
On the [extensions page](https://meshery.io/extensions), the Layer5 Cloud extension should have a "5" logo, not Meshery logo
![Screenshot 2024-08-05 at 5 08 05 PM](https://github.com/user-attachments/assets/8abd0e94-7dbe-42c4-85d7-3f4fec63fe81)

#### Desired State of the Meshery.io site
The "5" mark can be found at https://layer5.io/company/brand.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by dsawwork** [comment]
hi. would like to take a look at this if possible.

**Comment by rahulrana701** [comment]
@leecalcote would like to work on it

**Comment by Ashparshp** [comment]
@dsawwork, 🎉 Thanks for stepping up!

@rahulrana701 Thanks for asking... we assign tasks chronologically to ensure fairness. Don't worry, more opportunities are on the way! 👍😊

**Comment by dsawwork** [comment]
Hi @Ashparshp. when setting up the server for meshery on windows (git bash) I get compilation errors. I think I have the prerequisites but there might be a mismatch in the gcc versions. Any idea on how to go about it?
![image](https://github.com/user-attachments/assets/1f420e4d-25b0-49d8-8f22-01153237f955)
