### ISSUE TITLE
All items displayed on page load

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery.io#1852]
### Description
Link: [Meshery catalog screen](https://meshery.io/catalog)
When this page loads, I see all catalog items on the first page. When I press "Next," I see 9 catalog items.

### Expected Behavior
There should be 9 catalog items on all pages.

### Screenshots
![image](https://github.com/user-attachments/assets/915db625-ac19-4a76-976e-4b5f891caf72)

### Enviroment:
 - OS: Linux
 - Browser: Firefox
 - Version: Latest
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ashparshp** [comment]
Thank you @amitamrutiya, please go ahead.

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin, any luck?

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin, still working on it?

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin, still working on it?

Yes completed. Will raise PR.

**Comment by bhushan354** [comment]
Hi @amitamrutiya  and @sudhanshutech ,

Is this issue still active? If so, could you please assign it to me? I’d love to contribute.

**Comment by Ashparshp** [comment]
@bhushan354, Go ahead!

**Comment by bhushan354** [comment]
@Ashparshp I have fixed the issue

**Comment by bhushan354** [comment]
@Ashparshp can you review this ?
