### ISSUE TITLE
LFX URL in Programs Section Causes UI Breakdown on Smaller Screens

### ISSUE THREAD

**Issue by rahulrana701** [meshery/meshery.io#1857]
### Description
The LFX URL within the Programs section of the LFX Mentorship section in the Meshery UI is causing layout issues on screens with smaller widths. When the screen width decreases below a certain threshold, the UI elements in this section become misaligned, leading to a broken layout that negatively impacts user experience.

### Expected Behavior
The UI should remain responsive and well-aligned across all screen sizes.
The LFX URL should adapt to the screen width

### Screenshots

https://github.com/user-attachments/assets/c21913af-6665-46e5-b686-63b1b3012dcf

### STEPS TO REPRODUCE THE ISSUE
- On the Meshery homepage,
- In the navigation bar, click or hover over the "Community" section.
- Within the Community section, click on "Programs."
- On the Programs page, select the "LFX" section.
- There, you will see the "LFX Mentorship 2023 Spring Projects" section, which contains the issue.
- URL : https://meshery.io/programs/lfx/2023

### Environment:
 - OS:  Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by rahulrana701** [comment]
@leecalcote I would like to work on this issue

**Comment by Ashparshp** [comment]
@rahulrana701 Thanks for Opening the issue, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Ashparshp** [comment]
Thank you @rahulrana701 Also, if you don't mind, could you kindly mention the steps to reproduce the issue along with the URL?

**Comment by rahulrana701** [comment]
@Ashparshp done as suggested.

**Comment by Ashparshp** [comment]
Thank you @rahulrana701
