### ISSUE TITLE
Readability and Alignment Issues on Google Season of Docs Page in Programs Section

### ISSUE THREAD

**Issue by rahulrana701** [meshery/meshery.io#1858]
### Description
The Google Season of Docs page within the Programs section of the Meshery UI is currently experiencing readability and alignment issues. The text on the page is not properly aligned, causing headings to blend into paragraphs, which makes it difficult for users to distinguish between different sections. This issue affects the overall readability and user experience on the page

### Expected Behavior
Text and headings should be clearly aligned, with distinct separation between paragraphs and headings for better  readability.

### Screenshots
![Screenshot 2024-08-10 162144](https://github.com/user-attachments/assets/a371fcf1-3a85-4227-a9ea-55c9ce2fb7d2)
nshots
![Screenshot 2024-08-10 162214](https://github.com/user-attachments/assets/a18794b5-bcb3-4523-bb90-a0f926f57a58)

### Steps To Reproduce The Issue
- On the Meshery homepage,
- In the navigation bar, click or hover over the "Community" section.
- Within the Community section, click on "Programs."
- On the Programs page, select the "Google Season of Docs" section.
- There, you will see the "Project Ideas" section, which contains the issue.
-  URL : https://meshery.io/programs/gsod/2021

### Environment:
 - OS: Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)
-

**Comment by rahulrana701** [comment]
If you find this issue relevant, I would like to work on it.

**Comment by Ashparshp** [comment]
@rahulrana701 Thanks for Opening, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by rahulrana701** [comment]
@Ashparshp can I start working on this issue ?

**Comment by Ashparshp** [comment]
@rahulrana701 Also, if you don't mind, could you kindly mention the steps to reproduce the issue along with the URL?
