### ISSUE TITLE
[UI] Next button invisible when click on

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery.io#1863]
### Description
Link: [Extension Page](https://meshery.io/extensions)
On this page, when the "Next" button is clicked, it becomes invisible.

### Expected Behavior
If we choose not to use pagination, remove the "Next" and "Previous" buttons; otherwise, apply pagination.

### Screenshots
[Screencast from 2024-08-14 16-39-36.webm](https://github.com/user-attachments/assets/53e69a1d-961d-4eb5-9aac-be04aec49c8b)

### Environment:
 - OS: Linux
 - Browser: Firefox
 - Version: latest
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aviral0702** [comment]
@amitamrutiya I can reproduce the issue. You can ask for assignment and then go ahead.

**Comment by abbi4code** [comment]
Can i work on this issue?

**Comment by Ashparshp** [comment]
@amitamrutiya, @Aviral0702, we've implemented the pagination, right? The issue is that we don't have more cards to show when clicking `Next`. So, can we add a condition instead of removing the button?

**Comment by amitamrutiya** [comment]
Yeah that makes sense.

**Comment by Aviral0702** [comment]
@Ashparshp Makes sense.

**Comment by Ashparshp** [comment]
@abbi4code, Read the discussion and go accordingly!

**Comment by abbi4code** [comment]
@Ashparshp  Yeah, I got it. Instead of completely removing the 'Next' button, we can add a condition to check if there are more cards available to display. If there are more cards, the button should remain active, but if not, we can either disable the button or hide it. This way, we keep the pagination logic intact without breaking the user flow.

**Comment by bhushan354** [comment]
@Ashparshp @amitamrutiya can you assign this issue to me if no one else is currently working on it?
