### ISSUE TITLE
Catalog Item Buttons Not Visible on Smaller Screens

### ISSUE THREAD

**Issue by rahulrana701** [meshery/meshery.io#1875]
### Description
On smaller screens, the button like "Copy URL" on catalog items is not visible, making it difficult for users to interact with it and causes readability issue .

### Expected Behavior
The button should be visible and accessible on all screen sizes.

### Screenshots
![1](https://github.com/user-attachments/assets/8e1413f2-4ef9-4e8d-8056-4a67e39b9fb5)
![Screenshot 2024-08-16 170820](https://github.com/user-attachments/assets/f910d193-7058-45a6-8a44-d9ceca3a186f)

### Steps To Reproduce the issue 
- Go to meshery home page
- In the navigation bar, click or hover over the "Catalog" section.
- Scroll down and click on any item you want. Then, use the inspect tool to adjust your screen size .

### Environment:
 - OS: Windows
 - Browser: Chrome
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by rahulrana701** [comment]
@Ashparshp if you find this issue to be relevant I would like to work on it.

**Comment by amitamrutiya** [comment]
@Ashparshp For this issue, PR #1859 has been created. In this code [line](https://github.com/meshery/meshery.io/pull/1859/files#diff-0c61a1ade04bea3cb59b929bddbccd900317ae7879afa759ddcb1bbf2850e7daR1023), @kanishk6103 has fixed both issues.

**Comment by Ashparshp** [comment]
Thank you @amitamrutiya and @rahulrana701 please check once before opening new one.

**Comment by rahulrana701** [comment]
@Ashparshp sure
