### ISSUE TITLE
[Catalog] Meshery.io site builds with errors of malformatted YAML in catalog content

### ISSUE THREAD

**Issue by shubhusion** [meshery/meshery.io#1877]
### Description
When attempting to build the meshery.io site locally, an error occurs while reading the YAML front matter in the file `29b94780-865c-460b-b852-cc5c31730561.md` located in the `_catalog/deployment` directory. 

### Expected Behavior
No error during build.

### Screenshots
![image](https://github.com/user-attachments/assets/caeba5bd-e90c-4870-b260-8131e233febc)

### Environment:
- OS: Windows
- Browser: N/A
- Version: N/A
- Device: Desktop

---

## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing).
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io).

**Comment by rahulrana701** [comment]
@Ashparshk I would like to work on it

**Comment by shubhusion** [comment]
Hi @rahulrana701, thanks for your interest. I’m already working on this issue, but there are other open issues you can tackle. I appreciate your understanding!

**Comment by rahulrana701** [comment]
@shubhusion sure , I thought you weren’t working on it. Thank you!

**Comment by amitamrutiya** [comment]
Hey @shubhusion, how's the progress going? Are you stuck anywhere?

**Comment by lekaf974** [comment]
@vishalvivekm PR ready for review

**Comment by lekaf974** [comment]
@shubhusion PR ready for review

**Comment by leecalcote** [comment]
@Yashsharma1911 please review

**Comment by lekaf974** [comment]
@Yashsharma1911  If I am right this issue is fixed right ?

**Comment by Yashsharma1911** [comment]
Thankyou everyone, this issue has been fixed we are good to close this isue
