### ISSUE TITLE
[UI]: Center align images inside Card Modal of extensions page

### ISSUE THREAD

**Issue by SAHU-01** [meshery/meshery.io#1881]
### Description

When the Card in https://meshery.io/extensions page is clicked and the modal opens, the image is not center aligned.

### Expected Behavior

All images inside the card modal must be center aligned .

### Screenshots

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/8f7f0d74-930d-4c1d-a19a-8101441ee5f4">
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/c1172090-6f7b-442b-8579-f0384fd15c00">
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/e2b57282-e1e5-4fb3-a35a-39649bd64536">

### Environment:
 - OS: Mac
 - Browser: Chrome 
 - Version: 
 - Device: Desktop 

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by THEBOSS0369** [comment]
@SAHU-01 I think they have added these images like these purposely, so that longer images can easily be placed in the middle of the card or say the can be aligned in the center.
