### ISSUE TITLE
[UI] : Blur Screen shows up on clicking Extension Logo

### ISSUE THREAD

**Issue by Aviral0702** [meshery/meshery.io#1883]
### Description

On clicking on the logo of an extension a blurred screen appears on the screen. 

### Expected Behavior

Clicking the extension logo should display a full-sized image of the logo.

### Screenshots

![image](https://github.com/user-attachments/assets/14c85505-1fe8-4504-8678-3f3b02cbe7d2)

![image](https://github.com/user-attachments/assets/10865f4a-1735-4682-9c10-2ef9e2007e55)
### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by kanishk6103** [comment]
I wish to work on this

**Comment by Ashparshp** [comment]
@Aviral0702, are you working on this, or should we proceed with @kanishk6103?

**Comment by Aviral0702** [comment]
> @Aviral0702, are you working on this, or should we proceed with @kanishk6103?

I am working on it. Just waiting for some more information regarding it from @vishalvivekm .

**Comment by Aviral0702** [comment]
@kanishk6103 I have started to work on this issue. You can find another issues which are open and help wanted. You can leave comment over there and we will assign you that. Have you joined the slack channel ? We can help finding you some open issues over there.
