### ISSUE TITLE
[Website] Improve the CLS score of meshery.io/catalog page

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery.io#1887]
#### Current State of the Meshery.io site

Currently the cls score of meshery.io/catalog is poor. It need to be improved because its affecting the page performance and will give users a bad experience. The current performance of cls is 22% poor.
To understand cls: https://web.dev/articles/cls

#### Desired State of the Meshery.io site

Improve the cls 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by rahulrana701** [comment]
I think developing a page structure to display these catalog items might be helpful. We could display 9 items on the first page and the rest on subsequent pages. Additionally, a few other adjustments could be made to improve the layout. What are your thoughts on this, @sudhanshutech?

**Comment by sudhanshutech** [comment]
@THEBOSS0369 its good you want to try so if you would get some details and learn its details and come back with approach then we can get you this assigned.

**Comment by sudhanshutech** [comment]
@rahulrana701 seems a good plan , but we do show 9 results only per page.

**Comment by rahulrana701** [comment]
We will fix the size of the layout displaying the catalog items to show only 9 items at a time. If the user wants to see more items, we will provide a button to view additional catalog items or display the number of pages below, allowing users to navigate through the pages to see the items @sudhanshutech

**Comment by rahulrana701** [comment]
If you find this approach relevant , I would like to give it a shot. @leecalcote @sudhanshutech

**Comment by sudhanshutech** [comment]
@rahulrana701 i already said we already show 9 items per page and to see other catalog we can click the next button. However there is slight bug when first loads it show all items and when go to next page and come back it display as expected 9 cards. I guess @Muhammed-Moinuddin is fixing it.

**Comment by sudhanshutech** [comment]
@rahulrana701 cls is not dependent on the number of card displayed. Its a issue that if any component has issue with shift while interacted. Have you read the doc i mentioned in the issue. Please come back with solutions based on that and yes that would be great you can give a shot

**Comment by Muhammed-Moinuddin** [comment]
> @rahulrana701 i already said we already show 9 items per page and to see other catalog we can click the next button. However there is slight bug when first loads it show all items and when go to next page and come back it display as expected 9 cards. I guess @Muhammed-Moinuddin is fixing it.

Yup. Will share updates soon.
