### ISSUE TITLE
[UI] Navbar is not closing on click getting started in mobile view

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery.io#1888]
### Description
In mobile view, when we click on "Getting Started," the navbar menu does not close.

### Expected Behavior
In mobile view, the navbar should close when "Getting Started" is clicked.

### Screenshots
![image](https://github.com/user-attachments/assets/616d94ff-3283-4b86-8714-8bce5eb5bd8d)

### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by hymmns** [comment]
Hi @amitamrutiya, could this be assigned to me. Would like to work on it

**Comment by agamjotpanesar** [comment]
Hi @amitamrutiya 
I want to work on this issue. Can you please assign it to me.

**Comment by amitamrutiya** [comment]
@agamjotpanesar Thanks for showing interest in solving this issue. We are assigning tasks in chronological order, so you can find a different issue to work on.

@hymmns, you're good to go—let's make this happen!

**Comment by porobertdev** [comment]
I managed to fix it with vanilla JS while testing in DevTools.

<details>
  <summary>Tip</summary>
The `display` of the navbar's ul needs to be set to _none_ once the _Getting Started_ li is clicked_.
</details>

Hope it helps :)

Please let me know if my behavior is ok. It's the first time I do this, and I thought it's ok as a tip since someone else has been already assigned. Thank you!

**Comment by hymmns** [comment]
@porobertdev Thanks for the input.

**Comment by hymmns** [comment]
@amitamrutiya Please let me know if this fixes the issue or if there's any other comment kindly drop.
