### ISSUE TITLE
[Community page] inconsistent alignments of subheadings

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1895]
### Description

On https://meshery.io/community, in desktop view subheadings are center aligned.
![Screenshot from 2024-09-07 22-02-32](https://github.com/user-attachments/assets/fccbda27-5bce-4526-8fca-6cac9af4f54d)
![Screenshot from 2024-09-07 22-02-40](https://github.com/user-attachments/assets/3201bda7-08db-4318-a665-174ff02ed998)

### Expected Behavior

They need to be all left aligned.
### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Sumit2997** [comment]
Hi @vishalvivekm,
Can you please assign this issue to me.

**Comment by vishalvivekm** [comment]
> Hi @vishalvivekm, Can you please assign this issue to me.

Hi, Thank you @Sumit2997.
will you please confirm if you have the site set up?

**Comment by Sumit2997** [comment]
Yes, I have set up the website on my local system.
