### ISSUE TITLE
[Catalog] Generate Model for Azure architectural icons

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery.io#1911]
# Extending Meshery Models

Meshery as an extensible platform allows users to import, generate and export models that are either annotation (SVGs) or infrastructure configuration (CRDs).
Create a new model with the following specifications:

**Model:** 
**Model Display Name:** 
**Model Resources:** 

Then list the model on [](meshery.io/models) by raising a PR.

### Contributor Resources

- The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](https://slack.meshery.io/) for access.
- See how to [import](https://docs.meshery.io/guides/configuration-management/importing-models), [generate](https://docs.meshery.io/guides/configuration-management/generating-models) and [export](https://docs.meshery.io/guides/configuration-management/exporting-models) models.
- Link to [CSV template](https://docs.google.com/spreadsheets/d/19JEpqvHrG8UL-Bc-An9UIcubf1NVhlfnQSN1TD7JOZ4/edit?gid=0#gid=0)
- See live demo on how to contribute to Meshery Models: https://www.youtube.com/live/iKe52yMWWK4?si=YL8gTRF7yndHQEyt&t=1494

**Comment by TraXIcoN** [comment]
Hey @Jougan-0, can I work on this? I watched the YouTube livestream and got the hang of how we're using CSV to create models and which fields to fill.

Thanks!

**Comment by Jougan-0** [comment]
@TraXIcoN Sure man here you go.
