### ISSUE TITLE
[Catalog] Generate Model for Material designs icon pack

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery.io#1912]
# Extending Meshery Models

Meshery as an extensible platform allows users to import, generate and export models that are either annotation (SVGs) or infrastructure configuration (CRDs).
Create a new model with the following specifications:

**Model:** 
**Model Display Name:** 
**Model Resources:** 

Then list the model on [](meshery.io/models) by raising a PR.

### Contributor Resources

- The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](https://slack.meshery.io/) for access.
- See how to [import](https://docs.meshery.io/guides/configuration-management/importing-models), [generate](https://docs.meshery.io/guides/configuration-management/generating-models) and [export](https://docs.meshery.io/guides/configuration-management/exporting-models) models.
- Link to [CSV template](https://docs.google.com/spreadsheets/d/19JEpqvHrG8UL-Bc-An9UIcubf1NVhlfnQSN1TD7JOZ4/edit?gid=0#gid=0)

**Comment by Ansh-Sarkar** [comment]
Hi @Jougan-0 would love to work on this. Have attended a few of the Meshery Website meetings and would love to get started. Kindly do let me know if this could be assigned to me. Thanks !

**Comment by Jougan-0** [comment]
@Ansh-Sarkar here you go. I would suggest you to watch Fridays live stream at [Meshery](https://www.youtube.com/watch?v=iKe52yMWWK4) to help you with this topic.

**Comment by Ansh-Sarkar** [comment]
Sure thing. Thanks !

**Comment by Ansh-Sarkar** [comment]
Hi @Jougan-0 . Went through the live stream recording that you had referred to in the previous comment. Helped a lot and I now have a complete, end to end idea as to how to go about generating the model.

Just wanted to confirm that by "Material Designs Icon Pack", were you referring to this: https://github.com/google/material-design-icons , or is it some other resource ? I went through the community drive as well. Kindly do let me know. Thanks !

**Comment by bhushan354** [comment]
@Jougan-0 if the issue is still active , can you assign it to me ? I got the idea from that livestream

**Comment by Ansh-Sarkar** [comment]
Hey @bhushan354 just wanted to let you know that I'm actively working on this. Thanks.

**Comment by vishalvivekm** [comment]
@Ansh-Sarkar would you please sound off with your updates ?

**Comment by Ansh-Sarkar** [comment]
Hey yes. Almost done with this. Sorry about the delay. I'll raise a PR ASAP.
