### ISSUE TITLE
Missing features on meshery.io/features

### ISSUE THREAD

**Issue by miacycle** [meshery/meshery.io#1924]
### Current Behavior
Meshery does more than what is listed here - https://meshery.io/features

### Desired Behavior
An accurate depiction of capabilities.

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by mdkaifansari04** [comment]
@miacycle could you please list down the feature you feel like missing, or link to the document that contains that I would love to fix this from my end.

**Comment by leecalcote** [comment]
@SAHU-01

**Comment by mdkaifansari04** [comment]
@leecalcote I would appreciate it if you could assign this to me.

**Comment by SAHU-01** [comment]
Thank you for pointing this out @leecalcote , I'll update the feature descriptions and we can map this from the workflow as well.

**Comment by SAHU-01** [comment]
> @leecalcote I would appreciate it if you could assign this to me, to get started with my good first contributions

Thank you for your interest @mdkaifansari04 but I believe this aligns close to another issue I'm working on so I'll take this up regardless you can take a look at our other open good first issues and comment if you're interested and we can assign it to you , once you confirm you've been able to setup that repo loally.

You can check these:
- https://github.com/meshery/meshery/contribute
- https://github.com/meshery/meshery/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
- https://github.com/meshery/sistent/issues

**Comment by mdkaifansari04** [comment]
Thanks for sharing the relevant issues, I'll work on those

**Comment by vishalvivekm** [comment]
@SAHU-01 would you be sharing updates on this, in today websites' call ?
