### ISSUE TITLE
Enhance add-catalog workflow

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery.io#1929]
### Description

-  workflow `add-catalog.yml`: https://github.com/meshery/meshery.io/blob/master/.github/workflows/add-catalog.yml
-  `package.go`  : https://github.com/meshery/meshery.io/blob/master/assets/artifact-hub-pkg/package.go

When a design is published from kanvas, it wipes out the catalog content (see [commit](https://github.com/meshery/meshery.io/commit/1c747418e89e93eb03b7cdce7b2899096a204c91)).

https://github.com/meshery/meshery.io/blob/79d04d7ced6fa7e154d6aac9debe9b304fc4c8ab/assets/artifact-hub-pkg/package.go#L111

The error seems to stem from [^^](https://github.com/meshery/meshery.io/blob/master/assets/artifact-hub-pkg/package.go#L111)line in package.go, as the Cloud API expects pagination parameters in the request. We should gracefully handle the absence of pagination parameters in the Cloud API or enhance the package.go file accordingly

### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by naaa760** [comment]
I would like to work on this issue, Please assign me 
Thankyou!!
