### ISSUE TITLE
Create section for Meshery talks and presentations

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#193]
**Current Behavior**
The site is missing a section to capture presentations, talks, workshops that people have given on the the project.

**Desired Behavior**
Ideally, this is a new section in the community page.

**Comment by gunjanmimo** [comment]
@leecalcote sir, I am taking this issue

**Comment by leecalcote** [comment]
Excellent. 👍

**Comment by chinmaym07** [comment]
Hey @leecalcote I want to take this up.

**Comment by leecalcote** [comment]
Beautiful. That would be great.

**Comment by chinmaym07** [comment]
@leecalcote Sir can I get the design for this issue. ?
