### ISSUE TITLE
[Catalog UI] Download Button Generates Incorrect File with .html Extension and Embedded HTML Content

### ISSUE THREAD

**Issue by SAHU-01** [meshery/meshery.io#1936]
### Description
When a user clicks on a catalog card and opens the modal, clicking on the Download button triggers the download of a file named design.yml.html. Moreover, the downloaded file is not a valid .yml file but a .html code file.

### Expected Behavior
Upon clicking the Download button :
- a `.yml` extension file must be downloaded
- the downloaded file must contain valid `yml` content

### Screenshots
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/4c342eac-e7aa-4559-bd06-14b0986aaec6">

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/1518cfc9-8e05-4758-a796-6165be5c05e7">

### Environment:
 - OS: Mac 
 - Browser: Safari
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thank you!
