### ISSUE TITLE
[Website] [Catalog] Enhance dark mode compatibility of "Sort By" and "Search" input fields

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1939]
#### Current State of the Meshery.io site
On https://meshery.io/catalog, these two fields can be enhanced with a dark/light mode color variable

<img width="886" alt="Screenshot 2024-10-27 at 6 31 23 PM" src="https://github.com/user-attachments/assets/a300f34f-4ab7-4f6a-b308-38d85a6f92b4">

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by jayg2309** [comment]
@leecalcote Can I work on this?

**Comment by vishalvivekm** [comment]
@jayg2309 
will you please confirm, if you've the site running locally?

**Comment by hymmns** [comment]
I would like to work on this and I have the site running locally.

**Comment by Vidit-Kushwaha** [comment]
Can I work on this @leecalcote @vishalvivekm?

**Comment by jayg2309** [comment]
@vishalvivekm I haven't run it locally. Please feel free to assign this issue to someone else . 
Due to personal reasons , I can't do this right now.

**Comment by vishalvivekm** [comment]
Thank you for letting us know @jayg2309.

Thank you for chiming in @hymmns @Vidit-Kushwaha.
@hymmns will you please share whether or not you have the site set up ? Or if you need help while doing so ?

**Comment by hymmns** [comment]
Yes @vishalvivekm , I do have the site running locally

**Comment by snehaio** [comment]
hi @leecalcote @vishalvivekm ! Can i work on this issue, i have setup the site lacally.

**Comment by snehaio** [comment]
hi @leecalcote, I hopefully fixed this issue. Please assign me to raise a PR. 
![{14EDDFBE-2D20-4CFC-87ED-18B212E9677B}](https://github.com/user-attachments/assets/8a2e17c6-1839-432b-8023-59c7a4288301)

**Comment by vishalvivekm** [comment]
> Yes @vishalvivekm , I do have the site running locally

@hymmns Please go ahead.

**Comment by hymmns** [comment]
Thanks @vishalvivekm
