### ISSUE TITLE
Coming Soon Sign for draft extensions

### ISSUE THREAD

**Issue by jameshorton2337** [meshery/meshery.io#1948]
Oh, wait. I was expecting to see a coming soon flag or ribbon on top of this. Do we have one?

_Originally posted by @jameshorton2337 in https://github.com/meshery/meshery.io/issues/1947#issuecomment-2450723547_

**Comment by leecalcote** [comment]
Adding to the description of this issue:

The extension below needs a ribbon or sign similar to the red sign that is visible on the catalogue page over the OPA policy logo.

**Coming Soon Extension:**

<img width="263" alt="Screenshot 2024-10-31 at 3 09 48 PM" src="https://github.com/user-attachments/assets/1ecb36e7-7324-41c4-9d0e-7793604704ea">


**Coming Soon Ribbon/Sign**
<img width="1332" alt="Screenshot 2024-10-31 at 3 11 44 PM" src="https://github.com/user-attachments/assets/45dae83e-6610-458c-bd23-5e6f908dba19">

**Comment by leecalcote** [comment]
@jameshorton2337 I'll just reopen this issue with full description, yeah?

**Comment by jameshorton2337** [comment]
Yes, please do. I just didn't want this to get lost in the noise.
