### ISSUE TITLE
[Extensions] Coming Soon sign for extension cards

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1949]
### Current Behavior
The [collection of Meshery Extensions](https://meshery.io/extensions) contains some `status: coming-soon` extensions. The extension is an example of a "coming soon" extension. 
<img width="263" alt="Screenshot 2024-10-31 at 3 09 48 PM" src="https://github.com/user-attachments/assets/1ecb36e7-7324-41c4-9d0e-7793604704ea">

### Desired Behavior
Extensions with this status need the same red sign that is visible on the catalog page over the OPA policy logo.
<img width="1332" alt="Screenshot 2024-10-31 at 3 11 44 PM" src="https://github.com/user-attachments/assets/45dae83e-6610-458c-bd23-5e6f908dba19">

### Screenshots / Mockups

Reuse the same "Coming Soon" sign, positioning it over the appropriate extension cards.

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by hymmns** [comment]
Hi @leecalcote can you please assign it to me

**Comment by leecalcote** [comment]
@hymmns, yes, just as soon as your other PR merges.

**Comment by hymmns** [comment]
Got it. Thanks
