### ISSUE TITLE
[Blog] Meshery+GCP

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1957]
#### Current State of the Meshery.io site
Meshery supports GCP

#### Desired State of the Meshery.io site
People should be aware of this. A blog post would help.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by itsharshitrwt** [comment]
Hi @leecalcote ,  I'm interested in contributing to the documentation of meshery.io, but I would appreciate some guidance to ensure I’m heading in the right direction.

Could you please provide a brief overview or format of how the documentation should be structured or any previous resources i can take idea from? Specifically, any key points or sections that should be included, and if there’s a particular style or tone I should use.
