### ISSUE TITLE
[Docs] Issue template for blog posts

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#1964]
### Current State:
See these [issue templates](https://github.com/meshery/meshery.io/issues/new/choose)? We’re missing one for creating a blog post.

### Desired State:
Copy the issue template format from layer5io/layer5 repo and paste into a new issue template in meshery/meshery.io, making changes as appropriate?

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by hymmns** [comment]
Hi @leecalcote 
Could you please assign this to me, would love to work on it.

**Comment by leecalcote** [comment]
@hymmns so sorry... we just missed you. Sadam Mohamed volunteered just a bit earlier. He'll need to comment on this issue in order to have it assigned, though.

**Comment by leecalcote** [comment]
@hymmns, are you Taiwo (is that your name)? I'm just trying to ensure that I start to consider for you going forward and trying to align a Slack name to GitHub face, so to speak.

**Comment by hymmns** [comment]
Yes @leecalcote 
My name is Taiwo

**Comment by sadam-m** [comment]
https://github.com/meshery/meshery.io/pull/1966
