### ISSUE TITLE
Padding & Margin around Program Section 

### ISSUE THREAD

**Issue by chinmaym07** [meshery/meshery.io#421]
**Current State of the Meshery.io site**

1. Program Section is missing some padding & margin .
2. Subscribe Section on [Mehery's Program page](https://meshery.io/programs/) is missing padding.

**Desired State of the Meshery.io site**

1. Program Section must have some padding & margin around it.
2. Subscribe Section on [Mehery's Program page](https://meshery.io/programs/) must have some padding around it.

![Screenshot_2021-04-01 Meshery The Service Mesh Manager](https://user-images.githubusercontent.com/44670961/113331357-7fb83980-933d-11eb-802b-4c5298a5be9d.png)

![Screenshot_2021-04-01 Programs](https://user-images.githubusercontent.com/44670961/113331901-1f75c780-933e-11eb-905a-9f87c23e4431.png)

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by xdshivani** [comment]
Assign this to me.

**Comment by chinmaym07** [comment]
Go ahead @xdshivani Assigned to you .. Happy Contributing !!

**Comment by xdshivani** [comment]
Help me installing meshery.io in my system `windows10` environment. As am getting error while installing 
![code](https://user-images.githubusercontent.com/56837749/113481299-5f5fba80-94b6-11eb-836d-b5e0b5566f51.PNG)

**Comment by chinmaym07** [comment]
Hey @xdshivani 👋🏻 .Were you able to setup the project locally ? 
Have you joined the Meshery Community - http://slack.meshery.io? We have many helpful people that can point out resources for Jekyll & help you in setting up the project locally.

**Comment by Ayush-Khandelwal-007** [comment]
Is there any figma design for this frame?
