### ISSUE TITLE
Programs page is covered by footer 

### ISSUE THREAD

**Issue by Kn99HN** [meshery/meshery.io#429]
**Description**
Programs page at `https://meshery.io/programs` is hidden by the footer

**Expected Behavior**
A brief description of what you expected to happen.

**Screenshots**
Add screenshots, if applicable, to help explain your problem.
<img width="1440" alt="Screen Shot 2021-04-17 at 5 13 09 PM" src="https://user-images.githubusercontent.com/44149581/115126876-4f5cd600-9fa0-11eb-9cba-b01e41e20c99.png">

**Enviroment:**
 - OS: MacOS
 - Browser: Firefox
 - Version: 88.0b9
 - Device: Macbook Pro

---
[Optional] **To Reproduce**
1. Go to 'https://meshery.io/programs/'
3. Scroll down to Subcribe form

[Optional] **Additional Context**

**Comment by Josephchinedu** [comment]
In the `https://meshery.io/css/screen.css` add `margin-top: 300px;` to the footer styling

**Comment by leecalcote** [comment]
Good call, @Josephchinedu. Would you like to take this issue?

**Comment by leecalcote** [comment]
Thank you, @Josephchinedu 👍

**Comment by leecalcote** [comment]
Be sure to reference this issue in your PR's description (`This PR fixes #`) so that this issue will automatically be closed out.

**Comment by ishitakeshawani** [comment]
@Josephchinedu are you working on it?
Otherwise I like to solve it @Nikhil-Ladha
