### ISSUE TITLE
[Blog] Copy SMI Conformance blog from smi-spec.io

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#460]
**Current State of the Meshery.io site**
[This blog post](https://smi-spec.io/blog/validating-smi-conformance-with-meshery/) can be copied and posted on meshery.io.

**Desired State of the Meshery.io site**
The blog post, including images, should be posted on smi-spec.io and https://meshery.io/blog

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by josephmidura** [comment]
I'll work on this.

**Comment by leecalcote** [comment]
Oh, fantastic. Here is a [link to the source](https://github.com/servicemeshinterface/smi-spec.io/blob/main/content/blog/validating-smi-conformance-with-meshery.md) of the other blog post.

**Comment by josephmidura** [comment]
A couple of the images resized on the Meshery.io blog. Are there guidelines for the desired sizes, or should I just try to approximate the size on the original smi-spec.io post?
