### ISSUE TITLE
Enlistment of all platforms missing on Meshery installation page

### ISSUE THREAD

**Issue by alphaX86** [meshery/meshery.io#470]
**Current State of the Meshery.io site**
For now, the site provides instructions for 4 diff platforms for installing Meshery. But this is really outdated! There are many platforms available as compared to https://layer5.io/meshery

![image](https://user-images.githubusercontent.com/59508546/119934513-82cd5000-bfa3-11eb-9598-f6099989e3ac.png)

![image](https://user-images.githubusercontent.com/59508546/119934531-8a8cf480-bfa3-11eb-952c-69ace3562d00.png)

**Desired State of the Meshery.io site**
Add all kinds of platforms on that page, plus keep the info updated and clean

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by NikhilSharma03** [comment]
Can I work on this issue? @alphaX86

**Comment by alphaX86** [comment]
Sure :) 👍

**Comment by NikhilSharma03** [comment]
Thank you @alphaX86 👍
