### ISSUE TITLE
Add CNCF logo to meshery.io homepage

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery.io#476]
**Current State of the Meshery.io site**
Meshery is shown as a CNCF landscape project:

![Screenshot_20210626_111035](https://user-images.githubusercontent.com/49474499/123503236-4ad32e80-d66f-11eb-877d-211547987d58.png)

**Desired State of the Meshery.io site**
As Meshery is now a CNCF project and should use the plain CNCF logo:

[cncf-horizontal-color.svg](https://raw.githubusercontent.com/cncf/artwork/master/other/cncf/horizontal/color/cncf-color.svg)

Text in this section should be: "Meshery is a Cloud Native Computing Foundation project."

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by navendu-pottekkat** [comment]
@leecalcote please make changes if they are needed

**Comment by navendu-pottekkat** [comment]
Sure @alphaX86

**Comment by alphaX86** [comment]
@navendu-pottekkat quick Q the text "Meshery is a CNCF project" should be the title?

**Comment by navendu-pottekkat** [comment]
Yes, the subtitle can be black IMO // @leecalcote

**Comment by leecalcote** [comment]
"Meshery is a Cloud Native Computing Foundation project."

LOGO

"Proudly representing every service mesh."
