### ISSUE TITLE
Update Missing Links

### ISSUE THREAD

**Issue by chinmaym07** [meshery/meshery.io#482]
**Description**

Due to migration of meshery repo from `layer5io` to `meshery`, some links in meshery.io needs to be updated .

1. Update the `Github` url link in the navbar from `https://github.com/layer5io` to `https://github.com/meshery`

![Screenshot from 2021-07-02 01-32-13](https://user-images.githubusercontent.com/44670961/124183541-ffd57300-dad5-11eb-9bba-c18a90398656.png)

2. Update the links of `Star Count` & `Fork Count` as both are missing due to wrong url .

![image](https://user-images.githubusercontent.com/44670961/124184047-a7eb3c00-dad6-11eb-8347-392c5b22b798.png)

- Link for Star Count
 https://ghbtns.com/github-btn.html?user=meshery&repo=meshery&type=star&count=true&size=large
- Link for Fork Count
 https://ghbtns.com/github-btn.html?user=meshery&repo=meshery&type=fork&count=true&size=large

**Expected Behavior**
- Star & Fork Count Should be visible on the homepage
- Github link should redirect to `https://github.com/meshery` instead of `https://github.com/layer5io`

**Comment by NikhilSharma03** [comment]
Can I work on it?

**Comment by singh08prashant** [comment]
Can I take this up?

**Comment by leecalcote** [comment]
Yes, please, @singh08prashant.
