### ISSUE TITLE
Error on load of site

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#491]
**Description**
The following error is shown when the homepage is loaded. 

**Screenshots**
![56498824-AAD4-4553-846D-97C8C8E7E8AE](https://user-images.githubusercontent.com/7570704/124998097-6ba56780-e011-11eb-99ca-12920daeb9b7.png)

**Enviroment:**
 - Browser: Safari
 - Device:  iPhone

**Comment by warunicorn19** [comment]
@leecalcote i don't think this issue persists anymore, i just checked. Is it still happening your device?

**Comment by leecalcote** [comment]
You’re right. No, it’s not happening any longer. Thank you, sir.
