### ISSUE TITLE
[UI] Need some modifications

### ISSUE THREAD

**Issue by amino19** [meshery/meshery.io#492]
**Current State of the Meshery.io site**
Modification relates to `mobile view` in general:
1. [x] Needs to add Community Forum point at appropriate section [Community]
2. [ ] Alignment of `Created by LAYER5 and it's open source community` needs to set, i.e, flexible to current state - G
3. [ ] Horizontally footer content must be vertical represent - A
4. [ ] Menu issue - H

**Current State of the Meshery.io site**

<img width=30% src= "https://cdn.discordapp.com/attachments/859148438108504141/866917172541128764/Screenshot_2021-07-20-11-06-36-470_com.android.chrome.png"> <img width=30% src= "https://cdn.discordapp.com/attachments/859148438108504141/866917172915208192/Screenshot_2021-07-20-11-06-44-002_com.android.chrome.png"></br>
----
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by AKSHATNEMA** [comment]
Hi, I want to work on this issue. Please assign me this issue.

**Comment by Harsh-jot** [comment]
Hey, I would like to work on this issue!

**Comment by ghulamyazdani** [comment]
@amino19 I would like to work on this issue!!

**Comment by adithyaakrishna** [comment]
> **Current State of the Meshery.io site**
> Modification relates to `mobile view` in general:
> 
> 1. [x]  Needs to add Community Forum point at appropriate section [Community]
> 2. [ ]  Alignment of `Created by LAYER5 and it's open source community` needs to set, i.e, flexible to current state - G
> 3. [ ]  Horizontally footer content must be vertical represent - A
> 4. [ ]  Menu issue - H
> 
> **Current State of the Meshery.io site**
> 
> ## <img alt="" width="30%" src="https://camo.githubusercontent.com/c4f9259065022fc4d67a9c118740d210e94cf4c297abf32fed67545f6a7070eb/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3835393134383433383130383530343134312f3836363931373137323534313132383736342f53637265656e73686f745f323032312d30372d32302d31312d30362d33362d3437305f636f6d2e616e64726f69642e6368726f6d652e706e67"> <img alt="" width="30%" src="https://camo.githubusercontent.com/f074e528f570ac4d897c6c1715eb70664608ec08859bc82e0616f3569573c9c5/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3835393134383433383130383530343134312f3836363931373137323931353230383139322f53637265656e73686f745f323032312d30372d32302d31312d30362d34342d3030325f636f6d2e616e64726f69642e6368726f6d652e706e67">
> **Contributor Resources**
> 
> * See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

@leecalcote @amino19 Reopening this as the other 3 tasks are pending still

**Comment by leecalcote** [comment]
Thank you, @adithyaakrishna

**Comment by amino19** [comment]
@adithyaakrishna : Do you mind reassign, @ghulamyazdani-bot & @AKSHATNEMA. They're still working at the back-end! :slightly_smiling_face:
