### ISSUE TITLE
Fixing the broken profile Image for "Anand Kumar Singh"

### ISSUE THREAD

**Issue by hdck007** [meshery/meshery.io#495]
**Description**
The profile image link on the [https://meshery.io/community/](https://meshery.io/community/) and [https://meshery.io/contributors/anand-kumar-singh/](https://meshery.io/contributors/anand-kumar-singh/) is broken.

**Expected Behavior**
The profile image for Anand Kumar Singh on the above-mentioned pages should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/68905333/125391018-60f82300-e3c1-11eb-804d-91ba0bfd670c.png)

![bug](https://user-images.githubusercontent.com/68905333/125391131-8edd6780-e3c1-11eb-966e-2d4e6abd9d7e.png)

**Enviroment:**
 - OS: Windows 10
 - Browser: Chrome, Brave, FireFox
 - Version: [e.g. 22]
 - Device: Laptop

---
**To Reproduce**
1. Go to  [https://meshery.io/community/](https://meshery.io/community/) or [https://meshery.io/contributors/anand-kumar-singh/](https://meshery.io/contributors/anand-kumar-singh/)

**Additional Context**
The Image seems to be fine on mobile devices.

**Comment by leecalcote** [comment]
Thank you, @hdck007

**Comment by The-Loony-Coder** [comment]
Can I work on this issue?

**Comment by Anita-ihuman** [comment]
@The-Loony-Coder sure, go ahead.

**Comment by The-Loony-Coder** [comment]
hey @Anita-ihuman,images off all the members are stored in assets/images/photos except for anand kumar singh.He provided a link which is not working "https://pbs.twimg.com/profile_images/1102512808363679744/Rp8-3wn9_400x400.jpg", so I  guess I want an image of anand kumar to make it work .

**Comment by Anita-ihuman** [comment]
Hold up a bit, I will send it accross.

**Comment by The-Loony-Coder** [comment]
hey @hdck007,I think I fixed the issue #495 ,have a look and tell me if anything is missing.sorry for taking this long,didn't have an image of anand-kumar and I was also stuck with other issue
