### ISSUE TITLE
[Programs] Change label and icon from CommunityBridge to LFX

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#500]
**Current State of the Meshery.io site**
Main page has this section:

<img width="1262" alt="Screen Shot 2021-07-23 at 7 18 46 PM" src="https://user-images.githubusercontent.com/7570704/126852447-511ddd53-829b-4259-b41c-64d1aa09d9b0.png">

**Desired State of the Meshery.io site**
Both the label and icon for the CommunityBridge button should be that of LFX.

[lfx_reverse.svg.zip](https://github.com/meshery/meshery.io/files/6871661/lfx_reverse.svg.zip)

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by Meghana-12** [comment]
Hi, I'd like to work on this.

**Comment by sayantan1413** [comment]
Here you go @Meghana-12 🚀

**Comment by warunicorn19** [comment]
Hey @Meghana-12 sorry for this, but looks like nikhil has solved this issue in a PR he sent a few ours ago. Why don't look for some other issues with the tag https://github.com/meshery/meshery.io/labels/help%20wanted . Apologies for the misunderstanding.

**Comment by Meghana-12** [comment]
Should I change "CommunityBridge" to "LFX" ?

**Comment by Meghana-12** [comment]
Oh! Sure, no problem!

**Comment by aman-cpu** [comment]
Hey @leecalcote is this issue is open. If it is open pls assign to me.

**Comment by warunicorn19** [comment]
Hey @aman-cpu there's already an existing PR for this, you might want to take a look at other issue which have the `help wanted` label.

**Comment by warunicorn19** [comment]
@Meghana-12 Sorry for the miscommunication, but this still seems to be an issue, would you like to work on it.?

**Comment by Meghana-12** [comment]
Yeah sure

**Comment by warunicorn19** [comment]
Thanks @Meghana-12

**Comment by Meghana-12** [comment]
I'm busy with another issue rn. So if anyone else is interested then feel free to assign it to them. Else I'll work on this once I complete that task.

**Comment by warunicorn19** [comment]
Okay, @Meghana-12 no problem at all, thanks for letting us know😃.

**Comment by warunicorn19** [comment]
Yes sure @aman-cpu you can work on this.😃

**Comment by aman-cpu** [comment]
Thank you, Sir.

**Comment by ANURAG-PATHAK** [comment]
> **Current State of the Meshery.io site**
> Main page has this section:
> 
> <img alt="Screen Shot 2021-07-23 at 7 18 46 PM" width="1262" src="https://user-images.githubusercontent.com/7570704/126852447-511ddd53-829b-4259-b41c-64d1aa09d9b0.png">
> 
> **Desired State of the Meshery.io site**
> Both the label and icon for the CommunityBridge button should be that of LFX.
> 
> [lfx_reverse.svg.zip](https://github.com/meshery/meshery.io/files/6871661/lfx_reverse.svg.zip)
> 
> **Contributor Resources**
> 
> * See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

hey @leecalcote I was working on this issue just wanted a confirmation 
is it  the desired change and if you want me to change something else please let me know I will do the same 
<img width="1288" alt="Screenshot 2021-08-20 at 8 36 30 PM" src="https://user-images.githubusercontent.com/81188792/130254116-0a5cc9d2-c326-4a98-806f-8a2aa003d1e2.png">


if you could provide me with a better icon or a larger icon then it will be easier for me. 
thank you

**Comment by warunicorn19** [comment]
@ANURAG-PATHAK remove the community bridge all together and make that solely LFX, and you could just add some css properties to make it bigger and better

**Comment by ANURAG-PATHAK** [comment]
> @ANURAG-PATHAK remove the community bridge all together and make that solely LFX, and you could just add some css properties to make it bigger and better

okay

**Comment by ANURAG-PATHAK** [comment]
<img width="1288" alt="Screenshot 2021-08-20 at 8 46 55 PM" src="https://user-images.githubusercontent.com/81188792/130255265-21ff277a-6232-40d6-9950-44f550ed784c.png">
 
 @warunicorn19 
 is it the desired change

**Comment by warunicorn19** [comment]
no like it'll be just LFX that's it.

**Comment by ANURAG-PATHAK** [comment]
<img width="1288" alt="Screenshot 2021-08-20 at 11 59 06 PM" src="https://user-images.githubusercontent.com/81188792/130278036-5b9a3943-8f71-4d59-8b0e-8da42e71d955.png">


<img width="1288" alt="Screenshot 2021-08-20 at 11 59 49 PM" src="https://user-images.githubusercontent.com/81188792/130278079-18c8a0a9-dd9e-4e6d-9c09-aad8d071c0bd.png">


                   which one is the preferred one top one or bottom one?

**Comment by warunicorn19** [comment]
@leecalcote ^^^^

**Comment by leecalcote** [comment]
Looking good so far, @ANURAG-PATHAK. +1 to the bottom, but with the blue X made white. This can be done by editing the original SVG or by applying a CSS filter.

**Comment by ANURAG-PATHAK** [comment]
> Looking good so far, @ANURAG-PATHAK. +1 to the bottom, but with the blue X made white. This can be done by editing the original SVG or by applying a CSS filter.

okay

**Comment by ANURAG-PATHAK** [comment]
<img width="1288" alt="Screenshot 2021-08-21 at 12 14 52 AM" src="https://user-images.githubusercontent.com/81188792/130279595-8c7ca773-3a49-4f87-b8a6-c1ee560bea93.png">



is this one okay or should i change some thing else

**Comment by leecalcote** [comment]
@ANURAG-PATHAK I would've thought that we would just use a white version of the logo, since it has the name in the logo already, but there's a certain quality afforded to the buttons as a set when they are consistent in their presentation of logo+text. This looks good to me. ✔️

**Comment by ANURAG-PATHAK** [comment]
> @ANURAG-PATHAK I would've thought that we would just use a white version of the logo, since it has the name in the logo already, but there's a certain quality afforded to the buttons as a set when they are consistent in their presentation of logo+text. This looks good to me. ✔️

should I make a PR with this one as final? 
@leecalcote

**Comment by ANURAG-PATHAK** [comment]
issue fixed in the commit `c06ce3ba37655ca57a37b36a03069465b06679c5` in PR #520
