### ISSUE TITLE
[Getting started ] rectifying the installation commands for various platform

### ISSUE THREAD

**Issue by samirparhi-dev** [meshery/meshery.io#502]
**Description**
The Commands for installing meshery to be rectified for various platform. (https://meshery.io/#getting-started)

**Expected Behavior**
- Move "Using Manifests" section from helm to Kubernetes and correct the the helm command  where ever necessary
Correct command is `helm install meshery meshery/meshery --namespace meshery`
- Other platform section should have the command to install `mesheryctl` first 

**Screenshots**

<img width="884" alt="Screenshot 2021-07-30 at 10 10 43 PM" src="https://user-images.githubusercontent.com/59992800/127684839-dd62869b-28f0-4e3f-a4e7-63bc5b4e59aa.png">

---

**Comment by shahkushal38** [comment]
Hey @samirparhi-dev, I would like to work on this issue.

**Comment by warunicorn19** [comment]
Here you go! @shahkushal38

**Comment by amino19** [comment]
@samirparhi-dev : Couple of points I want to ask here as follows:-
1. I think, we've already "Using Manifests" section in `Kubernetes` commands itself, represents similar as `Helm`  :slightly_smiling_face: 

2. Under `Install on Kubernetes using Helm` section, there are 2 commands, I think the first one is incorrect, it must be like:
```
kubectl create --namespace meshery
```
Currently it is:

![image](https://user-images.githubusercontent.com/75872316/127970748-83978cb8-fefa-4b9e-bfc3-4c9eb8164fdb.png)

[_Correct me, if I'm wrong_]

**Comment by samirparhi-dev** [comment]
> @samirparhi-dev : Couple of points I want to ask here as follows:-
> 
>     1. I think, we've already "Using Manifests" section in `Kubernetes` commands itself, represents similar as `Helm`  🙂
> 
>     2. Under `Install on Kubernetes using Helm` section, there are 2 commands, I think the first one is incorrect, it must be like:
> 
> 
> ```
> kubectl create --namespace meshery
> ```
> 
> Currently it is:
> 
> ![image](https://user-images.githubusercontent.com/75872316/127970748-83978cb8-fefa-4b9e-bfc3-4c9eb8164fdb.png)
> 
> [_Correct me, if I'm wrong_]
@amino19 : Replace the command with this
```
kubectl create namespace meshery
helm repo add meshery https://meshery.io/charts/
helm install meshery meshery/meshery -n meshery
```

**Comment by samirparhi-dev** [comment]
@amino19 : Just remove the `using Manifest` section under Helm

**Comment by amino19** [comment]
@samirparhi-dev : Thanks for clearing this out! :heart: 

@shahkushal38 : Hope you got the way now! :eyes:

**Comment by shahkushal38** [comment]
Yes will do the said changes

**Comment by leecalcote** [comment]
@shahkushal38 we're having users reporting issues with these installation commands. We'll need to get this issue knocked out pronto.

**Comment by leecalcote** [comment]
Oh, I see now. The helm chart instructions under the Helm section are old, using:

```
helm install meshery --namespace meshery install/kubernetes/helm/meshery
```
