### ISSUE TITLE
[features page] Get Started button not linked to specific area of the Meshery docs

### ISSUE THREAD

**Issue by afzal442** [meshery/meshery.io#504]
**Description**
The four **“Get Started”** don't point to the specific area of the Meshery docs relevant to that category.
https://meshery.io/features

**Expected Behavior**
It should link to each specific area of docs.

**Enviroment:**
Everything

---

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
@afzal442 are you working on this?

**Comment by afzal442** [comment]
Yes @warunicorn19. I will work. Plz assign it to me. thanks
