### ISSUE TITLE
[Newsletter] Low contrast font not legible

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#506]
**Description**
See screenshot of https://meshery.io/subscribe page.

**Screenshots**
<img width="1743" alt="Screen Shot 2021-08-04 at 8 20 45 PM" src="https://user-images.githubusercontent.com/7570704/128276322-0b87481c-6c34-4f87-84be-3e1ad6220253.png">

**Enviroment:**
 - Browser: Safari]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by afzal442** [comment]
@warunicorn19 should I remove the color style?

**Comment by warunicorn19** [comment]
@afzal442 If there are no Figma designs, you can try out whatever you like and think would look nice 😅.
