### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery.io#509]
**Description**
There are 3 broken links on meshery.io.
1.MLH broken link on MLH program page + Naveen Jain profile link: https://meshery.io/programs/mlhfellowship/2020

2.Blog category links on blog page

<img width="775" alt="Screenshot 2021-08-06 at 1 36 05 PM" src="https://user-images.githubusercontent.com/53532328/128478872-78b704c6-2ab9-4e5d-bf30-ff78f18bf8c9.png">

3. Meshery link on GSOC Page

<img width="639" alt="Screenshot 2021-08-06 at 1 33 51 PM" src="https://user-images.githubusercontent.com/53532328/128478961-ab19382f-4fac-4ca4-a52f-9b2f40542c91.png">

**Expected Behavior**
Links should lead to the right place.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by yahyakhn** [comment]
Is this issue still open?

**Comment by warunicorn19** [comment]
Yup

**Comment by warunicorn19** [comment]
@yahyakhn would you like to try your hand at this?

**Comment by yahyakhn** [comment]
@warunicorn19 yeah sure.
