### ISSUE TITLE
Copy text gets hidden

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery.io#517]
**Description**
In the Getting Started portion of the website, the tooltip for the copy clipboard is getting cut off

**Expected Behavior**
The complete tooltip should be visible.

**Screenshots**

https://user-images.githubusercontent.com/53532328/129491907-3d9fc663-6192-4ba4-ae04-63d37ffe0d6a.mov

**Enviroment:**
 - OS: MacOs
 - Browser:  Chrome, Safari
 

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by ANURAG-PATHAK** [comment]
i would like to work on this issue

**Comment by warunicorn19** [comment]
sure @ANURAG-PATHAK !

**Comment by ANURAG-PATHAK** [comment]
WOULD YOU LIKE TO SUGGEST ME SOMETHING ANY HINTS OR ANYTHING AS THIS IS MY FIRST CONTRIBUTION SO I AM LITTLE NERVOUS

**Comment by warunicorn19** [comment]
😂 i would suggest you to calm down and take your time with it, no pressure.
Also, i think it has something to do with the `z-index` so you might want to look into that.

**Comment by warunicorn19** [comment]
Also, go through this https://github.com/meshery/meshery.io/blob/master/README.md#contributing to get your environment setup

**Comment by ANURAG-PATHAK** [comment]
> 😂 i would suggest you to calm down and take your time with it, no pressure.
> Also, i think it has something to do with the `z-index` so you might want to look into that.

OKAY THANK YOU SO MUCH

**Comment by ANURAG-PATHAK** [comment]
> Also, go through this https://github.com/meshery/meshery.io/blob/master/README.md#contributing to get your environment setup

OKAY ☺️

**Comment by ANURAG-PATHAK** [comment]
> 😂 i would suggest you to calm down and take your time with it, no pressure.
> Also, i think it has something to do with the `z-index` so you might want to look into that.

hey man I am not able to change the default ruby on my M1 mac 
I installed ruby using rbenv 
`rbenv install 3.0.2`
then I set it to global using 
`rbenv global 3.0.2`
when I type `rbenv global ` it is returning `3.0.2` but when I am typing `ruby -v` it is giving me the default version of ruby
`ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]` can you please help me

**Comment by warunicorn19** [comment]
Oh yes, ruby on M1 is really a hassle, `RUBY_CFLAGS="-w" rbenv install X.X.X` (X.X.X being the version you require), for meshery.io you'll require 2.7.0, after this use rbenv to set it to global. Please drop in more doubts in the slack channel, if you have any.

**Comment by ANURAG-PATHAK** [comment]
> Oh yes, ruby on M1 is really a hassle, use `RUBY_CFLAGS="-w" rbenv install X.X.X` (X.X.X being the version you require), for meshery.io you'll require 2.7.0, after this use rbenv to set it to global. Please drop in more doubts in the slack channel, if you have any.

okay
