### ISSUE TITLE
[Mailing Lists] Add the rest of the mailing lists to /subscribe page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#518]
**Current State of the Meshery.io site**
https://meshery.io/subscribe is missing entries for all the project mailing lists.

**Desired State of the Meshery.io site**
Have all lists available on /subscribe:

- | Meshery Developers | dev-group@meshery.io |
- | Meshery Users | user-group@meshery.io |
- | Meshery Maintainers | maintainers@meshery.io |
- | Meshery Security and Vulnerability Reports | meshery-security-vulns-reports@meshery.dev |
- | Meshery Community | community@meshery.io |

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Zain-Muiz** [comment]
Hey @leecalcote , Can I Take this ?

**Comment by sayantan1413** [comment]
Sure @Zain-Muiz go ahead.

**Comment by leecalcote** [comment]
Hi @Zain-Muiz, how are we doing here?

**Comment by Zain-Muiz** [comment]
Hey @leecalcote , We are ready here ! Having a small issue with my forked repo. Will need to re-fork. As soon as https://github.com/meshery/meshery.io/pull/523 gets merged, will have PR up for this issue as well !

**Comment by leecalcote** [comment]
@Zain-Muiz good deal. I wasn't sure that you were working through this or not. We need mailing lists published on smp-spec.io, meshery.io and getnighthawk.dev. In trying to get this behind us, I put in a few changes last night and just pushed before seeing your note. Will you review the main page and the mailing lists page to see if we need anything further here or if we can close this issue?

It would be great to get the getnighthawk mailers published on that site. [Mailing lists](https://docs.google.com/spreadsheets/d/14LPSEE6_IS2xB5oKvHY0BdfMFS0UvWTdcAkH7SRbIg8/edit#gid=0)

**Comment by Zain-Muiz** [comment]
@leecalcote As of now the meshery.io web has links to 2 of its mailing lists [Users and Dev], If that suffices I think this issue can be closed. But we have 3 more mailing lists that is to be a part as well. [ Maintainers, Community and Security Reports ].

**Comment by Zain-Muiz** [comment]
If we need all the mailing lists on this site, I can update the 3 which aren't available as of now with the present design [ The one you pushed yesterday ] , or have a PR with All 5 in, with the design I had previously coded and you can review and make a decision. @leecalcote .

**Comment by Zain-Muiz** [comment]
Also the smp-spec.io has a PR open for the Mailing list. Here : https://github.com/service-mesh-performance/service-mesh-performance/pull/216 .

2/3 mailers [Developers and Users] are already a part of getnighthawk web, if you want, I can add a PR adding the Maintainers Mailing list as well @leecalcote .
