### ISSUE TITLE
[UI] Add dropdown arrows in docs Sidebar Menu

### ISSUE THREAD

**Issue by Meghana-12** [meshery/meshery.io#521]
**Description**
I think it'd be better to add dropdown arrows for Sidebar in https://docs.meshery.io/ too, like the one discussed for [ this issue](https://github.com/meshery/meshery/issues/3940). It's not clear which Menu items have submenus and which ones do not. So, an arrow like the one below would make it clear. 
![Screenshot 2021-08-20 at 3 27 22 PM](https://user-images.githubusercontent.com/44519203/130315659-e4ab47f7-f5b5-4a59-9441-e585de73a05e.png)

**Expected Behavior**
Have a clear distinction between the Menu items which have submenus and which don't. 

**Screenshots**
![Screenshot 2021-08-21 at 1 50 41 PM](https://user-images.githubusercontent.com/44519203/130315702-b114d964-b39a-4d09-a3d1-d2cce2609456.png)
Here, the Menu item Contributing and FAQs have sub-menu items, but the rest don't. But all look the same. 

**Enviroment:**
 - OS: [MacOS]
 - Browser: [Chrome]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**
1. Go to 'https://docs.meshery.io/'

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by sayantan1413** [comment]
Hey @Meghana-12 for the docs issue can you open this issue in the Meshery repository beacuse this repository is for the meshery.io page.
