### ISSUE TITLE
[Security] Add missing security headers

### ISSUE THREAD

**Issue by Aman-Codes** [meshery/meshery.io#528]
**Description**
The current meshery website has a D grade in the security report. We need to add some missing security headers.
Reference Links:
- https://securityheaders.com/?q=https%3A%2F%2Fmeshery.io%2F&followRedirects=on
- https://observatory.mozilla.org/analyze/meshery.io

**Expected Behavior**
A grade in above security report

**Screenshots**
![image](https://user-images.githubusercontent.com/54680709/130942977-f0c6b4a8-d046-425d-8a30-14501d000cef.png)

---

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Good call out, @Aman-Codes 👍

**Comment by monalisha31** [comment]
Can i work on this issue?

**Comment by warunicorn19** [comment]
Sure @monalisha31.
