### ISSUE TITLE
[Performance] Improve website performance

### ISSUE THREAD

**Issue by Aman-Codes** [meshery/meshery.io#529]
**Description**
The current website homepage is getting too long which is impacting its performance.
Possible fixes:
- Remove all instances of unnecessary commented out code in production
![image](https://user-images.githubusercontent.com/54680709/130943791-106bcad8-56bc-44fe-a387-43a3c3d98ecf.png)
- Too many images and gifs are increasing the load time. we could use lazy loading for images. Reference: https://web.dev/browser-level-image-lazy-loading/
- Provide height and width attributes to images.
- Currently, there is a lot of empty space on the homepage. It could be redesigned to represent information in a more crisp and concise manner.
- Use of async and defer for non-critical javascript files
-  Use of advanced optimization techniques like preload, prefetch, etc. Reference: https://css-tricks.com/prefetching-preloading-prebrowsing/
- Add missing Cache Expiry headers to static assets

**Expected Behavior**
Full score in all the parameters in Lighthouse Report

**Screenshots**
![image](https://user-images.githubusercontent.com/54680709/130944589-1dda63a3-b772-4b0b-a86d-f6b9272cc981.png)

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Thanks for calling these out, @Aman-Codes 👍 

> - Provide height and width attributes to images.

Specifying height and width attributes of images has the adverse affect of them not being responsive. Their responsiveness will need too accounted for as well.

**Comment by Blakelist7** [comment]
@Aman-Codes if no one is working on this issue, can I give it a shot?

**Comment by warunicorn19** [comment]
Sure @Blakelist7

**Comment by Blakelist7** [comment]
Okay, so I was reading through the [Performance](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmeshery.io%2F) and saw that one of the [ways](https://web.dev/serve-responsive-images/) listed under "Properly size pictures" was to reduce the size of images ([imagemagic](https://web.dev/serve-responsive-images/#imagemagick)). 
What are your thoughts on this?

**Comment by Blakelist7** [comment]
@leecalcote I believe we could reopen this discussion because there are still certain things that have not been implemented. : )
