### ISSUE TITLE
[UI] Issues on disabling JavaScript

### ISSUE THREAD

**Issue by Aman-Codes** [meshery/meshery.io#530]
**Description**
When we [disable JavaScript](https://developer.chrome.com/docs/devtools/javascript/disable/) the following issues appear:
- Improper CSS of buttons
![image](https://user-images.githubusercontent.com/54680709/130946149-db71d549-34f2-40f1-a268-818d87fd71d1.png)
- Unreadable navbar text
![image](https://user-images.githubusercontent.com/54680709/130946204-6ca1cc07-5367-4576-9735-86fb3e62208a.png)

**Expected Behavior**

We should either fix the above issues or should add a `<noscript>` tag stating that You need to enable JavaScript to run this website.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by AnshumanDhiman** [comment]
can I work on this @warunicorn19 @leecalcote

**Comment by warunicorn19** [comment]
Sorry 😅, missed the comment.

**Comment by leecalcote** [comment]
Thanks for filing this @AnshumanDhiman

**Comment by leecalcote** [comment]
Is this a concern? Do we expect to have visitors with Javascript disabled? Are these target Meshery users?

**Comment by AnshumanDhiman** [comment]
I don't think that website visitors have their JavaScript disabled. But let's go for the safe side if any one by chance have their JavaScript disabled the website will automatically throw a small message at the top to enable the JavaScript for viewing full features of the website.

**Comment by AnshumanDhiman** [comment]
@warunicorn19 @leecalcote can you help in reviewing this one
