### ISSUE TITLE
[Enhacement] Improve UX

### ISSUE THREAD

**Issue by Aman-Codes** [meshery/meshery.io#532]
**Description**
- Display information in a card to effectively utilize space. Also, reference links could be replaced with a button with a hover effect.
![image](https://user-images.githubusercontent.com/54680709/130948193-57ce9bb7-c34b-4886-a268-4f78f3541135.png)
- In the used by section, display the company's logo on a marquee (logos moving from left to right)

---
**Additional Context**
**Note**: The above mentioned suggestions are open to discussion

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by AnshumanDhiman** [comment]
can I work on this @warunicorn19

**Comment by warunicorn19** [comment]
Go for it!
