### ISSUE TITLE
Add NGINX Service Mesh results to the SMI Conformance Dashboard

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#542]
**Current State of the Meshery.io site**
https://meshery.io/smi is missing an entry for NGINX Service Mesh.

**Desired State of the Meshery.io site**
Make the same results that are available here - https://layer5.io/service-mesh-landscape#smi, available on meshery.io, too.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by afzal442** [comment]
Can I take up this?
