### ISSUE TITLE
Add CNCF Webinar video and link to slides

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#548]
**Desired State of the Meshery.io site**
video: https://www.youtube.com/watch?v=mU8qHUGYsk8
slides: https://docs.google.com/presentation/d/1YxeERLarsh60ItrgT29KzlNQEjkRnw5WDnnwy2uUe1Y/edit?usp=sharing

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by AnshumanDhiman** [comment]
can I work on this @leecalcote

**Comment by leecalcote** [comment]
That would be great.

**Comment by error9098x** [comment]
Is this task done yet ?

**Comment by AnshumanDhiman** [comment]
I am working on it @error9098x

**Comment by AnshumanDhiman** [comment]
> That would be great.

@leecalcote can you help me in finding a place where to place this, like should I create a particular section for this or like add this in the normal form

**Comment by warunicorn19** [comment]
🤔🤔hmmm, @leecalcote the home page for meshery.io is already too long, which is affecting the performance of the website, should we create another section for videos and slides?

**Comment by leecalcote** [comment]
@warunicorn19, yes, please. FYI - https://github.com/meshery/meshery.io/issues/193
