### ISSUE TITLE
Button in a Button

### ISSUE THREAD

**Issue by AnshumanDhiman** [meshery/meshery.io#551]
**Description**
The "Become an Adopter" button is looking very weird (a button in a button)

**Expected Behavior**
The button should look normal 

**Screenshots**
![1](https://user-images.githubusercontent.com/67755381/132871530-bcaaedf6-eaeb-4c79-a9bf-69f238c27444.jpg)
![2](https://user-images.githubusercontent.com/67755381/132871338-bb27e0f3-f89f-4961-8db7-5ba193a731ff.jpg)

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@AnshumanDhiman good call out. Let's work through design in the Meshery Figma file, so that we are sure to consider the site holistically. Let's get a sitemap going in that Figma file.

**Comment by warunicorn19** [comment]
@AnshumanDhiman will you be working on this?

**Comment by AnshumanDhiman** [comment]
Yes @warunicorn19 let me take it.

**Comment by warunicorn19** [comment]
Great!
