### ISSUE TITLE
Add service mesh discussion community forum to menu

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#556]
**Current State of the Meshery.io site**
Menu is missing a link to the service mesh discussion community forum

<img width="283" alt="Screen Shot 2021-09-14 at 1 15 07 AM" src="https://user-images.githubusercontent.com/7570704/133204977-2e35bbe4-8744-48e1-9d77-ae022ce9993d.png">

**Desired State of the Meshery.io site**
"Discuss" with an external link icon pointing to https://discuss.layer5.io

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by AnshumanDhiman** [comment]
On it @leecalcote boss😃
