### ISSUE TITLE
[CI] add label commenter workflow

### ISSUE THREAD

**Issue by amino19** [meshery/meshery.io#558]
**Description:**

This repository should have the label commenter workflow.
It would run whenever an issue/pr is labelled with one of the targeted labels and comment down any relevant information.

**Contributor Reference:**

The workflow would use: https://github.com/peaceiris/actions-label-commenter

A sample workflow is defined in: https://github.com/meshery/meshery/blob/master/.github/workflows/label-commenter.yml.

It would also need a sample configuration which is defined in: https://github.com/meshery/meshery/blob/master/.github/label-commenter-config.yml

**NOTE:**

- In the above configuration https://github.com/meshery/meshery/blob/88d1c7c559259775ce2affab2a15a32c673c3f52/.github/label-commenter-config.yml#L26-L41 are specific to Meshery and won't be needed on every repository.
- Do comment in PR if you find any label is missing for the repo.

**Comment by chetak123** [comment]
Can I please take this issue ?

**Comment by warunicorn19** [comment]
Sure @chetak123.
