### ISSUE TITLE
Button in a Button Again

### ISSUE THREAD

**Issue by AnshumanDhiman** [meshery/meshery.io#562]
**Description**
I think someone has edited the div of the button or the button and the classes applied to different pages are facing this button in a button issue. 

**Expected Behavior**
Currently only this page buttons needs to be updated asap.

**Screenshots**
![1](https://user-images.githubusercontent.com/67755381/134567127-abdca3c0-03e5-44e7-aa08-f490bf6295ef.jpg)
![2](https://user-images.githubusercontent.com/67755381/134567132-69e0f450-70b2-4b71-a164-71ff2d3d7bc5.jpg)

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by AndrewArnita** [comment]
Hello, please can I take care of this issue?

**Comment by leecalcote** [comment]
Thank you, @AndrewArnita. Yes, please take it away. 👍

**Comment by AndrewArnita** [comment]
This issue has been fixed!
