### ISSUE TITLE
[CI] Upgrade Slack notifier to use Environment Files

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#569]
**Description**
The slack notifier [workflow fails](https://github.com/meshery/meshery.io/runs/3728731236?check_suite_focus=true) with the output shown in the screenshot.

**Expected Behavior**
Refactor to use recommended [environment files](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)

**Screenshots**
<img width="962" alt="Screen Shot 2021-09-29 at 12 43 04 PM" src="https://user-images.githubusercontent.com/7570704/135321328-f5e8421b-4df2-42b5-a99b-50301e98f314.png">

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by iamsdas** [comment]
I'd like to take up this issue

**Comment by amino19** [comment]
@iamsdas: Sure, deffo! :+1:
