### ISSUE TITLE
Meshery Blog sub-tags

### ISSUE THREAD

**Issue by AnshumanDhiman** [meshery/meshery.io#573]
**Description**
Currently the meshery blog website have heading and some sub-tags. But when use clicks to the tag such as (smi-conformance, specification, multimesh) it redirects to a page where it says page doesn't exist.

**Expected Behavior**
For the time being if the data is not available for the subtags anchor links should be disabled.

**Screenshots**
![Screenshot (53)](https://user-images.githubusercontent.com/67755381/135506402-39f09023-21c9-4667-8d0c-97c6a6af0fed.png)
![Screenshot (54)](https://user-images.githubusercontent.com/67755381/135506412-10bc9f47-bdc0-4cf2-8f52-dc1121281dcb.png)

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by AnshumanDhiman** [comment]
Can I work on this @warunicorn19 @vinayaksh42 @leecalcote

**Comment by warunicorn19** [comment]
@AnshumanDhiman there's already an open issue on this #509

**Comment by warunicorn19** [comment]
You could probably help the contributor in fixing this, you could take a look at his open PR

**Comment by AnshumanDhiman** [comment]
sorry I didn't noticed I'll just close this issue😅😅

**Comment by warunicorn19** [comment]
No problem 😄
