### ISSUE TITLE
Results from different versions of SMI test is not Visible

### ISSUE THREAD

**Issue by dhruv0000** [meshery/meshery.io#576]
**Description**

Issue 1 (High Priority):
The table in https://meshery.io/service-mesh-interface gets data from https://meshery.layer5.io/smi/results/public which has results for multiple versions for same mesh. We should ideally be able to see results of older version by clicking on them.

Issue 2 (Mid Priority):
The user should also have ability to navigate between diff test versions for future SMI tests versions. Eg: https://layer5.io/service-mesh-landscape#smi

**Expected Behavior**
A brief description of what you expected to happen.

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Sandesh1013** [comment]
Can I have a go on this?

**Comment by warunicorn19** [comment]
@dhruv0000 so we basically want all the data to be present in the table, like for all versions?

**Comment by leecalcote** [comment]
@dhruv0000 will you confirm that all test results are accompanied by an SMI version number?

**Comment by dhruv0000** [comment]
> @dhruv0000 so we basically want all the data to be present in the table, like for all versions?

For future versions. Currently we only have test results for `v0.6.0`

**Comment by dhruv0000** [comment]
> @dhruv0000 will you confirm that all test results are accompanied by an SMI version number?

The overall SMI version is included in the specific version detail of each spec.

Ideally, we should also show the SMI version along with mesh_name and mesh_version ..., but not sure if it's worth the pain to update the protobufs and rerun all the tests for a new structure, right now tbh.

**Comment by leecalcote** [comment]
@Sandesh1013 please do progress with a selector to allow the user to choose which version of SMI they want to review compatibility of.

**Comment by warunicorn19** [comment]
@Sandesh1013 do we have any updates on this?

**Comment by Sandesh1013** [comment]
Was facing some issues setting it up, I'll try to have a final go at it

**Comment by warunicorn19** [comment]
Okay sounds good.

**Comment by leecalcote** [comment]
@Sandesh1013 still working this one through? If not, let's unassign, so that another contributor might pick this up.

**Comment by leecalcote** [comment]
Bringing in the big guns...

**Comment by shubham-tyagi** [comment]
Oh missed this issue, will do it 😅

**Comment by RajGM** [comment]
Hi @shubham-tyagi 
Can I work on this along side with you?

**Comment by RajGM** [comment]
What to display on table if mesh version : none is present in the data
![meshVersionNone](https://user-images.githubusercontent.com/16620150/152850945-efcba669-5054-4c29-960f-dae839642cce.jpeg)
.

Also what to display if we don't have info for other mesh services with same version.

**Comment by leecalcote** [comment]
> What to display on table if mesh version : none is present in the data

Let's display "Unknown" for the time being.

> Also what to display if we don't have info for other mesh services with same version.

Show a blank table cell.

**Comment by shubham-tyagi** [comment]
> Hi @shubham-tyagi Can I work on this along side with you? I have worked on this kind of problem before in my project https://github.com/RajGM/GSoC_OrganizationsTracker That projects helping in filtering organization based on various parameters.

Hey @RajGM, I am stuck somewhere. Please proceed.

**Comment by RajGM** [comment]
> > Hi @shubham-tyagi Can I work on this along side with you? I have worked on this kind of problem before in my project https://github.com/RajGM/GSoC_OrganizationsTracker That projects helping in filtering organization based on various parameters.
> 
> Hey @RajGM, I am stuck somewhere. Please proceed.

Okay @shubham-tyagi

**Comment by RajGM** [comment]
Why @leecalcote 

Traffic Accessv0.6.0/v1alpha3 | Traffic Splitv0.6.0/v1alpha4 | Traffic Specv0.6.0/v1alpha4

All have v0.6.0 even if the mesh version is v0.8 or anything else.

Should I just put the value into table with the above conflict?

**Comment by RajGM** [comment]
Why @leecalcote 

Traffic Accessv0.6.0/v1alpha3 | Traffic Splitv0.6.0/v1alpha4 | Traffic Specv0.6.0/v1alpha4

All have v0.6.0 even if the mesh version is v0.8 or anything else.

Should I just put the value into table with the above conflict?

Also should I make a horizontal scroll for lot of mesh_version 
![table](https://user-images.githubusercontent.com/16620150/153155437-6ed81c0d-8cf7-42e1-b1ae-c1bc18c974ce.jpeg)

**Comment by RajGM** [comment]
Hi @leecalcote , @dhruv0000 and @shubham-tyagi 
It's done

Is this good to push?

https://user-images.githubusercontent.com/16620150/153194128-68ee6ac1-b512-47d2-9d0a-833c3eee5da8.mp4

**Comment by RajGM** [comment]
Hi @dhruv0000 
Is there any dummy data I can use for testing purposes?
