### ISSUE TITLE
[FEATURE] Add dark mode to the website

### ISSUE THREAD

**Issue by Panquesito7** [meshery/meshery.io#581]
**Current State of the Meshery.io site**

Currently, there is no dark mode for the website. It would look cool if we could add a dark mode.

**Desired State of the Meshery.io site**

It would be cool if a dark mode for the website be added.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
This would be excellent. There's design that needs done (see the linked Figma project). 

Also, @NikhilSharma03 has put some effort toward this. See is open PR. What do you think, @Panquesito7?

**Comment by Panquesito7** [comment]
Commented, so the issue doesn't get closed. 😅

**Comment by DhairyaBahl** [comment]
@Panquesito7 @leecalcote Is this issue still available ?

**Comment by Panquesito7** [comment]
> @Panquesito7 @leecalcote
> 
> If this issue still persists, Kindly assign this to me.

Sure, feel free to work on it! 😄

**Comment by warunicorn19** [comment]
@DhairyaBahl there's actually an open open PR on this already. Why don't you take a look at some other [help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Aservice-mesh-performance+org%3Ameshery+label%3A%22help+wanted%22+) issues.

**Comment by DhairyaBahl** [comment]
> @DhairyaBahl there's actually an open open PR on this already. Why don't you take a look at some other [help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Aservice-mesh-performance+org%3Ameshery+label%3A%22help+wanted%22+) issues.

No issues. I will check out other issues 😄

**Comment by Panquesito7** [comment]
> @DhairyaBahl there's actually an open open PR on this already. Why don't you take a look at some other [help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Aservice-mesh-performance+org%3Ameshery+label%3A%22help+wanted%22+) issues.

What is that PR? 👀 I haven't seen it, nor it's linked here to this issue.

**Comment by Panquesito7** [comment]
Can you re-open this issue? Thanks. 😅
