### ISSUE TITLE
[UI] Remove useless gap between "Overview" and "Getting Started" section

### ISSUE THREAD

**Issue by ghulamyazdani** [meshery/meshery.io#585]
**Description**
There is a useless gap between "Overview" and "Getting Started" section
![mesherypng](https://user-images.githubusercontent.com/55938346/137286367-d000809b-bee9-4c4c-a25a-5f3205c5d462.png)

**Expected Behavior**
The gap between "Overview" and "Getting Started"   should be removed.
![image](https://user-images.githubusercontent.com/55938346/137287188-4e963ee2-36f5-4784-8be1-63a504f9106b.png)

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**
1. Go to 'https://meshery.io/'
3. Scroll down to ' "Overview" and "Getting Started"  Section'

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by iambami** [comment]
Sure @ghulamyazdani you can
