### ISSUE TITLE
Blending Navbar dropdown hover color

### ISSUE THREAD

**Issue by AnshumanDhiman** [meshery/meshery.io#590]
**Description**
The current dropdown navbar option hover color in the meshery.io website is blending with the background of background color making it a little bit of harder to read. 

**Expected Behavior**
Boldness should be added or the color should be made a bit darker.

**Screenshots**
![image_2021-10-25_232159](https://user-images.githubusercontent.com/67755381/138745312-c19a5e06-3c46-4a1c-9257-4792714a212e.png)

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by vedant-kakde** [comment]
Tried these three options from https://meshery.io/brand . Let me know which one we can finalize or if you have more suggestions.
![image](https://user-images.githubusercontent.com/69970950/139055503-dfa3a27c-3d84-46e6-b4ea-592f64534a74.png)

![image](https://user-images.githubusercontent.com/69970950/139055563-583c903e-c77b-46cb-8cb0-177c2be08cb3.png)

![image](https://user-images.githubusercontent.com/69970950/139055618-a361ac97-55fa-4fb3-837c-837159acb90c.png)

**Comment by warunicorn19** [comment]
hey @vedant-kakde could you please just use the color that we use on the meshery.io website.
<img width="1440" alt="Screenshot 2021-10-27 at 5 53 23 PM" src="https://user-images.githubusercontent.com/53532328/139065227-59d41cf4-8bec-4825-b018-9b2972bf81a2.png">

**Comment by deeepsig** [comment]
> hey @vedant-kakde could you please just use the color that we use on the meshery.io website. <img alt="Screenshot 2021-10-27 at 5 53 23 PM" width="1440" src="https://user-images.githubusercontent.com/53532328/139065227-59d41cf4-8bec-4825-b018-9b2972bf81a2.png">

But in that way I think the background color for the drop down should also be changed to the one which @warunicorn19 suggested here. Make sense?😅
