### ISSUE TITLE
Github and Slack Icon color

### ISSUE THREAD

**Issue by AnshumanDhiman** [meshery/meshery.io#591]
**Description**
The current colors of the slack icon and github icon in the meshery.io are mixing with the footer which is not looking good.
![3](https://user-images.githubusercontent.com/67755381/138746610-8c0a0f84-5e0a-4eb2-aba6-5e5da790b39c.jpg)
![4](https://user-images.githubusercontent.com/67755381/138746616-1e997022-6857-4c6b-a0bc-75ddd1cc3ad5.jpg)

**Expected Behavior**
In the layer5 website the footer icons of the slack and github are looking good. 
Have a look at these
![1](https://user-images.githubusercontent.com/67755381/138746433-f957665f-bad6-4b5e-b28d-bb1a71bce925.jpg)
![2](https://user-images.githubusercontent.com/67755381/138746445-5082258e-0e0d-4dd8-b83e-1751f4951b34.jpg)
Try to make the icons in meshery.io like this.
If you want to check the footer have a look at layer5.io 

**Screenshots**

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by shubham-tyagi** [comment]
Hey @vedant-kakde, are you still working on this?
