### ISSUE TITLE
Getting Started section images skewed.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#598]
**Description**
Getting Started section images skewed.

**Enviroment:**
 - OS: Mac
 - Browser: Safari
 - Version: 15.0

**Screenshots**
<img width="1204" alt="Screen Shot 2021-10-31 at 11 39 16 AM" src="https://user-images.githubusercontent.com/7570704/139593654-90931b93-77c7-4300-a5bc-c9a37366e648.png">

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Thank you for taking this, @warunicorn19

**Comment by vedant-kakde** [comment]
This issue can be closed as @warunicorn19  's PR #600  has been merged for fixing this issue.

**Comment by warunicorn19** [comment]
Sorry my bad, I forgot to link.

**Comment by vedant-kakde** [comment]
No worries. It was urgent fix I can understand 😄
