### ISSUE TITLE
Newsletter Subscription enhancement on Programs page

### ISSUE THREAD

**Issue by debo19** [meshery/meshery.io#605]
**Description**
 On hover, the subscribe button blends with the background completely. (On [Programs](https://meshery.io/programs) page)

https://user-images.githubusercontent.com/85789734/139727744-b019bd94-0863-40c5-bf9b-1bd3a092748a.mp4

**Expected Behavior**

1) Change the hover effect of the subscribe button.
2) Remove the gray band between the footer and the newsletter section.

**Screenshots**

![band](https://user-images.githubusercontent.com/85789734/139727904-002b069e-303a-48f0-9336-a7a51f8791da.jpg)

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Generalsoi** [comment]
Hi, I would like to work on this issue.

**Comment by iambami** [comment]
Sure @Generalsoi Go ahead!

**Comment by Mr-DG-Wick** [comment]
How much have you progressed on this one ? @Generalsoi

**Comment by roman-rezinkin** [comment]
Hi I was wondering if I could be assigned to tackle this problem? @debo19 @Mr-DG-Wick @iambami

**Comment by debo19** [comment]
Sure, @roman-rezinkin go ahead.

**Comment by debo19** [comment]
Hey @Generalsoi, since the issue persists for a long time I'm assigning @roman-rezinkin as well to help you out here. In case you have any updates, please feel free to share them with us.

**Comment by roman-rezinkin** [comment]
I have removed the grey banner below the subscribe button, any kind of special request for the subscribe button hover, in terms of color? I can see that currently it would be a accessibility issue, so I am just wondering if a change in color would be enough? @debo19

**Comment by debo19** [comment]
@roman-rezinkin a change in color is not necessary, you can try any other hover effect as well. For example- adding a shadow or a slight translation on hover.

**Comment by roman-rezinkin** [comment]
@debo19 I made the hover over a black, just as a test:
![image](https://user-images.githubusercontent.com/17882264/144736584-8cc6c238-429f-4a0c-9860-a0ad147e3805.png)

https://user-images.githubusercontent.com/17882264/144736676-397cafa7-d594-44f0-871a-51a5a2b9ec4c.mp4




Here is the same hover color as the footer + a few shades lighter:

https://user-images.githubusercontent.com/17882264/144737469-7c901838-8866-434e-bd8d-78aec548b7ec.mp4

Please let me know what you think of these, and I can create a PR.

**Comment by debo19** [comment]
@roman-rezinkin Let's go with the last one(the one with the footer color) since we need to follow the color scheme on the site.

**Comment by roman-rezinkin** [comment]
I have created a PR, it is ready for review! [Pull Request](https://github.com/meshery/meshery.io/pull/625)
