### ISSUE TITLE
Change the cursor when it is on the right tick symbol

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery.io#615]
**Current State of the Meshery.io site**
on this [page](https://meshery.io/service-mesh-interface), there is no change of cursor when the cursor is on the **right tick** symbol in the column **Traffic Access**. 

![](https://imgur.com/TEQ3icP.png)

**Desired State of the Meshery.io site**

Change the cursor to like it changes when on any other symbol in the table.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Reedham20** [comment]
Hey, I was solving #619 and noticed this and solved this as well should I make a PR?

**Comment by warunicorn19** [comment]
Sure @Reedham20
