### ISSUE TITLE
A legend below the table

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery.io#616]
**Current State of the Meshery.io site**

There is no legend below the table on this  [page](https://meshery.io/service-mesh-interface).

**Desired State of the Meshery.io site**

We need a legend below the table on this [page](https://meshery.io/service-mesh-interface) like we have on this [page](https://layer5.io/service-mesh-landscape)
![](https://imgur.com/jU9fvrX.png)

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by roman-rezinkin** [comment]
Hi there, could I please take a crack at this, and implement the Legend?

**Comment by shubham-tyagi** [comment]
sure @roman-rezinkin, Thanks for taking this up.

**Comment by roman-rezinkin** [comment]
Could you please review my PR @shubham-tyagi #617

**Comment by shubham-tyagi** [comment]
sure @roman-rezinkin
