### ISSUE TITLE
Youtube video does not stop after modal has been closed.

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery.io#619]
**Description**
We have a youtube video embedded in a modal on this [page](https://meshery.io/talks-and-presentations). We can see the modal and hence youtube video after clicking on the button `find video and slides here`. When we start the video and then close the modal either by clicking outside or by clicking on the close symbol on the top right the video does not stop and keeps going.

**Expected Behavior**
The video should stop after we close the modal.

**Screenshots**
![](https://imgur.com/EE5UgLn.png)

---

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Reedham20** [comment]
Hey can I have a look at it?
I am new to open source and would like to contribute so if anyone can assign this to me, I would be happy to help.

**Comment by warunicorn19** [comment]
For sure @Reedham20, Thank you for taking this up.

**Comment by shubham-tyagi** [comment]
Hey @Reedham20, are you still working on this?

**Comment by Reedham20** [comment]
I am sorry... My exams are going on I will make updates on pr

**Comment by Reedham20** [comment]
Before 25th of the month

**Comment by shubham-tyagi** [comment]
Thanks, @Reedham20 .

**Comment by Susmita-Dey** [comment]
Hey, I'm new to open source. But here I can see there are controls in the video so on closing this the video can be stopped using the pause button otherwise one thing can be done like showing the thumbnails of the video on closing the window.

**Comment by shubham-tyagi** [comment]
hey @Reedham20, are you still working on it. There is a PR #651 which implements the stopping of video on closing the modal. It would be great if you could look into `assets/js/video-modal.js` file of that PR.

**Comment by shubham-tyagi** [comment]
@Susmita-Dey those are some interesting ideas. Our ultimate goal here is to stop the video after closing the modal. Do you wish to solve the issue. Seems like @Reedham20 is busy somewhere else.

**Comment by Susmita-Dey** [comment]
@shubham-tyagi I was learning javascript these days and so I don't have a deeper knowledge of it but still I wanna try it out once if I can help you to solve this issue and this would be a great opportunity for me in that case.

**Comment by shubham-tyagi** [comment]
thanks @Susmita-Dey for taking this up. If you face any hurdles while solving this issue please feel free to connect with me and other community members on slack.

**Comment by Susmita-Dey** [comment]
@shubham-tyagi Okay, thanks!

**Comment by leecalcote** [comment]
@shubham-tyagi please ensure that the same modal and javascript that we recently created is reused here.

**Comment by leecalcote** [comment]
Desired approach - https://github.com/meshery/meshery.io/pull/651

**Comment by shubham-tyagi** [comment]
sure @leecalcote, will make sure that same approach is being used here.

**Comment by leecalcote** [comment]
@Susmita-Dey progress to report?

**Comment by Susmita-Dey** [comment]
@leecalcote Sir I am just working on it. Please give me some time and I'll report soon.

**Comment by Susmita-Dey** [comment]
@shubham-tyagi @leecalcote Sir how could I run it on my local system to check if everything is working perfectly or not? 
The command "bundle install" is not working.

**Comment by Susmita-Dey** [comment]
@leecalcote @shubham-tyagi I have made some changes to the file but I can't check if it's working correctly or not. Shall I create a pull request and commit the changes?

**Comment by YashKamboj** [comment]
> @shubham-tyagi @leecalcote Sir how could I run it on my local system to check if everything is working perfectly or not? The command "bundle install" is not working.
What is the error showing ?

**Comment by shubham-tyagi** [comment]
> @leecalcote @shubham-tyagi I have made some changes to the file but I can't check if it's working correctly or not. Shall I create a pull request and commit the changes?

You should check by yourself first, so that you could debug it.

**Comment by shubham-tyagi** [comment]
have you gone through this -> https://docs.meshery.io/project/contributing/contributing-docs ?

> @leecalcote @shubham-tyagi I have made some changes to the file but I can't check if it's working correctly or not. Shall I create a pull request and commit the changes?

you could simply run `make site` command if the `gem install bundler` command is working fine. What is the ruby version that you have installed ?

**Comment by Susmita-Dey** [comment]
> have you gone through [this](https://docs.meshery.io/project/contributing/contributing-docs) ?
> 
> > @leecalcote @shubham-tyagi I have made some changes to the file but I can't check if it's working correctly or not. Shall I create a pull request and commit the changes?
> 
> you could simply run `make site` command if the `gem install bundler` command is working fine. What is the ruby version that you have installed ?

Ok I'm following it and installing ruby

**Comment by Susmita-Dey** [comment]
> have you gone through [this](https://docs.meshery.io/project/contributing/contributing-docs) ?
> 
> > @leecalcote @shubham-tyagi I have made some changes to the file but I can't check if it's working correctly or not. Shall I create a pull request and commit the changes?
> 
> you could simply run `make site` command if the `gem install bundler` command is working fine. What is the ruby version that you have installed ?
I have getting this type of error
![image](https://user-images.githubusercontent.com/79099734/150136014-e033918f-14d0-41e7-995c-d4bfcf1f19fe.png)

**Comment by RajGM** [comment]
Hi 
Can I look into the issue as well?
I am new to open source, so it would be good beginning point for me.

**Comment by shubham-tyagi** [comment]
@Susmita-Dey just change your ruby version to 2.7.0 . Use the command `rbenv install 2.7.0` if you have `rbenv` for managing ruby versions.

**Comment by shubham-tyagi** [comment]
Hi @RajGM, Thanks for going through this issue. Currently @Susmita-Dey is solving this issue. It would be great if you could go through other issues right now. Maybe you can assist @Susmita-Dey for solving this issue.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey just change your ruby version to 2.7.0 . Use the command `rbenv install 2.7.0` if you have `rbenv` for managing ruby versions.

I don't have `rbenv` for managing ruby versions.

**Comment by shubham-tyagi** [comment]
@Susmita-Dey You need to have ruby version 2.7.0. You can do that using anything like rvm, rbenv, etc. You just need to have any ruby version manager.

**Comment by RajGM** [comment]
Hi @shubham-tyagi 
Yeah I can look into other beginners issue alongside helping @Susmita-Dey.

**Comment by RajGM** [comment]
video-modal.js is not loading at all.
If I console log on it then it does not appear.

**Comment by RajGM** [comment]
Also I would suggest instead of having multiple modals with same ID.
We can store the link into an object and then depending upon the click we can load the url into video player.

**Comment by RajGM** [comment]
Should I proceed in this manner @leecalcote and @shubham-tyagi

**Comment by RajGM** [comment]
Hi @Susmita-Dey 
Have you able to solve those errors?

**Comment by Susmita-Dey** [comment]
> Hi @Susmita-Dey Have you able to solve those errors that you were encountering while running the site locally?

I can't run it on my local machine to see the output, that's the only problem otherwise I have corrected the file.

**Comment by asubedy** [comment]
Hi @Susmita-Dey, did you manage to install `ruby 2.7.0` using `rbenv` as mentioned on the comments above?

**Comment by Susmita-Dey** [comment]
> Hi @Susmita-Dey, did you manage to install `ruby 2.7.0` using `rbenv` as mentioned on the comments above?

No, I'm unable to do that it's not working...can't figure out what to do. Shall I make a pull request and the repository maintainers will review my work? Hope this would be better then.

**Comment by warunicorn19** [comment]
Please go ahead @Susmita-Dey

**Comment by Susmita-Dey** [comment]
> Please go ahead @Susmita-Dey

Okay

**Comment by warunicorn19** [comment]
Also you could try a hacky technique, in the gemfile change the gem version to whatever your local version is. Then run `bundle install` > `bundle exec jekyll serve` . Before making the commit just revert back the change or dont add the gemfile to your commit. (This works only sometimes though, worth a try)

**Comment by RajGM** [comment]
Hi @Susmita-Dey , @shubham-tyagi , @warunicorn19 and @asubedy 
I have solved the issue and it is working on my local machine.
Should I make a PR?

**Comment by RajGM** [comment]
> 

Hi @Susmita-Dey 
You can try WSL or try installing Linux on your system to get it running or try the hack as suggested by warunicorn19.

**Comment by Susmita-Dey** [comment]
> Hi @Susmita-Dey , @shubham-tyagi , @warunicorn19 and @asubedy 
> I have solved the issue and it is working on my local machine.
> Should I make a PR?

Make it

**Comment by Susmita-Dey** [comment]
> as

WSL doesn't work on my desktop. You carry on with this issue.

**Comment by shubham-tyagi** [comment]
Thanks @Susmita-Dey, for the update. But please have a look at the docs.meshery.io, you could directly install those required software in windows to solve more issues in the future.

**Comment by shubham-tyagi** [comment]
> > have you gone through [this](https://docs.meshery.io/project/contributing/contributing-docs) ?
> > > @leecalcote @shubham-tyagi I have made some changes to the file but I can't check if it's working correctly or not. Shall I create a pull request and commit the changes?
> > 
> > 
> > you could simply run `make site` command if the `gem install bundler` command is working fine. What is the ruby version that you have installed ?
> > I have getting this type of error
> > ![image](https://user-images.githubusercontent.com/79099734/150136014-e033918f-14d0-41e7-995c-d4bfcf1f19fe.png)

sorry I missed it @Susmita-Dey , you have to implement `make-site` command after going inside the docs folder.

**Comment by warunicorn19** [comment]
That's for the docs.meshery.io @shubham-tyagi, `make site` isn't working because `make` isn't installed

**Comment by Susmita-Dey** [comment]
> Thanks @Susmita-Dey, for the update. But please have a look at the docs.meshery.io, you could directly install those required software in windows to solve more issues in the future.

I'll try to solve issues in the near future after learning JavaScript properly.

**Comment by shubham-tyagi** [comment]
> That's for the docs.meshery.io @shubham-tyagi, `make site` isn't working because `make` isn't installed

yeah, completely missed the error statement @warunicorn19 😅 , only saw the current folder, my bad.

**Comment by shubham-tyagi** [comment]
> yeah, completely missed the error and issue statement @warunicorn19 , my bad😅.

yeah, completely missed the error and issue statement @warunicorn19 , my bad😅.

**Comment by shubham-tyagi** [comment]
> That's for the docs.meshery.io @shubham-tyagi, `make site` isn't working because `make` isn't installed

yeah, completely missed the error and issue statement @warunicorn19 , my bad😅.

**Comment by RajGM** [comment]
> > Thanks @Susmita-Dey, for the update. But please have a look at the docs.meshery.io, you could directly install those required software in windows to solve more issues in the future.
> 
> I'll try to solve issues in the near future after learning JavaScript properly.

Hi @Susmita-Dey 
Imposter syndrome can be the biggest challenge even after learning something. 
You can refer to https://www.w3schools.com and https://developer.mozilla.org/en-US/ for documentation.
