### ISSUE TITLE
[Website] Place service mesh patterns demo video into modal

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#628]
**Current State of the Meshery.io site**
On the index page of meshery.io, the short video linked under the button in this screenshot is directly linked. 

<img width="736" alt="Screen Shot 2021-12-09 at 5 03 56 PM" src="https://user-images.githubusercontent.com/7570704/145489628-6bbc59f7-0904-4113-bd9b-d96f5d2bfc90.png">

**Desired State of the Meshery.io site**
Ideally, this video plays in a modal, not as a separate, direct video.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by the-good-boy** [comment]
Can I work on this?
