### ISSUE TITLE
Add newcomers-alert.yml workflow to notify good-first-issue on slack

### ISSUE THREAD

**Issue by Ankita13-code** [meshery/meshery.io#630]
**Description**
Currently, as the maintainers mark any issue as a "good first issue",  there are no notifications on the slack channel for this repository.

**Expected Behavior**
Adding a Github workflow, so that newcomers on slack can get notified about the issues marked as good first issue.

**Comment by theBeginner86** [comment]
@Ankita13-code you are good to work on the issue 🚀

**Comment by Ankita13-code** [comment]
@theBeginner86 I have created a PR for this issue. Please take a look.
