### ISSUE TITLE
Add Discuss Forum to footer

### ISSUE THREAD

**Issue by debo19** [meshery/meshery.io#634]
**Current State of the Meshery.io site**
![footer](https://user-images.githubusercontent.com/85789734/145827219-c4e36ae0-39e2-4d55-89dd-2fd419cbff84.jpg)

**Desired State of the Meshery.io site**
Add a link to our [Discuss](https://discuss.layer5.io/) Forum on the footer under Community.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Abhipise81** [comment]
Hi @debo19, Can I work on this task?

**Comment by debo19** [comment]
Sure, go ahead @Abhipise81
