### ISSUE TITLE
Year in Footer is not updated.

### ISSUE THREAD

**Issue by developer-diganta** [meshery/meshery.io#656]
**Current State of the Meshery.io site**

The year in the main website footer seems to not update correctly. But the docs page shows the correct year though.
![image](https://user-images.githubusercontent.com/65999534/148604923-35bc6852-7351-4614-a059-bd33ecbc8de5.png)

**Desired State of the Meshery.io site**

The year should be 2022 i.e. "© 2022 The Meshery Authors".
---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@developer-diganta thanks for pointing this out. It would be great for this date to be dynamic. I _think_ that Meshery Docs has it dynamic in it's footer (I haven't looked in a long time) - https://docs.meshery.io.

**Comment by leecalcote** [comment]
Assigning this to you @developer-diganta, assuming that you want to work on it.

**Comment by developer-diganta** [comment]
@leecalcote yeah sure! I'll work on this!

**Comment by developer-diganta** [comment]
@leecalcote I compared the [docs footer](https://github.com/meshery/meshery/blob/master/docs/_includes/footer.html) and the [main website footer](https://github.com/meshery/meshery.io/blob/master/_includes/footer.html). Both seem to have the same code ` <div class="text-white">&copy; {{ site.time | date: '%Y' }} The Meshery Authors</div>` . Can I use Javascript Date to keep the main website updated?

**Comment by Anosh21** [comment]
@leecalcote can you please assign this issue to me?

**Comment by YashKamboj** [comment]
@Anosh21 , @developer-diganta is already working on it , you can look other issues with `help-wanted` tags.

**Comment by Anosh21** [comment]
Okay @YashKamboj

**Comment by leecalcote** [comment]
the year in the footer is 2022, currently, correct? is this issue still valid?

**Comment by leecalcote** [comment]
Assuming this is an invalid issue (@YashKamboj, please help figure this out in the future). Closing the issue. Let @YashKamboj know if I missed something and it needs to be reopened.

**Comment by YashKamboj** [comment]
Yeah invalid issue! , @leecalcote
