### ISSUE TITLE
Add DevConf talk to presentations list

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#659]
**Current State of the Meshery.io site**
List of presentations - https://meshery.io/talks-and-presentations

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by ashutosh887** [comment]
Should I work on this Issue @leecalcote ?

**Comment by adithyaakrishna** [comment]
Hey @ashutosh887 
This needs the access to slides and talks as well, I am working on this one 👀 
Please fell free to take a look at some other issues if interested and lmk if you want to work on any of them, I'll assign it to you (if it is unassigned though 😶 )
