### ISSUE TITLE
Add Coming Soon sign to Catalog

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#660]
**Desired State of the Meshery.io site**

Bad font - don't use - SVG - [coming-soon-patterns](https://user-images.githubusercontent.com/7570704/152087996-63c6dafe-314a-4599-b3de-35f6fe01b44f.svg)

PNG - [coming-soon-patterns](https://user-images.githubusercontent.com/7570704/152088060-ad808a2d-f38b-4844-b6c4-253eec817015.png)

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
The best that I could slap together in 6 minutes.

**Comment by warunicorn19** [comment]
That's really really red 😅
