### ISSUE TITLE
Not mobile friendly: service mesh catalog

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#664]
**Current State of the Meshery.io site**
The catalog on [meshery.io/catalog](http://meshery.io/catalog) is mobile challenged in two ways:

The catalog needs improvement to be mobile friendly both 1) in terms of the topmost patterns and filters icons/sections and 2) the catalog filters not displaying.

<img width="576" alt="Screen Shot 2022-02-03 at 8 56 23 PM" src="https://user-images.githubusercontent.com/7570704/152464824-1f07ad2c-553d-4031-a832-090f7914c409.png">

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
@leecalcote i've hidden the filters on purpose in the mobile-view

**Comment by akshitarora921** [comment]
@leecalcote, I can take this

**Comment by leecalcote** [comment]
@akshitarora921, sounds real good. 👍 

@warunicorn19, oh, I see. What do you recommend our next steps be toward the ability to filter in mobile view?

**Comment by warunicorn19** [comment]
If we want to move forward with filter in the mobile view, it should be collapsible, some like this.
![image](https://user-images.githubusercontent.com/53532328/152465907-40a9f011-f6fe-4663-81c6-ce372d8c1cde.png)

**Comment by ashutosh887** [comment]
@leecalcote I would like to work on this Issue if it's not done...

**Comment by ashutosh887** [comment]
Sure
I am working on this

**Comment by debo19** [comment]
@ashutosh887 any updates on this? Would you like to discuss this on the websites call today?

**Comment by ashutosh887** [comment]
@debo19 How may I join the Call?

**Comment by warunicorn19** [comment]
Hop on @ashutosh887 : meet.meshery.io/websites

**Comment by leecalcote** [comment]
Hi @ashutosh887, we missed you today. What progress can you report here? @YashKamboj, we might be in need of your assistance here.

**Comment by YashKamboj** [comment]
@ashutosh887 Do you need help with it????

**Comment by ashutosh887** [comment]
Yes @leecalcote @YashKamboj 
Needed some help in the setup of Project

**Comment by Nikhil-Ladha** [comment]
Any updates on the fix @ashutosh887 ?

**Comment by Akshit42-hue** [comment]
Hey @leecalcote, @Nikhil-Ladha Can I work on this issue

**Comment by Nikhil-Ladha** [comment]
Sure, go ahead @Akshit42-hue

**Comment by Nikhil-Ladha** [comment]
Ok, I just noticed there is an open PR from @ashutosh887 . Hold on @Akshit42-hue for a while.
Any updates on the PR @ashutosh887 ?

**Comment by Akshit42-hue** [comment]
Hey @Nikhil-Ladha should I go ahead and fix this bug

**Comment by Nikhil-Ladha** [comment]
Yes, @Akshit42-hue go ahead.

**Comment by YashKamboj** [comment]
@Akshit42-hue if you are not working on the issue, i added responsiveness to the catalog page in my pr (not dedicated to this issue) #703

**Comment by Akshit42-hue** [comment]
Go ahead @YashKamboj and thanks for taking it

**Comment by leecalcote** [comment]
@Akshit42-hue @Ardent10 there is an open need to clean up meshery.io/subscribe:
<img width="555" alt="Screen Shot 2022-05-05 at 7 41 21 AM" src="https://user-images.githubusercontent.com/7570704/166925283-9923ef6d-c9ae-431b-b5e5-ab08d54753c3.png">

**Comment by Akshit42-hue** [comment]
> meshery.io/subscribe
Looking into it

**Comment by Chadha93** [comment]
// @YashKamboj

**Comment by YashKamboj** [comment]
I guess this is no longer an issue, so we should close it, right? @asubedy @warunicorn19

**Comment by leecalcote** [comment]
It's not happening on my mobile phone any longer...
