### ISSUE TITLE
Fix mobile responsiveness of home page

### ISSUE THREAD

**Issue by debo19** [meshery/meshery.io#671]
**Description**
On the home page of meshery.io:

The "full catalog" link becomes too small in mobile view.
<img width="335" alt="Screenshot 2022-02-08 at 2 19 16 AM" src="https://user-images.githubusercontent.com/85789734/152869753-65f6124f-784e-4b14-b4b3-03e7ddc46502.png">

The button is not mobile-friendly.
<img width="481" alt="Screenshot 2022-02-08 at 2 18 11 AM" src="https://user-images.githubusercontent.com/85789734/152869766-44bea5a4-e322-4d97-b180-27a10d6ca999.png">

**Expected Behavior**

1. Make the link the same size as the rest of the text in mobile view.
2. Make the button mobile responsive. 

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by marpit19** [comment]
Hello everyone!!! Could I work on this issue?

**Comment by leecalcote** [comment]
hi @marpit19, yes, sounds great.

**Comment by marpit19** [comment]
Could you please review it @leecalcote
