### ISSUE TITLE
[UI] Add an entry for community handbook 

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery.io#673]
**Current State of the Meshery.io site**
No link/handbook is there for handbook on site.

**Desired State of the Meshery.io site**
Add a menu option for community handbook  under Community as a mega menu. option.
It should redirect the user to https://layer5.io/community/handbook
![Handbook link](https://user-images.githubusercontent.com/65453826/153219288-54bf649a-a378-44e7-a5a7-4db2b1f976ea.jpg)

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Chadha93

**Comment by warunicorn19** [comment]
@Chadha93  don't you think the drop down would become too long if we add another entry?

**Comment by Chadha93** [comment]
> @Chadha93 don't you think the drop down would become too long if we add another entry?

you can suggest any other place in the website :) how's this(lots of space here) in the footer.
![Screenshot from 2022-02-09 19-56-04](https://user-images.githubusercontent.com/65453826/153221062-00142c82-4c1f-463a-8d14-6a485dc65662.png)

**Comment by warunicorn19** [comment]
So the problem with adding the handbook here would be that it's the Meshery community handbook while this is the Meshery website. We want people to know that Meshery is a Meshery project but also want the 2 to be separate entities. So I think there's no need for anything to link back to the Meshery website. @leecalcote what do you think?

**Comment by leecalcote** [comment]
I'm not sure that this is desirable.

**Comment by Chadha93** [comment]
> I'm not sure that this is desirable.

Created this one because of this(we wan't community handbook link to spread across)?: https://app.clickup.com/t/1ydvcdq

**Comment by Akshit42-hue** [comment]
Should I work on it ?  @Chadha93
