### ISSUE TITLE
[UI] Loading animation for Calendar page

### ISSUE THREAD

**Issue by subhradwip01** [meshery/meshery.io#676]
**Current State of the Meshery.io site**

Currently, there is no Loading animation on the calendar page.

https://user-images.githubusercontent.com/88609894/153989609-63e220d2-4a8c-4829-b758-8b4c6dd30051.mp4

**Desired State of the Meshery.io site**

Need a loading animation for calendar page
---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by subhradwip01** [comment]
Resources for that animation:

**Comment by Sonichigo** [comment]
@subhradwip01 Can i take this up?

**Comment by subhradwip01** [comment]
@Sonichigo ya sure... @sayantan1413 can you assign him, please..I have not the access to assign him

**Comment by Sonichigo** [comment]
I am facing issue in bundle install part. Tried using 2.6.9 , 2.7.5 and 3.1.1 but each time i get this message: 

![image](https://user-images.githubusercontent.com/53110238/156702980-37270589-e29c-4769-a517-ba4c515cf61a.png)

But couldn't find 2.7.0 here : 
![image](https://user-images.githubusercontent.com/53110238/156703156-49ab6a22-43ed-4735-a66f-08074932bfe0.png)

**Comment by Nikhil-Ladha** [comment]
Which tool are you using to install `ruby`? @Sonichigo

**Comment by Sonichigo** [comment]
Not using any specific tool but from official ruby website. Found a workaround though. Have started working on Issue.
