### ISSUE TITLE
[Catalog] Expand Service Mesh Patterns catalog

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery.io#677]
**Description**
The current implementation of the catalog needs to be expanded to contain eBPF programs. 

**Expected Behavior**
Eventually, the catalog should also have the ability for the user to be able to directly import patterns into Meshery UI

**Screenshots**
<img width="1892" alt="Screen Shot 2022-02-15 at 12 23 43 PM" src="https://user-images.githubusercontent.com/53532328/154171416-da616f8d-ebd6-485b-98f4-3012e1e1ab81.png">

 **Additional Context**
More thoughts need to be put into Designing of the catalog for proper implementation. 

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by a-muk** [comment]
I would like to contribute to this project for GSOC'22. Are there any resources I can look at for knowing more about it?

**Comment by YashKamboj** [comment]
@a-muk You can check this out https://meshery.io/programs/gsoc

**Comment by Rahul7171** [comment]
Hi all. I am Excel, and I im interested in contributing to this project for GSoC '22. I have joined the community, and have been looking into Meshery too. I am thinking of attending the event that was posted on the community to get up to speed with Meshrey and Mesh Chaos in general.

Is this alright? And are there any prerequisites I need to complete to increase my chances, or to write a good proposal? Thank you!

**Comment by abh139** [comment]
I want to work on this issue

**Comment by leecalcote** [comment]
We need: to publish the collection into single pages, so that each asset in the catalog is addressable by single url.

**Comment by warunicorn19** [comment]
We could set an anchor to the modal right? That would help reference each asset. @leecalcote

**Comment by leecalcote** [comment]
@warunicorn19 poor seo; too fragile; too much for one page; we'll need pagination and single pages to follow anyway, particularly, since we're not able to figure out how to apply more than one filter to the view.

The answer to multiple filter views (on click) and to individual item pages requires no code, but only manipulation of the collection object and other settings in _config.yaml.

**Comment by leecalcote** [comment]
Moreover, we want individual contributors to bring their own catalog items and so we shouldn't make this contentious over a single data file or single page.

**Comment by YashKamboj** [comment]
What i found in other catalogs is that they have a modal for a item and an option to open them in a new page or something like read more , which results in opening the item in a new page
