### ISSUE TITLE
[Bug] : "join the community" button is getting cut 

### ISSUE THREAD

**Issue by Abhijay007** [meshery/meshery.io#684]
**Description**

on the community page the " "join the community" button is getting cut into half

**Screenshots** (currently)
![image](https://user-images.githubusercontent.com/64387054/159339853-8e4f8824-55d6-4acd-a668-e1a43260d869.png)

**Expected Behavior**

![image](https://user-images.githubusercontent.com/64387054/159340586-26b3146e-2424-4304-92b8-c66cfe0cc84d.png)

---
[Optional] **To Reproduce**

1. Go to 'https://meshery.io/community'
2. Click on '"join the community"'

[Optional] **Additional Context**

it will be great if we are able to replicate this page like this : https://layer5.io/community/members

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by sayan011** [comment]
Can I work on this issue?

**Comment by Abhijay007** [comment]
sure @sayan011 go ahead :)

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Abhijay007

**Comment by jjaw** [comment]
May I work on this issue? I can fix the button. @sayan011

**Comment by Abhijay007** [comment]
Hi @jjaw I have to assign this to @Akshit42-hue as he asked first, but you can try some other issues :) 

ping me if you need any assistance regarding finding issues or anything related to open-source contributions, you can join the meshery community by filling newcomers form( in case you haven't joined the community) , in the newcomer's channel there are a lot of good first issues on which you can work, join the community from here: https://meshery.io/community/newcomers

**Comment by Abhijay007** [comment]
> @Abhijay007 I found that issue here: https://twitter.com/goodfirstissue/status/1509224457201766415
> 
> Are there any other good beg/int issues?

ya, there are lot of good first issues, join the meshery community > in the newcomers channel on slack you will find some :)

**Comment by Akshit42-hue** [comment]
Please do have a look @Abhijay007
