### ISSUE TITLE
[UI] Enhancing the Newsletter 

### ISSUE THREAD

**Issue by Ardent10** [meshery/meshery.io#691]
#### Current Behavior

The newsletter has no color grading at the moment and looks odd.

#### Desired Behavior

It should be more distinct and catchy so that a user would be able to sign-up easily. 

#### Implementation

I would like to contribute to UI of this newsletter component as an OpenForce22 participant. 

# Mockups
## Before
![old](https://user-images.githubusercontent.com/73132031/158056524-fbc3d27d-0248-4d77-839f-e0879d342049.png)
## After
![newsletter](https://user-images.githubusercontent.com/73132031/158056531-603d80ee-fe3b-4d37-9f96-ea08d4c08476.png)

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Ardent10** [comment]
> Transfering the issue to the meshery.io repo, as the code for meshery.io lives there :)

Just wanted to know few things about the local installation: 
This is the first time I am working on a CNCF project. In the Meshery UI contribution we don't have a breif about what 'make' is. 
[https://docs.meshery.io/project/contributing/contributing-ui](url)

I don't have it pre-installed(windows) can you please tell me how can I get it installed to start working ?

**Comment by Nikhil-Ladha** [comment]
Meshery UI and meshery.io site are 2 different things. Don't mix them up.
Coming to your question `make` is a tool to run commands using a reference to a set of commands defined in the Makefile of the repo. Yes, you may not have the tool pre-installed in windows. You can download it and add it to your path and use it. If in case, you still get issues while running the make command locally, you can run the respective set of commands directly under that particular make command in the Makefile.

**Comment by Ardent10** [comment]
> Meshery UI and meshery.io site are 2 different things. Don't mix them up. Coming to your question `make` is a tool to run commands using a reference to a set of commands defined in the Makefile of the repo. Yes, you may not have the tool pre-installed in windows. You can download it and add it to your path and use it. If in case, you still get issues while running the make command locally, you can run the respective set of commands directly under that particular make command in the Makefile.

Thankyou I read about it and had it installed now.

**Comment by Ardent10** [comment]
@Nikhil-Ladha 
while serving the site locally I am trying to run this command and getting the following error. Is the semicolon a typo here or I am doing something wrong? 

![image](https://user-images.githubusercontent.com/73132031/164236702-796766f6-8c2b-442a-afe9-967256b8ccbd.png)
![image](https://user-images.githubusercontent.com/73132031/164236803-f273ccbf-ee8e-49f3-92e6-5aa3ec5dfc21.png)

**Comment by Nikhil-Ladha** [comment]
It is not a typo.
Try running the command on Powershell once. If it still doesn't work, execute the commands individually, i.e, first `bundle install` then `bundle exec jekyll serve --drafts --livereload`

**Comment by saucekode** [comment]
@Ardent10 are you developing it or working on the design?

**Comment by Ardent10** [comment]
> It is not a typo. Try running the command on Powershell once. If it still doesn't work, execute the commands individually, i.e, first `bundle install` then `bundle exec jekyll serve --drafts --livereload`

Thankyou for clarifying. 
I tried to run the commands one at a time and I get the following error

![image](https://user-images.githubusercontent.com/73132031/164282938-2e00b4a2-48e5-4c81-aa3b-0167d5fdf57e.png)
![image](https://user-images.githubusercontent.com/73132031/164282983-23cfd6d2-0540-49b0-8515-5d573a7e2a89.png)


I am trying to run this project on my local machine. I did all the installation that were ruby + bundle + gem.
Once I will get this project up and running on my local machine I will be making changes for the above design.

@saucekode I am new to the tech stacks used here. I am trying to run it on my local machine and then I will be working on the design.

**Comment by Nikhil-Ladha** [comment]
Yeah, known issue with Windows.
@Abhijay007 , @YashKamboj were you guys able to resolve the above issue?

**Comment by YashKamboj** [comment]
@Nikhil-Ladha i tried a lot but couldn't find the reason for the error

**Comment by Nikhil-Ladha** [comment]
@Ardent10 you will have to either switch to Linux totally or use WSL2, whichever you prefer.

**Comment by saucekode** [comment]
@Ardent10 okay. I wanted to be certain. When will you start working on the figma design?

**Comment by Ardent10** [comment]
@Nikhil-Ladha 
Why am I getting this error? 
Apart from this, whenever I try to change the css for the design the changes does not take place. The inline css works for the design but not the subscribe.css. 
![image](https://user-images.githubusercontent.com/73132031/164534699-57b950d9-051d-4642-a042-9aa3369ab212.png)
