### ISSUE TITLE
automate year

### ISSUE THREAD

**Issue by Akshit42-hue** [meshery/meshery.io#693]
The year in the footer section is not automate we have to change it manually

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Akshit42-hue** [comment]
My bad the year is already automate 
![Screenshot from 2022-04-10 09-39-26](https://user-images.githubusercontent.com/59443454/162601096-4423ffa0-4f50-4f7b-9c5e-67543e76f96c.png)

**Comment by leecalcote** [comment]
No sweat. While you're at it @Akshit42-hue, will you check on https://getnighthawk.dev, https://docs.meshery.io, and https://smp-spec.io?

**Comment by Akshit42-hue** [comment]
> No sweat. While you're at it @Akshit42-hue, will you check on https://getnighthawk.dev, https://docs.meshery.io, and https://smp-spec.io?

Let me check it

**Comment by Akshit42-hue** [comment]
https://docs.meshery.io/, and https://smp-spec.io/ looks good to me and in https://getnighthawk.dev/ raise an issue and will raise a PR as soon as possible @leecalcote
