### ISSUE TITLE
[Site] Update Service Mesh list

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery.io#694]
**Current State of the Meshery.io site**
![image](https://user-images.githubusercontent.com/65453826/163608722-0d4a7e8c-8b41-48c2-8941-5334619af49c.png)

**Desired State of the Meshery.io site**
Remove Octarine from the list and move cilium to beta

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by fazer1929** [comment]
I'd like to work on this issue.

**Comment by Chadha93** [comment]
> I'd like to work on this issue.

sure, go ahead @fazer1929

**Comment by harshitasao** [comment]
Hi, @Chadha93. Can I work on this if no one else is working?

**Comment by Chadha93** [comment]
> Hi, @Chadha93. Can I work on this if no one else is working?

Sure @harshitasao, are you still working on this @fazer1929?

**Comment by fazer1929** [comment]
> > Hi, @Chadha93. Can I work on this if no one else is working?
> 
> Sure @harshitasao, are you still working on this @fazer1929?

Oh yes, sorry I haven't yet created a PR, ill do it by tommorow
