### ISSUE TITLE
Add install instructions for Docker Extension for Meshery

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#702]
#### Current State
A Docker Extension for Meshery has been created and will be publicly available at DockerCon 2022.  A description of the extension and how to install it are needed. See https://layer5.io/docker-extension-meshery and https://hub.docker.com/r/meshery/docker-extension-meshery for details.

<img width="694" alt="Screen Shot 2022-05-03 at 5 49 53 PM" src="https://user-images.githubusercontent.com/7570704/166585632-50bf0e9d-75dc-4388-8954-e67cc66efca2.png">

#### Desired State
Add Docker Extension as a second option in the Docker deployment instructions.

```
docker extension install meshery/docker-extension-meshery:stable-latest
```

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by karnatisrinivas** [comment]
Hello @leecalcote ,If this is unassigned can I work on this? 

and is this related/same as https://github.com/meshery/meshery/issues/5473

**Comment by leecalcote** [comment]
@karnatisrinivas, right: two highly related issues. ✔️

**Comment by leecalcote** [comment]
Two related issues, but two different sites, so two updates needed.

**Comment by leecalcote** [comment]
@karnatisrinivas, heads-up: the deadline for this update is Sunday, May 8th, 2022. If a PR isn't submitted by the 7th, I'll carry this request forward.

**Comment by karnatisrinivas** [comment]
<img width="1259" alt="Screenshot 2022-05-07 at 9 55 37 AM" src="https://user-images.githubusercontent.com/52213014/167238111-84938370-ee73-4d1f-9623-55e99c4f81bd.png">

Hello Lee, Please let me know if this is the action required.

**Comment by leecalcote** [comment]
Looks good to me, @karnatisrinivas 👍
