### ISSUE TITLE
[Catalog] Create "related" pattern attribute

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#705]
**Current State of the Meshery.io site**
Each pattern modal will show related patterns, but these are hard-coded, self-references. 

**Desired State of the Meshery.io site**
The json data model needs to evolve to include a `related` attribute, so that pattern ids can be listed in an array.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by YashKamboj** [comment]
Working on it!!

**Comment by Chadha93** [comment]
// @YashKamboj

**Comment by leecalcote** [comment]
@asubedy will you please knock this out?
