### ISSUE TITLE
Copy to clipboard tooltip is not aligned / scroll always visible

### ISSUE THREAD

**Issue by chinmaym07** [meshery/meshery.io#715]
**Description**

1. `Copy to Clipboard` tooltip is not align properly
2. Scroll always visible.

**Expected Behavior**

1. `Copy to Clipboard` tooltip should be aligned properly.
2. Keep the scroll as `auto` like if the content exceeds then only it will be visible else remains hidden in the modal.

**Screenshots**

https://user-images.githubusercontent.com/44670961/171209794-8cd25020-c7d6-4914-be83-5a4160933c03.mp4

**Enviroment:**
 - OS:  Ubuntu
 - Browser: Chrome, firefox

---
[Optional] **To Reproduce**
1. Go to [Meshery Catalog](https://meshery.io/catalog)
2. Click on any card which will open a modal
3. Hover over `Copy Url` button.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Rohith-Raju** [comment]
Does this look good ? 
@chinmaym07 @theBeginner86 @leecalcote 
![image](https://user-images.githubusercontent.com/55309324/171559479-b6538705-c28f-4480-a6e0-150f4f117ed4.png)

**Comment by Rohith-Raju** [comment]
Removed unused white space aligned copy to clipboard tool-tip @leecalcote @theBeginner86 @chinmaym07 

https://user-images.githubusercontent.com/55309324/173629228-a75560d0-1d83-4315-bb0e-7ba3fa73bd2e.mp4

**Comment by chinmaym07** [comment]
Hi @Rohith-Raju .
Great work. Just a small tweak here.
It will be much better to keep the tooltip at the bottom rather than placing side by side .

**Comment by Rohith-Raju** [comment]
@chinmaym07 any particular reason? I aligned it to the side because there was a lot of unused space, as of now the height spans automatically, if we decide to add it to the bottom it will just take up more space  😄. What do you say?

**Comment by Rohith-Raju** [comment]
I also think that it's better if we try to fit the content rather than telling the user to scroll for more info.

**Comment by warunicorn19** [comment]
It wont be possible to have that much of information inside a modal especially in mobile without a scroll, we can hide the scrollbar but we can't remove it's functionality.
Currently I dont see a scrollbar in mobile view. 
Browser: Chrome
![image](https://user-images.githubusercontent.com/53532328/173714026-cf44fce7-6bc3-4b9a-acd4-e35f81985fc5.png)

**Comment by Rohith-Raju** [comment]
@warunicorn19   yes fixing on that

**Comment by leecalcote** [comment]
@Rohith-Raju i think that you have this one covered with n your upcoming PR…. @asubedy ?

**Comment by asubedy** [comment]
Yes @leecalcote  this will be covered once @Rohith-Raju PR gets merged, just one final image issue is left.
