### ISSUE TITLE
[Catalog] Categories for policies and programs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#729]
**Current State of the Meshery.io site**
The meshery.io/catalog lists OPA policies and eBPF programs as upcoming asset types.

**Desired State of the Meshery.io site**
The meshery.io/catalog should  have OPA and eBPF categories (radio buttons).

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by sumitshinde2608** [comment]
@leecalcote if @asubedy isn't working on this, I would like to work on it

**Comment by asubedy** [comment]
Sure @sumitshinde2608 you can work on this.

**Comment by sumitshinde2608** [comment]
thanks @asubedy.

**Comment by warunicorn19** [comment]
@sumitshinde2608 I think there's been some sort of a mix up, this issue has already been resolved. Sorry if you've already spent time on this, please feel free to take a look at the other open issues.

**Comment by sumitshinde2608** [comment]
@warunicorn19 Currently the OPA and eBPF buttons are not under the 'categories' tab as mentioned in the issue. I thought the desired state was putting these buttons in the 'categories' tab rather in the 'technology' section as there are now. Do correct me I am wrong

**Comment by warunicorn19** [comment]
No not exactly, this issue was just to add the radio buttons for OPA and eBPF, I understand the confusion since it says "categories" in the issue.

**Comment by sumitshinde2608** [comment]
Cool. I'll look for other issues. Thanks for clearing.

**Comment by leecalcote** [comment]
@sumitshinde2608, let us know if you don't find one and we'll help get you one.

**Comment by leecalcote** [comment]
@sumitshinde2608 here's one: the menu item should say "Cloud Native Catalog", not "Service Mesh Catalog":

<img width="1167" alt="Screen Shot 2022-07-05 at 8 21 47 AM" src="https://user-images.githubusercontent.com/7570704/177337798-ded32198-75fd-49e5-85c8-a26d3d84938e.png">

**Comment by sumitshinde2608** [comment]
Thanks @leecalcote. I ll update it. I also mentioned you in an open issue regarding Pagination - #732. I would like to work on it if it ain't done
