### ISSUE TITLE
[Catalog] Overview page should show all types of catalog items

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#730]
**Desired State of the Meshery.io site**
1. The meshery.io/catalog landing page should show all types of catalog items.
1. The total number displayed should be paginated and limited to 50 per page.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by asubedy** [comment]
@lee `1.` is done after [this](https://github.com/meshery/meshery.io/pull/744) PR gets merged

**Comment by leecalcote** [comment]
Is pagination still a to-do item?

**Comment by leecalcote** [comment]
@asubedy make a call for help?

**Comment by asubedy** [comment]
Yes I'll make an issue for the pagination. I can't seem to figure it out.

**Comment by asubedy** [comment]
Closing this issue, 1 is complete 2 is being tracked in https://github.com/meshery/meshery.io/issues/732
