### ISSUE TITLE
[Catalog] Search catalog items

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#731]
**Current State of the Meshery.io site**
Visitors of the https://meshery.io/catalog cannot search for items in the catalog.

**Desired State of the Meshery.io site**
Visitors should be able to match search terms found in the title or in the description of the catalog entry.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Rahul7171** [comment]
I would Like to Work On This issue

**Comment by leecalcote** [comment]
Help, help!

**Comment by leecalcote** [comment]
@shivaylamba, perhaps?

**Comment by leecalcote** [comment]
@shivaylamba?

@asubedy?

**Comment by shivaylamba** [comment]
Hi @leecalcote I will take a look at this issue. And let you know
