### ISSUE TITLE
[Catalog] Coming Soon sign over OPA and eBPF

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#733]
**Current State of the Meshery.io site**
The coming soon sign on https://meshery.io/catalog is hung off to the upper right hand side.

**Desired State of the Meshery.io site**
Meshery Patterns and WASM Filters are ready, while OPA Policies and eBPF Programs are not. The red sign should updated to remove the word "PATTERNS" and hang two, small instances of the sign on top of the op and ebpf categories.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Graphic - ![coming-soon](https://user-images.githubusercontent.com/7570704/173958472-39b3d485-a131-4c28-a232-0a77874794c4.svg)

**Comment by warunicorn19** [comment]
Added in my open PR.
