### ISSUE TITLE
Improvement: Menu Styling

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#739]
**Current State of the Meshery.io site**
The current navigation menu is less than attractive. Screenshot below:
<img width="492" alt="Screen Shot 2022-06-14 at 1 54 20 PM" src="https://user-images.githubusercontent.com/7570704/173678509-9fbc92e7-5459-429f-b11f-f1849a581b38.png">

**Desired State of the Meshery.io site**
The navigation menu might be prettified with a bit of rounded corners and shadow or something similar. This issue is to request a contributor to brainstorm and propose an improvement.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Manish-Rawat-1186** [comment]
i want to work on this issue, so may you assign me ...

**Comment by leecalcote** [comment]
Hi @Manish-Rawat-1186, sounds real good.

**Comment by Rohith-Raju** [comment]
@leecalcote if there is no assignee i would like to take it up

**Comment by leecalcote** [comment]
Great, @Rohith-Raju. Yes, brainstorming and proposals needed.

**Comment by leecalcote** [comment]
@Manish-Rawat-1186 any progress to report?

**Comment by Rohith-Raju** [comment]
Yup, sure @leecalcote

**Comment by Rohith-Raju** [comment]
Hey @leecalcote I was thinking along the lines of this 
![image](https://user-images.githubusercontent.com/55309324/175800953-6a2a254c-6208-4d19-a73b-8c5ec39c0699.png)
https://www.figma.com/file/STEeqbqIpC9MqjcFLpLqx9/Meshery.io-Dropdown?node-id=0%3A1

**Comment by sahilsuman933** [comment]
> Hey @leecalcote I was thinking along the lines of this ![image](https://user-images.githubusercontent.com/55309324/175800953-6a2a254c-6208-4d19-a73b-8c5ec39c0699.png) https://www.figma.com/file/STEeqbqIpC9MqjcFLpLqx9/Meshery.io-Dropdown?node-id=0%3A1

I think you can decrease the space between icons and text. it will look even better.

**Comment by Rohith-Raju** [comment]
Ok, @sahilsuman933

**Comment by Rohith-Raju** [comment]
@leecalcote  @sahilsuman933 This is what I came up with, we can change logos if it's not up to the mark, also any changes?
![image](https://user-images.githubusercontent.com/55309324/177033466-ffb59e6f-282e-40b0-8722-805370f3f04a.png)

**Comment by sahilsuman933** [comment]
@Rohith-Raju it is looking really good. But I think text are not aligned properly and it will be better without the share icon. 

What's your view on this @leecalcote

**Comment by Rohith-Raju** [comment]
Yup I was thinking the same @sahilsuman933 , @leecalcote ?

**Comment by leecalcote** [comment]
Clarification: the “share” icon is an external link icon, denoting which links will director visitors to another domain.

**Comment by sumitshinde2608** [comment]
Hey @Rohith-Raju I think the external link icon can be removed( if possible) and increase a font size(or rather weight) a bit to cover up the space

**Comment by Rohith-Raju** [comment]
Sure, I'll bring it up in my next meet 😄
