### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by debo19** [meshery/meshery.io#740]
**Description**
The font size for some text is too small. (See the last line in Getting Started or the text in the body in the following screenshots)

**Expected Behavior**
Increase the font size uniformly across the site.

**Screenshots**
<img width="530" alt="Screenshot 2022-06-15 at 2 11 34 AM" src="https://user-images.githubusercontent.com/85789734/173684998-74fc817d-73ff-4b78-8ba2-faf5fc659051.png">
<img width="543" alt="Screenshot 2022-06-15 at 2 11 18 AM" src="https://user-images.githubusercontent.com/85789734/173685006-1e34d605-3f01-4085-a066-b905abe95d7b.png">
<img width="816" alt="Screenshot 2022-06-15 at 2 11 08 AM" src="https://user-images.githubusercontent.com/85789734/173685010-e847f429-cfd5-47b4-a082-b5610383b816.png">

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Rohith-Raju** [comment]
I wouldn't mind knocking this out @debo19, unless it's for beginners.

**Comment by leecalcote** [comment]
Yes, this is relatively straight-forward. @Manish-Rawat-1186, how is this coming along for you?

**Comment by eeshaanSA** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/100678386/175295799-14484f90-03cb-44db-ba5b-74723372cbcc.png">

I believe something like this or on similar terms should do the job. Need more suggestions. @leecalcote @debo19

**Comment by debo19** [comment]
@eeshaanSA it still looks quite small

**Comment by eeshaanSA** [comment]
Sure. This is a snap from the chrome dev, and i had minimized the screen size so maybe thats why looks a little wierd. Allow me to work on this so i can improve on it.

**Comment by eeshaanSA** [comment]
Thanks @leecalcote. I would like to start working as soon as possible, but is there a guide/documentation to setup the code for meshery.io on the local system, and also how to run the local system as website on my own computer?

**Comment by eeshaanSA** [comment]
Thanks @leecalcote. Will start working on it ASAP.

**Comment by leecalcote** [comment]
@eeshaanSA, sounds great. I'll do your homework for you this one time and expect that you look in the conspicuous spots from here on out: 

1. https://docs.meshery.io/project/contributing/contributing-docs
2. https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website
3. https://github.com/meshery/meshery.io/blob/master/CONTRIBUTING.md
4. Jekyll Tutorial - https://docs.google.com/document/d/1JoPujIO_dyX3pTHvbGtQ5OBXERlSInac3ecLSkgFFSo/edit
5. Meshery Documentation Design Spec - https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit
6. Working with Meshery Docs and Jekyll - [Slides](https://docs.google.com/presentation/d/1GhJH3YF5mBeYX7I7ItEd-EbUmk1cnn3BdK1X230kwII/edit?usp=sharing)
[Recording](https://www.youtube.com/watch?v=PBq7mIPnPhM) - Tutorials table on https://meshery.io/community/newcomers

**Comment by eeshaanSA** [comment]
![image](https://user-images.githubusercontent.com/100678386/175559120-446c097b-7ff3-49bf-af63-6f3df72dd7e3.png)
This is the final version i propose. I shifted "choose a  platform" line below the relevant section. Also fixed the text size in the last line of the image. Under the 02 section.

**Comment by leecalcote** [comment]
Heads-up: we’ll accept and merge a PR that has a docs update regarding RVM and make on Windows, not one that doesn’t. :grin:

This proposed change looks great, @eeshaanSA. 👍 Will you take a moment to correct the aspect ratio (un-skew) the Docker logo, too?

**Comment by eeshaanSA** [comment]
If we make the aspect ratio similar to the other images, the docker logo will not look as appealing as it now. So we will have to either keep it as it is, or minimise the image so that it fits in a 60x60 aspect ratio like other images.

**Comment by eeshaanSA** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/100678386/175564846-46940173-dc0a-426c-8169-9ce022b759b6.png">
Something like this? You can have a comparision with the help of the image above.

**Comment by eeshaanSA** [comment]
Also, I had one more query. Since the issue #745 is very much related to this PR, is it ok/allowed to push commit for the solution of the issue #745 in this PR itself?
