### ISSUE TITLE
Title should be capitalized 

### ISSUE THREAD

**Issue by Rohith-Raju** [meshery/meshery.io#745]
**Current State of the Meshery.io site**
The title is not capitalized
![image](https://user-images.githubusercontent.com/55309324/175452867-073a916e-d307-4837-943c-dc162ea25cf6.png)

**Desired State of the Meshery.io site**
The title should be capitalized
![image](https://user-images.githubusercontent.com/55309324/175452839-119d951d-e76a-4631-90a2-9a2d31ed7b14.png)

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by eeshaanSA** [comment]
Thanks for pointing the issue out. I can submit a PR for this right away, though I propose that the first letter in line " cloud native management with plugins should also be Capitalised. Your thoughts?

**Comment by Rohith-Raju** [comment]
Yes, Please wait until a member approves of this and assigns it to you. 😄 
@debo19 @warunicorn19 @asubedy

**Comment by Rohith-Raju** [comment]
@leecalcote  Ok ill bring it down

**Comment by leecalcote** [comment]
@Rohith-Raju thanks for raising this sort of issue up, though. Keep 'em coming. 👍

**Comment by Rohith-Raju** [comment]
Aye Aye Cap
