### ISSUE TITLE
Changes in Docs which help with setting up local developer env.

### ISSUE THREAD

**Issue by eeshaanSA** [meshery/meshery.io#747]
**Current State:**
Downloading and setting up the developer enviorment for any project may sometimes prove as a difficulty for first timers/ beginners. The Contributing.md file and the readme.md in this repository are making it easy for developers to set up their local enviorments, though I feel there are some changes that I feel have to be made [in README.md, CONTRIBUTING.MD, and the Meshery Docs], and have to be personalised and tuned a little, especially for the **Windows** section.

**Changes Proposed**
- Changes in CONTRIBUTING.md, including a link to the exact doc page where the guide to installing meshery.io code on the local system can be found.
- Changes to README.md, including potentially known bugs and glitches, that users are currently facing while setting up Ruby, RVM and Make on Windows.
- Including a " Best Downloading Path for *Windows* section," in the Docs, because there are many options a user can follow, but only some prove efficient for Windows.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by eeshaanSA** [comment]
I would personally like to work on this issue, though I need a confirmation and more information about the same from maintainers/admins, before I can start working with it.
@leecalcote

**Comment by Rahul7171** [comment]
I would Like to work on this Issue

**Comment by eeshaanSA** [comment]
These changes are subjective, and are dependant on third party software; and hence not necessary. The decision was taken in the Websites Meeting (4/07/2022). 
Marking as closed.
