### ISSUE TITLE
Delete generic "pricing" page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#748]
**Current State of the Meshery.io site**
https://meshery.io/archive/pricing/ is a holdover from the original theme used for this site.

**Desired State of the Meshery.io site**
This page should be deleted.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Santosh1176** [comment]
@leecalcote  Can I work on this?

**Comment by Santosh1176** [comment]
@leecalcote There seems to be some confusion here. @LewSplenda raised the PR to this issue.

**Comment by LewSplenda** [comment]
Can you explain what PR stands for? if I need to fix/remove anything let me know! I didn't mean to cause any issues or confusion.

**Comment by Santosh1176** [comment]
> Can you explain what PR stands for? if I need to fix/remove anything let me know! I didn't mean to cause any issues or confusion.

This is about the [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) you raised where you needed to add the issue number which this PR fixes in the Template which helps in tracking the status of the issue.

**Comment by leecalcote** [comment]
Here we are - https://github.blog/2013-05-14-closing-issues-via-pull-requests/

**Comment by LewSplenda** [comment]
Okay I will get this done! Thank you so much for your help. Still learning the ways!
