### ISSUE TITLE
[Docs] Basic Step Skipped in Installation/Running in Local Environment 

### ISSUE THREAD

**Issue by manikmmalhotra** [meshery/meshery.io#753]
**Current State of the Meshery.io site**
installation and running in local environment is missing a basic step

**Desired State of the Meshery.io site**
```cd meshery.io```
needs to be added after cloning the repo

i would like to work on this small issue.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Thanks
