### ISSUE TITLE
[Docs] Missing a "git" in the command

### ISSUE THREAD

**Issue by manikmmalhotra** [meshery/meshery.io#755]
**Current State:**
while signing commit message the command mentioned in readme is missing a "git"

**Desired State:**
```git commit -s -m “my commit message w/signoff” ```

i would like to work on this issue
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Fixed
