### ISSUE TITLE
Cncf page in meshery.io would look better when Aligned

### ISSUE THREAD

**Issue by manikmmalhotra** [meshery/meshery.io#757]
**Current Behavior**

In https://meshery.io/programs/meshery/cncf the content are not aligned properly, 

**Desired Behavior**

all the content after properly aligned will give more better look

**Screenshots / Mockups**

![Screenshot from 2022-07-04 15-18-48](https://user-images.githubusercontent.com/63007399/177129875-7ee2c508-1403-4d29-9f3b-1a91f4f645fd.png)

**Alternatives**

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

i would like to sove this issues

**Comment by eeshaanSA** [comment]
Hi manik. Could you please annotate/mark the area where you feel the problem is in the screenshot?

**Comment by manikmmalhotra** [comment]
@Chadha93 need your suggestion here

**Comment by Chadha93** [comment]
> @Chadha93 need your suggestion here

@manikmmalhotra What alignment issues are you highlighting? Please propose your suggestions in the PR description for specific alignments of components.

**Comment by manikmmalhotra** [comment]
@Chadha93 aligning as shown in the screenshot
![757](https://user-images.githubusercontent.com/63007399/178304727-71993d25-bd6a-45de-8dd8-d59a520f0dca.png)

**Comment by sourav-sharma7** [comment]
![Screenshot from 2022-07-29 14-17-38](https://user-images.githubusercontent.com/78010922/181721793-ba0a5323-0a98-44c9-8e80-276460ec6006.png)

@manikmmalhotra @Chadha93 
is this what we are trying to achieve ?

**Comment by Chadha93** [comment]
// @warunicorn19 views...

**Comment by warunicorn19** [comment]
The proposed solution looks good. @manikmmalhotra @sourav-sharma7

**Comment by manikmmalhotra** [comment]
@warunicorn19 yes, great work @sourav-sharma7
