### ISSUE TITLE
[UI] Incorrect copy url when clicked on copy url button 

### ISSUE THREAD

**Issue by Rohith-Raju** [meshery/meshery.io#760]
**Description**
`Download  Copy URL Copy to clipboard `  is what users get when clicking on Copy URL on an item in the Cloud Native Catalog.
The problem persists only in newly added wasm filters.

**Expected Behavior**
The correct URL should be copied to the clipboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/55309324/177463374-63ca9c31-0c1b-4aec-af98-36cfbe152fa1.png)

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**
Steps to reproduce the behaviour:
1. Go to  Cloud-Native Catalog 
2. Click on any  Wasm filter
3. Click on copy URL 

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@Rohith-Raju are you taking this on?

**Comment by Rohith-Raju** [comment]
Yes, I am @leecalcote

**Comment by legendarykamal** [comment]
hi, @Rohith-Raju are you still working on this issue?

**Comment by Rohith-Raju** [comment]
@legendarykamal, Was working on catalog but didn't really get to this. Do you want to take this up?

**Comment by legendarykamal** [comment]
yes @Rohith-Raju I saw you were quite into much things, Yes I will take this up :)

**Comment by Rohith-Raju** [comment]
Sure @legendarykamal all yours!
