### ISSUE TITLE
Represent Meshery's broader management capabilities

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#764]
**Current Behavior**
Meshery manages all kinds of cloud native infrastructure. Branding it as a service mesh manager only misrepresents the full-breadth of its capabilities.

**Desired Behavior**
Replace most, but not all, instances of "service mesh" with "cloud native". Examples: "service mesh manager", "service mesh management plane", "multi-mesh manager", "multi-mesh management plane"... these should be replaced with "cloud native manager".

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by eeshaanSA** [comment]
I would like to work on this issue. We had a talk about this in the sites meeting too.

**Comment by leecalcote** [comment]
Thanks, @eeshaanSA. Sounds real good.

**Comment by eeshaanSA** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/100678386/178148642-619fa07e-003e-45a5-9535-8410ffdd2255.png">

Would a change here be appropriate?

**Comment by leecalcote** [comment]
Yes, @eeshaanSA. How are you progressing the rest of this issue?

**Comment by eeshaanSA** [comment]
> Yes, @eeshaanSA. How are you progressing the rest of this issue?

Pretty well. I have been thinking of various methods we can use to find all/most of the instances where correction is needed. 
I am also going to discuss this issue in the upcoming websites call, hoping for some help regarding the same.

**Comment by harkiratsm** [comment]
@eeshaanSA you can checkout this [pr](https://github.com/meshery/meshery/pull/5805) to get a understanding on what changes are required.

**Comment by eeshaanSA** [comment]
Thanks @leecalcote for referencing @harkiratsm. Thanks for the link to the PR. I have gotten a rough idea in my mind now. Will push a few commits soon, to atleast get started with this issue.

**Comment by eeshaanSA** [comment]
@harkiratsm would you like to collaborate though? I wouldn't mind. 😄

**Comment by leecalcote** [comment]
@eeshaanSA, that’s good. We’re 9 days into the issue. We’re in need of having it completed. Let’s set 5pm IST on Sunday (tomorrow) as the deadline to have this issue completed in-full. I’ll reassign after this point. If this timeframe is too tight, don’t sweat it. We’ll find you another issue.

**Comment by eeshaanSA** [comment]
> @eeshaanSA, that’s good. We’re 9 days into the issue. We’re in need of having it completed. Let’s set 5pm IST on Sunday (tomorrow) as the deadline to have this issue completed in-full. I’ll reassign after this point. If this timeframe is too tight, don’t sweat it. We’ll find you another issue.

No worries, will have it done. 😄
I have already linked a PR for the same, need suggestions there @leecalcote .
