### ISSUE TITLE
[Docs] Lorem ipsum on Wasm Filter

### ISSUE THREAD

**Issue by Rohith-Raju** [meshery/meshery.io#768]
**Current State:**
The content is filled with lorem ipsum text 
![image](https://user-images.githubusercontent.com/55309324/178091721-09230414-c3d2-4882-bd19-be66aae8174b.png)

**Desired State:**
Content should be updated with the required information.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by bhargavmungara** [comment]
Hi @Rohith-Raju, Can i solve this issue Please assign it to me.

**Comment by subhamgcon** [comment]
Is this issue open for working? @Rohith-Raju , if yes can I work on it?

**Comment by Rohith-Raju** [comment]
Yes, @bhargavmungara all yours !!

**Comment by Rohith-Raju** [comment]
@subhamgcon Please be on the lookout for any other issues. I'll try finding you one 😄

**Comment by bhargavmungara** [comment]
@Rohith-Raju  Can you tell where to find the information to be updated with

**Comment by Rohith-Raju** [comment]
@bhargavmungara Slack is your best friend, just ask and people will get back to you.

**Comment by bhargavmungara** [comment]
Thank You @Rohith-Raju. I am super new to this repo. So,it would be better to assign this issue to @subhamgcon. Meanwhile i will get familiar with how this repo working and where to communicate about things.

**Comment by legendarykamal** [comment]
@Rohith-Raju if possible I would love to work on
This, I have explored Meshery a bit. 
If @subhamgcon doesn't have any problem then do assign to me.

**Comment by subhamgcon** [comment]
I would love to work on this issue! @bhargavmungara @Rohith-Raju.

**Comment by Rohith-Raju** [comment]
Sounds good @subhamgcon. All yours.

**Comment by subhamgcon** [comment]
Thanks for assigning the issue @Rohith-Raju. It would be really helpful if you describe the issue to me a little bit so that I can start working on it. Thank you.

**Comment by Rohith-Raju** [comment]
Sure @subhamgcon, First head over to [meshery catalog](https://meshery.io/catalog). Click on one of the wasm filters. As you can see that there is some filler text( which doesn't make sense ). You'll have to replace that text with the actual content. 😄

**Comment by Rohith-Raju** [comment]
@subhamgcon any updates?

**Comment by eeshaanSA** [comment]
@Rohith-Raju, i dont mind taking this up real quick, unless its for ones who are just starting out?

**Comment by eeshaanSA** [comment]
sure, thanks @Rohith-Raju!
Can you or anyone fill me in with the content to be replaced? maybe @leecalcote can.

**Comment by acald-creator** [comment]
ack, will work on this

**Comment by leecalcote** [comment]
Thank you, @acald-creator. A few markdown updates will do the trick.
