### ISSUE TITLE
[Catalog] Small-sized video displayed

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#771]
**Description**
Only a thumbnail of the video displays.

**Expected Behavior**
Full-sized video should display.

**Screenshots**
<img width="1203" alt="Screen Shot 2022-07-14 at 2 18 15 PM" src="https://user-images.githubusercontent.com/7570704/179066104-2f4dc824-4b3c-4aed-b358-a82718ea63a3.png">

**Enviroment:**
 - Browser: Safari

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
Safari specific

**Comment by manikmmalhotra** [comment]
i would like to try this

**Comment by warunicorn19** [comment]
Go ahead @manikmmalhotra. Before you start looking into this though, do have access to safari?

**Comment by manikmmalhotra** [comment]
yea i've access to safari
