### ISSUE TITLE
[Catalog] Improve ease by which modal can be dismissed

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#772]
**Current Behavior**
Users have to hunt for the small X to close the modal.

**Desired Behavior**
Users can click anywhere outside of the modal to dismiss the modal. 

**Screenshots / Mockups**
<img width="1162" alt="Screen Shot 2022-07-14 at 2 23 35 PM" src="https://user-images.githubusercontent.com/7570704/179066729-0904a634-437d-4d99-9e19-73f04f4a9ce0.png">

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
I'm just seeing https://github.com/meshery/meshery.io/pull/767. // @Rohith-Raju

**Comment by Rohith-Raju** [comment]
@leecalcote, I could fix it, but I have no access to safari to experiment and resolve the issue.

**Comment by leecalcote** [comment]
@manikmmalhotra ?

**Comment by manikmmalhotra** [comment]
@leecalcote yea I'll work on this too
