### ISSUE TITLE
[Catalog] Contributor Instructions

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#773]
**Current State of the Meshery.io site**
Missing contributor instructions on how to add an item.

**Desired State of the Meshery.io site**
"Have a design pattern to share? [Add yours to the catalog]." - add this sentence adjacent to the Meshery import instructions.

<img width="1127" alt="Screen Shot 2022-07-14 at 2 45 59 PM" src="https://user-images.githubusercontent.com/7570704/179070398-ac01f901-7572-4add-8faa-9e5c41cfa96a.png">

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
Yes I will complete today.

**Comment by warunicorn19** [comment]
@leecalcote should this link to the ISSUE TEMPLATE that I've made for the catalog?

**Comment by leecalcote** [comment]
I would rather than people are directly contributing instead of opening issues for maintainers to update on their behalf.
