### ISSUE TITLE
[Catalog] Item Modal: Horizontally-wrap compatibility list in responsive mode

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#774]
**Desired Behavior**
<img width="469" alt="Screen Shot 2022-07-14 at 2 58 20 PM" src="https://user-images.githubusercontent.com/7570704/179074103-904e36bc-e9b0-4124-a789-343f946dd866.png">

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Rohith-Raju here's a follow up issue post-merge of your current catalog PR.

**Comment by Rohith-Raju** [comment]
Sure @leecalcote
