### ISSUE TITLE
[Site] Change the background color of the menu similar to the Docs website

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery.io#778]
**Current State of the Meshery.io site**
Currently the menu  of individual pages in meshery.io site has this background color
![image](https://user-images.githubusercontent.com/51183483/179243848-8fdc3806-b948-43a1-93cf-211fb1c59c26.png)

**Desired State of the Meshery.io site**
Change the background color of the menu similar to https://docs.meshery.io 
![image](https://user-images.githubusercontent.com/51183483/179244048-8314f0a0-6144-41ab-9fde-15b2c1665ae3.png)

---
### Contributor Resources

Meshery docs can be found at this repository https://www.github.com/meshery/meshery

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Santosh1176** [comment]
@asubedy Can I work on this?

**Comment by asubedy** [comment]
Sure @Santosh1176 🚀

**Comment by lodenrogue** [comment]
From what I can tell this is the solution:

```
header.header-background {
    background: rgb(57, 80, 84);
}
```

**Comment by lodenrogue** [comment]
If @Santosh1176 is not able to complete this let me know and I'll try to add the fix.
