### ISSUE TITLE
[UI] Navbar Overrides the Catalog Heading and Catalog Item text overflows the card

### ISSUE THREAD

**Issue by echo-sg** [meshery/meshery.io#783]
**Description and Expected Behaviour**
There are some bugs with the current UI on the web. They are listed as follows:
- Navbar overrides the Heading.
Heading should be clearly visible and there should be space between navbar and heading.
![image](https://user-images.githubusercontent.com/56088056/179977924-98a16a62-4949-4e48-bf67-c82481a0be5f.png)
- Card Name overflows outside the card for longer texts.
Card name text should be wrapped inside the card
![image](https://user-images.githubusercontent.com/56088056/179978889-c9c6f7e5-35a1-4ecb-aec0-4bb88ad32431.png)

**Enviroment:**
 - OS: Ubuntu
 - Browser: Chrome
 - Device: laptop

### Contributor Resources

**Comment by manikmmalhotra** [comment]
@echo-sg it's working fine on my system, can you specify the aspect ratio for this ?

**Comment by echo-sg** [comment]
Aspect ratio is 16:9
Screen resolution: 1920x1080 pixels
Browser's inner resolution: 1920x920 pixels
