### ISSUE TITLE
Responsiveness lagging on the catalog section

### ISSUE THREAD

**Issue by manikmmalhotra** [meshery/meshery.io#784]
**Description**
A brief description of the issue.
the responsive design of the meshery.io/catalog has some bugs as shown in the image below:

**Expected Behavior**
A brief description of what you expected to happen.
the logos shouldn't be cropped when in responsive form
**Screenshots**
Add screenshots, if applicable, to help explain your problem.
![WhatsApp Image 2022-07-23 at 3 05 29 AM](https://user-images.githubusercontent.com/63007399/180572275-68335120-b899-4efd-86d6-db8d895c6840.jpeg)
**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**
1. Go to 'meshery.io/catalog'
2. See error when switched to mobile format

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Rohith-Raju** [comment]
Yes @manikmmalhotra, I'm working on it. Thanks for creating the issue 😄

**Comment by manikmmalhotra** [comment]
sure @Rohith-Raju lemme know if i could help

**Comment by Rohith-Raju** [comment]
Sure @manikmmalhotra, I'll ask for help if I need any. 😄

**Comment by leecalcote** [comment]
@Rohith-Raju should we reassign? @asubedy can you pick this up?

**Comment by Rohith-Raju** [comment]
@leecalcote is almost done actually, I'll demo this at today's meeting and get it merged if everything is ok.
