### ISSUE TITLE
[Catalog] Improve display of prev / next item links

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#786]
**Current Behavior**

<img width="1090" alt="Screen Shot 2022-07-25 at 7 59 51 AM" src="https://user-images.githubusercontent.com/7570704/180880791-606a252d-8830-48a4-b951-113f43c446db.png">

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rohith-Raju** [comment]
@leecalcote , @warunicorn19 I think I already addressed this in my upcoming [pr](https://github.com/meshery/meshery.io/pull/767)
![image](https://user-images.githubusercontent.com/55309324/181238589-d0d3ddf9-1fbc-4aa0-bdab-421e7b42bf22.png)

**Comment by Rohith-Raju** [comment]
@leecalcote @warunicorn19 The catalog pr is merged 😄
