### ISSUE TITLE
Fix typos in meshery Catalog page

### ISSUE THREAD

**Issue by Rohith-Raju** [meshery/meshery.io#788]
**Description**
Check for typos and fix them. One of which is 
![image](https://user-images.githubusercontent.com/55309324/181236595-d457964a-472a-4dbb-aada-e636464e34dc.png)

**Expected Behavior**
Fix typos 

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by manikmmalhotra** [comment]
@Rohith-Raju i'll work on this one

**Comment by Rohith-Raju** [comment]
Sure @manikmmalhotra

**Comment by rakshitgondwal** [comment]
Hey @Rohith-Raju 
Can i work on this issue too?
