### ISSUE TITLE
[Catalog] Create a reusable modal component. 

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery.io#790]
**Current Behavior**
With our current approach, we have to create a new modal component every time we need to put something in a modal.

**Desired Behavior**
There should be a reusable modal component that can be used everywhere.

**Screenshots / Mockups**

**Alternatives**

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@Rohith-Raju @manikmmalhotra @asubedy any one of you guys want to pick this one up??

**Comment by manikmmalhotra** [comment]
@warunicorn19 I can work on this

**Comment by asubedy** [comment]
@warunicorn19 aren't we using this already we have a `modal.html` file inside include which we are using to show the modal on all cases.

**Comment by asubedy** [comment]
Oh ok a modal component for the entire Meshery.io page. got it

**Comment by warunicorn19** [comment]
Please go ahead @manikmmalhotra

**Comment by manikmmalhotra** [comment]
@warunicorn19 any designs for this ??

**Comment by warunicorn19** [comment]
Nope no designs, the modal should be customizable according to its need.
