### ISSUE TITLE
[Site] Remove the extra LFX text 

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery.io#791]
**Description**
Remove the extra LFX text 
![bug](https://user-images.githubusercontent.com/65453826/181832216-652d3272-d497-4c06-a626-e0c99cfe2210.png)

**Expected Behavior**
Just keep the LFX logo, remove the extra text highlighted. 

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by legendarykamal** [comment]
@Chadha93 may I take on this?

**Comment by Chadha93** [comment]
> @Chadha93 may I take on this?

All yours @legendarykamal

**Comment by mihir2226** [comment]
May I land hand to this project

**Comment by kamalbuilds** [comment]
hi @mihir2226  this has been completed but you might want to try your hands on many good first issues waiting for you like this one https://github.com/meshery/meshery/issues/2991
