### ISSUE TITLE
Change background color of Header Navbar in getting started page

### ISSUE THREAD

**Issue by Santosh1176** [meshery/meshery.io#803]
#### Current State of the Meshery.io site

Currently, the background color of the Navbar in the [Getting Started](https://meshery.io/#getting-started) page has a dark background color.
![meshery-todo](https://user-images.githubusercontent.com/91916466/183722525-0d1d1342-eef4-4033-b525-ed66a983f85f.png)

#### Desired State of the Meshery.io site

To maintain consistency, change the background color similar to [this page](https://meshery.io/catalog).

![meshery-desired](https://user-images.githubusercontent.com/91916466/183722961-29384db0-79c5-4af1-8c63-d67c4e5cf3ba.png)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sourav-sharma7** [comment]
Hi @Santosh1176 Can You please assign me this issue I would like to work on this one

**Comment by sourav-sharma7** [comment]
![Screenshot from 2022-08-11 19-51-59](https://user-images.githubusercontent.com/78010922/184155740-37354d83-781c-4288-82d6-1ffce90c89d3.png)
Is this what we are trying to achieve

**Comment by Santosh1176** [comment]
@sourav-sharma7 Thank you for asking. A member will shortly assign you this task. Meanwhile, you can checkout the background Color for [Meshery docs](https://docs.meshery.io/), that’s the desired outcome.

**Comment by eeshaanSA** [comment]
Would like to work on this issue, I have made some changes to the getting started section before, so I have an idea about what needs to be done.

**Comment by sourav-sharma7** [comment]
Hi @eeshaanSA I was working on this issue for quite a while and will be making a PR today. Thanks for volunteering can I help you to find a different issue.

**Comment by eeshaanSA** [comment]
@sourav-sharma7 no problem. I can volunteer to help if you need any. Let me know. Also make sure the issue is approved before you start working on it.

**Comment by sourav-sharma7** [comment]
Thanks a lot @eeshaanSA will make sure of that.

**Comment by warunicorn19** [comment]
This is by design, there's no need for change here. We want the Getting Started section to stand out.
