### ISSUE TITLE
Meshery catalog site text overwrite 

### ISSUE THREAD

**Issue by sourav-sharma7** [meshery/meshery.io#804]
#### Description

Text overwrite and program catalog item is cropped in mobile view of site

#### Expected Behavior

suitable space to avoid overwrite and cropped program icon fixed  

#### Screenshots

![WhatsApp Image 2022-08-13 at 5 24 24 PM](https://user-images.githubusercontent.com/78010922/184493350-f225a39b-5757-4b88-b770-b8196591e31f.jpeg)

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by YashKamboj** [comment]
Already an open pr @sourav-sharma7
