### ISSUE TITLE
[UI] Consistency in Button Width on Landing Page

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [meshery/meshery.io#805]
#### Description
The Buttons linking to other pages on the Landing page are of inconsistent width.

#### Expected Behavior
Consistent Width for all Buttons on the Main Page

#### Screenshots
![image](https://user-images.githubusercontent.com/70568620/184533208-58582db1-3f66-432c-b7a3-f89f9f2b2ae9.png)

#### Environment:
 - OS: Windows
 - Browser: Chrome
 - Version: 103.0.5060.134 (Official Build) (64-bit)
 - Device: Desktop

#### Expected Behaviour/Look:
![image](https://user-images.githubusercontent.com/70568620/184533347-9195a57b-40d9-42a0-a72d-28558f149580.png)

---

**Comment by Prathamesh-Shanbhag** [comment]
If this issue gets approved I would like to work on it!

**Comment by leecalcote** [comment]
@Prathamesh-Shanbhag thanks for this. Will you propose a solution? "Consistent width" as a solution means cutting off half of the text or...?

**Comment by Prathamesh-Shanbhag** [comment]
Nope not at all, we keep the text as is: Only introduce a Max-width property for the text which also works perfectly on the Mobile version of the website

**Comment by vedant-kakde** [comment]
@leecalcote any updates on this issue?

**Comment by leecalcote** [comment]
Oh, I see. Not so much width, but consistent padding/margin. Yes, that'd be great. Please do proceed, @Prathamesh-Shanbhag, @vedant-kakde 👍

**Comment by Prathamesh-Shanbhag** [comment]
Thank you @vedant-kakde ,
@leecalcote I have fixed the issue.
Now the buttons have consistent padding across the page.
