### ISSUE TITLE
Fix missing spaces on meshery.io homepage

### ISSUE THREAD

**Issue by eeshaanSA** [meshery/meshery.io#806]
#### Current State of the Meshery.io site

On the home page, the text under the Patterns section misses a space bar.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/100678386/185167097-28f9dfc7-ac29-4483-8480-97740060b3e2.png">

#### Desired State of the Meshery.io site

<img width="305" alt="image" src="https://user-images.githubusercontent.com/100678386/185168623-2d20aabd-e7f9-4dac-a97f-a69cadb8e421.png">

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by eeshaanSA** [comment]
Would like to fix this myself.

**Comment by bhavyastar** [comment]
I would like to work on this issue.

**Comment by eeshaanSA** [comment]
Issue fixed.
