### ISSUE TITLE
Add Spire logo on public facing Design catalogue

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery.io#807]
**Current Behavior**

Currently on the IstioSpire design, we do not show the Spire logo on the card https://meshery.io/catalog

**Desired Behavior**

A spire logo should be added 
**Screenshots / Mockups**

**Alternatives**

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mharshita** [comment]
@Revolyssup Can I work on this issue?

**Comment by leecalcote** [comment]
@mharshita, yes, please. See @asubedy, if you have questions.

**Comment by mharshita** [comment]
Sure, Thankyou!

**Comment by mharshita** [comment]
Hi @asubedy! I had a few doubts. Can you please check slack DM?

**Comment by mharshita** [comment]
Hi @Revolyssup! I have made the changes but I am not sure about the position of both logos. Can you please confirm if this is the desired result?
<img width="1180" alt="Screenshot 2022-08-21 at 11 55 14 PM" src="https://user-images.githubusercontent.com/60281688/185805546-51ceea0b-de4d-4b89-a97d-ac9e8b9efff4.png">
<img width="872" alt="Screenshot 2022-08-21 at 11 55 27 PM" src="https://user-images.githubusercontent.com/60281688/185805554-4df80df3-be7c-437c-a921-edac5430bc36.png">

**Comment by asubedy** [comment]
@mharshita , this is not the desired result. We want the Istio + Spire logo only on the Istion and Spire card. So logo change on just this card 
<img width="255" alt="image" src="https://user-images.githubusercontent.com/51183483/185863437-2395cd75-9a68-46f7-b68f-93461359dcc3.png">


Here you should add the Istio and Spire logo instead of the pattern logo (the dots and line) and leave others as it is.

**Comment by mharshita** [comment]
I have made a PR. Please review.
<img width="294" alt="Screenshot 2022-08-22 at 7 16 11 PM" src="https://user-images.githubusercontent.com/60281688/185937288-dda7b8ae-456a-4508-ab22-ab4544e98d8c.png">
