### ISSUE TITLE
Typo Fix

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#810]
While looking at the Meshery website I saw a typo under the heading Operate with configuration best practices i.e  **Operational** is misspelled **(oprational)**
![Screenshot (450)](https://user-images.githubusercontent.com/67385503/185976835-1046dc37-7b53-49fa-84f7-20576856a3d6.png)

I would love to fix this typo

**Comment by warunicorn19** [comment]
Go ahead @UtkarshMishra12
