### ISSUE TITLE
[UI] Modifying Navbar dropdown such that it takes full width in mobile view

### ISSUE THREAD

**Issue by srrathi** [meshery/meshery.io#812]
#### Current Behavior
Navbar dropdown doesn't take full width in mobile view and looks a bit weird.

![Screenshot from 2022-06-07 02-05-36](https://user-images.githubusercontent.com/57089237/172206986-d7ecc5dc-e462-45b1-bfeb-40d6ce04a21f.png)

#### Desired Behavior
To modify Navbar dropdown in meshery.io UI such that it takes full width in mobile view with it's items aligned to left. After clicking on Menu the dropdown will roll down from bottom taking full width and items aligned in left side

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by tinniaru3005** [comment]
Hey I would like to work on the issue. Can you please assign it to me?

**Comment by legendarykamal** [comment]
yes, please go ahead .

**Comment by leecalcote** [comment]
@tinniaru3005 I believe that the only reloading issue here is that of menus not opening on click of the menu title. The issue of menu width has already been takin care of. 

https://user-images.githubusercontent.com/7570704/198832535-e923e3ca-5b0f-4a5d-b43b-173450364b11.MOV

**Comment by tinniaru3005** [comment]
Hey @leecalcote, okay I got it. Will work on it. Thanks :)

**Comment by tinniaru3005** [comment]
Hey @leecalcote, I have solved the issue. Can you please look into the PR?

**Comment by tinniaru3005** [comment]
Hey I am working on it

**Comment by eeshaanSA** [comment]
@tinniaru3005 how far are we from having this merged?

**Comment by tinniaru3005** [comment]
> @tinniaru3005 how far are we from having this merged?

Hey the issue is solved but some more changes have been discussed to make to drop down look good. I have my exams. I will work on it on Saturday and Sunday. So on Monday I can show the changes in the meet and if everyone agrees then it can get merged. The extra changes discussed are
[Slack message link](https://meshery.slack.com/archives/C015QJKUMPU/p1669656847983969)

**Comment by tinniaru3005** [comment]
The issue is solved. The PR is also approved and can be merged.
