### ISSUE TITLE
Twitter feed on the footer is overflowing

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery.io#817]
#### Description

https://user-images.githubusercontent.com/51183483/186899420-79336125-e29d-4cb4-ab62-f60765988a12.mov

#### Expected Behavior

Fix the height of the twitter feed. Reference: https://smp-spec.io
#### Enviroment:
 - OS: Mac 
 - Browser: Safari
 - Version: 
 - Device: Desktop

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
Jekyll 😃 Pls assign me to fix this 🔧

**Comment by asubedy** [comment]
Sure, here you go 🚀

**Comment by leecalcote** [comment]
@asubedy @legendarykamal I'm not able to reproduce this issue in Safari. Is this a Chrome-specific issue?

**Comment by asubedy** [comment]
I guess we can close this 😅 , the issue has been miraculously solved

**Comment by leecalcote** [comment]
It’s a miracle!
