### ISSUE TITLE
Fix program name on meshery.io/programs page

### ISSUE THREAD

**Issue by vedant-kakde** [meshery/meshery.io#820]
#### Current State of the Meshery.io site
![image](https://user-images.githubusercontent.com/69970950/187040604-6d05772e-8c80-4179-9def-09a57c9290db.png)

#### Desired State of the Meshery.io site
![image](https://user-images.githubusercontent.com/69970950/187040668-65cb252e-bf0a-4617-b353-67052c5a94a2.png)

Replace the heading "Google Summer of Docs" with "Google Season of Docs".

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Himanshu664** [comment]
I want to work on this please assign

**Comment by vedant-kakde** [comment]
Here you go @Himanshu664 🚀

**Comment by joanamadasun** [comment]
I and  and Sinon are  redesigning this page please
