### ISSUE TITLE
Nav bar drop-down menu problem

### ISSUE THREAD

**Issue by cunbex** [meshery/meshery.io#822]
#### Description

The nav bar class : " nav-item has-sub " the two drop down menu's when hovering over both ( community and resources ) they both drop down which causes an overlay on top of each other.

#### Expected Behavior

the user must be able to hover over only one , a single drop down menu occurs not both

#### Screenshots

https://user-images.githubusercontent.com/98683647/187045538-bdbfd67a-bbff-4277-9fbd-87766f8da9e7.mp4

#### Proposition

decrease the animation duration of the drop-down menu after the hover goes off , or make one drop drown menu available per hover

#### Environment:

 - OS: Linux Ubuntu 22.04
 - Browser: Brave
 - Version: 
 - Device: Desktop

---

**Comment by leecalcote** [comment]
Good eye, @cunbex. Is this an item that you would like to work on?

**Comment by cunbex** [comment]
> Good eye, @cunbex. Is this an item that you would like to work on?

Oh Na sorry I'm just a beginner I have no experience in Javascript or css yet , I'm still learning the basics , can't get my hands dirty yet . Thnx for asking tho

**Comment by legendarykamal** [comment]
JS + help wanted am here to 🙂
Please assign me @leecalcote .

**Comment by eeshaanSA** [comment]
Would like to try this one. I can work on it.

**Comment by Aqdas-7** [comment]
I can help...

**Comment by leecalcote** [comment]
Thank you, all. Assigning in order of request…

**Comment by anirudhp26** [comment]
is this issue still open? If yes then i would like to work on it @leecalcote

**Comment by legendarykamal** [comment]
hey @anirudhp26 nope , there's a PR linked with the issue  but I am sure you can find another good one to work for you.
Thanks

**Comment by anirudhp26** [comment]
@legendarykamal ok sure, and i have raised an issue but am having trouble with that

**Comment by legendarykamal** [comment]
> @legendarykamal ok sure, and i have raised an issue but am having trouble with that

well , let me help u with that :smiley:

**Comment by eeshaanSA** [comment]
Would like to help with this.

**Comment by leecalcote** [comment]
@Krishna2323

**Comment by legendarykamal** [comment]
Ok so are we looking to adjust the timings of the opening and closing of the dropdowns? @leecalcote
