### ISSUE TITLE
Scrolling Option inside the twitter column 

### ISSUE THREAD

**Issue by adityyaa-10** [meshery/meshery.io#824]
![image](https://user-images.githubusercontent.com/103577578/187120836-9d4e777c-5e8e-40fd-b88a-fbbb747889da.png)

This "Tweets from mesheryio" box should occupy just a certain height and width, and there should be a scrolling option right inside the box.

**Comment by Himanshu664** [comment]
Can I try this Issue

**Comment by deveshXm** [comment]
Hey! Can i also work on this issue

**Comment by Prathamesh-Shanbhag** [comment]
Hey can you assign this issue to me, I have the perfect solution for this.

**Comment by vedant-kakde** [comment]
@Prathamesh-Shanbhag 🚀
