### ISSUE TITLE
Styling the Dropdown Button on top right of Meshery's Docs page 

### ISSUE THREAD

**Issue by anirudhp26** [meshery/meshery.io#832]
**Styling the Dropdown Button**

**Screenshots / Mockups**

![image](https://user-images.githubusercontent.com/107875381/187997123-176ddcf3-29e3-456f-874e-181f31aad2d6.png)

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Himanshu664** [comment]
I want to work on this

**Comment by anirudhp26** [comment]
Same here @Himanshu664

**Comment by anirudhp26** [comment]
Maybe we can work together?

**Comment by anirudhp26** [comment]
It's my first time Raising an issue and contributing

**Comment by anirudhp26** [comment]
@Himanshu664 where can i find files for the Meshery's Doc page?

**Comment by anirudhp26** [comment]
@legendarykamal i am not able to find files relevent to this issue

**Comment by legendarykamal** [comment]
hey @anirudhp26 I see , just mention what changes you expect to do. 


> @Himanshu664 where can i find files for the Meshery's Doc page?

you can find it on the meshery repo.

**Comment by legendarykamal** [comment]
ok open your issue there https://github.com/meshery/meshery/issues would be great .
I am closing it here :+1:

**Comment by anirudhp26** [comment]
ok thanks
