### ISSUE TITLE
[Twitter] feed's border  needs to be circular

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery.io#838]
**Current Behavior**

![image](https://user-images.githubusercontent.com/95926324/190630152-2be1037e-b9fc-4dc9-bc12-8b660e52d301.png)

**Desired Behavior**

For consistency with other sites of meshery  like smp.spec Twitter feed's border  needs to be circular
**Screenshots / Mockups**

**Alternatives**

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Lalman888** [comment]
Is this issue resolved?

**Comment by K0more** [comment]
Ima open a PR real quick.

**Comment by K0more** [comment]
@legendarykamal hey, this and the issue#861 are the same.

**Comment by legendarykamal** [comment]
this is fixed by https://github.com/meshery/meshery.io/pull/818 .
