### ISSUE TITLE
[Docs] Update the getting started Helm steps

### ISSUE THREAD

**Issue by CyrineG** [meshery/meshery.io#840]
**Current State:**
![image](https://user-images.githubusercontent.com/25556789/191935561-18c45e23-396d-473f-a1b0-6b94d28e5984.png)

**Desired State:**
update the helm getting started state to be :

```
kubectl create ns meshery
helm repo add meshery https://meshery.io/charts
helm install meshery-operator meshery/meshery-operator -n meshery 
helm install meshery meshery/meshery -n meshery
```

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by K0more** [comment]
Hey @CyrineG, I am new to this project, can I get assigned to this issue.

**Comment by CyrineG** [comment]
@K0more sure! I'll assign it to you!

**Comment by K0more** [comment]
@CyrineG I have updated the docs, could you review the PR for any suggestions.
