### ISSUE TITLE
Improper Alignment of Boxes

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#843]
#### Description

While scrolling on the website I noticed a strange behavior in the size of the boxes (attaching the screenshot of the same)

#### Expected Behavior

The size of the boxes should be identical. (i.e Community Newsletter )

#### Screenshots

![Screenshot (465)](https://user-images.githubusercontent.com/67385503/192878002-54ef21f9-fb39-4402-8068-19b2ebf12973.png)

#### Enviroment:
 - OS: Windows
 - Browser: Chrome 
 - Version: Version 105.0.5195.127 (Official Build) (64-bit)
 - Device: Desktop

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue

**Comment by leecalcote** [comment]
Good stuff, @UtkarshMishra12. Thank you.

**Comment by UtkarshMishra12** [comment]
@leecalcote Please review this PR #864. It has been approved by @legendarykamal
