### ISSUE TITLE
Text and Heading not aligned, Getting Started Section.

### ISSUE THREAD

**Issue by eeshaanSA** [meshery/meshery.io#847]
#### Description

Text not aligned with the Heading on meshery.io site Getting Started Section.
![image](https://user-images.githubusercontent.com/100678386/193423587-764d3845-1057-47ca-afcc-cb643a3e0e42.png)

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by eeshaanSA** [comment]
Can you please assign this to me? @legendarykamal

**Comment by legendarykamal** [comment]
sounds good , remember that the followup texts don't get disturbed.

**Comment by leecalcote** [comment]
I'm not convinced that this is an issue. It's easy for your eyes to play tricks on you when two fonts are of different sizes like this. I'll close this until you prove me wrong (please do).
