### ISSUE TITLE
Homepage reversehero section is not responsive.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery.io#849]
#### Description
The reverse-hero section on the homepage is not responsive. Overflowing at around 600px of width.

#### Expected Behavior
The section must be wrapped into separate lines if needed.

#### Screenshots
![Screenshot 2022-10-02 022502](https://user-images.githubusercontent.com/85894871/193428115-7fc76029-6c3c-44ac-a73f-af3433b8da1e.png)

#### Environment:
 - OS: Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
thanks. Which it is fixed. Is this an issue that you were wearing to work on, @Krishna2323 ?

**Comment by Krishna2323** [comment]
Thanks, @leecalcote ✌.

**Comment by leecalcote** [comment]
And, thank you, too, @Krishna2323 🤝
