### ISSUE TITLE
Buttons transition is not set in the homepage>reverse-hero section>mailing-list 

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery.io#850]
**Current Behavior**
The transition behavior is not set on the buttons making it look different from other buttons.

**Desired Behavior**
The transition property should be defined on the buttons to make it look better.

**Screenshots / Mockups**

**Alternatives**

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Krishna2323** [comment]
Pls, assign me this issue so that I can start working on it and make a PR asap.

**Comment by legendarykamal** [comment]
What transition effect are you looking to accomplish ?

**Comment by Krishna2323** [comment]
@legendarykamal The effect that most of the buttons have {transition: all .3s ease-out;}

**Comment by Krishna2323** [comment]
@leecalcote pls, assign this issue to me.

**Comment by leecalcote** [comment]
@Krishna2323 I'm not sure that what you've described is an issue (bug / area for improvement). Given the small nature of the proposal, will you implement, record a screen capture and present here for clarity of your proposal and for consideration or acceptance?

**Comment by legendarykamal** [comment]
I feel that these links are one time clickable and then user gets redirected to somewhere else so no point in creating the hover delay effect.
