### ISSUE TITLE
enhance drop down menu 

### ISSUE THREAD

**Issue by nik132-eng** [meshery/meshery.io#855]
**Current Behavior**

currently looking without colors.
![image](https://user-images.githubusercontent.com/77881638/193520575-51734c3e-c998-435b-823b-acdf5f2930ac.png)

**Desired Behavior**
I want make it like this
![image](https://user-images.githubusercontent.com/77881638/193520820-2694b60e-ce10-4d05-8b26-d439f02e659e.png)

when user hover on text it shows in color.

**Screenshots / Mockups**

**Alternatives**

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by nik132-eng** [comment]
can i get this for hackctoberfest ?

**Comment by psancheti110** [comment]
Hi, 

I'd like to take this on if it's alright.
