### ISSUE TITLE
Add appropriate link for SMI spec logo

### ISSUE THREAD

**Issue by eeshaanSA** [meshery/meshery.io#859]
#### Description

![image](https://user-images.githubusercontent.com/100678386/193643713-3b3cf548-988d-4c14-b3c5-c3d34f902eba.png)
Clicking on the SMI logo currently opens up the image, whereas it should take us to https://smi-spec.io/

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by eeshaanSA** [comment]
Would like to fix it if it is valid.

**Comment by legendarykamal** [comment]
The current situation looks valid @eeshaanSA .

**Comment by eeshaanSA** [comment]
Should close this issue then?
