### ISSUE TITLE
Enhance the twitter feed in the footer.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery.io#861]
**Current Behavior**
The feed in the footer looks odd and it is not consistent with other cards on the website.

**Desired Behavior**
I want to add some CSS style to make it look like this.
![expected](https://user-images.githubusercontent.com/85894871/193765237-74d17986-1ae2-4d66-8014-5e0f1e5bc175.png)

**Screenshots / Mockups**
Current styling:
![current](https://user-images.githubusercontent.com/85894871/193765368-cc0c9a39-4a55-41a1-924d-b2372994f256.png)

**Alternatives**

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by K0more** [comment]
@Krishna2323 this will need alligning the feed in the center and making it curved edges right?

**Comment by leecalcote** [comment]
Thanks for opening this up, @Krishna2323. The proposed change would be great to have. Would you like to pick this up or would you like for @K0more to take it on?

**Comment by Krishna2323** [comment]
@leecalcote ok, assign it to @K0more, I can find 100 more issues🤣.

**Comment by K0more** [comment]
Thanks @Krishna2323 !

**Comment by Krishna2323** [comment]
@K0more don't forget to add box shadow.
Welcome✌

**Comment by leecalcote** [comment]
> @leecalcote ok, assign it to @K0more, I can find 100 more issues🤣.

How dare you, sir. Bugs? 🐛 Here? Improvements to be made?? I can't believe that you would suggest such a thing. 

😉

**Comment by Krishna2323** [comment]
Thanks @leecalcote 😀.

**Comment by K0more** [comment]
> > @leecalcote ok, assign it to @K0more, I can find 100 more issues🤣.
> 
> How dare you, sir. Bugs? 🐛 Here? Improvements to be made?? I can't believe that you would suggest such a thing.
> 
> 😉

Right! How can you expect bugs to show up with this perfect community. Unless you assign stuff to me then I'll make sure there are bugs for people to work onn. 😌

**Comment by Krishna2323** [comment]
Everyone makes mistakes, bugs are important to test and improve developer skills.

**Comment by psancheti110** [comment]
Hi @K0more,

Are you still working on this? I'd like to take this on otherwise.

**Comment by K0more** [comment]
@psancheti110 yeah I'm working on it, just I had exams this week so I had to focus on them first.
