### ISSUE TITLE
Cloud native catalog is not responsive.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery.io#862]
#### Description
Catalog cards are not responsive, each card takes the full width of the screen.

#### Expected Behavior
Cards must be placed side-by-side if there is space left in the row.
![expected](https://user-images.githubusercontent.com/85894871/193767974-a8d5cfbd-f929-446e-b854-00c0cb597957.png)

#### Screenshots
![current](https://user-images.githubusercontent.com/85894871/193767986-a0ee373d-e44d-4c4c-8427-7dbd20369b2f.png)

#### Enviroment:
 - OS: Windows
 - Browser: Chrome/Brave
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, but no thanks.
