### ISSUE TITLE
Cards to subscribe breaks at small screen size.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery.io#863]
#### Description
The cards on the /subscribe page look weird at the small screen size.

#### Expected Behavior
![expected](https://user-images.githubusercontent.com/85894871/193773047-7a66863e-28f8-43ff-bd78-9f60bcfc0211.png)

#### Screenshots
![current](https://user-images.githubusercontent.com/85894871/193773069-9fc9c157-8b4e-4fa8-9f9e-f781de4d0b6e.png)

#### Enviroment:
 - OS: Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Good eye, @Krishna2323. Thank you for this. Yes, please.
