### ISSUE TITLE
Overlap of text in `service-mesh-landscape`

### ISSUE THREAD

**Issue by debasishbsws** [meshery/meshery.io#866]
#### Description
in `https://layer5.io/service-mesh-landscape` two title texts overlap with each other.

#### Expected Behavior
Both texts should be separated from each other

#### Screenshots
![layer5](https://user-images.githubusercontent.com/65381620/194285321-7e94b1e8-7418-4e78-9b65-75620b07f05f.png)

#### Enviroment:
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 106.0.5249.103
 - Device: Desktop

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by K0more** [comment]
can I get assigned to this 👀

**Comment by leecalcote** [comment]
This is the wrong repo for the issue to be filed within. The appropriate repo is - meshery/meshery

**Comment by leecalcote** [comment]
@debo19

**Comment by kamalbuilds** [comment]
whoop , passing  it in the right repo .  Thankyou @debasishbsws for pointing this out . If you would like to contribute comment under it. https://github.com/meshery/meshery/issues/3271 .
