### ISSUE TITLE
[Docs] The default value of `mesheryctl mesh deploy --adapter` is inconsistent

### ISSUE THREAD

**Issue by gyohuangxin** [meshery/meshery.io#867]
**Current State:**
The default value in https://docs.meshery.io/reference/mesheryctl: 
![image](https://user-images.githubusercontent.com/42127654/194740895-b0052fa9-846a-4b99-8452-561d38616f09.png)

The default value in https://docs.meshery.io/reference/mesheryctl/mesh/deploy:
![image](https://user-images.githubusercontent.com/42127654/194740907-e133a080-e596-4b00-a4fb-5bac7bbdb6cf.png)

**Desired State:**

They should be consistent.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by RahulSurwade08** [comment]
Hey @leecalcote , I am a newcomer and would love to take this issue. How can I get started?

**Comment by leecalcote** [comment]
@RahulSurwade08, @gyohuangxin can guide you. Start by building mesheryctl. Join the next community newcomers meeting that happens weekly on Thursdays. Details at meet.meshery.io.

**Comment by leecalcote** [comment]
@sourav-sharma7 if your unable to PR this issue within a week, please unassign yourself so that someone may pick it up in the meantime while you work toward being able to do so.

**Comment by gyohuangxin** [comment]
@RahulSurwade08 Thanks for taking it, it's related to a simple mistake in the  mesheryctl docs.
The description for default value here of `mesheryctl mesh deploy --adapter` is incorrect: https://docs.meshery.io/reference/mesheryctl
![image](https://user-images.githubusercontent.com/42127654/200989416-43cb3340-db50-403e-abf6-67e942ded38f.png)
And the correct description should be 
``` 

--adapter, -a  (required) adapter to use for validation. Defaults to "meshery-istio:10000"

```
What needs to be changed is here: 
https://github.com/meshery/meshery/blob/f9a088364428aa23acb818aca1959cf7b75bd31f/docs/_data/mesheryctlcommands/cmds.yml#L530
https://github.com/meshery/meshery/blob/f9a088364428aa23acb818aca1959cf7b75bd31f/docs/_data/mesheryctlcommands/cmds.yml#L567

You can raise a PR to fix it in https://github.com/meshery/meshery repo, let me know if you need any help.

**Comment by RahulSurwade08** [comment]
Hey @gyohuangxin , I have raised the PR. Please let me know any changes.
