### ISSUE TITLE
Text is overlapping with the Debugging the Data Plane box from  771px to 856px on page: /catalog

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#876]
#### Description

Text is overlapping with the (Debugging the Data Plane) box from  771px to 856px on page: /catalog
![Issue](https://user-images.githubusercontent.com/67385503/196055896-f295ad6f-9706-4209-a8bd-23c680b975d3.jpg)

#### Expected Behavior

![After](https://user-images.githubusercontent.com/67385503/196055912-888f7016-3689-4b8e-b290-5567b8ccadb6.jpg)

#### Enviroment:
 - OS: Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Harshit-Dandriyal** [comment]
Thanks @UtkarshMishra12 , will you like to work on this?

**Comment by UtkarshMishra12** [comment]
@Harshit-Dandriyal Yes please assign it to me.
