### ISSUE TITLE
To correct the location of (excerpt: patterns in-action) written down the image

### ISSUE THREAD

**Issue by aditi5050** [meshery/meshery.io#878]
This is how  it should be
![err1](https://user-images.githubusercontent.com/102579070/196172905-5a117cce-aef9-4364-8b57-2c87bad082de.jpg)
a30-9e9e2a71c281.jpg)
![eer3](https://user-images.githubusercontent.com/102579070/196172990-697e46e0-4b25-4a6a-9f6c-3e62618c888f.jpg)
and this how it is shall i raise a PR for this

**Comment by Nikhil-Ladha** [comment]
I beg to differ.
Captions are not that far away from the images, in general. They are generally close to the images, so the current design seems totally fine to me.

**Comment by aditi5050** [comment]
oh got it so shall I close this issue and also don't raise  pr for this

**Comment by Nikhil-Ladha** [comment]
Yes, please.

**Comment by aditi5050** [comment]
I have closed the issue :)
