### ISSUE TITLE
Boxes are not correctly aligned and are small in size -> on page: meshery.io/programs

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#886]
#### Description

Boxes are not correctly aligned and are small in size -> on page: meshery.io/programs
![image](https://user-images.githubusercontent.com/67385503/197356724-037ec713-7927-4ed0-a1a8-5b8fdba4f1d2.png)

#### Expected Behavior

![image](https://user-images.githubusercontent.com/67385503/197356920-fd4865a5-5e5b-45cc-b870-fbad815828eb.png)

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by adithyaakrishna** [comment]
@UtkarshMishra12 As you are working on the responsiveness part, please make sure it is aligned across all the breakpoints :)

**Comment by manu-vaillant-afk** [comment]
@UtkarshMishra12 are you still working on this issue ? Otherwise I could try to fix it :D

**Comment by UtkarshMishra12** [comment]
Yes, @manu-vaillant-afk I'm working on this, soon I'll open a PR soon 😄
