### ISSUE TITLE
[Site Feature] Integrations page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#889]
**Current Behavior**
Meshery has many systems that it manages and through its integrations. 

**Desired Behavior**
The list of integrations is long and needs a visual navigator.

#### Implementation
1. Create a new page on meshery.io/integrations
1. Use this threejs periodic table
   - Source: https://github.com/mrdoob/three.js/blob/master/examples/css3d_periodictable.html
   - Allow users to switch between different layouts (table, helix, grid...)
1. Source integration data from this [spreadsheet](https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=345660040) or from this [collection](https://github.com/layer5io/layer5/tree/master/src/collections/integrations).
1. Use Meshery brand green colors.

**Screenshots / Mockups**
- Demo: https://threejs.org/examples/?q=peri#css3d_periodictable

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AgniveshChaubey** [comment]
Hey @leecalcote @legendarykamal @GaganpreetKaurKalsi I am new here, wanna work on this issue. Can you please let me know if I can help in any way?

**Comment by leecalcote** [comment]
+ // @Krishna2323

**Comment by legendarykamal** [comment]
Happy to hear that @AgniveshChaubey , The dark mode for meshery.io needs assistance , lend your keen eyes to it.

In Integrations Mr. Lee has already shown you a way to work around.
