### ISSUE TITLE
[Logo Improvement] Remove the names from the logo's

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery.io#895]
**Current Behavior**

![image](https://user-images.githubusercontent.com/95926324/199081084-05e668c5-c717-43f8-aa01-21f4369014b9.png)

**Desired Behavior**

Due to the names the logo size is getting hampered.

1> remove the names from the logos 
2> make sure the logos are in proper size.

here are the links to the logos 
1> https://layer5.io/static/dbbd9d90d2fe12ac0c0069e4aa7a23cb/kyverno-icon-color.svg
2> https://landscape.cncf.io/logos/mondoo.svg
**Alternatives**

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Ideally, logos do not need to be edited. Use https://github.com/cncf/artwork/blob/master/projects/kyverno/icon/white/kyverno-icon-white.svg for Kyverno.

**Comment by legendarykamal** [comment]
Thanks kyverno nice, we will need a little changes  for mondoo

**Comment by ADITYADAS1999** [comment]
> **Current Behavior**
> 
> ![image](https://user-images.githubusercontent.com/95926324/199081084-05e668c5-c717-43f8-aa01-21f4369014b9.png)
> 
> **Desired Behavior**
> 
> Due to the names the logo size is getting hampered.
> 
> 1> remove the names from the logos 2> make sure the logos are in proper size.
> 
> here are the links to the logos 1> https://meshery.io/static/dbbd9d90d2fe12ac0c0069e4aa7a23cb/kyverno-icon-color.svg 2> https://landscape.cncf.io/logos/mondoo.svg **Alternatives**
> 
> <img alt="" width="16px" src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png">
> 
> #### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
> * 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
> * 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
> * 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.meshery.io) and [Community Slack](http://slack.meshery.io)

Hi  [legendarykamal](https://github.com/legendarykamal) 👋🏻
This issue is still open ?

**Comment by leecalcote** [comment]
@ADITYADAS1999 thanks for asking. It was just recently fixed, actually. Here's an open one, though - https://github.com/meshery/meshery.io/issues/896
