### ISSUE TITLE
Remove border radius from getting started section.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery.io#902]
#### Description
Remove border radius from getting started section.
![getting-started-border-radius](https://user-images.githubusercontent.com/85894871/204031346-a22433f6-c2a9-4de5-8fed-f13594d12ac9.png)

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by HM-8** [comment]
Hi @Krishna2323 would like to work on this issue.

**Comment by Krishna2323** [comment]
@HM-8, Sure👌.

**Comment by HM-8** [comment]
I'll get on it👍

**Comment by UtkarshMishra12** [comment]
@HM-8 Please Update !!!

**Comment by gopivaibhav** [comment]
Can I work on this issue? @UtkarshMishra12 @Krishna2323

**Comment by UtkarshMishra12** [comment]
@gopivaibhav Here you go 🎉🌟

**Comment by gopivaibhav** [comment]
Hi @UtkarshMishra12 I have made the PR[#941](https://github.com/meshery/meshery.io/pull/941) which solves this issue. Since I am a newcomer, I am not sure what to do next. Can you please review the changes and merge the PR?
Thanks!!
