### ISSUE TITLE
Use filter to make the link icon light in dark mode.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery.io#903]
#### Description
Use filter to make the link icon light in dark mode.
![Dropdown-Link-Icon-Color](https://user-images.githubusercontent.com/85894871/204031799-cd1b7268-4ed3-4dfd-a490-36a9b74a2bca.png)

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by yashhhguptaaa** [comment]
Hey @Krishna2323 

Can you assign this issue to me?
I have already tried that
<img width="1439" alt="Screenshot 2022-12-06 at 12 34 26 AM" src="https://user-images.githubusercontent.com/82795074/205721623-2e40be48-2460-494e-9f53-4ee6280f9f2e.png">

**Comment by yashhhguptaaa** [comment]
> Hey @Krishna2323
> 
> Can you assign this issue to me? I have already tried that <img alt="Screenshot 2022-12-06 at 12 34 26 AM" width="1439" src="https://user-images.githubusercontent.com/82795074/205721623-2e40be48-2460-494e-9f53-4ee6280f9f2e.png">

Hey @leecalcote ,
Can you assign me this issue? I have found the fix and can be quickly resolved.

**Comment by Krishna2323** [comment]
@yashhhguptaaa, sure👍, sorry for delay.

**Comment by yashhhguptaaa** [comment]
> @yashhhguptaaa, sure👍, sorry for delay.

Thanks @Krishna2323, No problem
