### ISSUE TITLE
Change current box shadow.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery.io#905]
#### Description
Change current box shadow and add the box shadow used on SS above.
![Screenshot 2022-11-25 230608](https://user-images.githubusercontent.com/85894871/204034104-afbb28be-7db8-4342-a9c5-1c0379bce898.png)

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by rabbanirizwan** [comment]
@Krishna2323 I wanted to work on this issue

**Comment by Krishna2323** [comment]
@rabbanirizwan, sure👍, just replace the color with black.

**Comment by rabbanirizwan** [comment]
https://github.com/meshery/meshery.io/pull/916 @Krishna2323

**Comment by rabbanirizwan** [comment]
<img width="1248" alt="Screenshot 2022-11-30 at 8 18 54 PM" src="https://user-images.githubusercontent.com/33807776/204837757-08c8d6c5-83c2-430f-a94c-6fc2488484c1.png">

**Comment by Sreya27** [comment]
I would like to take this up!

**Comment by 120EE0980** [comment]
Please assign me this issue

**Comment by BabyElias** [comment]
@leecalcote Can I work on this issue?

**Comment by leecalcote** [comment]
Assign in chronological order…

**Comment by maushish** [comment]
I would like to work on this issue

**Comment by shyamtawli** [comment]
Hey @120EE0980 are you working on it ?

**Comment by 120EE0980** [comment]
Yeah I am working on it

**Comment by Savio629** [comment]
I feel this issue isn't valid anymore, as there is no `performance tests run` box present on the current meshery.io website.
@Krishna2323 @Chadha93 @leecalcote

**Comment by leecalcote** [comment]
@Savio629 see https://meshery.io/features
