### ISSUE TITLE
Add padding to categories dropdown.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery.io#906]
#### Description
Add padding to categories dropdown.
![Categories-Box-Current](https://user-images.githubusercontent.com/85894871/204034756-81505990-0df8-4d1c-9114-3f55f0f2e7f9.png)

#### Expected Behavior
![Categories-Box-Expected](https://user-images.githubusercontent.com/85894871/204034780-4877e797-a44b-471b-944f-25f9c80c9fda.png)

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by tinniaru3005** [comment]
Hey @Krishna2323, I would like to work on the issue. Can you please assign it to me.

**Comment by Krishna2323** [comment]
@tinniaru3005, sure✌️

**Comment by leecalcote** [comment]
A change that would save us some hassle here (including text overflowing the box) is to simply remove the box-shadow and leave the filter controls lying directly on the page (which is the original design). I chatted with @Krishna2323 on this and he is supportive of doing just this.

**Comment by Krishna2323** [comment]
@tinniaru3005, update?

**Comment by tinniaru3005** [comment]
> @tinniaru3005, update?

Hey, I am having my exams this week. Will send the PR by Sunday do that we can discuss it in the websites call ok Monday
