### ISSUE TITLE
Install: Incorporate helm package creation into Meshery release workflow

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#91]
**Current Behavior**
Given that the source for Meshery's helm charts in is the Meshery repo, instead of storing the compressed version of the charts in this repo (meshery.io) as a charts "release", can we consider incorporating the tar.gz creation of these charts to our GitHub Actions workflow in Meshery?

We would include the tar.gz creation part of the tagged workflow (the workflow that is enacted when a release tag is present). We could either have goreleaser tar.gz the charts or have a script executed to tar.gz the charts and make that tar.gz available alongside the rest of the Meshery release artifacts here - https://github.com/layer5io/meshery/releases

In this way, the Meshery helm chart is treated as another release artifact that is created each time we cut a new Meshery release.

**Comment by leecalcote** [comment]
@Aisuko identified a possible start to the solution for this issue - https://github.com/meshery/meshery.io/pull/93#issuecomment-583946862

**Comment by leecalcote** [comment]
@Aisuko, @mgfeller, what are your thoughts here? Is this something needed / worth pursuing?

Note the chart version on https://hub.helm.sh/charts/meshery/meshery. 
Note that this repo is use to host the chart: https://github.com/meshery/meshery.io/tree/master/charts

**Comment by Aisuko** [comment]
> @Aisuko, @mgfeller, what are your thoughts here? Is this something needed / worth pursuing?
> 
> Note the chart version on https://hub.helm.sh/charts/meshery/meshery.
> Note that this repo is use to host the chart: https://github.com/meshery/meshery.io/tree/master/charts


I saw the image tag in meshery Helm chart always set as the latest. since we change the CI scripts to build three version of the image like the `latest` `git tag as tag` etc. So, every time the user deploy meshery with helm chart will use  the tag `latest` image of meshery. So, I believe we do not need to add the Helm chart into the release page

**Comment by leecalcote** [comment]
Finally: DONE!
