### ISSUE TITLE
Ir-regular spaces between the logos on the main page

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#911]
#### Description

Ir-regular spaces between the logos on the main page

#### Expected Behavior

Regular space should be there

#### Screenshots

https://user-images.githubusercontent.com/67385503/204317461-625c683c-91a1-4c82-a8bb-26ef525bb110.mp4

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@Krishna2323 if there are plans to redesign this section already, then perhaps, @UtkarshMishra12 should hold off on a fix here for the time being.

**Comment by UtkarshMishra12** [comment]
@Krishna2323 Your thoughts?

**Comment by Krishna2323** [comment]
@UtkarshMishra12, I may have fixed that in the integrations PR because now it looks fine to me. Sorry for that.

**Comment by UtkarshMishra12** [comment]
@Krishna2323 So may I close this issue?
