### ISSUE TITLE
Community Newsletter box is not responsive as per the screen size

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#912]
#### Description

The Community Newsletter box is not responsive as per the screen size

#### Screenshots

https://user-images.githubusercontent.com/67385503/204348840-34103b6e-dfcb-41b3-925e-dad48ff20ed8.mp4

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thank you, @UtkarshMishra12
