### ISSUE TITLE
On hovering the text is not visible inside the button on page : meshery.io/subscribe

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#915]
#### Description

On hovering the text is not visible inside the button on page : meshery.io/subscribe

#### Expected Behavior

Is it a feature or bug, I'm not sure about it.

#### Screenshots

https://user-images.githubusercontent.com/67385503/204599864-ae632508-3676-459f-b966-144720a03115.mp4

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by UtkarshMishra12** [comment]
@leecalcote Your thoughts on this?

**Comment by leecalcote** [comment]
🐛 

Good eye, @UtkarshMishra12 👍
