### ISSUE TITLE
Make Case Corrections

### ISSUE THREAD

**Issue by BabyElias** [meshery/meshery.io#920]
#### Description
There are a few case errors with the text on the site. Improving these, would enhance the readability of the website

#### Screenshots
![image](https://user-images.githubusercontent.com/95405559/205126896-2f88c235-3a68-4752-bbda-8174d5b78dd0.png)

#### Enviroment:
 - OS: Windows
 - Browser: Chrome
 - Version: 
 - Device: Desktop 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Krishna2323** [comment]
@BabyElias, thanks for this, but we don't need any change here.
