### ISSUE TITLE
[Integrations] Buttons need to stay highlighted to show the active selection

### ISSUE THREAD

**Issue by eeshaanSA** [meshery/meshery.io#921]
#### Description

![image](https://user-images.githubusercontent.com/100678386/205212530-36b2da68-71a0-4804-9bf8-5cb347f889e1.png)

#### Expected Behavior

![image](https://user-images.githubusercontent.com/100678386/205212324-266043f6-587f-4016-bb0d-36197530cb7d.png)
![image](https://user-images.githubusercontent.com/100678386/205212506-81e8c8f1-8ef1-402c-88ff-501b26017a01.png)

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Yes, additionally, each integration will need to be clickable in order for site visitors to see details of each integration.

**Comment by leecalcote** [comment]
One of the two yellows from the brand color schemes Saffron #EBC017, or potentially, Blond #FFF3C5 might work well.

**Comment by eeshaanSA** [comment]
Sounds good, @yashhhguptaaa. I hope you' ll open a PR.
