### ISSUE TITLE
[Docs] Update contributor guide with enhanced with how dark mode works

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#922]
**Current State:**
Meshery.io has a new dark mode.

**Desired State:**
New and existing contributors need training / documentation on how this feature works. 

#### Acceptance Criteria
1. Concise instructions and example(s) should be included in this repo's readme.
2. A similar set of instructions should be included in a new page in https://docs.meshery.io/project/contributing

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Musab1258** [comment]
@leecalcote , can I work on this.

**Comment by leecalcote** [comment]
That would be helpful, @Musab1258. Thank you.

**Comment by Musab1258** [comment]
[screen-capture (1).webm](https://user-images.githubusercontent.com/67251181/207763200-5d866c13-b4e1-4b24-8600-1d0b33d8e0bc.webm)

**Comment by Musab1258** [comment]
@leecalcote , just to be sure is this the darrk mode you are talking about.

[screen-capture.webm](https://user-images.githubusercontent.com/67251181/207763357-a609e4be-f4f1-4d87-8ece-b1b2217d67b9.webm)

**Comment by leecalcote** [comment]
Tagging @Krishna2323

**Comment by Krishna2323** [comment]
@Musab1258, yes, we are talking about the dark mode on meshery.io, you can check out once how that is implemented and if you need help anywhere then pls ping me in slack.

**Comment by Musab1258** [comment]
okay.

**Comment by Shivam-AfA** [comment]
Hey @leecalcote I would like to give this a shot.
