### ISSUE TITLE
[Chore] Consolidate assets folders including js, css, images

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#923]
#### Current State of the Meshery.io site
These two folders and their content:

1. https://github.com/meshery/meshery.io/blob/master/js
1. https://github.com/meshery/meshery.io/blob/master/images

#### Desired State of the Meshery.io site
Can be combined under `/assets`.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by eagerashwani** [comment]
Hey @leecalcote , Please Assign it to me.

**Comment by leecalcote** [comment]
Sounds good, @eagerashwani

**Comment by StarTrooper08** [comment]
Is this issue this open and doable?
Cause I can see wontfix issue label.

**Comment by leecalcote** [comment]
Help wanted.

**Comment by RahulGopathi** [comment]
I would like to work on this issue.

**Comment by ShuvamChatterjee28** [comment]
I can also work if @RahulGopathi is not working.

**Comment by BabyElias** [comment]
@leecalcote Can I work on this issue?

**Comment by leecalcote** [comment]
@BabyElias yes, that’s be great.

**Comment by BabyElias** [comment]
Should I create separate folders for both the js and images files under assets?

**Comment by BabyElias** [comment]
Done consolidating all the files and updating their locations throughout the repo

**Comment by BabyElias** [comment]
@leecalcote , merging on the main branch is causing conflicts for these files as people are still adding images to the images folder that has been removed by this PR.

**Comment by BabyElias** [comment]
@leecalcote Can you please review the PR whenever possible. Thanks in advance!
