### ISSUE TITLE
Making the button cover the full width to improve the UX for users on Docs Page

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#924]
**Current Behavior**

As of now, it's not covering the entire width

**Desired Behavior**

Making the button cover the full width to improve the UX for users

**Screenshots / Mockups**

Now:

https://user-images.githubusercontent.com/67385503/205380508-fcf48183-dad7-4dce-94b4-c70568913d75.mp4

After:

https://user-images.githubusercontent.com/67385503/205380538-746d7207-19ac-477a-892e-89cc25cdf51e.mp4

**Alternatives**

---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by UtkarshMishra12** [comment]
@leecalcote  Your thoughts on this 👀

**Comment by UtkarshMishra12** [comment]
@Nikhil-Ladha What about this?

**Comment by Nikhil-Ladha** [comment]
It shouldn't be full-width.
Rather smaller width and center aligned for smaller resolution (i.e, once the sidebars are collapsed)

**Comment by yashhhguptaaa** [comment]
Hey @UtkarshMishra12 , @Nikhil-Ladha I want to work on this issue.
Can you assign this issue to me?

**Comment by Udit-takkar** [comment]
@Nikhil-Ladha  ok i'll fix this. it has been pending for a while now

**Comment by Udit-takkar** [comment]
@Nikhil-Ladha ok i'll fix this. it has been pending for a while now.

**Comment by leecalcote** [comment]
@Udit-takkar, the behavior of the changes in your PR look pretty good and inline with guidance provided by @Nikhil-Ladha.
