### ISSUE TITLE
Adding LinkedIn Page to Social of Meshery

### ISSUE THREAD

**Issue by SiddheshKukade** [meshery/meshery.io#925]
#### Current State of the Meshery.io site
We know that Meshery doesn't have its own LinkedIn page but as it is associated with Layer5 so a link to the socials must be added for its LinkedIn ultimately will help new people to understand that it is associated with layer5

Currently :
![image](https://user-images.githubusercontent.com/65951872/205507475-631bcb12-ffd2-486c-a22d-a08b8771f1d6.png)

#### Desired State of the Meshery.io site
Linked Page link redirecting [here](https://www.linkedin.com/company/layer5/)
![image](https://user-images.githubusercontent.com/65951872/205507560-0d98776e-0c8e-45c8-abd6-167fef821708.png)
---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by SiddheshKukade** [comment]
@leecalcote sir, can I take this?

**Comment by leecalcote** [comment]
This is great, @SiddheshKukade. You can use this link: https://www.linkedin.com/showcase/meshery
