### ISSUE TITLE
Menu Hamburger and Text are not centered

### ISSUE THREAD

**Issue by SiddheshKukade** [meshery/meshery.io#926]
#### Current State of the Meshery.io site
1. Go to [Meshery Site](https://www.meshery.io/)
1. If the size of the window is less than normal you will see a hamburger icon and `MENU` text
1. Zoom and check that it's actually not completely centred. Here's a photo
![image](https://user-images.githubusercontent.com/65951872/205508056-b52eb34e-0baa-4052-8e75-6c155dc28506.png)

#### Desired State of the Meshery.io site

The Hamburger Icon and `MENU` text must be centred for a consistent look.

![image](https://user-images.githubusercontent.com/65951872/205508142-046c714a-d577-4bd7-99fa-39258ee20ff7.png)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by SiddheshKukade** [comment]
Hello @leecalcote Sir, let me know if you need more details & I would like to take this issue. Actually, I'm new to this project so that's why I'm trying to fix small but important UI issues first. Thanks 👍🏻

**Comment by leecalcote** [comment]
// @Krishna2323

**Comment by Krishna2323** [comment]
@SiddheshKukade, thanks for raising the issue👍.

**Comment by Krishna2323** [comment]
@SiddheshKukade, have you successfully setup the website locally?
