### ISSUE TITLE
Adding some padding to the Meshery Catalog Categories Section

### ISSUE THREAD

**Issue by SiddheshKukade** [meshery/meshery.io#927]
#### Current State of the Meshery.io site
In the current design of the category section, the padding is not provided on the right side. This is not a good User Interface. A simple `padding-right:1rem` can solve this issue.

Current UI ⬇️ 
![image](https://user-images.githubusercontent.com/65951872/205508848-6a51b673-15ff-408a-ad2f-f5fca29d8372.png)

#### Desired State of the Meshery.io site
Some margin is provided on the right side ⬇️ 
![image](https://user-images.githubusercontent.com/65951872/205508896-7426a650-ac69-482c-8b05-6215a4335220.png)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by SiddheshKukade** [comment]
Hello @leecalcote Sir, let me know if you need more details & I would like to take this issue. Actually, I'm new to this project so that's why I'm trying to fix small but important UI issues first. Thanks 👍🏻

**Comment by leecalcote** [comment]
@SiddheshKukade thanks much. You're right about this being an issue. I'm not sure if another contributor is already addressing this issue or not. It has been a recent point of discussion. What we actually want to do is simply remove the box shadow completely. // @Krishna2323

**Comment by UtkarshMishra12** [comment]
@leecalcote  @Krishna2323  has already raised this issue and  it's assigned to @tinniaru3005  #906

**Comment by leecalcote** [comment]
Cool. I'm hoping that _someone_ takes care of this ~20 second change to remove the box-shadow soon. 😉
