### ISSUE TITLE
In Dark mode, some logos of the integrations are in color. It should be white similar to the dark mode of the layer5.io site

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#932]
#### Description

In Dark mode, some logos of the integrations are in color. It should be white similar to the dark mode of the layer5.io site.

#### Expected Behavior

All logos should be white.

#### Screenshots

https://user-images.githubusercontent.com/67385503/205699663-340c2ac9-a7f7-4e76-b361-5dc074998506.mp4

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by UtkarshMishra12** [comment]
@leecalcote Your thoughts on this?

**Comment by Musab1258** [comment]
@UtkarshMishra12,  can I work on this.

**Comment by leecalcote** [comment]
One option is to add a white stroke to the colored icons and then only colored icons can be used.

**Comment by Vaani-pathariya** [comment]
I think i can work on this , please assign it to me

**Comment by Shivam-AfA** [comment]
Hi @leecalcote @UtkarshMishra12, I would like to work on thsi issue!

**Comment by leecalcote** [comment]
> One option is to add a white stroke to the colored icons and then only colored icons can be used.

@Shivam-AfA it'd be great to see this suggestion in-action and have folks like @GaganpreetKaurKalsi and @Krishna2323 weigh-in on it.

**Comment by Shivam-AfA** [comment]
> @Shivam-AfA it'd be great to see this suggestion in-action and have folks like @GaganpreetKaurKalsi and @Krishna2323 weigh-in on it.
Just to confirm, @leecalcote do you mean that rather than using white icons, we can use the colored icons in the dark theme but with a white stroke?

**Comment by leecalcote** [comment]
Precisely - as an experiment.

Color icons are prettier. A wall of all white icons is pretty bland and more difficult to “read”.

**Comment by Shivam-AfA** [comment]
Gotcha! @leecalcote. I'll try my best design skills for this experiment. 😎

**Comment by Yashsharma1911** [comment]
Color icons will look good. It will help users to not put so much pressure on their eyes to understand the logo and color icons can be fast recognizable rather than white color icons

**Comment by Shivam-AfA** [comment]
True @Yashsharma1911. Would you like to contribute here?

**Comment by Yashsharma1911** [comment]
@Shivam-AfA would love to contribute kindly let me know how can I help in this issue

**Comment by Yashsharma1911** [comment]
@Shivam-AfA I will love to contribute kindly let me know how can I help in this issue

**Comment by Shivam-AfA** [comment]
First of all you need to run the site locally. Check the README docs for this repo. And then you can try changing the icons. @Yashsharma1911
