### ISSUE TITLE
Change the toggle icon when we switch to dark mode

### ISSUE THREAD

**Issue by tinniaru3005** [meshery/meshery.io#938]
#### Description

The toggle icon doesn't change when we switch to dark mode.

#### Expected Behavior

The toggle icon should switch to a moon icon when we switch to dark mode

#### Screenshots

https://user-images.githubusercontent.com/62856848/208439370-3dbd9520-84db-4bda-b4eb-f9f77ad625e4.mp4

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rishav1707** [comment]
Shall I work on this issue? @leecalcote

**Comment by UtkarshMishra12** [comment]
@Rishav1707  Are you able to set up the website locally?

**Comment by Rishav1707** [comment]
@UtkarshMishra12 Yeah I will try

**Comment by UtkarshMishra12** [comment]
@Rishav1707 Here you go 🚀

**Comment by Rishav1707** [comment]
Sorry, @UtkarshMishra12 I am unable to set up the website locally.
Please assign this issue to someone.
And thank you for your patience.

**Comment by UtkarshMishra12** [comment]
@Rishav1707 May I know what error you are facing? 
If you want to find the solution you can post your errors at https://discuss.meshery.io/. Someone will surely help you/or you might see the solution to your error.

**Comment by leecalcote** [comment]
Awesome suggestion, @UtkarshMishra12 👏

**Comment by shashank-kavli** [comment]
Hello @UtkarshMishra12 , I'm new here and want I to contribute to this particular issue 
I'm trying to setup the website locally and have the correct ruby version installed but this is the error I'm getting 
![image](https://user-images.githubusercontent.com/121170732/209117489-058591aa-0936-4871-85d9-6a198402bac8.png)

**Comment by tinniaru3005** [comment]
> Hello @UtkarshMishra12 , I'm new here and want I to contribute to this particular issue I'm trying to setup the website locally and have the correct ruby version installed but this is the error I'm getting Do you have any suggestions? Also, Sorry for the ping
> 
> ![image](https://user-images.githubusercontent.com/121170732/209117489-058591aa-0936-4871-85d9-6a198402bac8.png)

https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rvm-on-ubuntu-20-04

Try out this. It worked for me.

**Comment by shashank-kavli** [comment]
Thanks a lot @tinniaru3005 !!! The article was very helpful and I was able to setup the website locally.
Here are the screenshots after making changes

![image](https://user-images.githubusercontent.com/121170732/209126423-39aa6883-fb88-419e-8783-7cb374fd466b.png)
![image](https://user-images.githubusercontent.com/121170732/209126518-d9f249ba-49e7-4124-a81a-3b00e7e2cff8.png)

I have used preexisting css logic used in the Integrations section

And for the icon's part, the source files already had sun and moon icon svg files
![image](https://user-images.githubusercontent.com/121170732/209127611-08a83bf0-1324-457f-8ca5-1fc0704ed28d.png)
Earlier, the mode-toggle-icon.png was being used. But locally I'm using sun-icon.svg and moon-icon.svg

Are there changes good or do you have other suggestions? Please let me know...
Also can you please assign this issue to me
Once again thanks for the article @tinniaru3005

**Comment by UtkarshMishra12** [comment]
@shashank-kavli Here you go 🚀🌟

**Comment by shashank-kavli** [comment]
Thanks @UtkarshMishra12 
Can you please checkout https://github.com/meshery/meshery.io/issues/938#issuecomment-1362748073 and give your opinion?

**Comment by UtkarshMishra12** [comment]
@shashank-kavli It looks good 👀. For the size, you can take a reference from the [layer.io](https://layer5.io/) website

**Comment by shashank-kavli** [comment]
@UtkarshMishra12 is this looking good?
Here I'm using pngs for both sun and moon icon
Sun icon png is the one which was already in the source files and I've made the moon icon 
![image](https://user-images.githubusercontent.com/121170732/209156520-c6cda38e-a862-4ef5-9876-f38fd8ab79f8.png)

![image](https://user-images.githubusercontent.com/121170732/209156331-82b38e75-1bb5-41ea-9cb9-98f5e9c6b639.png)

Here I'm using pngs for both sun and moon icon
Sun icon png is the one which was already in the source files and I've made the moon icon 
As far as the theme toggle button on layer5.io is concerned, it is a shape made using css and transforms on clicking

**Comment by UtkarshMishra12** [comment]
@shashank-kavli It looks good, please open a PR so that I see your changes 👀

**Comment by ShashankKavli** [comment]
Hello @UtkarshMishra12 👋 This is my first PR and I'm very new to open source
I hope I've raised the PR correctly and according to the guidelines 
Pls let me know if I have made any mistakes
