### ISSUE TITLE
[SVG] Unwanted white background in bee icon

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery.io#939]
#### Description
The bee svg used to represent ebpf on the Meshery Catalog (https://meshery.io/catalog) has an unwanted white background that is visible in dark mode.

#### Expected Behavior
A transparent background is desirable.

#### Screenshots
<img width="1081" alt="Screenshot 2022-12-19 at 4 36 20 PM" src="https://user-images.githubusercontent.com/7570704/208540193-b89dde46-5f3c-4a88-a1ad-112e89a01a0b.png">

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Musab1258** [comment]
@leecalcote, Can you assign this to me?

**Comment by leecalcote** [comment]
Thanks, @Musab1258. If you’re unable to get this in a couple days, let’s give @BabyElias an opportunity.

**Comment by Musab1258** [comment]
@leecalcote, I get to it right away.

**Comment by Musab1258** [comment]
@leecalcote, I think this has to do with image itself.

**Comment by Musab1258** [comment]
The white color is part of the image.

**Comment by leecalcote** [comment]
@Musab1258, yes, edit the image. If this happens to be outside of your area of comfort / skills, please unassign and let's get you onto a different issue.

**Comment by GaganpreetKaurKalsi** [comment]
Issue fixed, closing up this issue
