### ISSUE TITLE
Terraform logo in Built-in Integrations section is not properly scaled

### ISSUE THREAD

**Issue by Aditya-150** [meshery/meshery.io#948]
### Description
**Terraform** logo in Built-in Integrations section is not properly scaled

### Expected Behavior
To scale the logo properly.

### Screenshots
![Screenshot 2022-12-24 211639](https://user-images.githubusercontent.com/78409764/210194690-be20b660-2c80-4756-b719-a4ede5289004.png)
explain your problem.-->

### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aditya-150** [comment]
@leecalcote can you assign this to me.

**Comment by leecalcote** [comment]
Thanks for calling this out, @Aditya-150. 👍

**Comment by Aarav238** [comment]
can i work on this issue @leecalcote ?

**Comment by GaganpreetKaurKalsi** [comment]
Why do I feel this issue is at the wrong place, @leecalcote? Anyways the terraform logo skewness is already been taken care of in another PR. Will close up this issue.
