### ISSUE TITLE
[Catalog] Resizing and alignment issue for several cards

### ISSUE THREAD

**Issue by MrBehl06** [meshery/meshery.io#951]
### Description
I found this at https://meshery.io/catalog/wasm/http-auth/ the image size is too big and the icons in the small box are not properly aligned. And the text is not properly visible even though the icons are too big inside modals and "Coming soon" cards are having there own modals with irrelative content inside them.

### Expected Behavior
the images and icons inside the small box should be properly aligned and the whole page contains many small image resizing issues. That can be solved if we adjust the size of the image and align it.

### Screens
<img width="1373" alt="Screenshot 2023-01-08 at 10 35 50" src="https://user-images.githubusercontent.com/101118926/211181413-4d01968b-f494-41ad-974f-11079f9933f6.png">
<img width="1440" alt="Screenshot 2023-01-07 at 23 55 18" src="https://user-images.githubusercontent.com/101118926/211181416-a7646138-5bbf-4883-9071-53f6f8e40dd6.png">
<img width="1435" alt="Screenshot 2023-01-07 at 23 42 38" src="https://user-images.githubusercontent.com/101118926/211181417-5e770500-6b7a-4635-8b99-c84e98cae74c.png">
<img width="1440" alt="Screenshot 2023-01-07 at 23 24 19" src="https://user-images.githubusercontent.com/101118926/211181419-3831fe0f-952e-4ad2-8938-3a2cddd4ab16.png">
hots
Current :

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by MrBehl06** [comment]
@leecalcote @GaganpreetKaurKalsi Please assign this issue to me.

**Comment by GaganpreetKaurKalsi** [comment]
There you go @MrBehl06 👍 Thanks 🚀

**Comment by GaganpreetKaurKalsi** [comment]
Any updates on this @MrBehl06 ??

**Comment by MrBehl06** [comment]
@GaganpreetKaurKalsi  Yes I have done with the resizing just of image just want to discuss some changes related to page.

**Comment by leecalcote** [comment]
@GaganpreetKaurKalsi @MrBehl06, this a high priority bug. Between one of the two of you, we need it fixed today. Let me know if you're not available or able to do so and I'll see that it gets taken care of.
