### ISSUE TITLE
[Catalog] Stop window/document scroll when modal is open

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [meshery/meshery.io#955]
### Description
When we open the catalog modal, we are able to scroll the back page.

### Expected Behavior
Stop document scroll when modal is open. Should be able to scroll inside modal only, if possible.

### Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/211884407-3106aa06-9a83-4939-987b-bbd10fde6165.png">

### Link
https://meshery.io/catalog

### Enviroment:
 - OS: Mac
 - Browser: Chrome
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by MrBehl06** [comment]
@GaganpreetKaurKalsi @leecalcote Please assign this issue to me.

**Comment by Avi-88** [comment]
Hi @MrBehl06 , are you still working on this ?
