### ISSUE TITLE
[Catalog] Open link in a new tab

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [meshery/meshery.io#956]
### Description
Clicking on the below icon takes you to the link on the same tab
<img width="59" alt="image" src="https://user-images.githubusercontent.com/54144759/211885989-3c16d592-5ad6-4539-b6e6-bd30df5fd3b9.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/211885937-9495f8fa-ca8f-4c3b-8124-41c590f7404b.png">

### Expected Behavior
Clicking on "new tab" icon should open the url in a new tab instead of the same tab.

### Enviroment:
 - OS: Mac
 - Browser: Chrome
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Sreya27** [comment]
I am interested in taking this up!

**Comment by GaganpreetKaurKalsi** [comment]
There you go, thanks 👍 @Sreya27
