### ISSUE TITLE
[Catalog] Fix Spelling

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [meshery/meshery.io#957]
### Description
Fix compatibility spelling in the below screen
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/211888023-48652d27-4307-4836-8b23-9c59712ec10c.png">

### Enviroment:
 - OS: Mac 
 - Browser: Chrome
 - Version: 
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Sreya27** [comment]
I am interested in taking this up!

**Comment by arunbingari** [comment]
I am interested in this task .

**Comment by leecalcote** [comment]
@arunbingari excellent. If @Sreya27 doesn't complete by end of day tomorrow, it's all yours.

**Comment by Sreya27** [comment]
Hey! I fixed this issue and the pull request was merged

**Comment by sajdakabir** [comment]
Hey @GaganpreetKaurKalsi i would like to work on this issue.

**Comment by Sreya27** [comment]
I think I made a few mistakes here and opened another pull request for an issue that was closed. Apologies for the inconvenience. I’m guessing this issue can be closed now

**Comment by sajdakabir** [comment]
yah, It's closed now
