### ISSUE TITLE
Text SUBSCRIBE inside button is not aligned properly

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery.io#959]
#### Current State of the Meshery.io site
The text `SUBSCRIBE` is not aligned properly in the middle of the button

![Frame 1](https://user-images.githubusercontent.com/71271069/211913558-db9aeee7-6292-470a-bd00-563febe101c6.jpg)

#### Desired State of the Meshery.io site
Text `SUBSCRIBE` inside button should be aligned in middle properly

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by MrBehl06** [comment]
@leecalcote @GaganpreetKaurKalsi Please assign this issue to me.

**Comment by Yashsharma1911** [comment]
Hey love to contribute but not this time so you can assign this to @MrBehl06
