### ISSUE TITLE
Incorrect numbering of the installation steps

### ISSUE THREAD

**Issue by AnnuCode** [meshery/meshery.io#960]
### Current State:
The 'Quick Start with Minikube' [page](https://docs.meshery.io/installation/platforms/minikube) in the installation guides has a mistake in numbering of the installation steps.
3rd step is numbered as 2nd step. 

![numbering](https://user-images.githubusercontent.com/97174641/212063906-d88b3439-0ad7-4b04-b7e8-1bf6b7c39d07.PNG)

### Desired State:
Step 3 should be renamed to "3." instead of "2.".  
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by UtkarshMishra12** [comment]
Good eye 👀 @AnnuCode. Please go ahead and make a PR for this.

**Comment by AnnuCode** [comment]
Thanks @UtkarshMishra12 . Sure, will do it.

**Comment by AnnuCode** [comment]
Hi @UtkarshMishra12, it looks like I have mistakenly opened this issue in the wrong repository as it deals with Meshery docs. Can you please [transfer](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) this issue?
I have opened a [pull request](https://github.com/meshery/meshery/pull/6874) to correct this issue in the correct repo.
