### ISSUE TITLE
[Catalog] Text colour and modal-chip alignment issue

### ISSUE THREAD

**Issue by MrBehl06** [meshery/meshery.io#962]
### Description
There are some minor issues which are mentioned below 
1) Text color is black in dark mode which is not visible.
2) Model-chip is not alignment and color needs to be fixed.

###Current Behaviour
<img width="392" alt="Screenshot 2023-01-13 at 00 27 54" src="https://user-images.githubusercontent.com/101118926/212158630-0f1d5b5f-b5e2-4f0b-b08d-665b6066202c.png">

<img width="1434" alt="Screenshot 2023-01-13 at 00 28 08" src="https://user-images.githubusercontent.com/101118926/212158062-ffacc674-d510-4a12-a343-725d807140f7.png">
<img width="280" alt="Screenshot 2023-01-13 at 00 27 35" src="https://user-images.githubusercontent.com/101118926/212158075-0ca07a14-c027-48f2-a7b2-e3c1d7e21dbe.png">

### Expected Behavior
<img width="1348" alt="Screenshot 2023-01-13 at 00 27 15" src="https://user-images.githubusercontent.com/101118926/212158123-42d10905-8ab3-4c1e-bfc4-4262c791a6cf.png">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by MrBehl06** [comment]
@leecalcote @GaganpreetKaurKalsi Please assign this issue to me.

**Comment by leecalcote** [comment]
Thanks, @MrBehl06. This does need a fix. 👍

**Comment by MrBehl06** [comment]
Thank you @leecalcote
