### ISSUE TITLE
[UI] Modifying Navigation menu for small media devices

### ISSUE THREAD

**Issue by gyancodes** [meshery/meshery.io#969]
### Description
The Navigation menu is not aligned in small media devices.

### Current Behavior
![issuenav](https://user-images.githubusercontent.com/61907167/212398143-1a46de17-44cf-471f-8be5-5692cc348e5c.png)

### Expected Behavior
 There should be a popover menu or flex-direction should be a column (other changes can also be required).

### Screenshots
![nav](https://user-images.githubusercontent.com/61907167/212398649-06ec215b-baaf-425d-8cce-44bef80a08f5.png)

### Environment:
 - OS:  Windows
 - Browser: Chrome 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Udit-takkar** [comment]
@gyancodes thanks for reporting. i am working on the fix

**Comment by gyancodes** [comment]
@Udit-takkar If you need any help let me know.
