### ISSUE TITLE
Spelling fix

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [meshery/meshery.io#971]
### Description
Fix spelling for "compatibility" in the below screen (mobile view for catalog page)
<img width="757" alt="image" src="https://user-images.githubusercontent.com/54144759/212482336-0f0713a0-2f52-4979-8028-27cbe5f53c57.png">

### Enviroment:
 - OS: Mac
 - Browser: Chrome
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by oneknucklehead** [comment]
Hey can i work on this?

**Comment by GaganpreetKaurKalsi** [comment]
Sure @oneknucklehead 💯

**Comment by saadkadhi2** [comment]
Hello I've solved the issue. Can I send a PR?

**Comment by oneknucklehead** [comment]
Fixed this!
