### ISSUE TITLE
[Docs] - Change the Community Welcome Guide link with the given link in README.md

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#972]
### Description

The link to the newcomer's welcome guide is redirecting toward the deleted docs link.
### Expected Behavior

Replace it with this link [Link](https://layer5.io/community/handbook/repository-overview)

### Screenshots

![image](https://user-images.githubusercontent.com/67385503/212485859-6f36ba1a-abaa-4491-97bc-d169ddbef989.png)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Amishakumari544** [comment]
I want to work on this :)

**Comment by UtkarshMishra12** [comment]
Here you go 🚀 @Amishakumari544

**Comment by msaini0r** [comment]
@UtkarshMishra12 if no one is working on this? can I take this issue.

**Comment by UtkarshMishra12** [comment]
Let us wait for a day or two if @Amishakumari544 does not reply you can proceed with the PR 👀 @msaini0r
