### ISSUE TITLE
[Docs] - Change the  Welcome Guide link with the given link on page : meshery.io/calendar

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#974]
### Description

The link to the welcome guide is redirecting toward the deleted docs link.

### Expected Behavior

Replace it with this link [Link](https://layer5.io/community/handbook/repository-overview)

### Screenshots

![image](https://user-images.githubusercontent.com/67385503/212556198-6fd18b47-eff9-4290-9a4e-246551894a99.png)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Udit-takkar** [comment]
okay 👍

**Comment by deep-poharkar** [comment]
can you assign me this?

**Comment by kushvahasumit** [comment]
I think I do this,  it's backend link are incorrect put new link in place of that i am right ?
