### ISSUE TITLE
Solving Readme build status

### ISSUE THREAD

**Issue by msaini0r** [meshery/meshery.io#978]
### Current State:

As there is no workflow or Build Status defined, don't you think we should remove this from the readme.

![meshery1](https://user-images.githubusercontent.com/87536360/212822355-0056589a-a0a8-4968-9a66-0b624048dcf9.png)

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by msaini0r** [comment]
@leecalcote if you think we should remove it, I would like to work on this issue.

**Comment by leecalcote** [comment]
@msaini0r thanks for pointing this out. I think that we should refactor it to use the same mechanism that meshery/meshery uses. Here's the build status - https://github.com/meshery/meshery.io/actions/workflows/pages/pages-build-deployment
