### ISSUE TITLE
Grammar correction

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [meshery/meshery.io#986]
### Description
**depicts an singleton -> depicts a singleton**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/213241432-bc656261-32d4-4eba-bc81-174854d0cc1a.png">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShuvamChatterjee28** [comment]
Hello @UtkarshMishra12 and @GaganpreetKaurKalsi, can you please assign me for this one?

**Comment by GaganpreetKaurKalsi** [comment]
Thanks @ShuvamChatterjee28 🚀

**Comment by kushvahasumit** [comment]
Hey can you assign i want to fix this

**Comment by kushvahasumit** [comment]
HEY , @GaganpreetKaurKalsi please assign me . I wanna work this.
