### ISSUE TITLE
Community Newsletter component should be consistent

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [meshery/meshery.io#987]
### Description
Community Newsletter component should be consistent across all screens

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/213243933-d457215a-9cae-4300-b0af-ca2d53f7b4f2.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/213244042-3c018699-bd2c-4edc-9965-06f599e27229.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/213244135-46545c0c-9205-40ee-9570-f895e1234ea7.png">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Adi-ty** [comment]
I would like to work on this please assign me this issue

**Comment by Adi-ty** [comment]
Can you tell me which newsletter component do you want in all three pages

**Comment by oneknucklehead** [comment]
Hey @GaganpreetKaurKalsi can you please elaborate on the expected behaviour? I think i can work on this

**Comment by GaganpreetKaurKalsi** [comment]
All smallcase looks good to me, for heading as well as button.

**Comment by Adi-ty** [comment]
Does it look good like this for every page 

<img width="804" alt="image" src="https://user-images.githubusercontent.com/92062352/213731098-b3b34c65-6f4c-43cf-b4c5-574da8afeaff.png">

**Comment by Adi-ty** [comment]
Is this what you were looking for @GaganpreetKaurKalsi 

<img width="867" alt="image" src="https://user-images.githubusercontent.com/92062352/213745162-d91ba0c6-a205-49a4-b2c3-3787355d4452.png">


<img width="854" alt="image" src="https://user-images.githubusercontent.com/92062352/213738307-c20bea50-7b83-42db-bca4-55faac007542.png">

<img width="854" alt="image" src="https://user-images.githubusercontent.com/92062352/213738655-9e23fbaf-13dd-4c53-b38d-aab648db2b8e.png">
