### ISSUE TITLE
Text is not visible on every page of programs (i.e change its color in dark mode) 

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery.io#994]
### Description

Text is not visible on every page of programs (i.e change its color in dark mode) 
[Link](https://meshery.io/programs)

### Expected Behavior

The text should be visible in dark mode.

### Screenshots

Now:
![image](https://user-images.githubusercontent.com/67385503/214120292-a399658e-4923-43ef-a209-aeea343c29dc.png)

Desired:
![image](https://user-images.githubusercontent.com/67385503/214120324-98cd26d8-2a92-44a4-ab18-9604cf7c60eb.png)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Adi-ty** [comment]
Hey @aryans1319 are you currently working on it?

**Comment by UtkarshMishra12** [comment]
@aryans1319 are you able to set up the project locally?

**Comment by UtkarshMishra12** [comment]
Here you go @aryans1319 🚀

**Comment by Adi-ty** [comment]
Can I work on this issue?

**Comment by UtkarshMishra12** [comment]
@aryans1319 Progress ???

**Comment by Avi-88** [comment]
Hi @UtkarshMishra12 , I had some suggestions for the ui. Currently the darkmode only changes the main background  and not the actual info's background. I was thinking of it being something like this 

![image](https://user-images.githubusercontent.com/79744258/217785768-6cc1c2af-502a-4997-bd1e-4f5b02d75ff2.png)

Also the navbar is currently fixed so the main content slides under it, It has been dealt by adding margin-top to the section which creates a weird gap in some screens like so 

![image](https://user-images.githubusercontent.com/79744258/217787312-73a36e64-9b5e-4191-b74e-e977de86b08c.png)

 I believe position: sticky will fix that without having to put excess  margin. Do let me know your thoughts on this and I can make a quick PR for it, thanks

**Comment by MrBehl06** [comment]
@UtkarshMishra12 Is it Resolved?

**Comment by UtkarshMishra12** [comment]
@Nikhil-Ladha Your thoughts 🤔

**Comment by Yashsharma1911** [comment]
> Hi @UtkarshMishra12 , I had some suggestions for the ui. Currently the darkmode only changes the main background and not the actual info's background. I was thinking of it being something like this
> 
> ![image](https://user-images.githubusercontent.com/79744258/217785768-6cc1c2af-502a-4997-bd1e-4f5b02d75ff2.png)
> 
> Also the navbar is currently fixed so the main content slides under it, It has been dealt by adding margin-top to the section which creates a weird gap in some screens like so
> 
> ![image](https://user-images.githubusercontent.com/79744258/217787312-73a36e64-9b5e-4191-b74e-e977de86b08c.png)
> 
> I believe position: sticky will fix that without having to put excess margin. Do let me know your thoughts on this and I can make a quick PR for it, thanks

I think @Avi-88 suggestion is good for dark mode

**Comment by Nikhil-Ladha** [comment]
Updating the background color of the program data for the light/dark theme sounds good.
Also, please get rid of that unnecessary top margin.

**Comment by Avi-88** [comment]
Cool, I'll make a quick PR for this, thanks for the feedback

**Comment by Avi-88** [comment]
Hi @Nikhil-Ladha , I noticed while making changes that the cncf landscape program page is completely broken. I thought it would be better to fix it in a different PR, can you also please let me know your thoughts on that and could you please guide me where I could find the design to refer for fixing that page if we do want to proceed with that, thanks

**Comment by Nikhil-Ladha** [comment]
> Hi @Nikhil-Ladha , I noticed while making changes that the cncf landscape program page is completely broken. I thought it would be better to fix it in a different PR, can you also please let me know your thoughts on that and could you please guide me where I could find the design to refer for fixing that page if we do want to proceed with that, thanks

Thanks for checking that up.
Technically, that is just a couple of line changes that are adjusting the `max-width` CSS property of the screenshot added and checking for responsiveness. No other design changes are needed.
Though, I will leave on to you, if you wanna create a different PR for that. I am fine with either of them.
