### ISSUE TITLE
[UI] Improve The UI for Mobile devices Unexpected Extra width

### ISSUE THREAD

**Issue by AFZL210** [meshery/meshery.io#995]
#### Current Behavior
I've created an issue regarding an issue with uneven spacing and component size on mobile devices when using Meshery. Specifically, it appears that there is extra width present on the mobile layout, potentially causing difficulty for users trying to interact with the interface.

This issue occur when the screen width is below 430px.
![](https://res.cloudinary.com/primeflix/image/upload/v1673979215/ezgif.com-gif-maker_zfo8rj.gif)

#### Desired Behavior

On mobile devices, the dimensions of the components should be adjusted in accordance with the device's screen size while maintaining the relative spacing between elements.
![](https://res.cloudinary.com/primeflix/image/upload/v1673979473/ezgif.com-gif-maker_mmmefs.gif)

#### Implementation

use CSS media query and decrease the size of the elements a little maintaing the proportions and relative spacing between different components.

#### Acceptance Tests

N/A

#### Mockups

N/A

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Transferred this issue to the meshery/meshery.io repo.

**Comment by aminoxix** [comment]
@Frs2304 you're all set, man!  🚀

**Comment by Frs2304** [comment]
> @Frs2304 you're all set, man! 🚀

Thankyou ;)

**Comment by Frs2304** [comment]
@aminoxix Thankyou :)

**Comment by BabyElias** [comment]
@aminoxix Can I work on this issue?

**Comment by aminoxix** [comment]
there you go! 🚀

**Comment by Ghat0tkach** [comment]
is this issue still active?if yes may i work on this issue?

**Comment by aminoxix** [comment]
Hey @Ghat0tkach, I think I would like to pick this up, as you see, others are literally not available for this issue.

@leecalcote I assured you this still persists, with `Galaxy S20 Android 11` or nearby with width `360px` approx (not gonna disappoint you!)

![image](https://github.com/meshery/meshery.io/assets/75872316/2daaf2db-1ffc-4107-903a-9dfe058d0604)

**Comment by ashutosh887** [comment]
@leecalcote 
Is this Issue resolved?
