### ISSUE TITLE
[UI] Fix the width of form container on programs page for Small Media Devices.

### ISSUE THREAD

**Issue by gyancodes** [meshery/meshery.io#998]
### Description
The form container is overflowing on the programs page on the small media devices.
![form](https://user-images.githubusercontent.com/61907167/215278086-58bd51c6-5fc3-484f-8fd6-7fcda5580e8f.PNG)

### Expected Behavior

On Small media devices the with should be auto.
![formfixed](https://user-images.githubusercontent.com/61907167/215278198-5bc5529a-f2cb-41b0-84a3-8b30f48939d2.PNG)

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by gyancodes** [comment]
@leecalcote I have fixed this issue and working toward pr

**Comment by MrBehl06** [comment]
@gyancodes @leecalcote Is it Resolved ??
